//! IApplication global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::application::*;

// ---- IApplication (ApplicationIFace) ----

extern "C" {
    pub static IApplication: *mut ApplicationIFace;
}

#[inline]
pub unsafe fn application_set_app_lib_attrs_a(tags: *mut TagItem) -> u32 {
    ((*IApplication).SetAppLibAttrsA)(IApplication, tags)
}

#[inline]
pub unsafe fn application_get_app_lib_attrs_a(tags: *mut TagItem) -> u32 {
    ((*IApplication).GetAppLibAttrsA)(IApplication, tags)
}

#[inline]
pub unsafe fn application_register_application_a(appName: CONST_STRPTR, tags: *mut TagItem) -> u32 {
    ((*IApplication).RegisterApplicationA)(IApplication, appName, tags)
}

#[inline]
pub unsafe fn application_unregister_application_a(appID: u32, tags: *mut TagItem) -> u32 {
    ((*IApplication).UnregisterApplicationA)(IApplication, appID, tags)
}

#[inline]
pub unsafe fn application_set_application_attrs_a(appID: u32, tags: *mut TagItem) -> u32 {
    ((*IApplication).SetApplicationAttrsA)(IApplication, appID, tags)
}

#[inline]
pub unsafe fn application_get_application_attrs_a(appID: u32, tags: *mut TagItem) -> u32 {
    ((*IApplication).GetApplicationAttrsA)(IApplication, appID, tags)
}

#[inline]
pub unsafe fn application_find_application_a(tags: *mut TagItem) -> u32 {
    ((*IApplication).FindApplicationA)(IApplication, tags)
}

#[inline]
pub unsafe fn application_lock_application_icon(appID: u32) -> u32 {
    ((*IApplication).LockApplicationIcon)(IApplication, appID)
}

#[inline]
pub unsafe fn application_unlock_application_icon(appID: u32) {
    ((*IApplication).UnlockApplicationIcon)(IApplication, appID)
}

#[inline]
pub unsafe fn application_get_application_list() -> *mut MinList {
    ((*IApplication).GetApplicationList)(IApplication, )
}

#[inline]
pub unsafe fn application_free_application_list(list: *mut MinList) {
    ((*IApplication).FreeApplicationList)(IApplication, list)
}

#[inline]
pub unsafe fn application_send_application_msg(senderAppID: u32, receiverAppID: u32, msg: *mut ApplicationMsg, msgType: u32) -> u32 {
    ((*IApplication).SendApplicationMsg)(IApplication, senderAppID, receiverAppID, msg, msgType)
}

#[inline]
pub unsafe fn application_notify_a(appID: u32, tags: *mut TagItem) -> u32 {
    ((*IApplication).NotifyA)(IApplication, appID, tags)
}

