//! IAsl global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::asl::*;

// ---- IAsl (AslIFace) ----

extern "C" {
    pub static IAsl: *mut AslIFace;
}

#[inline]
pub unsafe fn asl_obsolete_alloc_file_request() -> *mut FileRequester {
    ((*IAsl).OBSOLETE_AllocFileRequest)(IAsl, )
}

#[inline]
pub unsafe fn asl_obsolete_free_file_request(fileReq: *mut FileRequester) {
    ((*IAsl).OBSOLETE_FreeFileRequest)(IAsl, fileReq)
}

#[inline]
pub unsafe fn asl_obsolete_request_file(fileReq: *mut FileRequester) -> u32 {
    ((*IAsl).OBSOLETE_RequestFile)(IAsl, fileReq)
}

#[inline]
pub unsafe fn asl_alloc_asl_request(reqType: u32, tagList: *const TagItem) -> APTR {
    ((*IAsl).AllocAslRequest)(IAsl, reqType, tagList)
}

#[inline]
pub unsafe fn asl_free_asl_request(requester: APTR) {
    ((*IAsl).FreeAslRequest)(IAsl, requester)
}

#[inline]
pub unsafe fn asl_asl_request(requester: APTR, tagList: *const TagItem) -> u32 {
    ((*IAsl).AslRequest)(IAsl, requester, tagList)
}

#[inline]
pub unsafe fn asl_asl_free_vec(memory: APTR) {
    ((*IAsl).AslFreeVec)(IAsl, memory)
}

#[inline]
pub unsafe fn asl_asl_alloc_vec(byteSize: u32, attributes: u32) -> APTR {
    ((*IAsl).AslAllocVec)(IAsl, byteSize, attributes)
}

#[inline]
pub unsafe fn asl_abort_asl_request(requester: APTR) {
    ((*IAsl).AbortAslRequest)(IAsl, requester)
}

#[inline]
pub unsafe fn asl_activate_asl_request(requester: APTR) {
    ((*IAsl).ActivateAslRequest)(IAsl, requester)
}

#[inline]
pub unsafe fn asl_asl_control(tags: *const TagItem) -> u32 {
    ((*IAsl).AslControl)(IAsl, tags)
}

