//! IDataTypes global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::datatypes::*;

// ---- IDataTypes (DataTypesIFace) ----

extern "C" {
    pub static IDataTypes: *mut DataTypesIFace;
}

#[inline]
pub unsafe fn datatypes_rldispatch(rmsg: *mut RexxMsg, result: *mut STRPTR) -> i32 {
    ((*IDataTypes).RLDispatch)(IDataTypes, rmsg, result)
}

#[inline]
pub unsafe fn datatypes_obtain_data_type_a(r#type: u32, handle: APTR, attrs: *mut APTR) -> *mut DataType {
    ((*IDataTypes).ObtainDataTypeA)(IDataTypes, r#type, handle, attrs)
}

#[inline]
pub unsafe fn datatypes_release_data_type(dt: *mut DataType) {
    ((*IDataTypes).ReleaseDataType)(IDataTypes, dt)
}

#[inline]
pub unsafe fn datatypes_new_dtobject_a(name: CONST_STRPTR, attrs: *mut APTR) -> *mut APTR {
    ((*IDataTypes).NewDTObjectA)(IDataTypes, name, attrs)
}

#[inline]
pub unsafe fn datatypes_dispose_dtobject(o: *mut APTR) {
    ((*IDataTypes).DisposeDTObject)(IDataTypes, o)
}

#[inline]
pub unsafe fn datatypes_set_dtattrs_a(o: *mut APTR, win: *mut Window, req: *mut Requester, attrs: *mut APTR) -> u32 {
    ((*IDataTypes).SetDTAttrsA)(IDataTypes, o, win, req, attrs)
}

#[inline]
pub unsafe fn datatypes_get_dtattrs_a(o: *mut APTR, attrs: *mut APTR) -> u32 {
    ((*IDataTypes).GetDTAttrsA)(IDataTypes, o, attrs)
}

#[inline]
pub unsafe fn datatypes_add_dtobject(win: *mut Window, req: *mut Requester, o: *mut APTR, pos: i32) -> i32 {
    ((*IDataTypes).AddDTObject)(IDataTypes, win, req, o, pos)
}

#[inline]
pub unsafe fn datatypes_refresh_dtobject_a(o: *mut APTR, win: *mut Window, req: *mut Requester, attrs: *mut APTR) {
    ((*IDataTypes).RefreshDTObjectA)(IDataTypes, o, win, req, attrs)
}

#[inline]
pub unsafe fn datatypes_do_async_layout(o: *mut APTR, gpl: *mut gpLayout) -> u32 {
    ((*IDataTypes).DoAsyncLayout)(IDataTypes, o, gpl)
}

#[inline]
pub unsafe fn datatypes_do_dtmethod_a(o: *mut APTR, win: *mut Window, req: *mut Requester, msg: APTR) -> u32 {
    ((*IDataTypes).DoDTMethodA)(IDataTypes, o, win, req, msg)
}

#[inline]
pub unsafe fn datatypes_remove_dtobject(win: *mut Window, o: *mut APTR) -> i32 {
    ((*IDataTypes).RemoveDTObject)(IDataTypes, win, o)
}

#[inline]
pub unsafe fn datatypes_get_dtmethods(object: *mut APTR) -> *mut u32 {
    ((*IDataTypes).GetDTMethods)(IDataTypes, object)
}

#[inline]
pub unsafe fn datatypes_get_dttrigger_methods(object: *mut APTR) -> *mut DTMethod {
    ((*IDataTypes).GetDTTriggerMethods)(IDataTypes, object)
}

#[inline]
pub unsafe fn datatypes_print_dtobject_a(o: *mut APTR, w: *mut Window, r: *mut Requester, msg: *mut dtPrint) -> u32 {
    ((*IDataTypes).PrintDTObjectA)(IDataTypes, o, w, r, msg)
}

#[inline]
pub unsafe fn datatypes_obtain_dtdraw_info_a(o: *mut APTR, attrs: *mut APTR) -> APTR {
    ((*IDataTypes).ObtainDTDrawInfoA)(IDataTypes, o, attrs)
}

#[inline]
pub unsafe fn datatypes_draw_dtobject_a(rp: *mut RastPort, o: *mut APTR, x: i32, y: i32, w: i32, h: i32, th: i32, tv: i32, attrs: *mut APTR) -> i32 {
    ((*IDataTypes).DrawDTObjectA)(IDataTypes, rp, o, x, y, w, h, th, tv, attrs)
}

#[inline]
pub unsafe fn datatypes_release_dtdraw_info(o: *mut APTR, handle: APTR) {
    ((*IDataTypes).ReleaseDTDrawInfo)(IDataTypes, o, handle)
}

#[inline]
pub unsafe fn datatypes_get_dtstring(id: u32) -> CONST_STRPTR {
    ((*IDataTypes).GetDTString)(IDataTypes, id)
}

#[inline]
pub unsafe fn datatypes_reserved1() {
    ((*IDataTypes).Reserved1)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_reserved2() {
    ((*IDataTypes).Reserved2)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_reserved3() {
    ((*IDataTypes).Reserved3)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_reserved4() {
    ((*IDataTypes).Reserved4)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_reserved5() {
    ((*IDataTypes).Reserved5)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_reserved6() {
    ((*IDataTypes).Reserved6)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_reserved7() {
    ((*IDataTypes).Reserved7)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_reserved8() {
    ((*IDataTypes).Reserved8)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_reserved9() {
    ((*IDataTypes).Reserved9)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_reserved10() {
    ((*IDataTypes).Reserved10)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_reserved11() {
    ((*IDataTypes).Reserved11)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_reserved12() {
    ((*IDataTypes).Reserved12)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_lock_data_type(dt: *mut DataType) {
    ((*IDataTypes).LockDataType)(IDataTypes, dt)
}

#[inline]
pub unsafe fn datatypes_find_tool_node_a(tl: *mut List, attrs: *mut APTR) -> *mut ToolNode {
    ((*IDataTypes).FindToolNodeA)(IDataTypes, tl, attrs)
}

#[inline]
pub unsafe fn datatypes_launch_tool_a(t: *mut Tool, project: CONST_STRPTR, attrs: *mut APTR) -> u32 {
    ((*IDataTypes).LaunchToolA)(IDataTypes, t, project, attrs)
}

#[inline]
pub unsafe fn datatypes_find_method(methods: *mut u32, searchmethodid: u32) -> *mut u32 {
    ((*IDataTypes).FindMethod)(IDataTypes, methods, searchmethodid)
}

#[inline]
pub unsafe fn datatypes_find_trigger_method(dtm: *mut DTMethod, command: CONST_STRPTR, method: u32) -> *mut DTMethod {
    ((*IDataTypes).FindTriggerMethod)(IDataTypes, dtm, command, method)
}

#[inline]
pub unsafe fn datatypes_copy_dtmethods(methods: *mut u32, include: *mut u32, exclude: *mut u32) -> *mut u32 {
    ((*IDataTypes).CopyDTMethods)(IDataTypes, methods, include, exclude)
}

#[inline]
pub unsafe fn datatypes_copy_dttrigger_methods(methods: *mut DTMethod, include: *mut DTMethod, exclude: *mut DTMethod) -> *mut DTMethod {
    ((*IDataTypes).CopyDTTriggerMethods)(IDataTypes, methods, include, exclude)
}

#[inline]
pub unsafe fn datatypes_free_dtmethods(methods: APTR) {
    ((*IDataTypes).FreeDTMethods)(IDataTypes, methods)
}

#[inline]
pub unsafe fn datatypes_get_dttrigger_method_data_flags(triggermethod: u32) -> u32 {
    ((*IDataTypes).GetDTTriggerMethodDataFlags)(IDataTypes, triggermethod)
}

#[inline]
pub unsafe fn datatypes_save_dtobject_a(o: *mut APTR, win: *mut Window, req: *mut Requester, file: CONST_STRPTR, mode: u32, saveicon: u32, attrs: *mut APTR) -> u32 {
    ((*IDataTypes).SaveDTObjectA)(IDataTypes, o, win, req, file, mode, saveicon, attrs)
}

#[inline]
pub unsafe fn datatypes_start_drag_select(o: *mut APTR) -> u32 {
    ((*IDataTypes).StartDragSelect)(IDataTypes, o)
}

#[inline]
pub unsafe fn datatypes_do_dtdomain_a(o: *mut APTR, win: *mut Window, req: *mut Requester, rport: *mut RastPort, which: u32, domain: *mut IBox, attrs: *mut APTR) -> u32 {
    ((*IDataTypes).DoDTDomainA)(IDataTypes, o, win, req, rport, which, domain, attrs)
}

#[inline]
pub unsafe fn datatypes_datatypes_private001() -> u32 {
    ((*IDataTypes).datatypesPrivate001)(IDataTypes, )
}

#[inline]
pub unsafe fn datatypes_datatypes_private002() -> u32 {
    ((*IDataTypes).datatypesPrivate002)(IDataTypes, )
}

