//! IDiskfont global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::diskfont::*;

// ---- IDiskfont (DiskfontIFace) ----

extern "C" {
    pub static IDiskfont: *mut DiskfontIFace;
}

#[inline]
pub unsafe fn diskfont_open_disk_font(textAttr: *const TextAttr) -> *mut TextFont {
    ((*IDiskfont).OpenDiskFont)(IDiskfont, textAttr)
}

#[inline]
pub unsafe fn diskfont_avail_fonts(buffer: STRPTR, bufBytes: i32, flags: u32) -> i32 {
    ((*IDiskfont).AvailFonts)(IDiskfont, buffer, bufBytes, flags)
}

#[inline]
pub unsafe fn diskfont_new_font_contents(fontsLock: u32, fontName: CONST_STRPTR) -> *mut FontContentsHeader {
    ((*IDiskfont).NewFontContents)(IDiskfont, fontsLock, fontName)
}

#[inline]
pub unsafe fn diskfont_dispose_font_contents(fontContentsHeader: *mut FontContentsHeader) {
    ((*IDiskfont).DisposeFontContents)(IDiskfont, fontContentsHeader)
}

#[inline]
pub unsafe fn diskfont_new_scaled_disk_font(sourceFont: *mut TextFont, destTextAttr: *mut TextAttr) -> *mut DiskFontHeader {
    ((*IDiskfont).NewScaledDiskFont)(IDiskfont, sourceFont, destTextAttr)
}

#[inline]
pub unsafe fn diskfont_get_disk_font_ctrl(tagid: i32) -> i32 {
    ((*IDiskfont).GetDiskFontCtrl)(IDiskfont, tagid)
}

#[inline]
pub unsafe fn diskfont_set_disk_font_ctrl_a(taglist: *const TagItem) {
    ((*IDiskfont).SetDiskFontCtrlA)(IDiskfont, taglist)
}

#[inline]
pub unsafe fn diskfont_eopen_engine(EEngine: *mut EGlyphEngine) -> i32 {
    ((*IDiskfont).EOpenEngine)(IDiskfont, EEngine)
}

#[inline]
pub unsafe fn diskfont_eclose_engine(EEngine: *mut EGlyphEngine) {
    ((*IDiskfont).ECloseEngine)(IDiskfont, EEngine)
}

#[inline]
pub unsafe fn diskfont_eset_info_a(EEngine: *mut EGlyphEngine, taglist: *const TagItem) -> u32 {
    ((*IDiskfont).ESetInfoA)(IDiskfont, EEngine, taglist)
}

#[inline]
pub unsafe fn diskfont_eobtain_info_a(EEngine: *mut EGlyphEngine, taglist: *const TagItem) -> u32 {
    ((*IDiskfont).EObtainInfoA)(IDiskfont, EEngine, taglist)
}

#[inline]
pub unsafe fn diskfont_erelease_info_a(EEngine: *mut EGlyphEngine, taglist: *const TagItem) -> u32 {
    ((*IDiskfont).EReleaseInfoA)(IDiskfont, EEngine, taglist)
}

#[inline]
pub unsafe fn diskfont_open_outline_font(name: CONST_STRPTR, list: *mut List, flags: u32) -> *mut OutlineFont {
    ((*IDiskfont).OpenOutlineFont)(IDiskfont, name, list, flags)
}

#[inline]
pub unsafe fn diskfont_close_outline_font(olf: *mut OutlineFont, list: *mut List) {
    ((*IDiskfont).CloseOutlineFont)(IDiskfont, olf, list)
}

#[inline]
pub unsafe fn diskfont_write_font_contents(fontsLock: u32, fontName: CONST_STRPTR, fontContentsHeader: *mut FontContentsHeader) -> i32 {
    ((*IDiskfont).WriteFontContents)(IDiskfont, fontsLock, fontName, fontContentsHeader)
}

#[inline]
pub unsafe fn diskfont_write_disk_font_header_a(font: *mut TextFont, fileName: CONST_STRPTR, taglist: *const TagItem) -> i32 {
    ((*IDiskfont).WriteDiskFontHeaderA)(IDiskfont, font, fileName, taglist)
}

#[inline]
pub unsafe fn diskfont_obtain_charset_info(knownTag: u32, knownValue: u32, wantedTag: u32) -> u32 {
    ((*IDiskfont).ObtainCharsetInfo)(IDiskfont, knownTag, knownValue, wantedTag)
}

#[inline]
pub unsafe fn diskfont_obtain_ttext_attr(textFont: *mut TextFont) -> *mut TTextAttr {
    ((*IDiskfont).ObtainTTextAttr)(IDiskfont, textFont)
}

#[inline]
pub unsafe fn diskfont_free_ttext_attr(tta: *mut TTextAttr) {
    ((*IDiskfont).FreeTTextAttr)(IDiskfont, tta)
}

