//! IDOS global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::dos::*;

// ---- IDOS (DOSIFace) ----

extern "C" {
    pub static IDOS: *mut DOSIFace;
}

#[inline]
pub unsafe fn dos_open(name: CONST_STRPTR, accessMode: i32) -> u32 {
    ((*IDOS).Open)(IDOS, name, accessMode)
}

#[inline]
pub unsafe fn dos_close(file: u32) -> i32 {
    ((*IDOS).Close)(IDOS, file)
}

#[inline]
pub unsafe fn dos_read(file: u32, buffer: APTR, length: i32) -> i32 {
    ((*IDOS).Read)(IDOS, file, buffer, length)
}

#[inline]
pub unsafe fn dos_write(file: u32, buffer: CONST_APTR, length: i32) -> i32 {
    ((*IDOS).Write)(IDOS, file, buffer, length)
}

#[inline]
pub unsafe fn dos_input() -> u32 {
    ((*IDOS).Input)(IDOS, )
}

#[inline]
pub unsafe fn dos_output() -> u32 {
    ((*IDOS).Output)(IDOS, )
}

#[inline]
pub unsafe fn dos_obsoleteseek(file: u32, position: i32, offset: i32) -> i32 {
    ((*IDOS).OBSOLETESeek)(IDOS, file, position, offset)
}

#[inline]
pub unsafe fn dos_delete(name: CONST_STRPTR) -> i32 {
    ((*IDOS).Delete)(IDOS, name)
}

#[inline]
pub unsafe fn dos_rename(oldName: CONST_STRPTR, newName: CONST_STRPTR) -> i32 {
    ((*IDOS).Rename)(IDOS, oldName, newName)
}

#[inline]
pub unsafe fn dos_lock(name: CONST_STRPTR, r#type: i32) -> u32 {
    ((*IDOS).Lock)(IDOS, name, r#type)
}

#[inline]
pub unsafe fn dos_un_lock(lock: u32) {
    ((*IDOS).UnLock)(IDOS, lock)
}

#[inline]
pub unsafe fn dos_dup_lock(lock: u32) -> u32 {
    ((*IDOS).DupLock)(IDOS, lock)
}

#[inline]
pub unsafe fn dos_obsoleteexamine(lock: u32, fileInfoBlock: *mut FileInfoBlock) -> i32 {
    ((*IDOS).OBSOLETEExamine)(IDOS, lock, fileInfoBlock)
}

#[inline]
pub unsafe fn dos_obsoleteex_next(lock: u32, fileInfoBlock: *mut FileInfoBlock) -> i32 {
    ((*IDOS).OBSOLETEExNext)(IDOS, lock, fileInfoBlock)
}

#[inline]
pub unsafe fn dos_info(lock: u32, parameterBlock: *mut InfoData) -> i32 {
    ((*IDOS).Info)(IDOS, lock, parameterBlock)
}

#[inline]
pub unsafe fn dos_create_dir(name: CONST_STRPTR) -> u32 {
    ((*IDOS).CreateDir)(IDOS, name)
}

#[inline]
pub unsafe fn dos_set_current_dir(lock: u32) -> u32 {
    ((*IDOS).SetCurrentDir)(IDOS, lock)
}

#[inline]
pub unsafe fn dos_io_err() -> i32 {
    ((*IDOS).IoErr)(IDOS, )
}

#[inline]
pub unsafe fn dos_obsoletecreate_proc(name: CONST_STRPTR, pri: i32, segList: u32, stackSize: i32) -> *mut MsgPort {
    ((*IDOS).OBSOLETECreateProc)(IDOS, name, pri, segList, stackSize)
}

#[inline]
pub unsafe fn dos_obsoleteexit(returnCode: i32) {
    ((*IDOS).OBSOLETEExit)(IDOS, returnCode)
}

#[inline]
pub unsafe fn dos_obsoleteload_seg(name: CONST_STRPTR, hunktab: u32, stream: u32) -> u32 {
    ((*IDOS).OBSOLETELoadSeg)(IDOS, name, hunktab, stream)
}

#[inline]
pub unsafe fn dos_un_load_seg(seglist: u32) -> i32 {
    ((*IDOS).UnLoadSeg)(IDOS, seglist)
}

#[inline]
pub unsafe fn dos_privatedo_pkt32(port: *mut MsgPort, action: i32, arg1: i32, arg2: i32, arg3: i32, arg4: i32, arg5: i32, arg6: i32, arg7: i32) -> i32 {
    ((*IDOS).PRIVATEDoPkt32)(IDOS, port, action, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
}

#[inline]
pub unsafe fn dos_load_seg(name: CONST_STRPTR) -> u32 {
    ((*IDOS).LoadSeg)(IDOS, name)
}

#[inline]
pub unsafe fn dos_obsoletedevice_proc(name: CONST_STRPTR) -> *mut MsgPort {
    ((*IDOS).OBSOLETEDeviceProc)(IDOS, name)
}

#[inline]
pub unsafe fn dos_set_comment(name: CONST_STRPTR, comment: CONST_STRPTR) -> i32 {
    ((*IDOS).SetComment)(IDOS, name, comment)
}

#[inline]
pub unsafe fn dos_set_protection(name: CONST_STRPTR, protect: u32) -> i32 {
    ((*IDOS).SetProtection)(IDOS, name, protect)
}

#[inline]
pub unsafe fn dos_date_stamp(date: *mut DateStamp) -> *mut DateStamp {
    ((*IDOS).DateStamp)(IDOS, date)
}

#[inline]
pub unsafe fn dos_delay(timeout: u32) {
    ((*IDOS).Delay)(IDOS, timeout)
}

#[inline]
pub unsafe fn dos_wait_for_char(file: u32, timeout: i32) -> i32 {
    ((*IDOS).WaitForChar)(IDOS, file, timeout)
}

#[inline]
pub unsafe fn dos_parent_dir(lock: u32) -> u32 {
    ((*IDOS).ParentDir)(IDOS, lock)
}

#[inline]
pub unsafe fn dos_is_interactive(file: u32) -> i32 {
    ((*IDOS).IsInteractive)(IDOS, file)
}

#[inline]
pub unsafe fn dos_obsoleteexecute(string: CONST_STRPTR, file: u32, file2: u32) -> i32 {
    ((*IDOS).OBSOLETEExecute)(IDOS, string, file, file2)
}

#[inline]
pub unsafe fn dos_alloc_dos_object(r#type: u32, tags: *const TagItem) -> APTR {
    ((*IDOS).AllocDosObject)(IDOS, r#type, tags)
}

#[inline]
pub unsafe fn dos_alloc_dos_object_tag_list(r#type: u32, tags: *const TagItem) -> APTR {
    ((*IDOS).AllocDosObjectTagList)(IDOS, r#type, tags)
}

#[inline]
pub unsafe fn dos_free_dos_object(r#type: u32, ptr: APTR) {
    ((*IDOS).FreeDosObject)(IDOS, r#type, ptr)
}

#[inline]
pub unsafe fn dos_do_pkt(port: *mut MsgPort, action: i32, arg1: i32, arg2: i32, arg3: i32, arg4: i32, arg5: i32) -> i32 {
    ((*IDOS).DoPkt)(IDOS, port, action, arg1, arg2, arg3, arg4, arg5)
}

#[inline]
pub unsafe fn dos_do_pkt0(port: *mut MsgPort, action: i32) -> i32 {
    ((*IDOS).DoPkt0)(IDOS, port, action)
}

#[inline]
pub unsafe fn dos_do_pkt1(port: *mut MsgPort, action: i32, arg1: i32) -> i32 {
    ((*IDOS).DoPkt1)(IDOS, port, action, arg1)
}

#[inline]
pub unsafe fn dos_do_pkt2(port: *mut MsgPort, action: i32, arg1: i32, arg2: i32) -> i32 {
    ((*IDOS).DoPkt2)(IDOS, port, action, arg1, arg2)
}

#[inline]
pub unsafe fn dos_do_pkt3(port: *mut MsgPort, action: i32, arg1: i32, arg2: i32, arg3: i32) -> i32 {
    ((*IDOS).DoPkt3)(IDOS, port, action, arg1, arg2, arg3)
}

#[inline]
pub unsafe fn dos_do_pkt4(port: *mut MsgPort, action: i32, arg1: i32, arg2: i32, arg3: i32, arg4: i32) -> i32 {
    ((*IDOS).DoPkt4)(IDOS, port, action, arg1, arg2, arg3, arg4)
}

#[inline]
pub unsafe fn dos_send_pkt(dp: *mut DosPacket, port: *mut MsgPort, replyport: *mut MsgPort) {
    ((*IDOS).SendPkt)(IDOS, dp, port, replyport)
}

#[inline]
pub unsafe fn dos_wait_pkt(task_replyport: *mut MsgPort) -> *mut DosPacket {
    ((*IDOS).WaitPkt)(IDOS, task_replyport)
}

#[inline]
pub unsafe fn dos_reply_pkt(dp: *mut DosPacket, res1: i32, res2: i32) -> i32 {
    ((*IDOS).ReplyPkt)(IDOS, dp, res1, res2)
}

#[inline]
pub unsafe fn dos_obsoletelock_record(fh: u32, offset: u32, length: u32, mode: u32, timeout: u32) -> i32 {
    ((*IDOS).OBSOLETELockRecord)(IDOS, fh, offset, length, mode, timeout)
}

#[inline]
pub unsafe fn dos_lock_records(recArray: *mut RecordLock, timeout: u32) -> i32 {
    ((*IDOS).LockRecords)(IDOS, recArray, timeout)
}

#[inline]
pub unsafe fn dos_obsoleteun_lock_record(fh: u32, offset: u32, length: u32) -> i32 {
    ((*IDOS).OBSOLETEUnLockRecord)(IDOS, fh, offset, length)
}

#[inline]
pub unsafe fn dos_un_lock_records(recArray: *mut RecordLock) -> i32 {
    ((*IDOS).UnLockRecords)(IDOS, recArray)
}

#[inline]
pub unsafe fn dos_select_input(fh: u32) -> u32 {
    ((*IDOS).SelectInput)(IDOS, fh)
}

#[inline]
pub unsafe fn dos_select_output(fh: u32) -> u32 {
    ((*IDOS).SelectOutput)(IDOS, fh)
}

#[inline]
pub unsafe fn dos_fget_c(fh: u32) -> i32 {
    ((*IDOS).FGetC)(IDOS, fh)
}

#[inline]
pub unsafe fn dos_fput_c(fh: u32, ch: i32) -> i32 {
    ((*IDOS).FPutC)(IDOS, fh, ch)
}

#[inline]
pub unsafe fn dos_fun_get_c(fh: u32, character: i32) -> i32 {
    ((*IDOS).FUnGetC)(IDOS, fh, character)
}

#[inline]
pub unsafe fn dos_fread(fh: u32, block: APTR, blocklen: u32, number: u32) -> u32 {
    ((*IDOS).FRead)(IDOS, fh, block, blocklen, number)
}

#[inline]
pub unsafe fn dos_fwrite(fh: u32, block: CONST_APTR, blocklen: u32, number: u32) -> u32 {
    ((*IDOS).FWrite)(IDOS, fh, block, blocklen, number)
}

#[inline]
pub unsafe fn dos_fgets(fh: u32, buf: STRPTR, buflen: u32) -> STRPTR {
    ((*IDOS).FGets)(IDOS, fh, buf, buflen)
}

#[inline]
pub unsafe fn dos_fputs(fh: u32, str: CONST_STRPTR) -> i32 {
    ((*IDOS).FPuts)(IDOS, fh, str)
}

#[inline]
pub unsafe fn dos_obsoletevfwritef(fh: u32, format: CONST_STRPTR, argarray: *mut i32) {
    ((*IDOS).OBSOLETEVFWritef)(IDOS, fh, format, argarray)
}

#[inline]
pub unsafe fn dos_vfprintf(fh: u32, format: CONST_STRPTR, argarray: CONST_APTR) -> i32 {
    ((*IDOS).VFPrintf)(IDOS, fh, format, argarray)
}

#[inline]
pub unsafe fn dos_fflush(fh: u32) -> i32 {
    ((*IDOS).FFlush)(IDOS, fh)
}

#[inline]
pub unsafe fn dos_obsoleteset_vbuf(fh: u32, buff: STRPTR, r#type: i32, size: i32) -> i32 {
    ((*IDOS).OBSOLETESetVBuf)(IDOS, fh, buff, r#type, size)
}

#[inline]
pub unsafe fn dos_dup_lock_from_fh(fh: u32) -> u32 {
    ((*IDOS).DupLockFromFH)(IDOS, fh)
}

#[inline]
pub unsafe fn dos_open_from_lock(lock: u32) -> u32 {
    ((*IDOS).OpenFromLock)(IDOS, lock)
}

#[inline]
pub unsafe fn dos_parent_of_fh(fh: u32) -> u32 {
    ((*IDOS).ParentOfFH)(IDOS, fh)
}

#[inline]
pub unsafe fn dos_obsoleteexamine_fh(fh: u32, fib: *mut FileInfoBlock) -> i32 {
    ((*IDOS).OBSOLETEExamineFH)(IDOS, fh, fib)
}

#[inline]
pub unsafe fn dos_set_date(name: CONST_STRPTR, date: *const DateStamp) -> i32 {
    ((*IDOS).SetDate)(IDOS, name, date)
}

#[inline]
pub unsafe fn dos_name_from_lock(lock: u32, buffer: STRPTR, len: i32) -> i32 {
    ((*IDOS).NameFromLock)(IDOS, lock, buffer, len)
}

#[inline]
pub unsafe fn dos_name_from_fh(fh: u32, buffer: STRPTR, len: i32) -> i32 {
    ((*IDOS).NameFromFH)(IDOS, fh, buffer, len)
}

#[inline]
pub unsafe fn dos_split_name(name: CONST_STRPTR, separator: i32, buf: STRPTR, oldpos: i32, size: i32) -> i32 {
    ((*IDOS).SplitName)(IDOS, name, separator, buf, oldpos, size)
}

#[inline]
pub unsafe fn dos_same_lock(lock1: u32, lock2: u32) -> i32 {
    ((*IDOS).SameLock)(IDOS, lock1, lock2)
}

#[inline]
pub unsafe fn dos_set_mode(fh: u32, mode: i32) -> i32 {
    ((*IDOS).SetMode)(IDOS, fh, mode)
}

#[inline]
pub unsafe fn dos_obsoleteex_all(lock: u32, buffer: *mut ExAllData, size: i32, data: i32, control: *mut ExAllControl) -> i32 {
    ((*IDOS).OBSOLETEExAll)(IDOS, lock, buffer, size, data, control)
}

#[inline]
pub unsafe fn dos_read_soft_link(port: *mut MsgPort, lock: u32, path: CONST_STRPTR, buffer: STRPTR, size: u32) -> i32 {
    ((*IDOS).ReadSoftLink)(IDOS, port, lock, path, buffer, size)
}

#[inline]
pub unsafe fn dos_make_link(name: CONST_STRPTR, dest: APTR, soft: i32) -> i32 {
    ((*IDOS).MakeLink)(IDOS, name, dest, soft)
}

#[inline]
pub unsafe fn dos_change_mode(r#type: i32, fh: u32, newmode: i32) -> i32 {
    ((*IDOS).ChangeMode)(IDOS, r#type, fh, newmode)
}

#[inline]
pub unsafe fn dos_obsoleteset_file_size(fh: u32, pos: i32, mode: i32) -> i32 {
    ((*IDOS).OBSOLETESetFileSize)(IDOS, fh, pos, mode)
}

#[inline]
pub unsafe fn dos_set_io_err(result: i32) -> i32 {
    ((*IDOS).SetIoErr)(IDOS, result)
}

#[inline]
pub unsafe fn dos_fault(code: i32, header: CONST_STRPTR, buffer: STRPTR, len: i32) -> i32 {
    ((*IDOS).Fault)(IDOS, code, header, buffer, len)
}

#[inline]
pub unsafe fn dos_print_fault(code: i32, header: CONST_STRPTR) -> i32 {
    ((*IDOS).PrintFault)(IDOS, code, header)
}

#[inline]
pub unsafe fn dos_error_report(code: i32, r#type: i32, arg1: u32, device: *mut MsgPort) -> i32 {
    ((*IDOS).ErrorReport)(IDOS, code, r#type, arg1, device)
}

#[inline]
pub unsafe fn dos_privaterequester(s1: CONST_STRPTR, s2: CONST_STRPTR, s3: CONST_STRPTR, idcmp: i32) -> i32 {
    ((*IDOS).PRIVATERequester)(IDOS, s1, s2, s3, idcmp)
}

#[inline]
pub unsafe fn dos_cli() -> *mut CommandLineInterface {
    ((*IDOS).Cli)(IDOS, )
}

#[inline]
pub unsafe fn dos_create_new_proc(tags: *const TagItem) -> *mut Process {
    ((*IDOS).CreateNewProc)(IDOS, tags)
}

#[inline]
pub unsafe fn dos_create_new_proc_tag_list(tags: *const TagItem) -> *mut Process {
    ((*IDOS).CreateNewProcTagList)(IDOS, tags)
}

#[inline]
pub unsafe fn dos_run_command(seg: u32, stack: u32, paramptr: CONST_STRPTR, paramlen: i32) -> i32 {
    ((*IDOS).RunCommand)(IDOS, seg, stack, paramptr, paramlen)
}

#[inline]
pub unsafe fn dos_get_console_port() -> *mut MsgPort {
    ((*IDOS).GetConsolePort)(IDOS, )
}

#[inline]
pub unsafe fn dos_set_console_port(port: *const MsgPort) -> *mut MsgPort {
    ((*IDOS).SetConsolePort)(IDOS, port)
}

#[inline]
pub unsafe fn dos_get_file_sys_port() -> *mut MsgPort {
    ((*IDOS).GetFileSysPort)(IDOS, )
}

#[inline]
pub unsafe fn dos_set_file_sys_port(port: *const MsgPort) -> *mut MsgPort {
    ((*IDOS).SetFileSysPort)(IDOS, port)
}

#[inline]
pub unsafe fn dos_get_arg_str() -> STRPTR {
    ((*IDOS).GetArgStr)(IDOS, )
}

#[inline]
pub unsafe fn dos_set_arg_str(string: CONST_STRPTR) -> STRPTR {
    ((*IDOS).SetArgStr)(IDOS, string)
}

#[inline]
pub unsafe fn dos_find_cli_proc(num: u32) -> *mut Process {
    ((*IDOS).FindCliProc)(IDOS, num)
}

#[inline]
pub unsafe fn dos_max_cli() -> u32 {
    ((*IDOS).MaxCli)(IDOS, )
}

#[inline]
pub unsafe fn dos_set_cli_current_dir_name(name: CONST_STRPTR) -> i32 {
    ((*IDOS).SetCliCurrentDirName)(IDOS, name)
}

#[inline]
pub unsafe fn dos_get_cli_current_dir_name(buf: STRPTR, len: i32) -> i32 {
    ((*IDOS).GetCliCurrentDirName)(IDOS, buf, len)
}

#[inline]
pub unsafe fn dos_set_cli_program_name(name: CONST_STRPTR) -> i32 {
    ((*IDOS).SetCliProgramName)(IDOS, name)
}

#[inline]
pub unsafe fn dos_get_cli_program_name(buf: STRPTR, len: i32) -> i32 {
    ((*IDOS).GetCliProgramName)(IDOS, buf, len)
}

#[inline]
pub unsafe fn dos_set_cli_prompt(name: CONST_STRPTR) -> i32 {
    ((*IDOS).SetCliPrompt)(IDOS, name)
}

#[inline]
pub unsafe fn dos_get_cli_prompt(buf: STRPTR, len: i32) -> i32 {
    ((*IDOS).GetCliPrompt)(IDOS, buf, len)
}

#[inline]
pub unsafe fn dos_set_program_dir(lock: u32) -> u32 {
    ((*IDOS).SetProgramDir)(IDOS, lock)
}

#[inline]
pub unsafe fn dos_get_program_dir() -> u32 {
    ((*IDOS).GetProgramDir)(IDOS, )
}

#[inline]
pub unsafe fn dos_system_tag_list(command: CONST_STRPTR, tags: *const TagItem) -> i32 {
    ((*IDOS).SystemTagList)(IDOS, command, tags)
}

#[inline]
pub unsafe fn dos_system(command: CONST_STRPTR, tags: *const TagItem) -> i32 {
    ((*IDOS).System)(IDOS, command, tags)
}

#[inline]
pub unsafe fn dos_assign_lock(name: CONST_STRPTR, lock: u32) -> i32 {
    ((*IDOS).AssignLock)(IDOS, name, lock)
}

#[inline]
pub unsafe fn dos_assign_late(name: CONST_STRPTR, path: CONST_STRPTR) -> i32 {
    ((*IDOS).AssignLate)(IDOS, name, path)
}

#[inline]
pub unsafe fn dos_assign_path(name: CONST_STRPTR, path: CONST_STRPTR) -> i32 {
    ((*IDOS).AssignPath)(IDOS, name, path)
}

#[inline]
pub unsafe fn dos_assign_add(name: CONST_STRPTR, lock: u32) -> i32 {
    ((*IDOS).AssignAdd)(IDOS, name, lock)
}

#[inline]
pub unsafe fn dos_rem_assign_list(name: CONST_STRPTR, lock: u32) -> i32 {
    ((*IDOS).RemAssignList)(IDOS, name, lock)
}

#[inline]
pub unsafe fn dos_get_device_proc(name: CONST_STRPTR, dp: *mut DevProc) -> *mut DevProc {
    ((*IDOS).GetDeviceProc)(IDOS, name, dp)
}

#[inline]
pub unsafe fn dos_free_device_proc(dp: *mut DevProc) {
    ((*IDOS).FreeDeviceProc)(IDOS, dp)
}

#[inline]
pub unsafe fn dos_lock_dos_list(flags: u32) -> *mut DosList {
    ((*IDOS).LockDosList)(IDOS, flags)
}

#[inline]
pub unsafe fn dos_un_lock_dos_list(flags: u32) {
    ((*IDOS).UnLockDosList)(IDOS, flags)
}

#[inline]
pub unsafe fn dos_attempt_lock_dos_list(flags: u32) -> *mut DosList {
    ((*IDOS).AttemptLockDosList)(IDOS, flags)
}

#[inline]
pub unsafe fn dos_rem_dos_entry(dlist: *mut DosList) -> i32 {
    ((*IDOS).RemDosEntry)(IDOS, dlist)
}

#[inline]
pub unsafe fn dos_add_dos_entry(dlist: *mut DosList) -> i32 {
    ((*IDOS).AddDosEntry)(IDOS, dlist)
}

#[inline]
pub unsafe fn dos_find_dos_entry(dlist: *const DosList, name: CONST_STRPTR, flags: u32) -> *mut DosList {
    ((*IDOS).FindDosEntry)(IDOS, dlist, name, flags)
}

#[inline]
pub unsafe fn dos_next_dos_entry(dlist: *const DosList, flags: u32) -> *mut DosList {
    ((*IDOS).NextDosEntry)(IDOS, dlist, flags)
}

#[inline]
pub unsafe fn dos_make_dos_entry(name: CONST_STRPTR, r#type: i32) -> *mut DosList {
    ((*IDOS).MakeDosEntry)(IDOS, name, r#type)
}

#[inline]
pub unsafe fn dos_free_dos_entry(dlist: *mut DosList) {
    ((*IDOS).FreeDosEntry)(IDOS, dlist)
}

#[inline]
pub unsafe fn dos_is_file_system(name: CONST_STRPTR) -> i32 {
    ((*IDOS).IsFileSystem)(IDOS, name)
}

#[inline]
pub unsafe fn dos_format(filesystem: CONST_STRPTR, volumename: CONST_STRPTR, dostype: u32, flags: u32) -> i32 {
    ((*IDOS).Format)(IDOS, filesystem, volumename, dostype, flags)
}

#[inline]
pub unsafe fn dos_relabel(drive: CONST_STRPTR, newname: CONST_STRPTR) -> i32 {
    ((*IDOS).Relabel)(IDOS, drive, newname)
}

#[inline]
pub unsafe fn dos_inhibit(name: CONST_STRPTR, onoff: i32) -> i32 {
    ((*IDOS).Inhibit)(IDOS, name, onoff)
}

#[inline]
pub unsafe fn dos_add_buffers(name: CONST_STRPTR, number: i32) -> i32 {
    ((*IDOS).AddBuffers)(IDOS, name, number)
}

#[inline]
pub unsafe fn dos_compare_dates(date1: *const DateStamp, date2: *const DateStamp) -> i32 {
    ((*IDOS).CompareDates)(IDOS, date1, date2)
}

#[inline]
pub unsafe fn dos_date_to_str(datetime: *mut DateTime) -> i32 {
    ((*IDOS).DateToStr)(IDOS, datetime)
}

#[inline]
pub unsafe fn dos_str_to_date(datetime: *mut DateTime) -> i32 {
    ((*IDOS).StrToDate)(IDOS, datetime)
}

#[inline]
pub unsafe fn dos_obsoleteinternal_load_seg(fh: u32, table: u32, funcarray: *const i32) -> u32 {
    ((*IDOS).OBSOLETEInternalLoadSeg)(IDOS, fh, table, funcarray)
}

#[inline]
pub unsafe fn dos_obsoleteinternal_un_load_seg(seglist: u32, freefunc: APTR) -> i32 {
    ((*IDOS).OBSOLETEInternalUnLoadSeg)(IDOS, seglist, freefunc)
}

#[inline]
pub unsafe fn dos_obsoletenew_load_seg(file: CONST_STRPTR, tags: *const TagItem) -> u32 {
    ((*IDOS).OBSOLETENewLoadSeg)(IDOS, file, tags)
}

#[inline]
pub unsafe fn dos_obsoletenew_load_seg_tag_list(file: CONST_STRPTR, tags: *const TagItem) -> u32 {
    ((*IDOS).OBSOLETENewLoadSegTagList)(IDOS, file, tags)
}

#[inline]
pub unsafe fn dos_add_segment(name: CONST_STRPTR, seg: u32, r#type: i32) -> i32 {
    ((*IDOS).AddSegment)(IDOS, name, seg, r#type)
}

#[inline]
pub unsafe fn dos_find_segment(name: CONST_STRPTR, seg: *const DosResidentSeg, sys: i32) -> *mut DosResidentSeg {
    ((*IDOS).FindSegment)(IDOS, name, seg, sys)
}

#[inline]
pub unsafe fn dos_rem_segment(seg: *mut DosResidentSeg) -> i32 {
    ((*IDOS).RemSegment)(IDOS, seg)
}

#[inline]
pub unsafe fn dos_check_signal(mask: u32) -> u32 {
    ((*IDOS).CheckSignal)(IDOS, mask)
}

#[inline]
pub unsafe fn dos_read_args(arg_template: CONST_STRPTR, array: *mut i32, args: *mut RDArgs) -> *mut RDArgs {
    ((*IDOS).ReadArgs)(IDOS, arg_template, array, args)
}

#[inline]
pub unsafe fn dos_find_arg(arg_template: CONST_STRPTR, keyword: CONST_STRPTR) -> i32 {
    ((*IDOS).FindArg)(IDOS, arg_template, keyword)
}

#[inline]
pub unsafe fn dos_read_item(buffer: STRPTR, maxchars: i32, cSource: *mut CSource) -> i32 {
    ((*IDOS).ReadItem)(IDOS, buffer, maxchars, cSource)
}

#[inline]
pub unsafe fn dos_str_to_long(string: CONST_STRPTR, value: *mut i32) -> i32 {
    ((*IDOS).StrToLong)(IDOS, string, value)
}

#[inline]
pub unsafe fn dos_match_first(pat: CONST_STRPTR, anchor: *mut AnchorPath) -> i32 {
    ((*IDOS).MatchFirst)(IDOS, pat, anchor)
}

#[inline]
pub unsafe fn dos_match_next(anchor: *mut AnchorPath) -> i32 {
    ((*IDOS).MatchNext)(IDOS, anchor)
}

#[inline]
pub unsafe fn dos_match_end(anchor: *mut AnchorPath) {
    ((*IDOS).MatchEnd)(IDOS, anchor)
}

#[inline]
pub unsafe fn dos_parse_pattern(pat: CONST_STRPTR, buf: STRPTR, buflen: i32) -> i32 {
    ((*IDOS).ParsePattern)(IDOS, pat, buf, buflen)
}

#[inline]
pub unsafe fn dos_match_pattern(pat: CONST_STRPTR, str: CONST_STRPTR) -> i32 {
    ((*IDOS).MatchPattern)(IDOS, pat, str)
}

#[inline]
pub unsafe fn dos_free_args(args: *mut RDArgs) {
    ((*IDOS).FreeArgs)(IDOS, args)
}

#[inline]
pub unsafe fn dos_start_part(path: CONST_STRPTR) -> STRPTR {
    ((*IDOS).StartPart)(IDOS, path)
}

#[inline]
pub unsafe fn dos_file_part(path: CONST_STRPTR) -> CONST_STRPTR {
    ((*IDOS).FilePart)(IDOS, path)
}

#[inline]
pub unsafe fn dos_path_part(path: CONST_STRPTR) -> STRPTR {
    ((*IDOS).PathPart)(IDOS, path)
}

#[inline]
pub unsafe fn dos_add_part(destdirname: STRPTR, filename: CONST_STRPTR, size: u32) -> i32 {
    ((*IDOS).AddPart)(IDOS, destdirname, filename, size)
}

#[inline]
pub unsafe fn dos_start_notify(notify: *mut NotifyRequest) -> i32 {
    ((*IDOS).StartNotify)(IDOS, notify)
}

#[inline]
pub unsafe fn dos_end_notify(notify: *mut NotifyRequest) -> i32 {
    ((*IDOS).EndNotify)(IDOS, notify)
}

#[inline]
pub unsafe fn dos_set_var(name: CONST_STRPTR, buffer: CONST_STRPTR, size: i32, flags: u32) -> i32 {
    ((*IDOS).SetVar)(IDOS, name, buffer, size, flags)
}

#[inline]
pub unsafe fn dos_get_var(name: CONST_STRPTR, buffer: STRPTR, size: i32, flags: u32) -> i32 {
    ((*IDOS).GetVar)(IDOS, name, buffer, size, flags)
}

#[inline]
pub unsafe fn dos_delete_var(name: CONST_STRPTR, flags: u32) -> i32 {
    ((*IDOS).DeleteVar)(IDOS, name, flags)
}

#[inline]
pub unsafe fn dos_find_var(name: CONST_STRPTR, r#type: u32) -> *mut LocalVar {
    ((*IDOS).FindVar)(IDOS, name, r#type)
}

#[inline]
pub unsafe fn dos_privatecli_init(dp: *mut DosPacket) -> i32 {
    ((*IDOS).PRIVATECliInit)(IDOS, dp)
}

#[inline]
pub unsafe fn dos_cli_init_newcli(dp: *mut DosPacket) -> i32 {
    ((*IDOS).CliInitNewcli)(IDOS, dp)
}

#[inline]
pub unsafe fn dos_cli_init_run(dp: *mut DosPacket) -> i32 {
    ((*IDOS).CliInitRun)(IDOS, dp)
}

#[inline]
pub unsafe fn dos_write_chars(buf: CONST_STRPTR, buflen: u32) -> i32 {
    ((*IDOS).WriteChars)(IDOS, buf, buflen)
}

#[inline]
pub unsafe fn dos_put_str(str: CONST_STRPTR) -> i32 {
    ((*IDOS).PutStr)(IDOS, str)
}

#[inline]
pub unsafe fn dos_vprintf(format: CONST_STRPTR, argarray: CONST_APTR) -> i32 {
    ((*IDOS).VPrintf)(IDOS, format, argarray)
}

#[inline]
pub unsafe fn dos_parse_pattern_no_case(pat: CONST_STRPTR, buf: STRPTR, buflen: i32) -> i32 {
    ((*IDOS).ParsePatternNoCase)(IDOS, pat, buf, buflen)
}

#[inline]
pub unsafe fn dos_match_pattern_no_case(pat: CONST_STRPTR, str: CONST_STRPTR) -> i32 {
    ((*IDOS).MatchPatternNoCase)(IDOS, pat, str)
}

#[inline]
pub unsafe fn dos_privatedos_get_string(num: i32) -> STRPTR {
    ((*IDOS).PRIVATEDosGetString)(IDOS, num)
}

#[inline]
pub unsafe fn dos_same_device(lock1: u32, lock2: u32) -> i32 {
    ((*IDOS).SameDevice)(IDOS, lock1, lock2)
}

#[inline]
pub unsafe fn dos_obsoleteex_all_end(lock: u32, buffer: *mut ExAllData, size: i32, data: i32, control: *mut ExAllControl) {
    ((*IDOS).OBSOLETEExAllEnd)(IDOS, lock, buffer, size, data, control)
}

#[inline]
pub unsafe fn dos_obsoleteset_owner(name: CONST_STRPTR, owner_info: u32) -> i32 {
    ((*IDOS).OBSOLETESetOwner)(IDOS, name, owner_info)
}

#[inline]
pub unsafe fn dos_get_entry_data() -> i32 {
    ((*IDOS).GetEntryData)(IDOS, )
}

#[inline]
pub unsafe fn dos_read_line_item(buffer: STRPTR, maxchars: i32, taglist: *const TagItem) -> i32 {
    ((*IDOS).ReadLineItem)(IDOS, buffer, maxchars, taglist)
}

#[inline]
pub unsafe fn dos_privateinternal_run_command(seg: u32, stksize: u32, args: CONST_STRPTR, arglen: i32) -> i32 {
    ((*IDOS).PRIVATEInternalRunCommand)(IDOS, seg, stksize, args, arglen)
}

#[inline]
pub unsafe fn dos_get_current_dir() -> u32 {
    ((*IDOS).GetCurrentDir)(IDOS, )
}

#[inline]
pub unsafe fn dos_non_blocking_modify_dos_entry(dl: *mut DosList, mode: i32, arg1: APTR, arg2: APTR) -> i32 {
    ((*IDOS).NonBlockingModifyDosEntry)(IDOS, dl, mode, arg1, arg2)
}

#[inline]
pub unsafe fn dos_seconds_to_date_stamp(seconds: u32, ds: *mut DateStamp) -> *mut DateStamp {
    ((*IDOS).SecondsToDateStamp)(IDOS, seconds, ds)
}

#[inline]
pub unsafe fn dos_date_stamp_to_seconds(ds: *const DateStamp) -> u32 {
    ((*IDOS).DateStampToSeconds)(IDOS, ds)
}

#[inline]
pub unsafe fn dos_fix_date_stamp(ds: *mut DateStamp) -> i32 {
    ((*IDOS).FixDateStamp)(IDOS, ds)
}

#[inline]
pub unsafe fn dos_add_dates(to: *mut DateStamp, from: *const DateStamp) -> i32 {
    ((*IDOS).AddDates)(IDOS, to, from)
}

#[inline]
pub unsafe fn dos_subtract_dates(to: *mut DateStamp, from: *const DateStamp) -> i32 {
    ((*IDOS).SubtractDates)(IDOS, to, from)
}

#[inline]
pub unsafe fn dos_add_segment_tag_list(name: CONST_STRPTR, r#type: i32, tags: *const TagItem) -> i32 {
    ((*IDOS).AddSegmentTagList)(IDOS, name, r#type, tags)
}

#[inline]
pub unsafe fn dos_parse_capture_pattern(pat: CONST_STRPTR, dst: STRPTR, length: i32, casesen: i32) -> i32 {
    ((*IDOS).ParseCapturePattern)(IDOS, pat, dst, length, casesen)
}

#[inline]
pub unsafe fn dos_capture_pattern(pat: CONST_STRPTR, str: CONST_STRPTR, casesen: i32, cap: *mut *mut CapturedExpression) -> i32 {
    ((*IDOS).CapturePattern)(IDOS, pat, str, casesen, cap)
}

#[inline]
pub unsafe fn dos_release_captured_expressions(first: *mut CapturedExpression) {
    ((*IDOS).ReleaseCapturedExpressions)(IDOS, first)
}

#[inline]
pub unsafe fn dos_find_tracked_address(address: CONST_APTR, hook: *mut Hook) {
    ((*IDOS).FindTrackedAddress)(IDOS, address, hook)
}

#[inline]
pub unsafe fn dos_track_address_list(name: CONST_STRPTR, segment: u32, extra_info: CONST_APTR, extra_info_size: i32, aas: *const AddressAndSize, num_pairs: i32) -> i32 {
    ((*IDOS).TrackAddressList)(IDOS, name, segment, extra_info, extra_info_size, aas, num_pairs)
}

#[inline]
pub unsafe fn dos_track_segment_list(name: CONST_STRPTR, segment: u32, extra_info: CONST_APTR, extra_info_size: i32) -> i32 {
    ((*IDOS).TrackSegmentList)(IDOS, name, segment, extra_info, extra_info_size)
}

#[inline]
pub unsafe fn dos_un_track_address(address: APTR) {
    ((*IDOS).UnTrackAddress)(IDOS, address)
}

#[inline]
pub unsafe fn dos_un_track_segment_list(segment: u32) {
    ((*IDOS).UnTrackSegmentList)(IDOS, segment)
}

#[inline]
pub unsafe fn dos_get_exit_data() -> i32 {
    ((*IDOS).GetExitData)(IDOS, )
}

#[inline]
pub unsafe fn dos_put_err_str(str: CONST_STRPTR) -> i32 {
    ((*IDOS).PutErrStr)(IDOS, str)
}

#[inline]
pub unsafe fn dos_error_output() -> u32 {
    ((*IDOS).ErrorOutput)(IDOS, )
}

#[inline]
pub unsafe fn dos_select_error_output(fh: u32) -> u32 {
    ((*IDOS).SelectErrorOutput)(IDOS, fh)
}

#[inline]
pub unsafe fn dos_mount_device(name: CONST_STRPTR, r#type: i32, tags: *const TagItem) -> i32 {
    ((*IDOS).MountDevice)(IDOS, name, r#type, tags)
}

#[inline]
pub unsafe fn dos_set_proc_window(win: CONST_APTR) -> APTR {
    ((*IDOS).SetProcWindow)(IDOS, win)
}

#[inline]
pub unsafe fn dos_find_segment_stack_size(segment: u32) -> u32 {
    ((*IDOS).FindSegmentStackSize)(IDOS, segment)
}

#[inline]
pub unsafe fn dos_calculate_segment_checksum(segment: u32) -> u32 {
    ((*IDOS).CalculateSegmentChecksum)(IDOS, segment)
}

#[inline]
pub unsafe fn dos_alloc_seg_list(entry: CONST_APTR, data: CONST_APTR, datalen: u32, identkey: u32) -> u32 {
    ((*IDOS).AllocSegList)(IDOS, entry, data, datalen, identkey)
}

#[inline]
pub unsafe fn dos_get_seg_list_info(seglist: u32, tags: *const TagItem) -> i32 {
    ((*IDOS).GetSegListInfo)(IDOS, seglist, tags)
}

#[inline]
pub unsafe fn dos_add_seg_list_tail(bseglist_head: u32, bseg_new: u32) -> i32 {
    ((*IDOS).AddSegListTail)(IDOS, bseglist_head, bseg_new)
}

#[inline]
pub unsafe fn dos_dev_name_from_lock(lock: u32, buffer: STRPTR, buflen: i32, mode: i32) -> i32 {
    ((*IDOS).DevNameFromLock)(IDOS, lock, buffer, buflen, mode)
}

#[inline]
pub unsafe fn dos_get_proc_msg_port(proc: *const Process) -> *mut MsgPort {
    ((*IDOS).GetProcMsgPort)(IDOS, proc)
}

#[inline]
pub unsafe fn dos_wait_for_data(stream: u32, data_direction: i32, timeout: i32) -> i32 {
    ((*IDOS).WaitForData)(IDOS, stream, data_direction, timeout)
}

#[inline]
pub unsafe fn dos_set_blocking_mode(stream: u32, new_blocking_mode: i32) -> i32 {
    ((*IDOS).SetBlockingMode)(IDOS, stream, new_blocking_mode)
}

#[inline]
pub unsafe fn dos_set_current_cmd_path_list(pn: *mut PathNode) -> *mut PathNode {
    ((*IDOS).SetCurrentCmdPathList)(IDOS, pn)
}

#[inline]
pub unsafe fn dos_allocate_cmd_path_list(first_lock: u32) -> *mut PathNode {
    ((*IDOS).AllocateCmdPathList)(IDOS, first_lock)
}

#[inline]
pub unsafe fn dos_free_cmd_path_list(pn: *mut PathNode) {
    ((*IDOS).FreeCmdPathList)(IDOS, pn)
}

#[inline]
pub unsafe fn dos_remove_cmd_path_node(pn: *mut PathNode, lock: u32) -> *mut PathNode {
    ((*IDOS).RemoveCmdPathNode)(IDOS, pn, lock)
}

#[inline]
pub unsafe fn dos_add_cmd_path_node(pn: *mut PathNode, lock: u32, r#where: i32) -> *mut PathNode {
    ((*IDOS).AddCmdPathNode)(IDOS, pn, lock, r#where)
}

#[inline]
pub unsafe fn dos_search_cmd_path_list(pn: *const PathNode, h: *const Hook, name: CONST_STRPTR, tags: *const TagItem) -> i32 {
    ((*IDOS).SearchCmdPathList)(IDOS, pn, h, name, tags)
}

#[inline]
pub unsafe fn dos_scan_vars(hook: *const Hook, flags: u32, userdata: CONST_APTR) -> i32 {
    ((*IDOS).ScanVars)(IDOS, hook, flags, userdata)
}

#[inline]
pub unsafe fn dos_get_proc_seg_list(proc: *const Process, flags: u32) -> u32 {
    ((*IDOS).GetProcSegList)(IDOS, proc, flags)
}

#[inline]
pub unsafe fn dos_hex_to_long(string: CONST_STRPTR, value_ptr: *mut u32) -> i32 {
    ((*IDOS).HexToLong)(IDOS, string, value_ptr)
}

#[inline]
pub unsafe fn dos_get_device_proc_flags(name: CONST_STRPTR, odp: *mut DevProc, flags: u32) -> *mut DevProc {
    ((*IDOS).GetDeviceProcFlags)(IDOS, name, odp, flags)
}

#[inline]
pub unsafe fn dos_dos_control(tags: *const TagItem) -> i32 {
    ((*IDOS).DosControl)(IDOS, tags)
}

#[inline]
pub unsafe fn dos_create_dir_tree(name: CONST_STRPTR) -> u32 {
    ((*IDOS).CreateDirTree)(IDOS, name)
}

#[inline]
pub unsafe fn dos_notify_var(name: CONST_STRPTR, hook: *const Hook, flags: i32, userdata: CONST_APTR) -> i32 {
    ((*IDOS).NotifyVar)(IDOS, name, hook, flags, userdata)
}

#[inline]
pub unsafe fn dos_get_disk_file_system_data(name: CONST_STRPTR) -> *mut FileSystemData {
    ((*IDOS).GetDiskFileSystemData)(IDOS, name)
}

#[inline]
pub unsafe fn dos_free_disk_file_system_data(fsd: *mut FileSystemData) {
    ((*IDOS).FreeDiskFileSystemData)(IDOS, fsd)
}

#[inline]
pub unsafe fn dos_fopen(name: CONST_STRPTR, mode: i32, bufsize: i32) -> u32 {
    ((*IDOS).FOpen)(IDOS, name, mode, bufsize)
}

#[inline]
pub unsafe fn dos_fclose(scb: u32) -> i32 {
    ((*IDOS).FClose)(IDOS, scb)
}

#[inline]
pub unsafe fn dos_fopen_from_lock(lock: u32, bufsize: i32) -> u32 {
    ((*IDOS).FOpenFromLock)(IDOS, lock, bufsize)
}

#[inline]
pub unsafe fn dos_dup_cmd_path_list(source: *const PathNode) -> *mut PathNode {
    ((*IDOS).DupCmdPathList)(IDOS, source)
}

#[inline]
pub unsafe fn dos_timed_dos_requester(tags: *const TagItem) -> i32 {
    ((*IDOS).TimedDosRequester)(IDOS, tags)
}

#[inline]
pub unsafe fn dos_rename_dos_entry(dlist: *mut DosList, newname: CONST_STRPTR) -> i32 {
    ((*IDOS).RenameDosEntry)(IDOS, dlist, newname)
}

#[inline]
pub unsafe fn dos_dismount_device(name: CONST_STRPTR, flags: u32, reserved: APTR) -> i32 {
    ((*IDOS).DismountDevice)(IDOS, name, flags, reserved)
}

#[inline]
pub unsafe fn dos_dup_file_handle(scb: u32) -> u32 {
    ((*IDOS).DupFileHandle)(IDOS, scb)
}

#[inline]
pub unsafe fn dos_dev_name_from_fh(scb: u32, buffer: STRPTR, buflen: i32, mode: i32) -> i32 {
    ((*IDOS).DevNameFromFH)(IDOS, scb, buffer, buflen, mode)
}

#[inline]
pub unsafe fn dos_assign_add_to_list(name: CONST_STRPTR, lock: u32, endpos: i32) -> i32 {
    ((*IDOS).AssignAddToList)(IDOS, name, lock, endpos)
}

#[inline]
pub unsafe fn dos_set_file_handle_attr(fh: u32, tags: *const TagItem) -> i32 {
    ((*IDOS).SetFileHandleAttr)(IDOS, fh, tags)
}

#[inline]
pub unsafe fn dos_file_system_attr(tags: *const TagItem) -> i32 {
    ((*IDOS).FileSystemAttr)(IDOS, tags)
}

#[inline]
pub unsafe fn dos_fread_line(fh: u32, frld: *mut FReadLineData) -> i32 {
    ((*IDOS).FReadLine)(IDOS, fh, frld)
}

#[inline]
pub unsafe fn dos_copy_string_bstrto_c(bsrc: u32, dst: STRPTR, siz: u32) -> u32 {
    ((*IDOS).CopyStringBSTRToC)(IDOS, bsrc, dst, siz)
}

#[inline]
pub unsafe fn dos_copy_string_cto_bstr(src: CONST_STRPTR, bdest: u32, siz: u32) -> u32 {
    ((*IDOS).CopyStringCToBSTR)(IDOS, src, bdest, siz)
}

#[inline]
pub unsafe fn dos_get_file_position(fh: u32) -> i64 {
    ((*IDOS).GetFilePosition)(IDOS, fh)
}

#[inline]
pub unsafe fn dos_change_file_position(file: u32, position: i64, offset: i32) -> i32 {
    ((*IDOS).ChangeFilePosition)(IDOS, file, position, offset)
}

#[inline]
pub unsafe fn dos_change_file_size(fh: u32, pos: i64, mode: i32) -> i32 {
    ((*IDOS).ChangeFileSize)(IDOS, fh, pos, mode)
}

#[inline]
pub unsafe fn dos_get_file_size(fh: u32) -> i64 {
    ((*IDOS).GetFileSize)(IDOS, fh)
}

#[inline]
pub unsafe fn dos_do_pkt64(sendport: *mut MsgPort, r#type: i32, arg1: i32, arg2: i64, arg3: i32, arg4: i32, arg5: i64) -> i64 {
    ((*IDOS).DoPkt64)(IDOS, sendport, r#type, arg1, arg2, arg3, arg4, arg5)
}

#[inline]
pub unsafe fn dos_privatedo_pkt64(sendport: *mut MsgPort, r#type: i32, arg1: i32, arg2: i64, arg3: i32, arg4: i32, arg5: i64) -> i64 {
    ((*IDOS).PRIVATEDoPkt64)(IDOS, sendport, r#type, arg1, arg2, arg3, arg4, arg5)
}

#[inline]
pub unsafe fn dos_process_scan(hook: *const Hook, userdata: CONST_APTR, reserved: u32) -> i32 {
    ((*IDOS).ProcessScan)(IDOS, hook, userdata, reserved)
}

#[inline]
pub unsafe fn dos_notify_dos_list_change(process: *mut Process, signalnum: u32, reserved: u32) -> i32 {
    ((*IDOS).NotifyDosListChange)(IDOS, process, signalnum, reserved)
}

#[inline]
pub unsafe fn dos_notify_proc_list_change(process: *mut Process, signalnum: u32, reserved: u32) -> i32 {
    ((*IDOS).NotifyProcListChange)(IDOS, process, signalnum, reserved)
}

#[inline]
pub unsafe fn dos_get_disk_info(tags: *const TagItem) -> i32 {
    ((*IDOS).GetDiskInfo)(IDOS, tags)
}

#[inline]
pub unsafe fn dos_write_protect_volume(name: CONST_STRPTR, on_off: i32, passkey: u32, reserved: i32) -> i32 {
    ((*IDOS).WriteProtectVolume)(IDOS, name, on_off, passkey, reserved)
}

#[inline]
pub unsafe fn dos_examine_object(ctags: *const TagItem) -> *mut ExamineData {
    ((*IDOS).ExamineObject)(IDOS, ctags)
}

#[inline]
pub unsafe fn dos_examine_dir(context: APTR) -> *mut ExamineData {
    ((*IDOS).ExamineDir)(IDOS, context)
}

#[inline]
pub unsafe fn dos_obtain_dir_context(ctags: *const TagItem) -> APTR {
    ((*IDOS).ObtainDirContext)(IDOS, ctags)
}

#[inline]
pub unsafe fn dos_release_dir_context(contx: APTR) {
    ((*IDOS).ReleaseDirContext)(IDOS, contx)
}

#[inline]
pub unsafe fn dos_get_owner_info(tags: *const TagItem) -> i32 {
    ((*IDOS).GetOwnerInfo)(IDOS, tags)
}

#[inline]
pub unsafe fn dos_set_owner_info(tags: *const TagItem) -> i32 {
    ((*IDOS).SetOwnerInfo)(IDOS, tags)
}

#[inline]
pub unsafe fn dos_lock_tag_list(tags: *const TagItem) -> u32 {
    ((*IDOS).LockTagList)(IDOS, tags)
}

#[inline]
pub unsafe fn dos_get_pid(process: *const Process, which: i32) -> u32 {
    ((*IDOS).GetPID)(IDOS, process, which)
}

#[inline]
pub unsafe fn dos_flush_volume(name: CONST_STRPTR) -> i32 {
    ((*IDOS).FlushVolume)(IDOS, name)
}

#[inline]
pub unsafe fn dos_obtain_console_data(ctags: *const TagItem) -> *mut ConsoleWindowData {
    ((*IDOS).ObtainConsoleData)(IDOS, ctags)
}

#[inline]
pub unsafe fn dos_release_console_data(data: *mut ConsoleWindowData) {
    ((*IDOS).ReleaseConsoleData)(IDOS, data)
}

#[inline]
pub unsafe fn dos_serialize(name: CONST_STRPTR) -> i32 {
    ((*IDOS).Serialize)(IDOS, name)
}

#[inline]
pub unsafe fn dos_name_from_port(port: *mut MsgPort, buffer: STRPTR, buflen: i32, add_colon: i32) -> i32 {
    ((*IDOS).NameFromPort)(IDOS, port, buffer, buflen, add_colon)
}

#[inline]
pub unsafe fn dos_dev_name_from_port(port: *mut MsgPort, buffer: STRPTR, buflen: i32, add_colon: i32) -> i32 {
    ((*IDOS).DevNameFromPort)(IDOS, port, buffer, buflen, add_colon)
}

#[inline]
pub unsafe fn dos_same_fh(scb1: u32, scb2: u32) -> i32 {
    ((*IDOS).SameFH)(IDOS, scb1, scb2)
}

#[inline]
pub unsafe fn dos_lock_record(fh: u32, offset: i64, length: i64, mode: u32, timeout: u32) -> i32 {
    ((*IDOS).LockRecord)(IDOS, fh, offset, length, mode, timeout)
}

#[inline]
pub unsafe fn dos_un_lock_record(fh: u32, offset: i64, length: i64) -> i32 {
    ((*IDOS).UnLockRecord)(IDOS, fh, offset, length)
}

#[inline]
pub unsafe fn dos_is_file_system_port(port: *mut MsgPort) -> i32 {
    ((*IDOS).IsFileSystemPort)(IDOS, port)
}

#[inline]
pub unsafe fn dos_inhibit_port(port: *mut MsgPort, state: i32) -> i32 {
    ((*IDOS).InhibitPort)(IDOS, port, state)
}

#[inline]
pub unsafe fn dos_format_port(port: *mut MsgPort, volumename: CONST_STRPTR, dostype: u32, flags: u32) -> i32 {
    ((*IDOS).FormatPort)(IDOS, port, volumename, dostype, flags)
}

#[inline]
pub unsafe fn dos_serialize_port(port: *mut MsgPort) -> i32 {
    ((*IDOS).SerializePort)(IDOS, port)
}

#[inline]
pub unsafe fn dos_flush_volume_port(port: *mut MsgPort) -> i32 {
    ((*IDOS).FlushVolumePort)(IDOS, port)
}

#[inline]
pub unsafe fn dos_file_handle_scan(hook: *const Hook, userdata: CONST_APTR, reserved: u32) -> i32 {
    ((*IDOS).FileHandleScan)(IDOS, hook, userdata, reserved)
}

#[inline]
pub unsafe fn dos_get_file_system_vector_port(port: *mut MsgPort, min_version: u32) -> *mut FileSystemVectorPort {
    ((*IDOS).GetFileSystemVectorPort)(IDOS, port, min_version)
}

#[inline]
pub unsafe fn dos_resolve_path(port: *mut MsgPort, path: CONST_STRPTR, inlock: u32, out: STRPTR, outlen: u32, outdir: *mut u32, slcount: *mut u32) -> i32 {
    ((*IDOS).ResolvePath)(IDOS, port, path, inlock, out, outlen, outdir, slcount)
}

#[inline]
pub unsafe fn dos_write_protect_volume_port(port: *mut MsgPort, on_off: i32, passkey: u32, reserved: i32) -> i32 {
    ((*IDOS).WriteProtectVolumePort)(IDOS, port, on_off, passkey, reserved)
}

#[inline]
pub unsafe fn dos_async_io(tags: *const TagItem) -> i32 {
    ((*IDOS).AsyncIO)(IDOS, tags)
}

#[inline]
pub unsafe fn dos_wait_for_child_exit(pid: u32) -> i32 {
    ((*IDOS).WaitForChildExit)(IDOS, pid)
}

#[inline]
pub unsafe fn dos_check_for_child_exit(pid: u32) -> i32 {
    ((*IDOS).CheckForChildExit)(IDOS, pid)
}

