//! IExec global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::exec::*;

// ---- IExec (ExecIFace) ----

extern "C" {
    pub static IExec: *mut ExecIFace;
}

#[inline]
pub unsafe fn exec_add_head(list: *mut List, node: *mut Node) {
    ((*IExec).AddHead)(IExec, list, node)
}

#[inline]
pub unsafe fn exec_add_mem_handler(memHandler: *mut Interrupt) {
    ((*IExec).AddMemHandler)(IExec, memHandler)
}

#[inline]
pub unsafe fn exec_add_mem_list(size: u32, attributes: u32, pri: i32, base: APTR, name: CONST_STRPTR) {
    ((*IExec).AddMemList)(IExec, size, attributes, pri, base, name)
}

#[inline]
pub unsafe fn exec_add_tail(list: *mut List, node: *mut Node) {
    ((*IExec).AddTail)(IExec, list, node)
}

#[inline]
pub unsafe fn exec_alloc_abs(byteSize: u32, location: APTR) -> APTR {
    ((*IExec).AllocAbs)(IExec, byteSize, location)
}

#[inline]
pub unsafe fn exec_allocate(memHeader: *mut MemHeader, byteSize: u32) -> APTR {
    ((*IExec).Allocate)(IExec, memHeader, byteSize)
}

#[inline]
pub unsafe fn exec_alloc_entry(memList: *mut MemList) -> *mut MemList {
    ((*IExec).AllocEntry)(IExec, memList)
}

#[inline]
pub unsafe fn exec_alloc_mem(byteSize: u32, attributes: u32) -> APTR {
    ((*IExec).AllocMem)(IExec, byteSize, attributes)
}

#[inline]
pub unsafe fn exec_alloc_pooled(poolHeader: APTR, memSize: u32) -> APTR {
    ((*IExec).AllocPooled)(IExec, poolHeader, memSize)
}

#[inline]
pub unsafe fn exec_alloc_vec(byteSize: u32, attributes: u32) -> APTR {
    ((*IExec).AllocVec)(IExec, byteSize, attributes)
}

#[inline]
pub unsafe fn exec_alloc_vec_pooled(poolHeader: APTR, size: u32) -> APTR {
    ((*IExec).AllocVecPooled)(IExec, poolHeader, size)
}

#[inline]
pub unsafe fn exec_avail_mem(attributes: u32) -> u32 {
    ((*IExec).AvailMem)(IExec, attributes)
}

#[inline]
pub unsafe fn exec_copy_mem(source: CONST_APTR, dest: APTR, size: u32) {
    ((*IExec).CopyMem)(IExec, source, dest, size)
}

#[inline]
pub unsafe fn exec_copy_mem_quick(source: CONST_APTR, dest: APTR, size: u32) {
    ((*IExec).CopyMemQuick)(IExec, source, dest, size)
}

#[inline]
pub unsafe fn exec_create_pool(memFlags: u32, puddleSize: u32, threshSize: u32) -> APTR {
    ((*IExec).CreatePool)(IExec, memFlags, puddleSize, threshSize)
}

#[inline]
pub unsafe fn exec_deallocate(memHeader: *mut MemHeader, memoryBlock: APTR, byteSize: u32) {
    ((*IExec).Deallocate)(IExec, memHeader, memoryBlock, byteSize)
}

#[inline]
pub unsafe fn exec_delete_pool(poolHeader: APTR) {
    ((*IExec).DeletePool)(IExec, poolHeader)
}

#[inline]
pub unsafe fn exec_enqueue(list: *mut List, node: *mut Node) {
    ((*IExec).Enqueue)(IExec, list, node)
}

#[inline]
pub unsafe fn exec_find_name(start: *mut List, name: CONST_STRPTR) -> *mut Node {
    ((*IExec).FindName)(IExec, start, name)
}

#[inline]
pub unsafe fn exec_find_iname(start: *mut List, name: CONST_STRPTR) -> *mut Node {
    ((*IExec).FindIName)(IExec, start, name)
}

#[inline]
pub unsafe fn exec_forbid() {
    ((*IExec).Forbid)(IExec, )
}

#[inline]
pub unsafe fn exec_free_entry(memList: *mut MemList) {
    ((*IExec).FreeEntry)(IExec, memList)
}

#[inline]
pub unsafe fn exec_free_mem(memoryBlock: APTR, byteSize: u32) {
    ((*IExec).FreeMem)(IExec, memoryBlock, byteSize)
}

#[inline]
pub unsafe fn exec_free_pooled(poolHeader: APTR, memory: APTR, memSize: u32) {
    ((*IExec).FreePooled)(IExec, poolHeader, memory, memSize)
}

#[inline]
pub unsafe fn exec_free_vec(memoryBlock: APTR) {
    ((*IExec).FreeVec)(IExec, memoryBlock)
}

#[inline]
pub unsafe fn exec_free_vec_pooled(poolHeader: APTR, memory: APTR) {
    ((*IExec).FreeVecPooled)(IExec, poolHeader, memory)
}

#[inline]
pub unsafe fn exec_init_data(initTab: CONST_APTR, memory: APTR, size: u32) {
    ((*IExec).InitData)(IExec, initTab, memory, size)
}

#[inline]
pub unsafe fn exec_init_struct(initTable: CONST_APTR, memory: APTR, size: u32) {
    ((*IExec).InitStruct)(IExec, initTable, memory, size)
}

#[inline]
pub unsafe fn exec_insert(list: *mut List, node: *mut Node, listNode: *mut Node) {
    ((*IExec).Insert)(IExec, list, node, listNode)
}

#[inline]
pub unsafe fn exec_make_interface(library: *mut Library, taglist: *const TagItem) -> *mut Interface {
    ((*IExec).MakeInterface)(IExec, library, taglist)
}

#[inline]
pub unsafe fn exec_permit() {
    ((*IExec).Permit)(IExec, )
}

#[inline]
pub unsafe fn exec_raw_do_fmt(formatString: CONST_STRPTR, dataStream: CONST_APTR, PutChProc: APTR, PutChData: APTR) -> APTR {
    ((*IExec).RawDoFmt)(IExec, formatString, dataStream, PutChProc, PutChData)
}

#[inline]
pub unsafe fn exec_rem_head(list: *mut List) -> *mut Node {
    ((*IExec).RemHead)(IExec, list)
}

#[inline]
pub unsafe fn exec_rem_mem_handler(memHandler: *mut Interrupt) {
    ((*IExec).RemMemHandler)(IExec, memHandler)
}

#[inline]
pub unsafe fn exec_remove(node: *mut Node) {
    ((*IExec).Remove)(IExec, node)
}

#[inline]
pub unsafe fn exec_rem_tail(list: *mut List) -> *mut Node {
    ((*IExec).RemTail)(IExec, list)
}

#[inline]
pub unsafe fn exec_type_of_mem(address: CONST_APTR) -> u32 {
    ((*IExec).TypeOfMem)(IExec, address)
}

#[inline]
pub unsafe fn exec_init_resident(resident: *const Resident, segList: u32) -> APTR {
    ((*IExec).InitResident)(IExec, resident, segList)
}

#[inline]
pub unsafe fn exec_init_code(startClass: u32, version: u32) {
    ((*IExec).InitCode)(IExec, startClass, version)
}

#[inline]
pub unsafe fn exec_sum_kick_data() -> u32 {
    ((*IExec).SumKickData)(IExec, )
}

#[inline]
pub unsafe fn exec_add_task(task: *mut Task, initialPC: CONST_APTR, finalPC: CONST_APTR, tagList: *const TagItem) -> APTR {
    ((*IExec).AddTask)(IExec, task, initialPC, finalPC, tagList)
}

#[inline]
pub unsafe fn exec_disable() {
    ((*IExec).Disable)(IExec, )
}

#[inline]
pub unsafe fn exec_enable() {
    ((*IExec).Enable)(IExec, )
}

#[inline]
pub unsafe fn exec_reschedule() {
    ((*IExec).Reschedule)(IExec, )
}

#[inline]
pub unsafe fn exec_find_task(name: CONST_STRPTR) -> *mut Task {
    ((*IExec).FindTask)(IExec, name)
}

#[inline]
pub unsafe fn exec_rem_task(task: *mut Task) {
    ((*IExec).RemTask)(IExec, task)
}

#[inline]
pub unsafe fn exec_set_task_pri(task: *mut Task, priority: i8) -> i8 {
    ((*IExec).SetTaskPri)(IExec, task, priority)
}

#[inline]
pub unsafe fn exec_stack_swap(newstack: *mut StackSwapStruct) {
    ((*IExec).StackSwap)(IExec, newstack)
}

#[inline]
pub unsafe fn exec_alloc_signal(signalNum: i8) -> i8 {
    ((*IExec).AllocSignal)(IExec, signalNum)
}

#[inline]
pub unsafe fn exec_free_signal(signalNum: i8) {
    ((*IExec).FreeSignal)(IExec, signalNum)
}

#[inline]
pub unsafe fn exec_set_except(newSignals: u32, signalMask: u32) -> u32 {
    ((*IExec).SetExcept)(IExec, newSignals, signalMask)
}

#[inline]
pub unsafe fn exec_set_signal(newSignals: u32, signalMask: u32) -> u32 {
    ((*IExec).SetSignal)(IExec, newSignals, signalMask)
}

#[inline]
pub unsafe fn exec_signal(task: *mut Task, signals: u32) {
    ((*IExec).Signal)(IExec, task, signals)
}

#[inline]
pub unsafe fn exec_wait(signalSet: u32) -> u32 {
    ((*IExec).Wait)(IExec, signalSet)
}

#[inline]
pub unsafe fn exec_add_port(port: *mut MsgPort) {
    ((*IExec).AddPort)(IExec, port)
}

#[inline]
pub unsafe fn exec_create_port(name: CONST_STRPTR, pri: i8) -> *mut MsgPort {
    ((*IExec).CreatePort)(IExec, name, pri)
}

#[inline]
pub unsafe fn exec_create_msg_port() -> *mut MsgPort {
    ((*IExec).CreateMsgPort)(IExec, )
}

#[inline]
pub unsafe fn exec_delete_port(port: *mut MsgPort) {
    ((*IExec).DeletePort)(IExec, port)
}

#[inline]
pub unsafe fn exec_delete_msg_port(port: *mut MsgPort) {
    ((*IExec).DeleteMsgPort)(IExec, port)
}

#[inline]
pub unsafe fn exec_find_port(name: CONST_STRPTR) -> *mut MsgPort {
    ((*IExec).FindPort)(IExec, name)
}

#[inline]
pub unsafe fn exec_get_msg(port: *mut MsgPort) -> *mut Message {
    ((*IExec).GetMsg)(IExec, port)
}

#[inline]
pub unsafe fn exec_put_msg(port: *mut MsgPort, message: *mut Message) {
    ((*IExec).PutMsg)(IExec, port, message)
}

#[inline]
pub unsafe fn exec_rem_port(port: *mut MsgPort) {
    ((*IExec).RemPort)(IExec, port)
}

#[inline]
pub unsafe fn exec_reply_msg(message: *mut Message) {
    ((*IExec).ReplyMsg)(IExec, message)
}

#[inline]
pub unsafe fn exec_wait_port(port: *mut MsgPort) -> *mut Message {
    ((*IExec).WaitPort)(IExec, port)
}

#[inline]
pub unsafe fn exec_cause(interrupt: *mut Interrupt) {
    ((*IExec).Cause)(IExec, interrupt)
}

#[inline]
pub unsafe fn exec_add_semaphore(semaphore: *mut SignalSemaphore) {
    ((*IExec).AddSemaphore)(IExec, semaphore)
}

#[inline]
pub unsafe fn exec_attempt_semaphore(semaphore: *mut SignalSemaphore) -> i32 {
    ((*IExec).AttemptSemaphore)(IExec, semaphore)
}

#[inline]
pub unsafe fn exec_attempt_semaphore_shared(semaphore: *mut SignalSemaphore) -> i32 {
    ((*IExec).AttemptSemaphoreShared)(IExec, semaphore)
}

#[inline]
pub unsafe fn exec_find_semaphore(name: CONST_STRPTR) -> *mut SignalSemaphore {
    ((*IExec).FindSemaphore)(IExec, name)
}

#[inline]
pub unsafe fn exec_init_semaphore(semaphore: *mut SignalSemaphore) {
    ((*IExec).InitSemaphore)(IExec, semaphore)
}

#[inline]
pub unsafe fn exec_obtain_semaphore(semaphore: *mut SignalSemaphore) {
    ((*IExec).ObtainSemaphore)(IExec, semaphore)
}

#[inline]
pub unsafe fn exec_obtain_semaphore_list(list: *mut List) {
    ((*IExec).ObtainSemaphoreList)(IExec, list)
}

#[inline]
pub unsafe fn exec_obtain_semaphore_shared(semaphore: *mut SignalSemaphore) {
    ((*IExec).ObtainSemaphoreShared)(IExec, semaphore)
}

#[inline]
pub unsafe fn exec_procure(semaphore: *mut SignalSemaphore, bidMessage: *mut SemaphoreMessage) {
    ((*IExec).Procure)(IExec, semaphore, bidMessage)
}

#[inline]
pub unsafe fn exec_release_semaphore(semaphore: *mut SignalSemaphore) {
    ((*IExec).ReleaseSemaphore)(IExec, semaphore)
}

#[inline]
pub unsafe fn exec_release_semaphore_list(list: *mut List) {
    ((*IExec).ReleaseSemaphoreList)(IExec, list)
}

#[inline]
pub unsafe fn exec_rem_semaphore(semaphore: *mut SignalSemaphore) {
    ((*IExec).RemSemaphore)(IExec, semaphore)
}

#[inline]
pub unsafe fn exec_vacate(semaphore: *mut SignalSemaphore, bidMessage: *mut SemaphoreMessage) {
    ((*IExec).Vacate)(IExec, semaphore, bidMessage)
}

#[inline]
pub unsafe fn exec_create_task(name: CONST_STRPTR, pri: i32, initPC: CONST_APTR, stackSize: u32, tagList: *const TagItem) -> *mut Task {
    ((*IExec).CreateTask)(IExec, name, pri, initPC, stackSize, tagList)
}

#[inline]
pub unsafe fn exec_delete_task(task: *mut Task) {
    ((*IExec).DeleteTask)(IExec, task)
}

#[inline]
pub unsafe fn exec_sum_library(library: *mut Library) {
    ((*IExec).SumLibrary)(IExec, library)
}

#[inline]
pub unsafe fn exec_create_library(taglist: *const TagItem) -> *mut Library {
    ((*IExec).CreateLibrary)(IExec, taglist)
}

#[inline]
pub unsafe fn exec_open_library(name: CONST_STRPTR, version: u32) -> *mut Library {
    ((*IExec).OpenLibrary)(IExec, name, version)
}

#[inline]
pub unsafe fn exec_close_library(library: *mut Library) -> APTR {
    ((*IExec).CloseLibrary)(IExec, library)
}

#[inline]
pub unsafe fn exec_add_library(library: *mut Library) {
    ((*IExec).AddLibrary)(IExec, library)
}

#[inline]
pub unsafe fn exec_rem_library(library: *mut Library) -> u32 {
    ((*IExec).RemLibrary)(IExec, library)
}

#[inline]
pub unsafe fn exec_add_device(device: *mut Device) {
    ((*IExec).AddDevice)(IExec, device)
}

#[inline]
pub unsafe fn exec_rem_device(device: *mut Device) -> u32 {
    ((*IExec).RemDevice)(IExec, device)
}

#[inline]
pub unsafe fn exec_get_interface(library: *mut Library, name: CONST_STRPTR, version: u32, taglist: *const TagItem) -> *mut Interface {
    ((*IExec).GetInterface)(IExec, library, name, version, taglist)
}

#[inline]
pub unsafe fn exec_drop_interface(interface: *mut Interface) {
    ((*IExec).DropInterface)(IExec, interface)
}

#[inline]
pub unsafe fn exec_add_interface(library: *mut Library, interface: *mut Interface) {
    ((*IExec).AddInterface)(IExec, library, interface)
}

#[inline]
pub unsafe fn exec_rem_interface(interface: *mut Interface) {
    ((*IExec).RemInterface)(IExec, interface)
}

#[inline]
pub unsafe fn exec_sum_interface(interface: *mut Interface) {
    ((*IExec).SumInterface)(IExec, interface)
}

#[inline]
pub unsafe fn exec_find_resident(name: CONST_STRPTR) -> *mut Resident {
    ((*IExec).FindResident)(IExec, name)
}

#[inline]
pub unsafe fn exec_set_method(interface: *mut Interface, funcOffset: i32, newFunc: CONST_APTR) -> APTR {
    ((*IExec).SetMethod)(IExec, interface, funcOffset, newFunc)
}

#[inline]
pub unsafe fn exec_delete_interface(interface: *mut Interface) {
    ((*IExec).DeleteInterface)(IExec, interface)
}

#[inline]
pub unsafe fn exec_delete_library(library: *mut Library) {
    ((*IExec).DeleteLibrary)(IExec, library)
}

#[inline]
pub unsafe fn exec_set_function(library: *mut Library, funcOffset: i32, newFunc: CONST_APTR) -> APTR {
    ((*IExec).SetFunction)(IExec, library, funcOffset, newFunc)
}

#[inline]
pub unsafe fn exec_cache_clear_e(address: APTR, length: u32, caches: u32) {
    ((*IExec).CacheClearE)(IExec, address, length, caches)
}

#[inline]
pub unsafe fn exec_cache_clear_u() {
    ((*IExec).CacheClearU)(IExec, )
}

#[inline]
pub unsafe fn exec_make_functions(target: APTR, functionArray: CONST_APTR, funcDispBase: CONST_APTR) -> u32 {
    ((*IExec).MakeFunctions)(IExec, target, functionArray, funcDispBase)
}

#[inline]
pub unsafe fn exec_open_device(devName: CONST_STRPTR, unitNumber: u32, ioRequest: *mut IORequest, flags: u32) -> i32 {
    ((*IExec).OpenDevice)(IExec, devName, unitNumber, ioRequest, flags)
}

#[inline]
pub unsafe fn exec_close_device(ioRequest: *mut IORequest) -> APTR {
    ((*IExec).CloseDevice)(IExec, ioRequest)
}

#[inline]
pub unsafe fn exec_create_iorequest(ioReplyPort: *const MsgPort, size: u32) -> *mut IORequest {
    ((*IExec).CreateIORequest)(IExec, ioReplyPort, size)
}

#[inline]
pub unsafe fn exec_delete_iorequest(ioRequest: *mut IORequest) {
    ((*IExec).DeleteIORequest)(IExec, ioRequest)
}

#[inline]
pub unsafe fn exec_abort_io(ioRequest: *mut IORequest) {
    ((*IExec).AbortIO)(IExec, ioRequest)
}

#[inline]
pub unsafe fn exec_check_io(ioRequest: *mut IORequest) -> *mut IORequest {
    ((*IExec).CheckIO)(IExec, ioRequest)
}

#[inline]
pub unsafe fn exec_do_io(ioRequest: *mut IORequest) -> i8 {
    ((*IExec).DoIO)(IExec, ioRequest)
}

#[inline]
pub unsafe fn exec_send_io(ioRequest: *mut IORequest) {
    ((*IExec).SendIO)(IExec, ioRequest)
}

#[inline]
pub unsafe fn exec_begin_io(ioRequest: *mut IORequest) {
    ((*IExec).BeginIO)(IExec, ioRequest)
}

#[inline]
pub unsafe fn exec_wait_io(ioRequest: *mut IORequest) -> i8 {
    ((*IExec).WaitIO)(IExec, ioRequest)
}

#[inline]
pub unsafe fn exec_add_resource(resource: APTR) {
    ((*IExec).AddResource)(IExec, resource)
}

#[inline]
pub unsafe fn exec_rem_resource(resource: APTR) {
    ((*IExec).RemResource)(IExec, resource)
}

#[inline]
pub unsafe fn exec_open_resource(resName: CONST_STRPTR) -> APTR {
    ((*IExec).OpenResource)(IExec, resName)
}

#[inline]
pub unsafe fn exec_add_int_server(intNum: u32, interrupt: *mut Interrupt) -> u32 {
    ((*IExec).AddIntServer)(IExec, intNum, interrupt)
}

#[inline]
pub unsafe fn exec_rem_int_server(intNum: u32, interrupt: *mut Interrupt) {
    ((*IExec).RemIntServer)(IExec, intNum, interrupt)
}

#[inline]
pub unsafe fn exec_set_int_vector(intNum: u32, interrupt: *const Interrupt) -> *mut Interrupt {
    ((*IExec).SetIntVector)(IExec, intNum, interrupt)
}

#[inline]
pub unsafe fn exec_obtain_quick_vector(interruptCode: APTR) -> u32 {
    ((*IExec).ObtainQuickVector)(IExec, interruptCode)
}

#[inline]
pub unsafe fn exec_alert(alertNum: u32) {
    ((*IExec).Alert)(IExec, alertNum)
}

#[inline]
pub unsafe fn exec_super_state() -> APTR {
    ((*IExec).SuperState)(IExec, )
}

#[inline]
pub unsafe fn exec_user_state(sysStack: APTR) {
    ((*IExec).UserState)(IExec, sysStack)
}

#[inline]
pub unsafe fn exec_supervisor(userFunc: APTR) -> u32 {
    ((*IExec).Supervisor)(IExec, userFunc)
}

#[inline]
pub unsafe fn exec_set_task_trap(trapNum: u32, trapCode: CONST_APTR, trapData: CONST_APTR) -> u32 {
    ((*IExec).SetTaskTrap)(IExec, trapNum, trapCode, trapData)
}

#[inline]
pub unsafe fn exec_alloc_trap(trapNum: u32) -> i32 {
    ((*IExec).AllocTrap)(IExec, trapNum)
}

#[inline]
pub unsafe fn exec_free_trap(trapNum: u32) {
    ((*IExec).FreeTrap)(IExec, trapNum)
}

#[inline]
pub unsafe fn exec_get_cc() -> u16 {
    ((*IExec).GetCC)(IExec, )
}

#[inline]
pub unsafe fn exec_set_sr(newSR: u32, mask: u32) -> u32 {
    ((*IExec).SetSR)(IExec, newSR, mask)
}

#[inline]
pub unsafe fn exec_avl_add_node(root: *mut *mut AVLNode, node: *mut AVLNode, func: APTR) -> *mut AVLNode {
    ((*IExec).AVL_AddNode)(IExec, root, node, func)
}

#[inline]
pub unsafe fn exec_avl_find_first_node(root: *const AVLNode) -> *mut AVLNode {
    ((*IExec).AVL_FindFirstNode)(IExec, root)
}

#[inline]
pub unsafe fn exec_avl_find_last_node(root: *const AVLNode) -> *mut AVLNode {
    ((*IExec).AVL_FindLastNode)(IExec, root)
}

#[inline]
pub unsafe fn exec_avl_find_next_node_by_address(root: *const AVLNode) -> *mut AVLNode {
    ((*IExec).AVL_FindNextNodeByAddress)(IExec, root)
}

#[inline]
pub unsafe fn exec_avl_find_next_node_by_key(root: *const AVLNode, key: APTR, func: APTR) -> *mut AVLNode {
    ((*IExec).AVL_FindNextNodeByKey)(IExec, root, key, func)
}

#[inline]
pub unsafe fn exec_avl_find_node(root: *const AVLNode, key: APTR, func: APTR) -> *mut AVLNode {
    ((*IExec).AVL_FindNode)(IExec, root, key, func)
}

#[inline]
pub unsafe fn exec_avl_find_prev_node_by_address(root: *const AVLNode) -> *mut AVLNode {
    ((*IExec).AVL_FindPrevNodeByAddress)(IExec, root)
}

#[inline]
pub unsafe fn exec_avl_find_prev_node_by_key(root: *const AVLNode, key: APTR, func: APTR) -> *mut AVLNode {
    ((*IExec).AVL_FindPrevNodeByKey)(IExec, root, key, func)
}

#[inline]
pub unsafe fn exec_avl_rem_node_by_address(root: *mut *mut AVLNode, node: *mut AVLNode) -> *mut AVLNode {
    ((*IExec).AVL_RemNodeByAddress)(IExec, root, node)
}

#[inline]
pub unsafe fn exec_avl_rem_node_by_key(root: *mut *mut AVLNode, key: APTR, func: APTR) -> *mut AVLNode {
    ((*IExec).AVL_RemNodeByKey)(IExec, root, key, func)
}

#[inline]
pub unsafe fn exec_cache_control(cacheBits: u32, cacheMask: u32) -> u32 {
    ((*IExec).CacheControl)(IExec, cacheBits, cacheMask)
}

#[inline]
pub unsafe fn exec_lock_mem(baseAddress: APTR, size: u32) -> u32 {
    ((*IExec).LockMem)(IExec, baseAddress, size)
}

#[inline]
pub unsafe fn exec_unlock_mem(baseAddress: APTR, size: u32) {
    ((*IExec).UnlockMem)(IExec, baseAddress, size)
}

#[inline]
pub unsafe fn exec_cache_pre_dma(vaddr: CONST_APTR, length: *mut u32, flags: u32) -> APTR {
    ((*IExec).CachePreDMA)(IExec, vaddr, length, flags)
}

#[inline]
pub unsafe fn exec_cache_post_dma(vaddr: CONST_APTR, length: *mut u32, flags: u32) {
    ((*IExec).CachePostDMA)(IExec, vaddr, length, flags)
}

#[inline]
pub unsafe fn exec_start_dma(startAddr: CONST_APTR, blockSize: u32, flags: u32) -> u32 {
    ((*IExec).StartDMA)(IExec, startAddr, blockSize, flags)
}

#[inline]
pub unsafe fn exec_end_dma(startAddr: CONST_APTR, blockSize: u32, flags: u32) {
    ((*IExec).EndDMA)(IExec, startAddr, blockSize, flags)
}

#[inline]
pub unsafe fn exec_get_dmalist(startAddr: CONST_APTR, blockSize: u32, flags: u32, dmaList: *mut DMAEntry) {
    ((*IExec).GetDMAList)(IExec, startAddr, blockSize, flags, dmaList)
}

#[inline]
pub unsafe fn exec_add_trackable(usingTask: *mut Task, object: APTR, destFunc: *mut Hook) -> *mut Trackable {
    ((*IExec).AddTrackable)(IExec, usingTask, object, destFunc)
}

#[inline]
pub unsafe fn exec_find_trackable(usingTask: *mut Task, object: APTR) -> *mut Trackable {
    ((*IExec).FindTrackable)(IExec, usingTask, object)
}

#[inline]
pub unsafe fn exec_rem_trackable(usingTask: *mut Task, trackable: *mut Trackable) -> *mut Trackable {
    ((*IExec).RemTrackable)(IExec, usingTask, trackable)
}

#[inline]
pub unsafe fn exec_delete_trackable(trackable: *mut Trackable) {
    ((*IExec).DeleteTrackable)(IExec, trackable)
}

#[inline]
pub unsafe fn exec_alloc_sys_object(r#type: u32, tags: *const TagItem) -> APTR {
    ((*IExec).AllocSysObject)(IExec, r#type, tags)
}

#[inline]
pub unsafe fn exec_free_sys_object(r#type: u32, object: APTR) {
    ((*IExec).FreeSysObject)(IExec, r#type, object)
}

#[inline]
pub unsafe fn exec_suspend_task(whichTask: *mut Task, flags: u32) {
    ((*IExec).SuspendTask)(IExec, whichTask, flags)
}

#[inline]
pub unsafe fn exec_restart_task(whichTask: *mut Task, flags: u32) {
    ((*IExec).RestartTask)(IExec, whichTask, flags)
}

#[inline]
pub unsafe fn exec_move_list(destinationList: *mut List, sourceList: *mut List) {
    ((*IExec).MoveList)(IExec, destinationList, sourceList)
}

#[inline]
pub unsafe fn exec_new_list(list: *mut List) {
    ((*IExec).NewList)(IExec, list)
}

#[inline]
pub unsafe fn exec_new_min_list(list: *mut MinList) {
    ((*IExec).NewMinList)(IExec, list)
}

#[inline]
pub unsafe fn exec_cold_reboot() {
    ((*IExec).ColdReboot)(IExec, )
}

#[inline]
pub unsafe fn exec_make_library(vectors: CONST_APTR, structure: CONST_APTR, init: CONST_APTR, dataSize: u32, segList: APTR) -> *mut Library {
    ((*IExec).MakeLibrary)(IExec, vectors, structure, init, dataSize, segList)
}

#[inline]
pub unsafe fn exec_emulate(InitPC: CONST_APTR, tagList: *const TagItem) -> u32 {
    ((*IExec).Emulate)(IExec, InitPC, tagList)
}

#[inline]
pub unsafe fn exec_is_native(code: CONST_APTR) -> u32 {
    ((*IExec).IsNative)(IExec, code)
}

#[inline]
pub unsafe fn exec_get_cpuinfo(TagList: *const TagItem) {
    ((*IExec).GetCPUInfo)(IExec, TagList)
}

#[inline]
pub unsafe fn exec_owner_of_mem(Address: CONST_APTR) -> *mut Task {
    ((*IExec).OwnerOfMem)(IExec, Address)
}

#[inline]
pub unsafe fn exec_add_reset_callback(resetCallback: *mut Interrupt) -> u32 {
    ((*IExec).AddResetCallback)(IExec, resetCallback)
}

#[inline]
pub unsafe fn exec_rem_reset_callback(resetCallback: *mut Interrupt) {
    ((*IExec).RemResetCallback)(IExec, resetCallback)
}

#[inline]
pub unsafe fn exec_item_pool_alloc(itemPool: APTR) -> APTR {
    ((*IExec).ItemPoolAlloc)(IExec, itemPool)
}

#[inline]
pub unsafe fn exec_item_pool_free(itemPool: APTR, item: APTR) {
    ((*IExec).ItemPoolFree)(IExec, itemPool, item)
}

#[inline]
pub unsafe fn exec_item_pool_gc(itemPool: APTR) {
    ((*IExec).ItemPoolGC)(IExec, itemPool)
}

#[inline]
pub unsafe fn exec_item_pool_control(itemPool: APTR, tagList: *const TagItem) -> u32 {
    ((*IExec).ItemPoolControl)(IExec, itemPool, tagList)
}

#[inline]
pub unsafe fn exec_item_pool_flush(itemPool: APTR) {
    ((*IExec).ItemPoolFlush)(IExec, itemPool)
}

#[inline]
pub unsafe fn exec_get_head(list: *mut List) -> *mut Node {
    ((*IExec).GetHead)(IExec, list)
}

#[inline]
pub unsafe fn exec_get_tail(list: *mut List) -> *mut Node {
    ((*IExec).GetTail)(IExec, list)
}

#[inline]
pub unsafe fn exec_get_succ(node: *mut Node) -> *mut Node {
    ((*IExec).GetSucc)(IExec, node)
}

#[inline]
pub unsafe fn exec_get_pred(node: *mut Node) -> *mut Node {
    ((*IExec).GetPred)(IExec, node)
}

#[inline]
pub unsafe fn exec_ice_cold_reboot() {
    ((*IExec).IceColdReboot)(IExec, )
}

#[inline]
pub unsafe fn exec_rmap_alloc(Map: APTR, size: u32, flags: u32) -> APTR {
    ((*IExec).RMapAlloc)(IExec, Map, size, flags)
}

#[inline]
pub unsafe fn exec_rmap_free(Map: APTR, addr: APTR, size: u32) {
    ((*IExec).RMapFree)(IExec, Map, addr, size)
}

#[inline]
pub unsafe fn exec_alloc_vec_tag_list(size: u32, tags: *const TagItem) -> APTR {
    ((*IExec).AllocVecTagList)(IExec, size, tags)
}

#[inline]
pub unsafe fn exec_rmap_ext_alloc(Map: APTR, size: u32, alignment: u32, flags: u32) -> APTR {
    ((*IExec).RMapExtAlloc)(IExec, Map, size, alignment, flags)
}

#[inline]
pub unsafe fn exec_rmap_ext_free(Map: APTR, addr: APTR, size: u32) {
    ((*IExec).RMapExtFree)(IExec, Map, addr, size)
}

#[inline]
pub unsafe fn exec_alloc_named_memory(byteSize: u32, space: CONST_STRPTR, name: CONST_STRPTR, tagList: *mut TagItem) -> APTR {
    ((*IExec).AllocNamedMemory)(IExec, byteSize, space, name, tagList)
}

#[inline]
pub unsafe fn exec_free_named_memory(space: CONST_STRPTR, name: CONST_STRPTR) -> u32 {
    ((*IExec).FreeNamedMemory)(IExec, space, name)
}

#[inline]
pub unsafe fn exec_find_named_memory(space: CONST_STRPTR, name: CONST_STRPTR) -> *mut () {
    ((*IExec).FindNamedMemory)(IExec, space, name)
}

#[inline]
pub unsafe fn exec_update_named_memory(space: CONST_STRPTR, name: CONST_STRPTR) {
    ((*IExec).UpdateNamedMemory)(IExec, space, name)
}

#[inline]
pub unsafe fn exec_lock_named_memory(space: CONST_STRPTR, name: CONST_STRPTR) -> *mut () {
    ((*IExec).LockNamedMemory)(IExec, space, name)
}

#[inline]
pub unsafe fn exec_attempt_named_memory(space: CONST_STRPTR, name: CONST_STRPTR) -> *mut () {
    ((*IExec).AttemptNamedMemory)(IExec, space, name)
}

#[inline]
pub unsafe fn exec_unlock_named_memory(space: CONST_STRPTR, name: CONST_STRPTR) {
    ((*IExec).UnlockNamedMemory)(IExec, space, name)
}

#[inline]
pub unsafe fn exec_scan_named_memory(scHook: *mut Hook, flags: u32, user: APTR) -> u32 {
    ((*IExec).ScanNamedMemory)(IExec, scHook, flags, user)
}

#[inline]
pub unsafe fn exec_alloc_task_mem_entry(memList: *mut MemList) -> *mut MemList {
    ((*IExec).AllocTaskMemEntry)(IExec, memList)
}

#[inline]
pub unsafe fn exec_mutex_obtain(Mutex: APTR) {
    ((*IExec).MutexObtain)(IExec, Mutex)
}

#[inline]
pub unsafe fn exec_mutex_attempt(Mutex: APTR) -> u32 {
    ((*IExec).MutexAttempt)(IExec, Mutex)
}

#[inline]
pub unsafe fn exec_mutex_release(Mutex: APTR) {
    ((*IExec).MutexRelease)(IExec, Mutex)
}

#[inline]
pub unsafe fn exec_mutex_attempt_with_signal(Mutex: APTR, SigSet: u32) -> u32 {
    ((*IExec).MutexAttemptWithSignal)(IExec, Mutex, SigSet)
}

#[inline]
pub unsafe fn exec_new_stack_run(initPC: APTR, TagList: *const TagItem) -> i32 {
    ((*IExec).NewStackRun)(IExec, initPC, TagList)
}

#[inline]
pub unsafe fn exec_attempt_semaphore_with_signal(semaphore: *mut SignalSemaphore, sigmask: u32) -> u32 {
    ((*IExec).AttemptSemaphoreWithSignal)(IExec, semaphore, sigmask)
}

#[inline]
pub unsafe fn exec_attempt_semaphore_shared_with_signal(semaphore: *mut SignalSemaphore, sigmask: u32) -> u32 {
    ((*IExec).AttemptSemaphoreSharedWithSignal)(IExec, semaphore, sigmask)
}

#[inline]
pub unsafe fn exec_get_task_attrs(task: *mut Task, taglist: *const TagItem) -> i32 {
    ((*IExec).GetTaskAttrs)(IExec, task, taglist)
}

#[inline]
pub unsafe fn exec_obsoletemutex_obtain_disable(mutex: APTR) {
    ((*IExec).OBSOLETEMutexObtainDisable)(IExec, mutex)
}

#[inline]
pub unsafe fn exec_obsoletemutex_release_enable(mutex: APTR) {
    ((*IExec).OBSOLETEMutexReleaseEnable)(IExec, mutex)
}

#[inline]
pub unsafe fn exec_find_resident_tag_list(tagList: *const TagItem) -> *mut Resident {
    ((*IExec).FindResidentTagList)(IExec, tagList)
}

#[inline]
pub unsafe fn exec_get_system_info(TagList: *const TagItem) {
    ((*IExec).GetSystemInfo)(IExec, TagList)
}

#[inline]
pub unsafe fn exec_set_task_affinity(task: *mut Task, TagList: *const TagItem) {
    ((*IExec).SetTaskAffinity)(IExec, task, TagList)
}

