//! IGadTools global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::gadtools::*;

// ---- IGadTools (GadToolsIFace) ----

extern "C" {
    pub static IGadTools: *mut GadToolsIFace;
}

#[inline]
pub unsafe fn gadtools_create_gadget_a(kind: u32, gad: *mut Gadget, ng: *const NewGadget, taglist: *const TagItem) -> *mut Gadget {
    ((*IGadTools).CreateGadgetA)(IGadTools, kind, gad, ng, taglist)
}

#[inline]
pub unsafe fn gadtools_free_gadgets(gad: *mut Gadget) {
    ((*IGadTools).FreeGadgets)(IGadTools, gad)
}

#[inline]
pub unsafe fn gadtools_gt_set_gadget_attrs_a(gad: *mut Gadget, win: *mut Window, req: *mut Requester, taglist: *const TagItem) {
    ((*IGadTools).GT_SetGadgetAttrsA)(IGadTools, gad, win, req, taglist)
}

#[inline]
pub unsafe fn gadtools_create_menus_a(newmenu: *const NewMenu, taglist: *const TagItem) -> *mut Menu {
    ((*IGadTools).CreateMenusA)(IGadTools, newmenu, taglist)
}

#[inline]
pub unsafe fn gadtools_free_menus(menu: *mut Menu) {
    ((*IGadTools).FreeMenus)(IGadTools, menu)
}

#[inline]
pub unsafe fn gadtools_layout_menu_items_a(firstitem: *mut MenuItem, vi: APTR, taglist: *const TagItem) -> u32 {
    ((*IGadTools).LayoutMenuItemsA)(IGadTools, firstitem, vi, taglist)
}

#[inline]
pub unsafe fn gadtools_layout_menus_a(firstmenu: *mut Menu, vi: APTR, taglist: *const TagItem) -> u32 {
    ((*IGadTools).LayoutMenusA)(IGadTools, firstmenu, vi, taglist)
}

#[inline]
pub unsafe fn gadtools_gt_get_imsg(iport: *mut MsgPort) -> *mut IntuiMessage {
    ((*IGadTools).GT_GetIMsg)(IGadTools, iport)
}

#[inline]
pub unsafe fn gadtools_gt_reply_imsg(imsg: *mut IntuiMessage) {
    ((*IGadTools).GT_ReplyIMsg)(IGadTools, imsg)
}

#[inline]
pub unsafe fn gadtools_gt_refresh_window(win: *mut Window, req: *mut Requester) {
    ((*IGadTools).GT_RefreshWindow)(IGadTools, win, req)
}

#[inline]
pub unsafe fn gadtools_gt_begin_refresh(win: *mut Window) {
    ((*IGadTools).GT_BeginRefresh)(IGadTools, win)
}

#[inline]
pub unsafe fn gadtools_gt_end_refresh(win: *mut Window, complete: u32) {
    ((*IGadTools).GT_EndRefresh)(IGadTools, win, complete)
}

#[inline]
pub unsafe fn gadtools_gt_filter_imsg(imsg: *const IntuiMessage) -> *mut IntuiMessage {
    ((*IGadTools).GT_FilterIMsg)(IGadTools, imsg)
}

#[inline]
pub unsafe fn gadtools_gt_post_filter_imsg(imsg: *mut IntuiMessage) -> *mut IntuiMessage {
    ((*IGadTools).GT_PostFilterIMsg)(IGadTools, imsg)
}

#[inline]
pub unsafe fn gadtools_create_context(glistptr: *mut *mut Gadget) -> *mut Gadget {
    ((*IGadTools).CreateContext)(IGadTools, glistptr)
}

#[inline]
pub unsafe fn gadtools_draw_bevel_box_a(rport: *mut RastPort, left: i16, top: i16, width: i16, height: i16, taglist: *const TagItem) {
    ((*IGadTools).DrawBevelBoxA)(IGadTools, rport, left, top, width, height, taglist)
}

#[inline]
pub unsafe fn gadtools_get_visual_info_a(screen: *mut Screen, taglist: *const TagItem) -> APTR {
    ((*IGadTools).GetVisualInfoA)(IGadTools, screen, taglist)
}

#[inline]
pub unsafe fn gadtools_free_visual_info(vi: APTR) {
    ((*IGadTools).FreeVisualInfo)(IGadTools, vi)
}

#[inline]
pub unsafe fn gadtools_gtreserved0() {
    ((*IGadTools).GTReserved0)(IGadTools, )
}

#[inline]
pub unsafe fn gadtools_gtreserved1() {
    ((*IGadTools).GTReserved1)(IGadTools, )
}

#[inline]
pub unsafe fn gadtools_gtreserved2() {
    ((*IGadTools).GTReserved2)(IGadTools, )
}

#[inline]
pub unsafe fn gadtools_gtreserved3() {
    ((*IGadTools).GTReserved3)(IGadTools, )
}

#[inline]
pub unsafe fn gadtools_gtreserved4() {
    ((*IGadTools).GTReserved4)(IGadTools, )
}

#[inline]
pub unsafe fn gadtools_gtreserved5() {
    ((*IGadTools).GTReserved5)(IGadTools, )
}

#[inline]
pub unsafe fn gadtools_gt_get_gadget_attrs_a(gad: *mut Gadget, win: *mut Window, req: *mut Requester, taglist: *const TagItem) -> i32 {
    ((*IGadTools).GT_GetGadgetAttrsA)(IGadTools, gad, win, req, taglist)
}

