//! IGraphics global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::graphics::*;

// ---- IGraphics (GraphicsIFace) ----

extern "C" {
    pub static IGraphics: *mut GraphicsIFace;
}

#[inline]
pub unsafe fn graphics_blt_bit_map(srcBitMap: *mut APTR, xSrc: i16, ySrc: i16, destBitMap: *mut BitMap, xDest: i16, yDest: i16, xSize: i16, ySize: i16, minterm: u8, mask: u8, tempA: APTR) -> u32 {
    ((*IGraphics).BltBitMap)(IGraphics, srcBitMap, xSrc, ySrc, destBitMap, xDest, yDest, xSize, ySize, minterm, mask, tempA)
}

#[inline]
pub unsafe fn graphics_blt_template(source: APTR, xSrc: i16, srcMod: i16, destRP: *mut RastPort, xDest: i16, yDest: i16, xSize: i16, ySize: i16) {
    ((*IGraphics).BltTemplate)(IGraphics, source, xSrc, srcMod, destRP, xDest, yDest, xSize, ySize)
}

#[inline]
pub unsafe fn graphics_clear_eol(rp: *mut RastPort) {
    ((*IGraphics).ClearEOL)(IGraphics, rp)
}

#[inline]
pub unsafe fn graphics_clear_screen(rp: *mut RastPort) {
    ((*IGraphics).ClearScreen)(IGraphics, rp)
}

#[inline]
pub unsafe fn graphics_text_length(rp: *mut RastPort, string: CONST_STRPTR, count: u16) -> i16 {
    ((*IGraphics).TextLength)(IGraphics, rp, string, count)
}

#[inline]
pub unsafe fn graphics_text(rp: *mut RastPort, string: CONST_STRPTR, count: u16) {
    ((*IGraphics).Text)(IGraphics, rp, string, count)
}

#[inline]
pub unsafe fn graphics_set_font(rp: *mut RastPort, textFont: *mut TextFont) {
    ((*IGraphics).SetFont)(IGraphics, rp, textFont)
}

#[inline]
pub unsafe fn graphics_open_font(textAttr: *mut APTR) -> *mut TextFont {
    ((*IGraphics).OpenFont)(IGraphics, textAttr)
}

#[inline]
pub unsafe fn graphics_close_font(textFont: *mut TextFont) {
    ((*IGraphics).CloseFont)(IGraphics, textFont)
}

#[inline]
pub unsafe fn graphics_ask_soft_style(rp: *mut RastPort) -> u32 {
    ((*IGraphics).AskSoftStyle)(IGraphics, rp)
}

#[inline]
pub unsafe fn graphics_set_soft_style(rp: *mut RastPort, style: u32, enable: u32) -> u32 {
    ((*IGraphics).SetSoftStyle)(IGraphics, rp, style, enable)
}

#[inline]
pub unsafe fn graphics_add_bob(bob: *mut Bob, rp: *mut RastPort) {
    ((*IGraphics).AddBob)(IGraphics, bob, rp)
}

#[inline]
pub unsafe fn graphics_add_vsprite(vSprite: *mut VSprite, rp: *mut RastPort) {
    ((*IGraphics).AddVSprite)(IGraphics, vSprite, rp)
}

#[inline]
pub unsafe fn graphics_do_collision(rp: *mut RastPort) {
    ((*IGraphics).DoCollision)(IGraphics, rp)
}

#[inline]
pub unsafe fn graphics_draw_glist(rp: *mut RastPort, vp: *mut ViewPort) {
    ((*IGraphics).DrawGList)(IGraphics, rp, vp)
}

#[inline]
pub unsafe fn graphics_init_gels(head: *mut VSprite, tail: *mut VSprite, gelsInfo: *mut GelsInfo) {
    ((*IGraphics).InitGels)(IGraphics, head, tail, gelsInfo)
}

#[inline]
pub unsafe fn graphics_init_masks(vSprite: *mut VSprite) {
    ((*IGraphics).InitMasks)(IGraphics, vSprite)
}

#[inline]
pub unsafe fn graphics_rem_ibob(bob: *mut Bob, rp: *mut RastPort, vp: *mut ViewPort) {
    ((*IGraphics).RemIBob)(IGraphics, bob, rp, vp)
}

#[inline]
pub unsafe fn graphics_rem_vsprite(vSprite: *mut VSprite) {
    ((*IGraphics).RemVSprite)(IGraphics, vSprite)
}

#[inline]
pub unsafe fn graphics_set_collision(num: u32, routine: APTR, gelsInfo: *mut GelsInfo) {
    ((*IGraphics).SetCollision)(IGraphics, num, routine, gelsInfo)
}

#[inline]
pub unsafe fn graphics_sort_glist(rp: *mut RastPort) {
    ((*IGraphics).SortGList)(IGraphics, rp)
}

#[inline]
pub unsafe fn graphics_add_anim_ob(anOb: *mut AnimOb, anKey: *mut *mut AnimOb, rp: *mut RastPort) {
    ((*IGraphics).AddAnimOb)(IGraphics, anOb, anKey, rp)
}

#[inline]
pub unsafe fn graphics_animate(anKey: *mut *mut AnimOb, rp: *mut RastPort) {
    ((*IGraphics).Animate)(IGraphics, anKey, rp)
}

#[inline]
pub unsafe fn graphics_get_gbuffers(anOb: *mut AnimOb, rp: *mut RastPort, flag: u32) -> u32 {
    ((*IGraphics).GetGBuffers)(IGraphics, anOb, rp, flag)
}

#[inline]
pub unsafe fn graphics_init_gmasks(anOb: *mut AnimOb) {
    ((*IGraphics).InitGMasks)(IGraphics, anOb)
}

#[inline]
pub unsafe fn graphics_draw_ellipse(rp: *mut RastPort, xCenter: i16, yCenter: i16, a: i16, b: i16) {
    ((*IGraphics).DrawEllipse)(IGraphics, rp, xCenter, yCenter, a, b)
}

#[inline]
pub unsafe fn graphics_area_ellipse(rp: *mut RastPort, xCenter: i16, yCenter: i16, a: i16, b: i16) -> i32 {
    ((*IGraphics).AreaEllipse)(IGraphics, rp, xCenter, yCenter, a, b)
}

#[inline]
pub unsafe fn graphics_load_rgb4(vp: *mut ViewPort, colors: *mut APTR, count: u16) {
    ((*IGraphics).LoadRGB4)(IGraphics, vp, colors, count)
}

#[inline]
pub unsafe fn graphics_init_rast_port(rp: *mut RastPort) {
    ((*IGraphics).InitRastPort)(IGraphics, rp)
}

#[inline]
pub unsafe fn graphics_init_vport(vp: *mut ViewPort) {
    ((*IGraphics).InitVPort)(IGraphics, vp)
}

#[inline]
pub unsafe fn graphics_mrg_cop(view: *mut View) -> u32 {
    ((*IGraphics).MrgCop)(IGraphics, view)
}

#[inline]
pub unsafe fn graphics_make_vport(view: *mut View, vp: *mut ViewPort) -> u32 {
    ((*IGraphics).MakeVPort)(IGraphics, view, vp)
}

#[inline]
pub unsafe fn graphics_load_view(view: *mut View) {
    ((*IGraphics).LoadView)(IGraphics, view)
}

#[inline]
pub unsafe fn graphics_wait_blit() {
    ((*IGraphics).WaitBlit)(IGraphics, )
}

#[inline]
pub unsafe fn graphics_set_rast(rp: *mut RastPort, pen: u8) {
    ((*IGraphics).SetRast)(IGraphics, rp, pen)
}

#[inline]
pub unsafe fn graphics_move(rp: *mut RastPort, x: i16, y: i16) {
    ((*IGraphics).Move)(IGraphics, rp, x, y)
}

#[inline]
pub unsafe fn graphics_draw(rp: *mut RastPort, x: i16, y: i16) {
    ((*IGraphics).Draw)(IGraphics, rp, x, y)
}

#[inline]
pub unsafe fn graphics_area_move(rp: *mut RastPort, x: i16, y: i16) -> i32 {
    ((*IGraphics).AreaMove)(IGraphics, rp, x, y)
}

#[inline]
pub unsafe fn graphics_area_draw(rp: *mut RastPort, x: i16, y: i16) -> i32 {
    ((*IGraphics).AreaDraw)(IGraphics, rp, x, y)
}

#[inline]
pub unsafe fn graphics_area_end(rp: *mut RastPort) -> i32 {
    ((*IGraphics).AreaEnd)(IGraphics, rp)
}

#[inline]
pub unsafe fn graphics_wait_tof() {
    ((*IGraphics).WaitTOF)(IGraphics, )
}

#[inline]
pub unsafe fn graphics_qblit(blit: *mut bltnode) {
    ((*IGraphics).QBlit)(IGraphics, blit)
}

#[inline]
pub unsafe fn graphics_init_area(areaInfo: *mut AreaInfo, vectorBuffer: APTR, maxVectors: i16) {
    ((*IGraphics).InitArea)(IGraphics, areaInfo, vectorBuffer, maxVectors)
}

#[inline]
pub unsafe fn graphics_set_rgb4(vp: *mut ViewPort, colindex: u16, red: u8, green: u8, blue: u8) {
    ((*IGraphics).SetRGB4)(IGraphics, vp, colindex, red, green, blue)
}

#[inline]
pub unsafe fn graphics_qbsblit(blit: *mut bltnode) {
    ((*IGraphics).QBSBlit)(IGraphics, blit)
}

#[inline]
pub unsafe fn graphics_blt_clear(memBlock: APTR, byteCount: u32, flags: u32) {
    ((*IGraphics).BltClear)(IGraphics, memBlock, byteCount, flags)
}

#[inline]
pub unsafe fn graphics_rect_fill(rp: *mut RastPort, xMin: i16, yMin: i16, xMax: i16, yMax: i16) {
    ((*IGraphics).RectFill)(IGraphics, rp, xMin, yMin, xMax, yMax)
}

#[inline]
pub unsafe fn graphics_blt_pattern(rp: *mut RastPort, mask: APTR, xMin: i16, yMin: i16, xMax: i16, yMax: i16, maskBPR: u16) {
    ((*IGraphics).BltPattern)(IGraphics, rp, mask, xMin, yMin, xMax, yMax, maskBPR)
}

#[inline]
pub unsafe fn graphics_read_pixel(rp: *mut RastPort, x: i16, y: i16) -> i32 {
    ((*IGraphics).ReadPixel)(IGraphics, rp, x, y)
}

#[inline]
pub unsafe fn graphics_write_pixel(rp: *mut RastPort, x: i16, y: i16) -> i32 {
    ((*IGraphics).WritePixel)(IGraphics, rp, x, y)
}

#[inline]
pub unsafe fn graphics_flood(rp: *mut RastPort, mode: u32, x: i16, y: i16) -> u32 {
    ((*IGraphics).Flood)(IGraphics, rp, mode, x, y)
}

#[inline]
pub unsafe fn graphics_poly_draw(rp: *mut RastPort, count: i16, polyTable: *mut APTR) {
    ((*IGraphics).PolyDraw)(IGraphics, rp, count, polyTable)
}

#[inline]
pub unsafe fn graphics_set_apen(rp: *mut RastPort, pen: u8) {
    ((*IGraphics).SetAPen)(IGraphics, rp, pen)
}

#[inline]
pub unsafe fn graphics_set_bpen(rp: *mut RastPort, pen: u8) {
    ((*IGraphics).SetBPen)(IGraphics, rp, pen)
}

#[inline]
pub unsafe fn graphics_set_dr_md(rp: *mut RastPort, drawMode: u8) {
    ((*IGraphics).SetDrMd)(IGraphics, rp, drawMode)
}

#[inline]
pub unsafe fn graphics_init_view(view: *mut View) {
    ((*IGraphics).InitView)(IGraphics, view)
}

#[inline]
pub unsafe fn graphics_cbump(copList: *mut UCopList) {
    ((*IGraphics).CBump)(IGraphics, copList)
}

#[inline]
pub unsafe fn graphics_cmove(copList: *mut UCopList, destoffset: i16, data: i16) {
    ((*IGraphics).CMove)(IGraphics, copList, destoffset, data)
}

#[inline]
pub unsafe fn graphics_cwait(copList: *mut UCopList, v: i16, h: i16) {
    ((*IGraphics).CWait)(IGraphics, copList, v, h)
}

#[inline]
pub unsafe fn graphics_vbeam_pos() -> i32 {
    ((*IGraphics).VBeamPos)(IGraphics, )
}

#[inline]
pub unsafe fn graphics_init_bit_map(bitMap: *mut BitMap, depth: i8, width: u16, height: u16) {
    ((*IGraphics).InitBitMap)(IGraphics, bitMap, depth, width, height)
}

#[inline]
pub unsafe fn graphics_scroll_raster(rp: *mut RastPort, dx: i16, dy: i16, xMin: i16, yMin: i16, xMax: i16, yMax: i16) {
    ((*IGraphics).ScrollRaster)(IGraphics, rp, dx, dy, xMin, yMin, xMax, yMax)
}

#[inline]
pub unsafe fn graphics_wait_bovp(vp: *mut ViewPort) {
    ((*IGraphics).WaitBOVP)(IGraphics, vp)
}

#[inline]
pub unsafe fn graphics_get_sprite(sprite: *mut SimpleSprite, num: i16) -> i16 {
    ((*IGraphics).GetSprite)(IGraphics, sprite, num)
}

#[inline]
pub unsafe fn graphics_free_sprite(num: i16) {
    ((*IGraphics).FreeSprite)(IGraphics, num)
}

#[inline]
pub unsafe fn graphics_change_sprite(vp: *mut ViewPort, sprite: *mut SimpleSprite, newData: APTR) {
    ((*IGraphics).ChangeSprite)(IGraphics, vp, sprite, newData)
}

#[inline]
pub unsafe fn graphics_move_sprite(vp: *mut ViewPort, sprite: *mut SimpleSprite, x: i16, y: i16) {
    ((*IGraphics).MoveSprite)(IGraphics, vp, sprite, x, y)
}

#[inline]
pub unsafe fn graphics_lock_layer_rom(layer: *mut Layer) {
    ((*IGraphics).LockLayerRom)(IGraphics, layer)
}

#[inline]
pub unsafe fn graphics_unlock_layer_rom(layer: *mut Layer) {
    ((*IGraphics).UnlockLayerRom)(IGraphics, layer)
}

#[inline]
pub unsafe fn graphics_sync_sbit_map(layer: *mut Layer) {
    ((*IGraphics).SyncSBitMap)(IGraphics, layer)
}

#[inline]
pub unsafe fn graphics_copy_sbit_map(layer: *mut Layer) {
    ((*IGraphics).CopySBitMap)(IGraphics, layer)
}

#[inline]
pub unsafe fn graphics_own_blitter() {
    ((*IGraphics).OwnBlitter)(IGraphics, )
}

#[inline]
pub unsafe fn graphics_disown_blitter() {
    ((*IGraphics).DisownBlitter)(IGraphics, )
}

#[inline]
pub unsafe fn graphics_init_tmp_ras(tmpRas: *mut TmpRas, buffer: APTR, size: i32) -> *mut TmpRas {
    ((*IGraphics).InitTmpRas)(IGraphics, tmpRas, buffer, size)
}

#[inline]
pub unsafe fn graphics_ask_font(rp: *mut RastPort, textAttr: *mut TextAttr) {
    ((*IGraphics).AskFont)(IGraphics, rp, textAttr)
}

#[inline]
pub unsafe fn graphics_add_font(textFont: *mut TextFont) {
    ((*IGraphics).AddFont)(IGraphics, textFont)
}

#[inline]
pub unsafe fn graphics_rem_font(textFont: *mut TextFont) {
    ((*IGraphics).RemFont)(IGraphics, textFont)
}

#[inline]
pub unsafe fn graphics_alloc_raster(width: u16, height: u16) -> APTR {
    ((*IGraphics).AllocRaster)(IGraphics, width, height)
}

#[inline]
pub unsafe fn graphics_free_raster(p: APTR, width: u16, height: u16) {
    ((*IGraphics).FreeRaster)(IGraphics, p, width, height)
}

#[inline]
pub unsafe fn graphics_and_rect_region(region: *mut Region, rectangle: *mut APTR) {
    ((*IGraphics).AndRectRegion)(IGraphics, region, rectangle)
}

#[inline]
pub unsafe fn graphics_or_rect_region(region: *mut Region, rectangle: *mut APTR) -> u32 {
    ((*IGraphics).OrRectRegion)(IGraphics, region, rectangle)
}

#[inline]
pub unsafe fn graphics_new_region() -> *mut Region {
    ((*IGraphics).NewRegion)(IGraphics, )
}

#[inline]
pub unsafe fn graphics_clear_rect_region(region: *mut Region, rectangle: *mut APTR) -> u32 {
    ((*IGraphics).ClearRectRegion)(IGraphics, region, rectangle)
}

#[inline]
pub unsafe fn graphics_clear_region(region: *mut Region) {
    ((*IGraphics).ClearRegion)(IGraphics, region)
}

#[inline]
pub unsafe fn graphics_dispose_region(region: *mut Region) {
    ((*IGraphics).DisposeRegion)(IGraphics, region)
}

#[inline]
pub unsafe fn graphics_free_vport_cop_lists(vp: *mut ViewPort) {
    ((*IGraphics).FreeVPortCopLists)(IGraphics, vp)
}

#[inline]
pub unsafe fn graphics_free_cop_list(copList: *mut CopList) {
    ((*IGraphics).FreeCopList)(IGraphics, copList)
}

#[inline]
pub unsafe fn graphics_clip_blit(srcRP: *mut RastPort, xSrc: i16, ySrc: i16, destRP: *mut RastPort, xDest: i16, yDest: i16, xSize: i16, ySize: i16, minterm: u8) {
    ((*IGraphics).ClipBlit)(IGraphics, srcRP, xSrc, ySrc, destRP, xDest, yDest, xSize, ySize, minterm)
}

#[inline]
pub unsafe fn graphics_xor_rect_region(region: *mut Region, rectangle: *mut APTR) -> u32 {
    ((*IGraphics).XorRectRegion)(IGraphics, region, rectangle)
}

#[inline]
pub unsafe fn graphics_free_cpr_list(cprList: *mut cprlist) {
    ((*IGraphics).FreeCprList)(IGraphics, cprList)
}

#[inline]
pub unsafe fn graphics_get_color_map(entries: u16) -> *mut ColorMap {
    ((*IGraphics).GetColorMap)(IGraphics, entries)
}

#[inline]
pub unsafe fn graphics_free_color_map(colorMap: *mut ColorMap) {
    ((*IGraphics).FreeColorMap)(IGraphics, colorMap)
}

#[inline]
pub unsafe fn graphics_get_rgb4(colorMap: *mut ColorMap, entry: u16) -> i32 {
    ((*IGraphics).GetRGB4)(IGraphics, colorMap, entry)
}

#[inline]
pub unsafe fn graphics_scroll_vport(vp: *mut ViewPort) {
    ((*IGraphics).ScrollVPort)(IGraphics, vp)
}

#[inline]
pub unsafe fn graphics_ucopper_list_init(uCopList: *mut UCopList, n: i16) -> *mut CopList {
    ((*IGraphics).UCopperListInit)(IGraphics, uCopList, n)
}

#[inline]
pub unsafe fn graphics_free_gbuffers(anOb: *mut AnimOb, rp: *mut RastPort, flag: u32) {
    ((*IGraphics).FreeGBuffers)(IGraphics, anOb, rp, flag)
}

#[inline]
pub unsafe fn graphics_blt_bit_map_rast_port(srcBitMap: *mut APTR, xSrc: i16, ySrc: i16, destRP: *mut RastPort, xDest: i16, yDest: i16, xSize: i16, ySize: i16, minterm: u8) -> u32 {
    ((*IGraphics).BltBitMapRastPort)(IGraphics, srcBitMap, xSrc, ySrc, destRP, xDest, yDest, xSize, ySize, minterm)
}

#[inline]
pub unsafe fn graphics_or_region_region(srcRegion: *mut APTR, destRegion: *mut Region) -> u32 {
    ((*IGraphics).OrRegionRegion)(IGraphics, srcRegion, destRegion)
}

#[inline]
pub unsafe fn graphics_xor_region_region(srcRegion: *mut APTR, destRegion: *mut Region) -> u32 {
    ((*IGraphics).XorRegionRegion)(IGraphics, srcRegion, destRegion)
}

#[inline]
pub unsafe fn graphics_and_region_region(srcRegion: *mut APTR, destRegion: *mut Region) -> u32 {
    ((*IGraphics).AndRegionRegion)(IGraphics, srcRegion, destRegion)
}

#[inline]
pub unsafe fn graphics_set_rgb4_cm(colorMap: *mut ColorMap, colindex: u16, red: u8, green: u8, blue: u8) {
    ((*IGraphics).SetRGB4CM)(IGraphics, colorMap, colindex, red, green, blue)
}

#[inline]
pub unsafe fn graphics_blt_mask_bit_map_rast_port(srcBitMap: *mut BitMap, xSrc: i16, ySrc: i16, destRP: *mut RastPort, xDest: i16, yDest: i16, xSize: i16, ySize: i16, minterm: u8, bltMask: APTR) {
    ((*IGraphics).BltMaskBitMapRastPort)(IGraphics, srcBitMap, xSrc, ySrc, destRP, xDest, yDest, xSize, ySize, minterm, bltMask)
}

#[inline]
pub unsafe fn graphics_gfx_internal1() {
    ((*IGraphics).GfxInternal1)(IGraphics, )
}

#[inline]
pub unsafe fn graphics_gfx_internal2() {
    ((*IGraphics).GfxInternal2)(IGraphics, )
}

#[inline]
pub unsafe fn graphics_attempt_lock_layer_rom(layer: *mut Layer) -> u32 {
    ((*IGraphics).AttemptLockLayerRom)(IGraphics, layer)
}

#[inline]
pub unsafe fn graphics_gfx_new(gfxNodeType: u32) -> APTR {
    ((*IGraphics).GfxNew)(IGraphics, gfxNodeType)
}

#[inline]
pub unsafe fn graphics_gfx_free(gfxNodePtr: *mut ExtendedNode) {
    ((*IGraphics).GfxFree)(IGraphics, gfxNodePtr)
}

#[inline]
pub unsafe fn graphics_gfx_associate(associateNode: APTR, gfxNodePtr: *mut ExtendedNode) {
    ((*IGraphics).GfxAssociate)(IGraphics, associateNode, gfxNodePtr)
}

#[inline]
pub unsafe fn graphics_bit_map_scale(bitScaleArgs: *mut BitScaleArgs) {
    ((*IGraphics).BitMapScale)(IGraphics, bitScaleArgs)
}

#[inline]
pub unsafe fn graphics_scaler_div(factor: u16, numerator: u16, denominator: u16) -> u16 {
    ((*IGraphics).ScalerDiv)(IGraphics, factor, numerator, denominator)
}

#[inline]
pub unsafe fn graphics_text_extent(rp: *mut RastPort, string: CONST_STRPTR, count: u16, textExtent: *mut TextExtent) {
    ((*IGraphics).TextExtent)(IGraphics, rp, string, count, textExtent)
}

#[inline]
pub unsafe fn graphics_text_fit(rp: *mut RastPort, string: CONST_STRPTR, strLen: u16, textExtent: *mut TextExtent, constrainingExtent: *mut APTR, strDirection: i16, constrainingBitWidth: u16, constrainingBitHeight: u16) -> u16 {
    ((*IGraphics).TextFit)(IGraphics, rp, string, strLen, textExtent, constrainingExtent, strDirection, constrainingBitWidth, constrainingBitHeight)
}

#[inline]
pub unsafe fn graphics_gfx_look_up(associateNode: APTR) -> APTR {
    ((*IGraphics).GfxLookUp)(IGraphics, associateNode)
}

#[inline]
pub unsafe fn graphics_video_control(colorMap: *mut ColorMap, tagarray: *mut TagItem) -> u32 {
    ((*IGraphics).VideoControl)(IGraphics, colorMap, tagarray)
}

#[inline]
pub unsafe fn graphics_open_monitor(monitorName: CONST_STRPTR, displayID: u32) -> *mut MonitorSpec {
    ((*IGraphics).OpenMonitor)(IGraphics, monitorName, displayID)
}

#[inline]
pub unsafe fn graphics_close_monitor(monitorSpec: *mut MonitorSpec) -> i32 {
    ((*IGraphics).CloseMonitor)(IGraphics, monitorSpec)
}

#[inline]
pub unsafe fn graphics_find_display_info(displayID: u32) -> APTR {
    ((*IGraphics).FindDisplayInfo)(IGraphics, displayID)
}

#[inline]
pub unsafe fn graphics_next_display_info(displayID: u32) -> u32 {
    ((*IGraphics).NextDisplayInfo)(IGraphics, displayID)
}

#[inline]
pub unsafe fn graphics_add_display_info(displayInfoRecord: APTR) {
    ((*IGraphics).AddDisplayInfo)(IGraphics, displayInfoRecord)
}

#[inline]
pub unsafe fn graphics_add_display_info_data(handle: APTR, buf: *mut u8, size: u32, tagID: u32, displayID: u32) {
    ((*IGraphics).AddDisplayInfoData)(IGraphics, handle, buf, size, tagID, displayID)
}

#[inline]
pub unsafe fn graphics_set_display_info_data(handle: APTR, buf: APTR, size: u32, tagID: u32, displayID: u32) -> APTR {
    ((*IGraphics).SetDisplayInfoData)(IGraphics, handle, buf, size, tagID, displayID)
}

#[inline]
pub unsafe fn graphics_get_display_info_data(handle: APTR, buf: APTR, size: u32, tagID: u32, displayID: u32) -> u32 {
    ((*IGraphics).GetDisplayInfoData)(IGraphics, handle, buf, size, tagID, displayID)
}

#[inline]
pub unsafe fn graphics_font_extent(font: *mut APTR, fontExtent: *mut TextExtent) {
    ((*IGraphics).FontExtent)(IGraphics, font, fontExtent)
}

#[inline]
pub unsafe fn graphics_read_pixel_line8(rp: *mut RastPort, xstart: u16, ystart: u16, width: u16, array: *mut u8, tempRP: *mut RastPort) -> i32 {
    ((*IGraphics).ReadPixelLine8)(IGraphics, rp, xstart, ystart, width, array, tempRP)
}

#[inline]
pub unsafe fn graphics_write_pixel_line8(rp: *mut RastPort, xstart: u16, ystart: u16, width: u16, array: *mut u8, tempRP: *mut RastPort) -> i32 {
    ((*IGraphics).WritePixelLine8)(IGraphics, rp, xstart, ystart, width, array, tempRP)
}

#[inline]
pub unsafe fn graphics_read_pixel_array8(rp: *mut RastPort, xstart: u16, ystart: u16, xstop: u16, ystop: u16, array: *mut u8, temprp: *mut RastPort) -> i32 {
    ((*IGraphics).ReadPixelArray8)(IGraphics, rp, xstart, ystart, xstop, ystop, array, temprp)
}

#[inline]
pub unsafe fn graphics_write_pixel_array8(rp: *mut RastPort, xstart: u16, ystart: u16, xstop: u16, ystop: u16, array: *mut u8, temprp: *mut RastPort) -> i32 {
    ((*IGraphics).WritePixelArray8)(IGraphics, rp, xstart, ystart, xstop, ystop, array, temprp)
}

#[inline]
pub unsafe fn graphics_get_vpmode_id(vp: *mut APTR) -> u32 {
    ((*IGraphics).GetVPModeID)(IGraphics, vp)
}

#[inline]
pub unsafe fn graphics_mode_not_available(modeID: u32) -> u32 {
    ((*IGraphics).ModeNotAvailable)(IGraphics, modeID)
}

#[inline]
pub unsafe fn graphics_weigh_tamatch(reqTextAttr: *mut TextAttr, targetTextAttr: *mut TextAttr, targetTags: *mut APTR) -> i16 {
    ((*IGraphics).WeighTAMatch)(IGraphics, reqTextAttr, targetTextAttr, targetTags)
}

#[inline]
pub unsafe fn graphics_erase_rect(rp: *mut RastPort, xMin: i16, yMin: i16, xMax: i16, yMax: i16) {
    ((*IGraphics).EraseRect)(IGraphics, rp, xMin, yMin, xMax, yMax)
}

#[inline]
pub unsafe fn graphics_extend_font(font: *mut TextFont, fontTags: *mut APTR) -> u32 {
    ((*IGraphics).ExtendFont)(IGraphics, font, fontTags)
}

#[inline]
pub unsafe fn graphics_strip_font(font: *mut TextFont) {
    ((*IGraphics).StripFont)(IGraphics, font)
}

#[inline]
pub unsafe fn graphics_calc_ivg(v: *mut View, vp: *mut ViewPort) -> u16 {
    ((*IGraphics).CalcIVG)(IGraphics, v, vp)
}

#[inline]
pub unsafe fn graphics_attach_pal_extra(cm: *mut ColorMap, vp: *mut ViewPort) -> i32 {
    ((*IGraphics).AttachPalExtra)(IGraphics, cm, vp)
}

#[inline]
pub unsafe fn graphics_obtain_best_pen_a(cm: *mut ColorMap, r: u32, g: u32, b: u32, tags: *mut APTR) -> i32 {
    ((*IGraphics).ObtainBestPenA)(IGraphics, cm, r, g, b, tags)
}

#[inline]
pub unsafe fn graphics_gfx_internal3() {
    ((*IGraphics).GfxInternal3)(IGraphics, )
}

#[inline]
pub unsafe fn graphics_set_rgb32(vp: *mut ViewPort, n: u32, r: u32, g: u32, b: u32) {
    ((*IGraphics).SetRGB32)(IGraphics, vp, n, r, g, b)
}

#[inline]
pub unsafe fn graphics_get_apen(rp: *mut RastPort) -> u32 {
    ((*IGraphics).GetAPen)(IGraphics, rp)
}

#[inline]
pub unsafe fn graphics_get_bpen(rp: *mut RastPort) -> u32 {
    ((*IGraphics).GetBPen)(IGraphics, rp)
}

#[inline]
pub unsafe fn graphics_get_dr_md(rp: *mut RastPort) -> u32 {
    ((*IGraphics).GetDrMd)(IGraphics, rp)
}

#[inline]
pub unsafe fn graphics_get_outline_pen(rp: *mut RastPort) -> u32 {
    ((*IGraphics).GetOutlinePen)(IGraphics, rp)
}

#[inline]
pub unsafe fn graphics_load_rgb32(vp: *mut ViewPort, table: *mut APTR) {
    ((*IGraphics).LoadRGB32)(IGraphics, vp, table)
}

#[inline]
pub unsafe fn graphics_set_chip_rev(want: u32) -> u32 {
    ((*IGraphics).SetChipRev)(IGraphics, want)
}

#[inline]
pub unsafe fn graphics_set_abpen_dr_md(rp: *mut RastPort, apen: u32, bpen: u32, drawmode: u32) {
    ((*IGraphics).SetABPenDrMd)(IGraphics, rp, apen, bpen, drawmode)
}

#[inline]
pub unsafe fn graphics_get_rgb32(cm: *mut APTR, firstcolor: u16, ncolors: u16, table: *mut u32) {
    ((*IGraphics).GetRGB32)(IGraphics, cm, firstcolor, ncolors, table)
}

#[inline]
pub unsafe fn graphics_blt_bit_map_tag_list(tags: *mut APTR) -> i32 {
    ((*IGraphics).BltBitMapTagList)(IGraphics, tags)
}

#[inline]
pub unsafe fn graphics_set_default_monitor(mon: u16) -> u32 {
    ((*IGraphics).SetDefaultMonitor)(IGraphics, mon)
}

#[inline]
pub unsafe fn graphics_alloc_bit_map(sizex: u32, sizey: u32, depth: u32, flags: u32, friendBitmap: *mut APTR) -> *mut BitMap {
    ((*IGraphics).AllocBitMap)(IGraphics, sizex, sizey, depth, flags, friendBitmap)
}

#[inline]
pub unsafe fn graphics_free_bit_map(bm: *mut BitMap) {
    ((*IGraphics).FreeBitMap)(IGraphics, bm)
}

#[inline]
pub unsafe fn graphics_get_ext_sprite_a(ss: *mut ExtSprite, tags: *mut APTR) -> i32 {
    ((*IGraphics).GetExtSpriteA)(IGraphics, ss, tags)
}

#[inline]
pub unsafe fn graphics_coerce_mode(vp: *mut ViewPort, monitorid: u32, flags: u32) -> u32 {
    ((*IGraphics).CoerceMode)(IGraphics, vp, monitorid, flags)
}

#[inline]
pub unsafe fn graphics_change_vpbit_map(vp: *mut ViewPort, bm: *mut BitMap, db: *mut DBufInfo) {
    ((*IGraphics).ChangeVPBitMap)(IGraphics, vp, bm, db)
}

#[inline]
pub unsafe fn graphics_release_pen(cm: *mut ColorMap, n: i32) {
    ((*IGraphics).ReleasePen)(IGraphics, cm, n)
}

#[inline]
pub unsafe fn graphics_obtain_pen(cm: *mut ColorMap, n: i32, r: u32, g: u32, b: u32, f: i32) -> i32 {
    ((*IGraphics).ObtainPen)(IGraphics, cm, n, r, g, b, f)
}

#[inline]
pub unsafe fn graphics_get_bit_map_attr(bm: *mut APTR, attrnum: u32) -> u32 {
    ((*IGraphics).GetBitMapAttr)(IGraphics, bm, attrnum)
}

#[inline]
pub unsafe fn graphics_alloc_dbuf_info(vp: *mut ViewPort) -> *mut DBufInfo {
    ((*IGraphics).AllocDBufInfo)(IGraphics, vp)
}

#[inline]
pub unsafe fn graphics_free_dbuf_info(dbi: *mut DBufInfo) {
    ((*IGraphics).FreeDBufInfo)(IGraphics, dbi)
}

#[inline]
pub unsafe fn graphics_set_outline_pen(rp: *mut RastPort, pen: u32) -> u32 {
    ((*IGraphics).SetOutlinePen)(IGraphics, rp, pen)
}

#[inline]
pub unsafe fn graphics_set_write_mask(rp: *mut RastPort, msk: u32) -> u32 {
    ((*IGraphics).SetWriteMask)(IGraphics, rp, msk)
}

#[inline]
pub unsafe fn graphics_set_max_pen(rp: *mut RastPort, maxpen: u32) {
    ((*IGraphics).SetMaxPen)(IGraphics, rp, maxpen)
}

#[inline]
pub unsafe fn graphics_set_rgb32_cm(cm: *mut ColorMap, n: u16, r: u32, g: u32, b: u32) {
    ((*IGraphics).SetRGB32CM)(IGraphics, cm, n, r, g, b)
}

#[inline]
pub unsafe fn graphics_scroll_raster_bf(rp: *mut RastPort, dx: i16, dy: i16, xMin: i16, yMin: i16, xMax: i16, yMax: i16) {
    ((*IGraphics).ScrollRasterBF)(IGraphics, rp, dx, dy, xMin, yMin, xMax, yMax)
}

#[inline]
pub unsafe fn graphics_find_color(cm: *mut ColorMap, r: u32, g: u32, b: u32, maxcolor: i32) -> u16 {
    ((*IGraphics).FindColor)(IGraphics, cm, r, g, b, maxcolor)
}

#[inline]
pub unsafe fn graphics_alloc_sprite_data_a(bm: *mut APTR, tags: *mut APTR) -> *mut ExtSprite {
    ((*IGraphics).AllocSpriteDataA)(IGraphics, bm, tags)
}

#[inline]
pub unsafe fn graphics_change_ext_sprite_a(vp: *mut ViewPort, oldsprite: *mut ExtSprite, newsprite: *mut ExtSprite, tags: *mut APTR) -> i32 {
    ((*IGraphics).ChangeExtSpriteA)(IGraphics, vp, oldsprite, newsprite, tags)
}

#[inline]
pub unsafe fn graphics_free_sprite_data(sp: *mut ExtSprite) {
    ((*IGraphics).FreeSpriteData)(IGraphics, sp)
}

#[inline]
pub unsafe fn graphics_set_rpattrs_a(rp: *mut RastPort, tags: *mut APTR) -> u32 {
    ((*IGraphics).SetRPAttrsA)(IGraphics, rp, tags)
}

#[inline]
pub unsafe fn graphics_get_rpattrs_a(rp: *mut APTR, tags: *mut APTR) -> u32 {
    ((*IGraphics).GetRPAttrsA)(IGraphics, rp, tags)
}

#[inline]
pub unsafe fn graphics_best_mode_ida(tags: *mut APTR) -> u32 {
    ((*IGraphics).BestModeIDA)(IGraphics, tags)
}

#[inline]
pub unsafe fn graphics_write_chunky_pixels(rp: *mut RastPort, xstart: u16, ystart: u16, xstop: u16, ystop: u16, array: *mut APTR, bytesperrow: i32) {
    ((*IGraphics).WriteChunkyPixels)(IGraphics, rp, xstart, ystart, xstop, ystop, array, bytesperrow)
}

#[inline]
pub unsafe fn graphics_composite_tag_list(Operator: APTR, Source: *mut APTR, Destination: *mut APTR, tags: *mut APTR) -> u32 {
    ((*IGraphics).CompositeTagList)(IGraphics, Operator, Source, Destination, tags)
}

#[inline]
pub unsafe fn graphics_alloc_bit_map_tag_list(sizex: u32, sizey: u32, depth: u32, tags: *mut APTR) -> *mut BitMap {
    ((*IGraphics).AllocBitMapTagList)(IGraphics, sizex, sizey, depth, tags)
}

#[inline]
pub unsafe fn graphics_get_monitor_data_tag_list(boardNum: u32, monitorNum: u32, tags: *mut TagItem) -> i32 {
    ((*IGraphics).GetMonitorDataTagList)(IGraphics, boardNum, monitorNum, tags)
}

#[inline]
pub unsafe fn graphics_get_board_data_tag_list(boardNum: u32, tags: *mut TagItem) -> i32 {
    ((*IGraphics).GetBoardDataTagList)(IGraphics, boardNum, tags)
}

#[inline]
pub unsafe fn graphics_lock_bit_map_tag_list(bitMap: *mut BitMap, tags: *mut TagItem) -> APTR {
    ((*IGraphics).LockBitMapTagList)(IGraphics, bitMap, tags)
}

#[inline]
pub unsafe fn graphics_unlock_bit_map(lock: APTR) {
    ((*IGraphics).UnlockBitMap)(IGraphics, lock)
}

#[inline]
pub unsafe fn graphics_rect_fill_color(rp: *mut RastPort, xMin: u32, yMin: u32, xMax: u32, yMax: u32, color: u32) {
    ((*IGraphics).RectFillColor)(IGraphics, rp, xMin, yMin, xMax, yMax, color)
}

#[inline]
pub unsafe fn graphics_write_pixel_color(rp: *mut RastPort, x: u32, y: u32, color: u32) -> i32 {
    ((*IGraphics).WritePixelColor)(IGraphics, rp, x, y, color)
}

#[inline]
pub unsafe fn graphics_read_pixel_color(rp: *mut RastPort, x: u32, y: u32) -> u32 {
    ((*IGraphics).ReadPixelColor)(IGraphics, rp, x, y)
}

#[inline]
pub unsafe fn graphics_read_pixel_array(src: *mut RastPort, srcX: u32, srcY: u32, dst: *mut u8, dstX: u32, dstY: u32, dstBytesPerRow: u32, dstPixelFormat: APTR, sizeX: u32, sizeY: u32) {
    ((*IGraphics).ReadPixelArray)(IGraphics, src, srcX, srcY, dst, dstX, dstY, dstBytesPerRow, dstPixelFormat, sizeX, sizeY)
}

#[inline]
pub unsafe fn graphics_write_pixel_array(src: *mut u8, srcX: u32, srcY: u32, srcBytesPerRow: u32, srcPixelFormat: APTR, dst: *mut RastPort, dstX: u32, dstY: u32, sizeX: u32, sizeY: u32) {
    ((*IGraphics).WritePixelArray)(IGraphics, src, srcX, srcY, srcBytesPerRow, srcPixelFormat, dst, dstX, dstY, sizeX, sizeY)
}

#[inline]
pub unsafe fn graphics_graphics_control_tag_list(tags: *const TagItem) -> u32 {
    ((*IGraphics).GraphicsControlTagList)(IGraphics, tags)
}

#[inline]
pub unsafe fn graphics_lock_bit_map_to_board_tag_list(bitMap: *mut BitMap, boardNum: u32, tags: *mut TagItem) -> APTR {
    ((*IGraphics).LockBitMapToBoardTagList)(IGraphics, bitMap, boardNum, tags)
}

#[inline]
pub unsafe fn graphics_unlock_bit_map_from_board(lock: APTR, modified: u32) {
    ((*IGraphics).UnlockBitMapFromBoard)(IGraphics, lock, modified)
}

#[inline]
pub unsafe fn graphics_get_board_bytes_per_row(boardNum: u32, pixelFormat: APTR, width: u32) -> u32 {
    ((*IGraphics).GetBoardBytesPerRow)(IGraphics, boardNum, pixelFormat, width)
}

#[inline]
pub unsafe fn graphics_init_board_tag_list(boardName: CONST_STRPTR, tags: *mut TagItem) -> APTR {
    ((*IGraphics).InitBoardTagList)(IGraphics, boardName, tags)
}

#[inline]
pub unsafe fn graphics_create_display_info_data(boardInfo: APTR) -> u32 {
    ((*IGraphics).CreateDisplayInfoData)(IGraphics, boardInfo)
}

#[inline]
pub unsafe fn graphics_pip_open_tag_list(Tags: *mut TagItem) -> *mut Window {
    ((*IGraphics).PIP_OpenTagList)(IGraphics, Tags)
}

#[inline]
pub unsafe fn graphics_pip_close(window: *mut Window) -> u32 {
    ((*IGraphics).PIP_Close)(IGraphics, window)
}

#[inline]
pub unsafe fn graphics_pip_set_tag_list(window: *mut Window, Tags: *mut TagItem) -> u32 {
    ((*IGraphics).PIP_SetTagList)(IGraphics, window, Tags)
}

#[inline]
pub unsafe fn graphics_pip_get_tag_list(window: *mut Window, Tags: *mut TagItem) -> u32 {
    ((*IGraphics).PIP_GetTagList)(IGraphics, window, Tags)
}

#[inline]
pub unsafe fn graphics_set_rast_color(rp: *mut RastPort, color: u32) {
    ((*IGraphics).SetRastColor)(IGraphics, rp, color)
}

