//! IIcon global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::icon::*;

// ---- IIcon (IconIFace) ----

extern "C" {
    pub static IIcon: *mut IconIFace;
}

#[inline]
pub unsafe fn icon_free_free_list(freelist: *mut FreeList) {
    ((*IIcon).FreeFreeList)(IIcon, freelist)
}

#[inline]
pub unsafe fn icon_add_free_list(freelist: *mut FreeList, mem: CONST_APTR, size: u32) -> u32 {
    ((*IIcon).AddFreeList)(IIcon, freelist, mem, size)
}

#[inline]
pub unsafe fn icon_get_disk_object(name: CONST_STRPTR) -> *mut DiskObject {
    ((*IIcon).GetDiskObject)(IIcon, name)
}

#[inline]
pub unsafe fn icon_put_disk_object(name: CONST_STRPTR, diskobj: *mut APTR) -> u32 {
    ((*IIcon).PutDiskObject)(IIcon, name, diskobj)
}

#[inline]
pub unsafe fn icon_free_disk_object(diskobj: *mut DiskObject) {
    ((*IIcon).FreeDiskObject)(IIcon, diskobj)
}

#[inline]
pub unsafe fn icon_find_tool_type(toolTypeArray: *mut STRPTR, typeName: CONST_STRPTR) -> STRPTR {
    ((*IIcon).FindToolType)(IIcon, toolTypeArray, typeName)
}

#[inline]
pub unsafe fn icon_match_tool_value(typeString: CONST_STRPTR, value: CONST_STRPTR) -> u32 {
    ((*IIcon).MatchToolValue)(IIcon, typeString, value)
}

#[inline]
pub unsafe fn icon_bump_revision(newname: STRPTR, oldname: CONST_STRPTR) -> STRPTR {
    ((*IIcon).BumpRevision)(IIcon, newname, oldname)
}

#[inline]
pub unsafe fn icon_free_alloc(freelist: *mut FreeList, len: u32, r#type: u32) -> APTR {
    ((*IIcon).FreeAlloc)(IIcon, freelist, len, r#type)
}

#[inline]
pub unsafe fn icon_get_def_disk_object(r#type: i32) -> *mut DiskObject {
    ((*IIcon).GetDefDiskObject)(IIcon, r#type)
}

#[inline]
pub unsafe fn icon_put_def_disk_object(diskObject: *mut APTR) -> u32 {
    ((*IIcon).PutDefDiskObject)(IIcon, diskObject)
}

#[inline]
pub unsafe fn icon_get_disk_object_new(name: CONST_STRPTR) -> *mut DiskObject {
    ((*IIcon).GetDiskObjectNew)(IIcon, name)
}

#[inline]
pub unsafe fn icon_delete_disk_object(name: CONST_STRPTR) -> u32 {
    ((*IIcon).DeleteDiskObject)(IIcon, name)
}

#[inline]
pub unsafe fn icon_free_free(fl: *mut FreeList, address: APTR) -> u32 {
    ((*IIcon).FreeFree)(IIcon, fl, address)
}

#[inline]
pub unsafe fn icon_dup_disk_object_a(diskObject: *mut APTR, tags: *mut APTR) -> *mut DiskObject {
    ((*IIcon).DupDiskObjectA)(IIcon, diskObject, tags)
}

#[inline]
pub unsafe fn icon_icon_control_a(icon: *mut DiskObject, tags: *mut APTR) -> u32 {
    ((*IIcon).IconControlA)(IIcon, icon, tags)
}

#[inline]
pub unsafe fn icon_draw_icon_state_a(rp: *mut RastPort, icon: *mut APTR, label: CONST_STRPTR, leftOffset: i32, topOffset: i32, state: u32, tags: *mut APTR) {
    ((*IIcon).DrawIconStateA)(IIcon, rp, icon, label, leftOffset, topOffset, state, tags)
}

#[inline]
pub unsafe fn icon_get_icon_rectangle_a(rp: *mut RastPort, icon: *mut APTR, label: CONST_STRPTR, rect: *mut Rectangle, tags: *mut APTR) -> u32 {
    ((*IIcon).GetIconRectangleA)(IIcon, rp, icon, label, rect, tags)
}

#[inline]
pub unsafe fn icon_new_disk_object(r#type: i32) -> *mut DiskObject {
    ((*IIcon).NewDiskObject)(IIcon, r#type)
}

#[inline]
pub unsafe fn icon_get_icon_tag_list(name: CONST_STRPTR, tags: *mut APTR) -> *mut DiskObject {
    ((*IIcon).GetIconTagList)(IIcon, name, tags)
}

#[inline]
pub unsafe fn icon_put_icon_tag_list(name: CONST_STRPTR, icon: *mut APTR, tags: *mut APTR) -> u32 {
    ((*IIcon).PutIconTagList)(IIcon, name, icon, tags)
}

#[inline]
pub unsafe fn icon_layout_icon_a(icon: *mut DiskObject, screen: *mut Screen, tags: *mut APTR) -> u32 {
    ((*IIcon).LayoutIconA)(IIcon, icon, screen, tags)
}

#[inline]
pub unsafe fn icon_change_to_selected_icon_color(cr: *mut ColorRegister) {
    ((*IIcon).ChangeToSelectedIconColor)(IIcon, cr)
}

#[inline]
pub unsafe fn icon_bump_revision_length(newname: STRPTR, oldname: CONST_STRPTR, maxlength: u32) -> STRPTR {
    ((*IIcon).BumpRevisionLength)(IIcon, newname, oldname, maxlength)
}

