//! IIFFParse global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::iffparse::*;

// ---- IIFFParse (IFFParseIFace) ----

extern "C" {
    pub static IIFFParse: *mut IFFParseIFace;
}

#[inline]
pub unsafe fn iffparse_alloc_iff() -> *mut IFFHandle {
    ((*IIFFParse).AllocIFF)(IIFFParse, )
}

#[inline]
pub unsafe fn iffparse_open_iff(iff: *mut IFFHandle, rwMode: i32) -> i32 {
    ((*IIFFParse).OpenIFF)(IIFFParse, iff, rwMode)
}

#[inline]
pub unsafe fn iffparse_parse_iff(iff: *mut IFFHandle, control: i32) -> i32 {
    ((*IIFFParse).ParseIFF)(IIFFParse, iff, control)
}

#[inline]
pub unsafe fn iffparse_close_iff(iff: *mut IFFHandle) {
    ((*IIFFParse).CloseIFF)(IIFFParse, iff)
}

#[inline]
pub unsafe fn iffparse_free_iff(iff: *mut IFFHandle) {
    ((*IIFFParse).FreeIFF)(IIFFParse, iff)
}

#[inline]
pub unsafe fn iffparse_read_chunk_bytes(iff: *mut IFFHandle, buf: APTR, numBytes: i32) -> i32 {
    ((*IIFFParse).ReadChunkBytes)(IIFFParse, iff, buf, numBytes)
}

#[inline]
pub unsafe fn iffparse_write_chunk_bytes(iff: *mut IFFHandle, buf: CONST_APTR, numBytes: i32) -> i32 {
    ((*IIFFParse).WriteChunkBytes)(IIFFParse, iff, buf, numBytes)
}

#[inline]
pub unsafe fn iffparse_read_chunk_records(iff: *mut IFFHandle, buf: APTR, bytesPerRecord: i32, numRecords: i32) -> i32 {
    ((*IIFFParse).ReadChunkRecords)(IIFFParse, iff, buf, bytesPerRecord, numRecords)
}

#[inline]
pub unsafe fn iffparse_write_chunk_records(iff: *mut IFFHandle, buf: CONST_APTR, bytesPerRecord: i32, numRecords: i32) -> i32 {
    ((*IIFFParse).WriteChunkRecords)(IIFFParse, iff, buf, bytesPerRecord, numRecords)
}

#[inline]
pub unsafe fn iffparse_push_chunk(iff: *mut IFFHandle, r#type: i32, id: i32, size: i32) -> i32 {
    ((*IIFFParse).PushChunk)(IIFFParse, iff, r#type, id, size)
}

#[inline]
pub unsafe fn iffparse_pop_chunk(iff: *mut IFFHandle) -> i32 {
    ((*IIFFParse).PopChunk)(IIFFParse, iff)
}

#[inline]
pub unsafe fn iffparse_entry_handler(iff: *mut IFFHandle, r#type: i32, id: i32, position: i32, handler: *mut Hook, object: APTR) -> i32 {
    ((*IIFFParse).EntryHandler)(IIFFParse, iff, r#type, id, position, handler, object)
}

#[inline]
pub unsafe fn iffparse_exit_handler(iff: *mut IFFHandle, r#type: i32, id: i32, position: i32, handler: *mut Hook, object: APTR) -> i32 {
    ((*IIFFParse).ExitHandler)(IIFFParse, iff, r#type, id, position, handler, object)
}

#[inline]
pub unsafe fn iffparse_prop_chunk(iff: *mut IFFHandle, r#type: i32, id: i32) -> i32 {
    ((*IIFFParse).PropChunk)(IIFFParse, iff, r#type, id)
}

#[inline]
pub unsafe fn iffparse_prop_chunks(iff: *mut IFFHandle, propArray: *const i32, numPairs: i32) -> i32 {
    ((*IIFFParse).PropChunks)(IIFFParse, iff, propArray, numPairs)
}

#[inline]
pub unsafe fn iffparse_stop_chunk(iff: *mut IFFHandle, r#type: i32, id: i32) -> i32 {
    ((*IIFFParse).StopChunk)(IIFFParse, iff, r#type, id)
}

#[inline]
pub unsafe fn iffparse_stop_chunks(iff: *mut IFFHandle, propArray: *const i32, numPairs: i32) -> i32 {
    ((*IIFFParse).StopChunks)(IIFFParse, iff, propArray, numPairs)
}

#[inline]
pub unsafe fn iffparse_collection_chunk(iff: *mut IFFHandle, r#type: i32, id: i32) -> i32 {
    ((*IIFFParse).CollectionChunk)(IIFFParse, iff, r#type, id)
}

#[inline]
pub unsafe fn iffparse_collection_chunks(iff: *mut IFFHandle, propArray: *const i32, numPairs: i32) -> i32 {
    ((*IIFFParse).CollectionChunks)(IIFFParse, iff, propArray, numPairs)
}

#[inline]
pub unsafe fn iffparse_stop_on_exit(iff: *mut IFFHandle, r#type: i32, id: i32) -> i32 {
    ((*IIFFParse).StopOnExit)(IIFFParse, iff, r#type, id)
}

#[inline]
pub unsafe fn iffparse_find_prop(iff: *const IFFHandle, r#type: i32, id: i32) -> *mut StoredProperty {
    ((*IIFFParse).FindProp)(IIFFParse, iff, r#type, id)
}

#[inline]
pub unsafe fn iffparse_find_collection(iff: *const IFFHandle, r#type: i32, id: i32) -> *mut CollectionItem {
    ((*IIFFParse).FindCollection)(IIFFParse, iff, r#type, id)
}

#[inline]
pub unsafe fn iffparse_find_prop_context(iff: *const IFFHandle) -> *mut ContextNode {
    ((*IIFFParse).FindPropContext)(IIFFParse, iff)
}

#[inline]
pub unsafe fn iffparse_current_chunk(iff: *const IFFHandle) -> *mut ContextNode {
    ((*IIFFParse).CurrentChunk)(IIFFParse, iff)
}

#[inline]
pub unsafe fn iffparse_parent_chunk(contextNode: *const ContextNode) -> *mut ContextNode {
    ((*IIFFParse).ParentChunk)(IIFFParse, contextNode)
}

#[inline]
pub unsafe fn iffparse_alloc_local_item(r#type: i32, id: i32, ident: i32, dataSize: i32) -> *mut LocalContextItem {
    ((*IIFFParse).AllocLocalItem)(IIFFParse, r#type, id, ident, dataSize)
}

#[inline]
pub unsafe fn iffparse_local_item_data(localItem: *const LocalContextItem) -> APTR {
    ((*IIFFParse).LocalItemData)(IIFFParse, localItem)
}

#[inline]
pub unsafe fn iffparse_set_local_item_purge(localItem: *mut LocalContextItem, purgeHook: *const Hook) {
    ((*IIFFParse).SetLocalItemPurge)(IIFFParse, localItem, purgeHook)
}

#[inline]
pub unsafe fn iffparse_free_local_item(localItem: *mut LocalContextItem) {
    ((*IIFFParse).FreeLocalItem)(IIFFParse, localItem)
}

#[inline]
pub unsafe fn iffparse_find_local_item(iff: *const IFFHandle, r#type: i32, id: i32, ident: i32) -> *mut LocalContextItem {
    ((*IIFFParse).FindLocalItem)(IIFFParse, iff, r#type, id, ident)
}

#[inline]
pub unsafe fn iffparse_store_local_item(iff: *mut IFFHandle, localItem: *mut LocalContextItem, position: i32) -> i32 {
    ((*IIFFParse).StoreLocalItem)(IIFFParse, iff, localItem, position)
}

#[inline]
pub unsafe fn iffparse_store_item_in_context(iff: *mut IFFHandle, localItem: *mut LocalContextItem, contextNode: *mut ContextNode) {
    ((*IIFFParse).StoreItemInContext)(IIFFParse, iff, localItem, contextNode)
}

#[inline]
pub unsafe fn iffparse_init_iff(iff: *mut IFFHandle, flags: i32, streamHook: *const Hook) {
    ((*IIFFParse).InitIFF)(IIFFParse, iff, flags, streamHook)
}

#[inline]
pub unsafe fn iffparse_init_iffas_dos(iff: *mut IFFHandle) {
    ((*IIFFParse).InitIFFasDOS)(IIFFParse, iff)
}

#[inline]
pub unsafe fn iffparse_init_iffas_clip(iff: *mut IFFHandle) {
    ((*IIFFParse).InitIFFasClip)(IIFFParse, iff)
}

#[inline]
pub unsafe fn iffparse_open_clipboard(unitNumber: i32) -> *mut ClipboardHandle {
    ((*IIFFParse).OpenClipboard)(IIFFParse, unitNumber)
}

#[inline]
pub unsafe fn iffparse_close_clipboard(clipHandle: *mut ClipboardHandle) {
    ((*IIFFParse).CloseClipboard)(IIFFParse, clipHandle)
}

#[inline]
pub unsafe fn iffparse_good_id(id: i32) -> i32 {
    ((*IIFFParse).GoodID)(IIFFParse, id)
}

#[inline]
pub unsafe fn iffparse_good_type(r#type: i32) -> i32 {
    ((*IIFFParse).GoodType)(IIFFParse, r#type)
}

#[inline]
pub unsafe fn iffparse_idto_str(id: i32, buf: STRPTR) -> STRPTR {
    ((*IIFFParse).IDtoStr)(IIFFParse, id, buf)
}

