//! IIntuition global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::intuition::*;

// ---- IIntuition (IntuitionIFace) ----

extern "C" {
    pub static IIntuition: *mut IntuitionIFace;
}

#[inline]
pub unsafe fn intuition_open_intuition() {
    ((*IIntuition).OpenIntuition)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_intuition(iEvent: *mut InputEvent) {
    ((*IIntuition).Intuition)(IIntuition, iEvent)
}

#[inline]
pub unsafe fn intuition_add_gadget(window: *mut Window, gadget: *mut Gadget, position: u16) -> u16 {
    ((*IIntuition).AddGadget)(IIntuition, window, gadget, position)
}

#[inline]
pub unsafe fn intuition_clear_dmrequest(window: *mut Window) -> u32 {
    ((*IIntuition).ClearDMRequest)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_clear_menu_strip(window: *mut Window) {
    ((*IIntuition).ClearMenuStrip)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_clear_pointer(window: *mut Window) {
    ((*IIntuition).ClearPointer)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_close_screen(screen: *mut Screen) -> u32 {
    ((*IIntuition).CloseScreen)(IIntuition, screen)
}

#[inline]
pub unsafe fn intuition_close_window(window: *mut Window) {
    ((*IIntuition).CloseWindow)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_close_work_bench() -> i32 {
    ((*IIntuition).CloseWorkBench)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_current_time(seconds: *mut u32, micros: *mut u32) {
    ((*IIntuition).CurrentTime)(IIntuition, seconds, micros)
}

#[inline]
pub unsafe fn intuition_display_alert(alertNumber: u32, string: CONST_STRPTR, height: u16) -> u32 {
    ((*IIntuition).DisplayAlert)(IIntuition, alertNumber, string, height)
}

#[inline]
pub unsafe fn intuition_display_beep(screen: *mut Screen) {
    ((*IIntuition).DisplayBeep)(IIntuition, screen)
}

#[inline]
pub unsafe fn intuition_double_click(sSeconds: u32, sMicros: u32, cSeconds: u32, cMicros: u32) -> u32 {
    ((*IIntuition).DoubleClick)(IIntuition, sSeconds, sMicros, cSeconds, cMicros)
}

#[inline]
pub unsafe fn intuition_draw_border(rp: *mut RastPort, border: *const Border, leftOffset: i16, topOffset: i16) {
    ((*IIntuition).DrawBorder)(IIntuition, rp, border, leftOffset, topOffset)
}

#[inline]
pub unsafe fn intuition_draw_image(rp: *mut RastPort, image: *mut Image, leftOffset: i16, topOffset: i16) {
    ((*IIntuition).DrawImage)(IIntuition, rp, image, leftOffset, topOffset)
}

#[inline]
pub unsafe fn intuition_end_request(requester: *mut Requester, window: *mut Window) {
    ((*IIntuition).EndRequest)(IIntuition, requester, window)
}

#[inline]
pub unsafe fn intuition_get_def_prefs(preferences: *mut Preferences, size: i16) -> *mut Preferences {
    ((*IIntuition).GetDefPrefs)(IIntuition, preferences, size)
}

#[inline]
pub unsafe fn intuition_get_prefs(preferences: *mut Preferences, size: i16) -> *mut Preferences {
    ((*IIntuition).GetPrefs)(IIntuition, preferences, size)
}

#[inline]
pub unsafe fn intuition_init_requester(requester: *mut Requester) {
    ((*IIntuition).InitRequester)(IIntuition, requester)
}

#[inline]
pub unsafe fn intuition_item_address(menuStrip: *const Menu, menuNumber: u16) -> *mut MenuItem {
    ((*IIntuition).ItemAddress)(IIntuition, menuStrip, menuNumber)
}

#[inline]
pub unsafe fn intuition_modify_idcmp(window: *mut Window, flags: u32) -> u32 {
    ((*IIntuition).ModifyIDCMP)(IIntuition, window, flags)
}

#[inline]
pub unsafe fn intuition_modify_prop(gadget: *mut Gadget, window: *mut Window, requester: *mut Requester, flags: u16, horizPot: u16, vertPot: u16, horizBody: u16, vertBody: u16) {
    ((*IIntuition).ModifyProp)(IIntuition, gadget, window, requester, flags, horizPot, vertPot, horizBody, vertBody)
}

#[inline]
pub unsafe fn intuition_move_screen(screen: *mut Screen, dx: i16, dy: i16) {
    ((*IIntuition).MoveScreen)(IIntuition, screen, dx, dy)
}

#[inline]
pub unsafe fn intuition_move_window(window: *mut Window, dx: i16, dy: i16) {
    ((*IIntuition).MoveWindow)(IIntuition, window, dx, dy)
}

#[inline]
pub unsafe fn intuition_off_gadget(gadget: *mut Gadget, window: *mut Window, requester: *mut Requester) {
    ((*IIntuition).OffGadget)(IIntuition, gadget, window, requester)
}

#[inline]
pub unsafe fn intuition_off_menu(window: *mut Window, menuNumber: u16) {
    ((*IIntuition).OffMenu)(IIntuition, window, menuNumber)
}

#[inline]
pub unsafe fn intuition_on_gadget(gadget: *mut Gadget, window: *mut Window, requester: *mut Requester) {
    ((*IIntuition).OnGadget)(IIntuition, gadget, window, requester)
}

#[inline]
pub unsafe fn intuition_on_menu(window: *mut Window, menuNumber: u16) {
    ((*IIntuition).OnMenu)(IIntuition, window, menuNumber)
}

#[inline]
pub unsafe fn intuition_open_screen(newScreen: *const NewScreen) -> *mut Screen {
    ((*IIntuition).OpenScreen)(IIntuition, newScreen)
}

#[inline]
pub unsafe fn intuition_open_window(newWindow: *const NewWindow) -> *mut Window {
    ((*IIntuition).OpenWindow)(IIntuition, newWindow)
}

#[inline]
pub unsafe fn intuition_open_work_bench() -> u32 {
    ((*IIntuition).OpenWorkBench)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_print_itext(rp: *mut RastPort, iText: *const IntuiText, left: i16, top: i16) {
    ((*IIntuition).PrintIText)(IIntuition, rp, iText, left, top)
}

#[inline]
pub unsafe fn intuition_refresh_gadgets(gadgets: *mut Gadget, window: *mut Window, requester: *mut Requester) {
    ((*IIntuition).RefreshGadgets)(IIntuition, gadgets, window, requester)
}

#[inline]
pub unsafe fn intuition_remove_gadget(window: *mut Window, gadget: *mut Gadget) -> u16 {
    ((*IIntuition).RemoveGadget)(IIntuition, window, gadget)
}

#[inline]
pub unsafe fn intuition_report_mouse(flag: u32, window: *mut Window) {
    ((*IIntuition).ReportMouse)(IIntuition, flag, window)
}

#[inline]
pub unsafe fn intuition_report_mouse1(window: *mut Window, flag: u32) {
    ((*IIntuition).ReportMouse1)(IIntuition, window, flag)
}

#[inline]
pub unsafe fn intuition_request(requester: *mut Requester, window: *mut Window) -> u32 {
    ((*IIntuition).Request)(IIntuition, requester, window)
}

#[inline]
pub unsafe fn intuition_screen_to_back(screen: *mut Screen) {
    ((*IIntuition).ScreenToBack)(IIntuition, screen)
}

#[inline]
pub unsafe fn intuition_screen_to_front(screen: *mut Screen) {
    ((*IIntuition).ScreenToFront)(IIntuition, screen)
}

#[inline]
pub unsafe fn intuition_set_dmrequest(window: *mut Window, requester: *mut Requester) -> u32 {
    ((*IIntuition).SetDMRequest)(IIntuition, window, requester)
}

#[inline]
pub unsafe fn intuition_set_menu_strip(window: *mut Window, menu: *mut Menu) -> u32 {
    ((*IIntuition).SetMenuStrip)(IIntuition, window, menu)
}

#[inline]
pub unsafe fn intuition_set_pointer(window: *mut Window, pointer: *mut u16, height: i16, width: i16, xOffset: i16, yOffset: i16) {
    ((*IIntuition).SetPointer)(IIntuition, window, pointer, height, width, xOffset, yOffset)
}

#[inline]
pub unsafe fn intuition_set_window_titles(window: *mut Window, windowTitle: CONST_STRPTR, screenTitle: CONST_STRPTR) {
    ((*IIntuition).SetWindowTitles)(IIntuition, window, windowTitle, screenTitle)
}

#[inline]
pub unsafe fn intuition_show_title(screen: *mut Screen, showIt: u32) {
    ((*IIntuition).ShowTitle)(IIntuition, screen, showIt)
}

#[inline]
pub unsafe fn intuition_size_window(window: *mut Window, dx: i16, dy: i16) {
    ((*IIntuition).SizeWindow)(IIntuition, window, dx, dy)
}

#[inline]
pub unsafe fn intuition_view_address() -> *mut View {
    ((*IIntuition).ViewAddress)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_view_port_address(window: *const Window) -> *mut ViewPort {
    ((*IIntuition).ViewPortAddress)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_window_to_back(window: *mut Window) {
    ((*IIntuition).WindowToBack)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_window_to_front(window: *mut Window) {
    ((*IIntuition).WindowToFront)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_window_limits(window: *mut Window, widthMin: i32, heightMin: i32, widthMax: u32, heightMax: u32) -> u32 {
    ((*IIntuition).WindowLimits)(IIntuition, window, widthMin, heightMin, widthMax, heightMax)
}

#[inline]
pub unsafe fn intuition_set_prefs(preferences: *const Preferences, size: i32, inform: u32) -> *mut Preferences {
    ((*IIntuition).SetPrefs)(IIntuition, preferences, size, inform)
}

#[inline]
pub unsafe fn intuition_intui_text_length(iText: *const IntuiText) -> i32 {
    ((*IIntuition).IntuiTextLength)(IIntuition, iText)
}

#[inline]
pub unsafe fn intuition_wbench_to_back() -> u32 {
    ((*IIntuition).WBenchToBack)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_wbench_to_front() -> u32 {
    ((*IIntuition).WBenchToFront)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_auto_request(window: *mut Window, body: *const IntuiText, posText: *const IntuiText, negText: *const IntuiText, pFlag: u32, nFlag: u32, width: u16, height: u16) -> u32 {
    ((*IIntuition).AutoRequest)(IIntuition, window, body, posText, negText, pFlag, nFlag, width, height)
}

#[inline]
pub unsafe fn intuition_begin_refresh(window: *mut Window) {
    ((*IIntuition).BeginRefresh)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_build_sys_request(window: *mut Window, body: *const IntuiText, posText: *const IntuiText, negText: *const IntuiText, flags: u32, width: u16, height: u16) -> *mut Window {
    ((*IIntuition).BuildSysRequest)(IIntuition, window, body, posText, negText, flags, width, height)
}

#[inline]
pub unsafe fn intuition_end_refresh(window: *mut Window, complete: i32) {
    ((*IIntuition).EndRefresh)(IIntuition, window, complete)
}

#[inline]
pub unsafe fn intuition_free_sys_request(window: *mut Window) {
    ((*IIntuition).FreeSysRequest)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_make_screen(screen: *mut Screen) -> i32 {
    ((*IIntuition).MakeScreen)(IIntuition, screen)
}

#[inline]
pub unsafe fn intuition_remake_display() -> i32 {
    ((*IIntuition).RemakeDisplay)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_rethink_display() -> i32 {
    ((*IIntuition).RethinkDisplay)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_alloc_remember(rememberKey: *mut *mut Remember, size: u32, flags: u32) -> APTR {
    ((*IIntuition).AllocRemember)(IIntuition, rememberKey, size, flags)
}

#[inline]
pub unsafe fn intuition_aloha_workbench(wbport: i32) {
    ((*IIntuition).AlohaWorkbench)(IIntuition, wbport)
}

#[inline]
pub unsafe fn intuition_free_remember(rememberKey: *mut *mut Remember, reallyForget: u32) {
    ((*IIntuition).FreeRemember)(IIntuition, rememberKey, reallyForget)
}

#[inline]
pub unsafe fn intuition_lock_ibase(dontknow: u32) -> u32 {
    ((*IIntuition).LockIBase)(IIntuition, dontknow)
}

#[inline]
pub unsafe fn intuition_unlock_ibase(ibLock: u32) {
    ((*IIntuition).UnlockIBase)(IIntuition, ibLock)
}

#[inline]
pub unsafe fn intuition_get_screen_data(buffer: APTR, size: u16, r#type: u16, screen: *const Screen) -> i32 {
    ((*IIntuition).GetScreenData)(IIntuition, buffer, size, r#type, screen)
}

#[inline]
pub unsafe fn intuition_refresh_glist(gadgets: *mut Gadget, window: *mut Window, requester: *mut Requester, numGad: i16) {
    ((*IIntuition).RefreshGList)(IIntuition, gadgets, window, requester, numGad)
}

#[inline]
pub unsafe fn intuition_add_glist(window: *mut Window, gadget: *mut Gadget, position: u16, numGad: i16, requester: *mut Requester) -> u16 {
    ((*IIntuition).AddGList)(IIntuition, window, gadget, position, numGad, requester)
}

#[inline]
pub unsafe fn intuition_remove_glist(remPtr: *mut Window, gadget: *mut Gadget, numGad: i16) -> u16 {
    ((*IIntuition).RemoveGList)(IIntuition, remPtr, gadget, numGad)
}

#[inline]
pub unsafe fn intuition_activate_window(window: *mut Window) {
    ((*IIntuition).ActivateWindow)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_refresh_window_frame(window: *mut Window) {
    ((*IIntuition).RefreshWindowFrame)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_activate_gadget(gadgets: *mut Gadget, window: *mut Window, requester: *mut Requester) -> u32 {
    ((*IIntuition).ActivateGadget)(IIntuition, gadgets, window, requester)
}

#[inline]
pub unsafe fn intuition_new_modify_prop(gadget: *mut Gadget, window: *mut Window, requester: *mut Requester, flags: u16, horizPot: u16, vertPot: u16, horizBody: u16, vertBody: u16, numGad: i16) {
    ((*IIntuition).NewModifyProp)(IIntuition, gadget, window, requester, flags, horizPot, vertPot, horizBody, vertBody, numGad)
}

#[inline]
pub unsafe fn intuition_query_overscan(displayID: u32, rect: *mut Rectangle, oScanType: i16) -> i32 {
    ((*IIntuition).QueryOverscan)(IIntuition, displayID, rect, oScanType)
}

#[inline]
pub unsafe fn intuition_move_window_in_front_of(window: *mut Window, behindWindow: *mut Window) {
    ((*IIntuition).MoveWindowInFrontOf)(IIntuition, window, behindWindow)
}

#[inline]
pub unsafe fn intuition_change_window_box(window: *mut Window, left: i16, top: i16, width: i16, height: i16) {
    ((*IIntuition).ChangeWindowBox)(IIntuition, window, left, top, width, height)
}

#[inline]
pub unsafe fn intuition_set_edit_hook(hook: *mut Hook) -> *mut Hook {
    ((*IIntuition).SetEditHook)(IIntuition, hook)
}

#[inline]
pub unsafe fn intuition_set_mouse_queue(window: *mut Window, queueLength: u16) -> i32 {
    ((*IIntuition).SetMouseQueue)(IIntuition, window, queueLength)
}

#[inline]
pub unsafe fn intuition_zip_window(window: *mut Window) {
    ((*IIntuition).ZipWindow)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_lock_pub_screen(name: CONST_STRPTR) -> *mut Screen {
    ((*IIntuition).LockPubScreen)(IIntuition, name)
}

#[inline]
pub unsafe fn intuition_unlock_pub_screen(name: CONST_STRPTR, screen: *mut Screen) {
    ((*IIntuition).UnlockPubScreen)(IIntuition, name, screen)
}

#[inline]
pub unsafe fn intuition_lock_pub_screen_list() -> *mut List {
    ((*IIntuition).LockPubScreenList)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_unlock_pub_screen_list() {
    ((*IIntuition).UnlockPubScreenList)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_next_pub_screen(screen: *const Screen, namebuf: STRPTR) -> STRPTR {
    ((*IIntuition).NextPubScreen)(IIntuition, screen, namebuf)
}

#[inline]
pub unsafe fn intuition_set_default_pub_screen(name: CONST_STRPTR) {
    ((*IIntuition).SetDefaultPubScreen)(IIntuition, name)
}

#[inline]
pub unsafe fn intuition_set_pub_screen_modes(modes: u16) -> u16 {
    ((*IIntuition).SetPubScreenModes)(IIntuition, modes)
}

#[inline]
pub unsafe fn intuition_pub_screen_status(screen: *mut Screen, statusFlags: u16) -> u16 {
    ((*IIntuition).PubScreenStatus)(IIntuition, screen, statusFlags)
}

#[inline]
pub unsafe fn intuition_obtain_girport(gInfo: *mut GadgetInfo) -> *mut RastPort {
    ((*IIntuition).ObtainGIRPort)(IIntuition, gInfo)
}

#[inline]
pub unsafe fn intuition_release_girport(rp: *mut RastPort) {
    ((*IIntuition).ReleaseGIRPort)(IIntuition, rp)
}

#[inline]
pub unsafe fn intuition_gadget_mouse(gadget: *mut Gadget, gInfo: *mut GadgetInfo, mousePoint: *mut i16) {
    ((*IIntuition).GadgetMouse)(IIntuition, gadget, gInfo, mousePoint)
}

#[inline]
pub unsafe fn intuition_set_iprefs(ptr: APTR, size: i32, r#type: i32) -> APTR {
    ((*IIntuition).SetIPrefs)(IIntuition, ptr, size, r#type)
}

#[inline]
pub unsafe fn intuition_get_default_pub_screen(nameBuffer: STRPTR) {
    ((*IIntuition).GetDefaultPubScreen)(IIntuition, nameBuffer)
}

#[inline]
pub unsafe fn intuition_easy_request_args(window: *mut Window, easyStruct: *const EasyStruct, idcmpPtr: *mut u32, args: APTR) -> i32 {
    ((*IIntuition).EasyRequestArgs)(IIntuition, window, easyStruct, idcmpPtr, args)
}

#[inline]
pub unsafe fn intuition_build_easy_request_args(window: *mut Window, easyStruct: *const EasyStruct, idcmp: u32, args: APTR) -> *mut Window {
    ((*IIntuition).BuildEasyRequestArgs)(IIntuition, window, easyStruct, idcmp, args)
}

#[inline]
pub unsafe fn intuition_sys_req_handler(window: *mut Window, idcmpPtr: *mut u32, waitInput: u32) -> i32 {
    ((*IIntuition).SysReqHandler)(IIntuition, window, idcmpPtr, waitInput)
}

#[inline]
pub unsafe fn intuition_open_window_tag_list(newWindow: *const NewWindow, tagList: *const TagItem) -> *mut Window {
    ((*IIntuition).OpenWindowTagList)(IIntuition, newWindow, tagList)
}

#[inline]
pub unsafe fn intuition_open_screen_tag_list(newScreen: *const NewScreen, tagList: *const TagItem) -> *mut Screen {
    ((*IIntuition).OpenScreenTagList)(IIntuition, newScreen, tagList)
}

#[inline]
pub unsafe fn intuition_draw_image_state(rp: *mut RastPort, image: *mut Image, leftOffset: i16, topOffset: i16, state: u32, drawInfo: *const DrawInfo) {
    ((*IIntuition).DrawImageState)(IIntuition, rp, image, leftOffset, topOffset, state, drawInfo)
}

#[inline]
pub unsafe fn intuition_point_in_image(point: u32, image: *mut Image) -> u32 {
    ((*IIntuition).PointInImage)(IIntuition, point, image)
}

#[inline]
pub unsafe fn intuition_erase_image(rp: *mut RastPort, image: *mut Image, leftOffset: i16, topOffset: i16) {
    ((*IIntuition).EraseImage)(IIntuition, rp, image, leftOffset, topOffset)
}

#[inline]
pub unsafe fn intuition_new_object_a(cl: *mut APTR, classID: APTR, tagList: *const TagItem) -> *mut APTR {
    ((*IIntuition).NewObjectA)(IIntuition, cl, classID, tagList)
}

#[inline]
pub unsafe fn intuition_dispose_object(object: *mut APTR) {
    ((*IIntuition).DisposeObject)(IIntuition, object)
}

#[inline]
pub unsafe fn intuition_set_attrs_a(object: *mut APTR, tagList: *const TagItem) -> u32 {
    ((*IIntuition).SetAttrsA)(IIntuition, object, tagList)
}

#[inline]
pub unsafe fn intuition_get_attr(attrID: u32, object: *mut APTR, storagePtr: *mut u32) -> u32 {
    ((*IIntuition).GetAttr)(IIntuition, attrID, object, storagePtr)
}

#[inline]
pub unsafe fn intuition_set_gadget_attrs_a(gadget: *mut Gadget, window: *mut Window, requester: *mut Requester, tagList: *const TagItem) -> u32 {
    ((*IIntuition).SetGadgetAttrsA)(IIntuition, gadget, window, requester, tagList)
}

#[inline]
pub unsafe fn intuition_next_object(objectPtrPtr: *mut *mut APTR) -> *mut APTR {
    ((*IIntuition).NextObject)(IIntuition, objectPtrPtr)
}

#[inline]
pub unsafe fn intuition_find_class(classID: APTR) -> *mut APTR {
    ((*IIntuition).FindClass)(IIntuition, classID)
}

#[inline]
pub unsafe fn intuition_make_class(classID: APTR, superClassID: APTR, superClassPtr: *const APTR, instanceSize: u16, flags: u32) -> *mut APTR {
    ((*IIntuition).MakeClass)(IIntuition, classID, superClassID, superClassPtr, instanceSize, flags)
}

#[inline]
pub unsafe fn intuition_add_class(cl: *mut APTR) {
    ((*IIntuition).AddClass)(IIntuition, cl)
}

#[inline]
pub unsafe fn intuition_get_screen_draw_info(screen: *mut Screen) -> *mut DrawInfo {
    ((*IIntuition).GetScreenDrawInfo)(IIntuition, screen)
}

#[inline]
pub unsafe fn intuition_free_screen_draw_info(screen: *mut Screen, drawInfo: *mut DrawInfo) {
    ((*IIntuition).FreeScreenDrawInfo)(IIntuition, screen, drawInfo)
}

#[inline]
pub unsafe fn intuition_reset_menu_strip(window: *mut Window, menu: *mut Menu) -> u32 {
    ((*IIntuition).ResetMenuStrip)(IIntuition, window, menu)
}

#[inline]
pub unsafe fn intuition_remove_class(cl: *mut APTR) {
    ((*IIntuition).RemoveClass)(IIntuition, cl)
}

#[inline]
pub unsafe fn intuition_free_class(cl: *mut APTR) -> u32 {
    ((*IIntuition).FreeClass)(IIntuition, cl)
}

#[inline]
pub unsafe fn intuition_lock_class_list() -> *mut List {
    ((*IIntuition).LockClassList)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_unlock_class_list() {
    ((*IIntuition).UnlockClassList)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_reserved1() {
    ((*IIntuition).Reserved1)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_reserved2() {
    ((*IIntuition).Reserved2)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_reserved3() {
    ((*IIntuition).Reserved3)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_reserved4() {
    ((*IIntuition).Reserved4)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_reserved5() {
    ((*IIntuition).Reserved5)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_reserved6() {
    ((*IIntuition).Reserved6)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_alloc_screen_buffer(sc: *mut Screen, bm: *mut BitMap, flags: u32) -> *mut ScreenBuffer {
    ((*IIntuition).AllocScreenBuffer)(IIntuition, sc, bm, flags)
}

#[inline]
pub unsafe fn intuition_free_screen_buffer(sc: *mut Screen, sb: *mut ScreenBuffer) {
    ((*IIntuition).FreeScreenBuffer)(IIntuition, sc, sb)
}

#[inline]
pub unsafe fn intuition_change_screen_buffer(sc: *mut Screen, sb: *mut ScreenBuffer) -> u32 {
    ((*IIntuition).ChangeScreenBuffer)(IIntuition, sc, sb)
}

#[inline]
pub unsafe fn intuition_screen_depth(screen: *mut Screen, flags: u32, reserved: APTR) {
    ((*IIntuition).ScreenDepth)(IIntuition, screen, flags, reserved)
}

#[inline]
pub unsafe fn intuition_screen_position(screen: *mut Screen, flags: u32, x1: i32, y1: i32, x2: i32, y2: i32) {
    ((*IIntuition).ScreenPosition)(IIntuition, screen, flags, x1, y1, x2, y2)
}

#[inline]
pub unsafe fn intuition_scroll_window_raster(win: *mut Window, dx: i16, dy: i16, xMin: i16, yMin: i16, xMax: i16, yMax: i16) {
    ((*IIntuition).ScrollWindowRaster)(IIntuition, win, dx, dy, xMin, yMin, xMax, yMax)
}

#[inline]
pub unsafe fn intuition_lend_menus(fromwindow: *mut Window, towindow: *mut Window) {
    ((*IIntuition).LendMenus)(IIntuition, fromwindow, towindow)
}

#[inline]
pub unsafe fn intuition_do_gadget_method_a(gad: *mut Gadget, win: *mut Window, req: *mut Requester, message: APTR) -> u32 {
    ((*IIntuition).DoGadgetMethodA)(IIntuition, gad, win, req, message)
}

#[inline]
pub unsafe fn intuition_set_window_pointer_a(win: *mut Window, taglist: *const TagItem) {
    ((*IIntuition).SetWindowPointerA)(IIntuition, win, taglist)
}

#[inline]
pub unsafe fn intuition_timed_display_alert(alertNumber: u32, string: CONST_STRPTR, height: u16, Time: u32) -> u32 {
    ((*IIntuition).TimedDisplayAlert)(IIntuition, alertNumber, string, height, Time)
}

#[inline]
pub unsafe fn intuition_help_control(win: *mut Window, flags: u32) {
    ((*IIntuition).HelpControl)(IIntuition, win, flags)
}

#[inline]
pub unsafe fn intuition_show_window(window: *mut Window, other: *mut Window) -> u32 {
    ((*IIntuition).ShowWindow)(IIntuition, window, other)
}

#[inline]
pub unsafe fn intuition_hide_window(window: *mut Window) -> u32 {
    ((*IIntuition).HideWindow)(IIntuition, window)
}

#[inline]
pub unsafe fn intuition_get_attrs_a(object: *mut APTR, tagList: *mut TagItem) -> u32 {
    ((*IIntuition).GetAttrsA)(IIntuition, object, tagList)
}

#[inline]
pub unsafe fn intuition_lock_guiprefs(reserved: u32) -> APTR {
    ((*IIntuition).LockGUIPrefs)(IIntuition, reserved)
}

#[inline]
pub unsafe fn intuition_unlock_guiprefs(lock: APTR) {
    ((*IIntuition).UnlockGUIPrefs)(IIntuition, lock)
}

#[inline]
pub unsafe fn intuition_set_guiattrs_a(reserved: APTR, drawinfo: *mut DrawInfo, taglist: *mut TagItem) -> u32 {
    ((*IIntuition).SetGUIAttrsA)(IIntuition, reserved, drawinfo, taglist)
}

#[inline]
pub unsafe fn intuition_get_guiattrs_a(reserved: APTR, drawinfo: *mut DrawInfo, taglist: *mut TagItem) -> u32 {
    ((*IIntuition).GetGUIAttrsA)(IIntuition, reserved, drawinfo, taglist)
}

#[inline]
pub unsafe fn intuition_get_half_pens(drawinfo: *mut DrawInfo, basepen: u32, halfshineptr: *mut u16, halfshadowptr: *mut u16) -> u32 {
    ((*IIntuition).GetHalfPens)(IIntuition, drawinfo, basepen, halfshineptr, halfshadowptr)
}

#[inline]
pub unsafe fn intuition_gadget_box(gadget: *mut Gadget, domain: APTR, domaintype: u32, flags: u32, r#box: APTR) -> u32 {
    ((*IIntuition).GadgetBox)(IIntuition, gadget, domain, domaintype, flags, r#box)
}

#[inline]
pub unsafe fn intuition_refresh_set_gadget_attrs_a(gadget: *mut Gadget, window: *mut Window, req: *mut Requester, taglist: *mut TagItem) {
    ((*IIntuition).RefreshSetGadgetAttrsA)(IIntuition, gadget, window, req, taglist)
}

#[inline]
pub unsafe fn intuition_ido_super_method_a(cl: *mut APTR, object: *mut APTR, msg: APTR) -> u32 {
    ((*IIntuition).IDoSuperMethodA)(IIntuition, cl, object, msg)
}

#[inline]
pub unsafe fn intuition_iset_super_attrs_a(cl: *mut APTR, object: *mut APTR, taglist: *mut TagItem) -> u32 {
    ((*IIntuition).ISetSuperAttrsA)(IIntuition, cl, object, taglist)
}

#[inline]
pub unsafe fn intuition_icoerce_method_a(cl: *mut APTR, object: *mut APTR, msg: APTR) -> u32 {
    ((*IIntuition).ICoerceMethodA)(IIntuition, cl, object, msg)
}

#[inline]
pub unsafe fn intuition_ido_method_a(object: *mut APTR, msg: APTR) -> u32 {
    ((*IIntuition).IDoMethodA)(IIntuition, object, msg)
}

#[inline]
pub unsafe fn intuition_open_class(name: CONST_STRPTR, version: u32, cl_ptr: *mut *mut APTR) -> *mut ClassLibrary {
    ((*IIntuition).OpenClass)(IIntuition, name, version, cl_ptr)
}

#[inline]
pub unsafe fn intuition_close_class(cl: *mut ClassLibrary) {
    ((*IIntuition).CloseClass)(IIntuition, cl)
}

#[inline]
pub unsafe fn intuition_set_display_beep_hook(hook: *mut Hook) -> *mut Hook {
    ((*IIntuition).SetDisplayBeepHook)(IIntuition, hook)
}

#[inline]
pub unsafe fn intuition_lock_screen(screen: *mut Screen, micros: u32) -> u32 {
    ((*IIntuition).LockScreen)(IIntuition, screen, micros)
}

#[inline]
pub unsafe fn intuition_unlock_screen(screen: *mut Screen) {
    ((*IIntuition).UnlockScreen)(IIntuition, screen)
}

#[inline]
pub unsafe fn intuition_get_window_attrs_a(win: *mut Window, taglist: *mut TagItem) -> i32 {
    ((*IIntuition).GetWindowAttrsA)(IIntuition, win, taglist)
}

#[inline]
pub unsafe fn intuition_set_window_attrs_a(win: *mut Window, taglist: *mut TagItem) -> i32 {
    ((*IIntuition).SetWindowAttrsA)(IIntuition, win, taglist)
}

#[inline]
pub unsafe fn intuition_get_window_attr(win: *mut Window, attr: u32, data: APTR, size: u32) -> i32 {
    ((*IIntuition).GetWindowAttr)(IIntuition, win, attr, data, size)
}

#[inline]
pub unsafe fn intuition_set_window_attr(win: *mut Window, attr: u32, data: APTR, size: u32) -> i32 {
    ((*IIntuition).SetWindowAttr)(IIntuition, win, attr, data, size)
}

#[inline]
pub unsafe fn intuition_strip_intui_messages(port: *mut MsgPort, win: *mut Window) {
    ((*IIntuition).StripIntuiMessages)(IIntuition, port, win)
}

#[inline]
pub unsafe fn intuition_reserved7() {
    ((*IIntuition).Reserved7)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_reserved8() {
    ((*IIntuition).Reserved8)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_get_screen_attrs_a(scr: *mut Screen, taglist: *mut TagItem) -> i32 {
    ((*IIntuition).GetScreenAttrsA)(IIntuition, scr, taglist)
}

#[inline]
pub unsafe fn intuition_set_screen_attrs_a(scr: *mut Screen, taglist: *mut TagItem) -> i32 {
    ((*IIntuition).SetScreenAttrsA)(IIntuition, scr, taglist)
}

#[inline]
pub unsafe fn intuition_get_screen_attr(scr: *mut Screen, attr: u32, data: APTR, size: u32) -> i32 {
    ((*IIntuition).GetScreenAttr)(IIntuition, scr, attr, data, size)
}

#[inline]
pub unsafe fn intuition_set_screen_attr(scr: *mut Screen, attr: u32, data: APTR, size: u32) -> i32 {
    ((*IIntuition).SetScreenAttr)(IIntuition, scr, attr, data, size)
}

#[inline]
pub unsafe fn intuition_lock_screen_list() -> *mut Screen {
    ((*IIntuition).LockScreenList)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_unlock_screen_list() {
    ((*IIntuition).UnlockScreenList)(IIntuition, )
}

#[inline]
pub unsafe fn intuition_lock_screen_gi(gi: *mut GadgetInfo, micros: u32) -> *mut RastPort {
    ((*IIntuition).LockScreenGI)(IIntuition, gi, micros)
}

#[inline]
pub unsafe fn intuition_unlock_screen_gi(gi: *mut GadgetInfo, rp: *mut RastPort) {
    ((*IIntuition).UnlockScreenGI)(IIntuition, gi, rp)
}

#[inline]
pub unsafe fn intuition_get_marked_block(sgw: *mut SGWork) -> u32 {
    ((*IIntuition).GetMarkedBlock)(IIntuition, sgw)
}

#[inline]
pub unsafe fn intuition_set_marked_block(sgw: *mut SGWork, block: u32) {
    ((*IIntuition).SetMarkedBlock)(IIntuition, sgw, block)
}

#[inline]
pub unsafe fn intuition_obtain_bit_map_source_a(name: CONST_STRPTR, taglist: *mut TagItem) -> APTR {
    ((*IIntuition).ObtainBitMapSourceA)(IIntuition, name, taglist)
}

#[inline]
pub unsafe fn intuition_release_bit_map_source(bitmapsource: APTR) {
    ((*IIntuition).ReleaseBitMapSource)(IIntuition, bitmapsource)
}

#[inline]
pub unsafe fn intuition_obtain_bit_map_instance_a(bitmapsource: APTR, screen: *mut Screen, taglist: *mut TagItem) -> APTR {
    ((*IIntuition).ObtainBitMapInstanceA)(IIntuition, bitmapsource, screen, taglist)
}

#[inline]
pub unsafe fn intuition_release_bit_map_instance(bitmapinstance: APTR) {
    ((*IIntuition).ReleaseBitMapInstance)(IIntuition, bitmapinstance)
}

#[inline]
pub unsafe fn intuition_emboss_disable_rect(rp: *mut RastPort, minx: i32, miny: i32, maxx: i32, maxy: i32, backtype: u32, contrast: u32, dri: *mut DrawInfo) {
    ((*IIntuition).EmbossDisableRect)(IIntuition, rp, minx, miny, maxx, maxy, backtype, contrast, dri)
}

#[inline]
pub unsafe fn intuition_emboss_disable_text(rp: *mut RastPort, text: CONST_STRPTR, len: u32, backtype: u32, contrast: u32, dri: *mut DrawInfo) {
    ((*IIntuition).EmbossDisableText)(IIntuition, rp, text, len, backtype, contrast, dri)
}

#[inline]
pub unsafe fn intuition_print_embossed_disabled_itext(rp: *mut RastPort, itext: *mut IntuiText, left: i32, top: i32, backtype: u32, contrast: u32, dri: *mut DrawInfo) {
    ((*IIntuition).PrintEmbossedDisabledIText)(IIntuition, rp, itext, left, top, backtype, contrast, dri)
}

#[inline]
pub unsafe fn intuition_intui_text_extent(rp: *mut RastPort, itext: *mut IntuiText, textent: *mut TextExtent) -> u32 {
    ((*IIntuition).IntuiTextExtent)(IIntuition, rp, itext, textent)
}

#[inline]
pub unsafe fn intuition_shade_rect_old(rp: *mut RastPort, minx: i32, miny: i32, maxx: i32, maxy: i32, shadelevel: u32, backtype: u32, state: u32, dri: *mut DrawInfo) -> u32 {
    ((*IIntuition).ShadeRectOld)(IIntuition, rp, minx, miny, maxx, maxy, shadelevel, backtype, state, dri)
}

#[inline]
pub unsafe fn intuition_disable_template_rgb(rp: *mut RastPort, left: i32, top: i32, width: i32, height: i32, template_ptr: APTR, brightlevel: u32, darklevel: u32) {
    ((*IIntuition).DisableTemplateRGB)(IIntuition, rp, left, top, width, height, template_ptr, brightlevel, darklevel)
}

#[inline]
pub unsafe fn intuition_set_screen_bit_map_instance(scr: *mut Screen, id: u32, source: APTR) -> u32 {
    ((*IIntuition).SetScreenBitMapInstance)(IIntuition, scr, id, source)
}

#[inline]
pub unsafe fn intuition_find_menu_key(menu: *mut Menu, code: i32) -> u16 {
    ((*IIntuition).FindMenuKey)(IIntuition, menu, code)
}

#[inline]
pub unsafe fn intuition_bit_map_instance_control_a(bitmapinstance: APTR, taglist: *mut TagItem) -> u32 {
    ((*IIntuition).BitMapInstanceControlA)(IIntuition, bitmapinstance, taglist)
}

#[inline]
pub unsafe fn intuition_obtain_iplugin_list(r#type: u32, attrmask: u32, applymask: u32) -> *mut List {
    ((*IIntuition).ObtainIPluginList)(IIntuition, r#type, attrmask, applymask)
}

#[inline]
pub unsafe fn intuition_release_iplugin_list(list: *mut List) {
    ((*IIntuition).ReleaseIPluginList)(IIntuition, list)
}

#[inline]
pub unsafe fn intuition_open_guiplugin(name: STRPTR, version: u32, r#type: u32, attrmask: u32, applymask: u32) -> *mut GUIPlugin {
    ((*IIntuition).OpenGUIPlugin)(IIntuition, name, version, r#type, attrmask, applymask)
}

#[inline]
pub unsafe fn intuition_close_guiplugin(plugin: *mut GUIPlugin) {
    ((*IIntuition).CloseGUIPlugin)(IIntuition, plugin)
}

#[inline]
pub unsafe fn intuition_draw_sys_image_a(rp: *mut RastPort, left: i32, top: i32, width: i32, height: i32, which: u32, backtype: u32, state: u32, dri: *mut DrawInfo, taglist: *mut TagItem) -> u32 {
    ((*IIntuition).DrawSysImageA)(IIntuition, rp, left, top, width, height, which, backtype, state, dri, taglist)
}

#[inline]
pub unsafe fn intuition_do_render(o: *mut APTR, gi: *mut GadgetInfo, flags: u32) -> u32 {
    ((*IIntuition).DoRender)(IIntuition, o, gi, flags)
}

#[inline]
pub unsafe fn intuition_set_render_domain(rp: *mut RastPort, domain: *mut Rectangle) -> u32 {
    ((*IIntuition).SetRenderDomain)(IIntuition, rp, domain)
}

#[inline]
pub unsafe fn intuition_get_render_domain(rp: *mut RastPort, domain: *mut Rectangle) -> u32 {
    ((*IIntuition).GetRenderDomain)(IIntuition, rp, domain)
}

#[inline]
pub unsafe fn intuition_draw_gradient(rp: *mut RastPort, left: i32, top: i32, width: i32, height: i32, domain: *mut IBox, reserved: u32, gradientspec: *mut GradientSpec, dri: *mut DrawInfo) -> u32 {
    ((*IIntuition).DrawGradient)(IIntuition, rp, left, top, width, height, domain, reserved, gradientspec, dri)
}

#[inline]
pub unsafe fn intuition_direction_vector(degrees: u32) -> u32 {
    ((*IIntuition).DirectionVector)(IIntuition, degrees)
}

#[inline]
pub unsafe fn intuition_shade_rect_a(rp: *mut RastPort, minx: i32, miny: i32, maxx: i32, maxy: i32, shadelevel: u32, backtype: u32, state: u32, dri: *mut DrawInfo, taglist: *mut TagItem) -> u32 {
    ((*IIntuition).ShadeRectA)(IIntuition, rp, minx, miny, maxx, maxy, shadelevel, backtype, state, dri, taglist)
}

#[inline]
pub unsafe fn intuition_do_scroll_hook(scrollhook: *mut ScrollHook, scrollmode: i32) {
    ((*IIntuition).DoScrollHook)(IIntuition, scrollhook, scrollmode)
}

#[inline]
pub unsafe fn intuition_obtain_iback_fill(dri: *mut DrawInfo, element: u32, state: u32, flags: u32) -> *mut Hook {
    ((*IIntuition).ObtainIBackFill)(IIntuition, dri, element, state, flags)
}

#[inline]
pub unsafe fn intuition_release_iback_fill(hook: *mut Hook) {
    ((*IIntuition).ReleaseIBackFill)(IIntuition, hook)
}

#[inline]
pub unsafe fn intuition_intuition_control_a(object: APTR, taglist: *mut TagItem) -> u32 {
    ((*IIntuition).IntuitionControlA)(IIntuition, object, taglist)
}

#[inline]
pub unsafe fn intuition_start_screen_notify_tag_list(taglist: *mut TagItem) -> APTR {
    ((*IIntuition).StartScreenNotifyTagList)(IIntuition, taglist)
}

#[inline]
pub unsafe fn intuition_end_screen_notify(request: APTR) -> u32 {
    ((*IIntuition).EndScreenNotify)(IIntuition, request)
}

#[inline]
pub unsafe fn intuition_disable_template(rp: *mut RastPort, left: i32, top: i32, width: i32, height: i32, template_ptr: APTR, offx: i32, template_type: u32, bytesperrow: u32, backtype: u32, dri: *mut DrawInfo) {
    ((*IIntuition).DisableTemplate)(IIntuition, rp, left, top, width, height, template_ptr, offx, template_type, bytesperrow, backtype, dri)
}

