//! IKeymap global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::keymap::*;

// ---- IKeymap (KeymapIFace) ----

extern "C" {
    pub static IKeymap: *mut KeymapIFace;
}

#[inline]
pub unsafe fn keymap_set_key_map_default(keyMap: *const KeyMap) {
    ((*IKeymap).SetKeyMapDefault)(IKeymap, keyMap)
}

#[inline]
pub unsafe fn keymap_ask_key_map_default() -> *mut KeyMap {
    ((*IKeymap).AskKeyMapDefault)(IKeymap, )
}

#[inline]
pub unsafe fn keymap_map_raw_key(event: *const InputEvent, buffer: STRPTR, length: i16, keyMap: *const KeyMap) -> i16 {
    ((*IKeymap).MapRawKey)(IKeymap, event, buffer, length, keyMap)
}

#[inline]
pub unsafe fn keymap_map_ansi(string: CONST_STRPTR, count: i32, buffer: STRPTR, length: i32, keyMap: *const KeyMap) -> i32 {
    ((*IKeymap).MapANSI)(IKeymap, string, count, buffer, length, keyMap)
}

#[inline]
pub unsafe fn keymap_open_key_map_handle_a(filename: CONST_STRPTR, taglist: *const TagItem) -> APTR {
    ((*IKeymap).OpenKeyMapHandleA)(IKeymap, filename, taglist)
}

#[inline]
pub unsafe fn keymap_close_key_map_handle(handle: APTR) {
    ((*IKeymap).CloseKeyMapHandle)(IKeymap, handle)
}

#[inline]
pub unsafe fn keymap_obtain_key_map_info_a(handle: APTR, taglist: *const TagItem) -> u32 {
    ((*IKeymap).ObtainKeyMapInfoA)(IKeymap, handle, taglist)
}

#[inline]
pub unsafe fn keymap_release_key_map_info_a(handle: APTR, taglist: *const TagItem) {
    ((*IKeymap).ReleaseKeyMapInfoA)(IKeymap, handle, taglist)
}

#[inline]
pub unsafe fn keymap_obtain_raw_key_info_a(taglist: *const TagItem) {
    ((*IKeymap).ObtainRawKeyInfoA)(IKeymap, taglist)
}

#[inline]
pub unsafe fn keymap_key_map_control_tag_list(tags: *const TagItem) -> u32 {
    ((*IKeymap).KeyMapControlTagList)(IKeymap, tags)
}

