//! ILayers global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::layers::*;

// ---- ILayers (LayersIFace) ----

extern "C" {
    pub static ILayers: *mut LayersIFace;
}

#[inline]
pub unsafe fn layers_init_layers(li: *mut Layer_Info) {
    ((*ILayers).InitLayers)(ILayers, li)
}

#[inline]
pub unsafe fn layers_create_upfront_layer(li: *mut Layer_Info, bm: *mut BitMap, x0: i32, y0: i32, x1: i32, y1: i32, flags: i32, bm2: *mut BitMap) -> *mut Layer {
    ((*ILayers).CreateUpfrontLayer)(ILayers, li, bm, x0, y0, x1, y1, flags, bm2)
}

#[inline]
pub unsafe fn layers_create_behind_layer(li: *mut Layer_Info, bm: *mut BitMap, x0: i32, y0: i32, x1: i32, y1: i32, flags: i32, bm2: *mut BitMap) -> *mut Layer {
    ((*ILayers).CreateBehindLayer)(ILayers, li, bm, x0, y0, x1, y1, flags, bm2)
}

#[inline]
pub unsafe fn layers_upfront_layer(dummy: i32, layer: *mut Layer) -> i32 {
    ((*ILayers).UpfrontLayer)(ILayers, dummy, layer)
}

#[inline]
pub unsafe fn layers_behind_layer(dummy: i32, layer: *mut Layer) -> i32 {
    ((*ILayers).BehindLayer)(ILayers, dummy, layer)
}

#[inline]
pub unsafe fn layers_move_layer(dummy: i32, layer: *mut Layer, dx: i32, dy: i32) -> i32 {
    ((*ILayers).MoveLayer)(ILayers, dummy, layer, dx, dy)
}

#[inline]
pub unsafe fn layers_size_layer(dummy: i32, layer: *mut Layer, dx: i32, dy: i32) -> i32 {
    ((*ILayers).SizeLayer)(ILayers, dummy, layer, dx, dy)
}

#[inline]
pub unsafe fn layers_scroll_layer(dummy: i32, layer: *mut Layer, dx: i32, dy: i32) {
    ((*ILayers).ScrollLayer)(ILayers, dummy, layer, dx, dy)
}

#[inline]
pub unsafe fn layers_begin_update(l: *mut Layer) -> i32 {
    ((*ILayers).BeginUpdate)(ILayers, l)
}

#[inline]
pub unsafe fn layers_end_update(layer: *mut Layer, flag: u16) {
    ((*ILayers).EndUpdate)(ILayers, layer, flag)
}

#[inline]
pub unsafe fn layers_delete_layer(dummy: i32, layer: *mut Layer) -> i32 {
    ((*ILayers).DeleteLayer)(ILayers, dummy, layer)
}

#[inline]
pub unsafe fn layers_lock_layer(dummy: i32, layer: *mut Layer) {
    ((*ILayers).LockLayer)(ILayers, dummy, layer)
}

#[inline]
pub unsafe fn layers_unlock_layer(layer: *mut Layer) {
    ((*ILayers).UnlockLayer)(ILayers, layer)
}

#[inline]
pub unsafe fn layers_lock_layers(li: *mut Layer_Info) {
    ((*ILayers).LockLayers)(ILayers, li)
}

#[inline]
pub unsafe fn layers_unlock_layers(li: *mut Layer_Info) -> u32 {
    ((*ILayers).UnlockLayers)(ILayers, li)
}

#[inline]
pub unsafe fn layers_lock_layer_info(li: *mut Layer_Info) {
    ((*ILayers).LockLayerInfo)(ILayers, li)
}

#[inline]
pub unsafe fn layers_swap_bits_rast_port_clip_rect(rp: *mut RastPort, cr: *mut ClipRect) {
    ((*ILayers).SwapBitsRastPortClipRect)(ILayers, rp, cr)
}

#[inline]
pub unsafe fn layers_which_layer(li: *mut Layer_Info, x: i16, y: i16) -> *mut Layer {
    ((*ILayers).WhichLayer)(ILayers, li, x, y)
}

#[inline]
pub unsafe fn layers_unlock_layer_info(li: *mut Layer_Info) {
    ((*ILayers).UnlockLayerInfo)(ILayers, li)
}

#[inline]
pub unsafe fn layers_new_layer_info() -> *mut Layer_Info {
    ((*ILayers).NewLayerInfo)(ILayers, )
}

#[inline]
pub unsafe fn layers_dispose_layer_info(li: *mut Layer_Info) {
    ((*ILayers).DisposeLayerInfo)(ILayers, li)
}

#[inline]
pub unsafe fn layers_fatten_layer_info(li: *mut Layer_Info) -> i32 {
    ((*ILayers).FattenLayerInfo)(ILayers, li)
}

#[inline]
pub unsafe fn layers_thin_layer_info(li: *mut Layer_Info) {
    ((*ILayers).ThinLayerInfo)(ILayers, li)
}

#[inline]
pub unsafe fn layers_move_layer_in_front_of(layer_to_move: *mut Layer, other_layer: *mut Layer) -> i32 {
    ((*ILayers).MoveLayerInFrontOf)(ILayers, layer_to_move, other_layer)
}

#[inline]
pub unsafe fn layers_install_clip_region(layer: *mut Layer, region: *mut APTR) -> *mut Region {
    ((*ILayers).InstallClipRegion)(ILayers, layer, region)
}

#[inline]
pub unsafe fn layers_move_size_layer(layer: *mut Layer, dx: i32, dy: i32, dw: i32, dh: i32) -> i32 {
    ((*ILayers).MoveSizeLayer)(ILayers, layer, dx, dy, dw, dh)
}

#[inline]
pub unsafe fn layers_create_upfront_hook_layer(li: *mut Layer_Info, bm: *mut BitMap, x0: i32, y0: i32, x1: i32, y1: i32, flags: i32, hook: *mut Hook, bm2: *mut BitMap) -> *mut Layer {
    ((*ILayers).CreateUpfrontHookLayer)(ILayers, li, bm, x0, y0, x1, y1, flags, hook, bm2)
}

#[inline]
pub unsafe fn layers_create_behind_hook_layer(li: *mut Layer_Info, bm: *mut BitMap, x0: i32, y0: i32, x1: i32, y1: i32, flags: i32, hook: *mut Hook, bm2: *mut BitMap) -> *mut Layer {
    ((*ILayers).CreateBehindHookLayer)(ILayers, li, bm, x0, y0, x1, y1, flags, hook, bm2)
}

#[inline]
pub unsafe fn layers_install_layer_hook(layer: *mut Layer, hook: *mut Hook) -> *mut Hook {
    ((*ILayers).InstallLayerHook)(ILayers, layer, hook)
}

#[inline]
pub unsafe fn layers_install_layer_info_hook(li: *mut Layer_Info, hook: *mut APTR) -> *mut Hook {
    ((*ILayers).InstallLayerInfoHook)(ILayers, li, hook)
}

#[inline]
pub unsafe fn layers_sort_layer_cr(layer: *mut Layer, dx: i16, dy: i16) {
    ((*ILayers).SortLayerCR)(ILayers, layer, dx, dy)
}

#[inline]
pub unsafe fn layers_do_hook_clip_rects(hook: *mut APTR, rport: *mut RastPort, rect: *mut APTR) {
    ((*ILayers).DoHookClipRects)(ILayers, hook, rport, rect)
}

#[inline]
pub unsafe fn layers_layer_occluded(layer: *mut Layer) -> i32 {
    ((*ILayers).LayerOccluded)(ILayers, layer)
}

#[inline]
pub unsafe fn layers_hide_layer(layer: *mut Layer) -> i32 {
    ((*ILayers).HideLayer)(ILayers, layer)
}

#[inline]
pub unsafe fn layers_show_layer(layer: *mut Layer, infront_of: *mut Layer) -> i32 {
    ((*ILayers).ShowLayer)(ILayers, layer, infront_of)
}

#[inline]
pub unsafe fn layers_set_layer_info_bounds(li: *mut Layer_Info, bounds: *mut Rectangle) -> i32 {
    ((*ILayers).SetLayerInfoBounds)(ILayers, li, bounds)
}

#[inline]
pub unsafe fn layers_alloc_clip_rect(li: *mut Layer_Info) -> *mut ClipRect {
    ((*ILayers).AllocClipRect)(ILayers, li)
}

#[inline]
pub unsafe fn layers_free_clip_rect(li: *mut Layer_Info, cr: *mut ClipRect) {
    ((*ILayers).FreeClipRect)(ILayers, li, cr)
}

#[inline]
pub unsafe fn layers_create_layer_a(li: *mut Layer_Info, tlist: *mut TagItem) -> *mut Layer {
    ((*ILayers).CreateLayerA)(ILayers, li, tlist)
}

#[inline]
pub unsafe fn layers_change_layer_shape(layer: *mut Layer, region: *mut Region, hook: *mut Hook) -> *mut Region {
    ((*ILayers).ChangeLayerShape)(ILayers, layer, region, hook)
}

#[inline]
pub unsafe fn layers_create_back_fill_hook_a(tlist: *mut TagItem) -> *mut Hook {
    ((*ILayers).CreateBackFillHookA)(ILayers, tlist)
}

#[inline]
pub unsafe fn layers_delete_back_fill_hook(hook: *mut Hook) {
    ((*ILayers).DeleteBackFillHook)(ILayers, hook)
}

#[inline]
pub unsafe fn layers_set_back_fill_hook_attrs_a(h: *mut Hook, tags: *mut TagItem) -> u32 {
    ((*ILayers).SetBackFillHookAttrsA)(ILayers, h, tags)
}

#[inline]
pub unsafe fn layers_get_back_fill_hook_attrs_a(h: *mut Hook, tags: *mut TagItem) -> u32 {
    ((*ILayers).GetBackFillHookAttrsA)(ILayers, h, tags)
}

#[inline]
pub unsafe fn layers_compose_layers_a(l: *mut Layer, rect: *mut Rectangle, taglist: *mut TagItem) -> u32 {
    ((*ILayers).ComposeLayersA)(ILayers, l, rect, taglist)
}

#[inline]
pub unsafe fn layers_get_off_screen_layer_bit_map(l: *mut Layer, fallback: *mut BitMap, bounds: *mut Rectangle) -> *mut BitMap {
    ((*ILayers).GetOffScreenLayerBitMap)(ILayers, l, fallback, bounds)
}

#[inline]
pub unsafe fn layers_set_layer_info_attrs_a(li: *mut Layer_Info, taglist: *mut TagItem) -> u32 {
    ((*ILayers).SetLayerInfoAttrsA)(ILayers, li, taglist)
}

#[inline]
pub unsafe fn layers_get_layer_info_attrs_a(li: *mut Layer_Info, taglist: *mut TagItem) -> u32 {
    ((*ILayers).GetLayerInfoAttrsA)(ILayers, li, taglist)
}

#[inline]
pub unsafe fn layers_change_layer_alpha(layer: *mut Layer, clips: *mut ClipRect, hook: *mut Hook) -> *mut ClipRect {
    ((*ILayers).ChangeLayerAlpha)(ILayers, layer, clips, hook)
}

#[inline]
pub unsafe fn layers_set_foreground_alpha(layer: *mut Layer, templateptr: APTR, templatetype: u32, bytesperrow: u32, left: i32, top: i32, width: u32, height: u32, flags: u32) -> u32 {
    ((*ILayers).SetForegroundAlpha)(ILayers, layer, templateptr, templatetype, bytesperrow, left, top, width, height, flags)
}

#[inline]
pub unsafe fn layers_set_layer_opaqueness(layer: *mut Layer, opaqueness: u32) -> u32 {
    ((*ILayers).SetLayerOpaqueness)(ILayers, layer, opaqueness)
}

#[inline]
pub unsafe fn layers_set_layer_overlay_rect(layer: *mut Layer, left: i32, top: i32, width: i32, height: i32, flags: u32) -> u32 {
    ((*ILayers).SetLayerOverlayRect)(ILayers, layer, left, top, width, height, flags)
}

