//! ILocale global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::locale::*;

// ---- ILocale (LocaleIFace) ----

extern "C" {
    pub static ILocale: *mut LocaleIFace;
}

#[inline]
pub unsafe fn locale_close_catalog(catalog: *mut Catalog) {
    ((*ILocale).CloseCatalog)(ILocale, catalog)
}

#[inline]
pub unsafe fn locale_close_locale(locale: *mut Locale) {
    ((*ILocale).CloseLocale)(ILocale, locale)
}

#[inline]
pub unsafe fn locale_conv_to_lower(locale: *mut Locale, character: u32) -> u32 {
    ((*ILocale).ConvToLower)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_conv_to_upper(locale: *mut Locale, character: u32) -> u32 {
    ((*ILocale).ConvToUpper)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_format_date(locale: *mut Locale, fmtTemplate: CONST_STRPTR, date: *mut DateStamp, putCharFunc: *mut Hook) {
    ((*ILocale).FormatDate)(ILocale, locale, fmtTemplate, date, putCharFunc)
}

#[inline]
pub unsafe fn locale_format_string(locale: *mut Locale, fmtTemplate: CONST_STRPTR, dataStream: APTR, putCharFunc: *mut Hook) -> APTR {
    ((*ILocale).FormatString)(ILocale, locale, fmtTemplate, dataStream, putCharFunc)
}

#[inline]
pub unsafe fn locale_get_catalog_str(catalog: *mut Catalog, stringNum: i32, defaultString: CONST_STRPTR) -> CONST_STRPTR {
    ((*ILocale).GetCatalogStr)(ILocale, catalog, stringNum, defaultString)
}

#[inline]
pub unsafe fn locale_get_locale_str(locale: *mut Locale, stringNum: u32) -> CONST_STRPTR {
    ((*ILocale).GetLocaleStr)(ILocale, locale, stringNum)
}

#[inline]
pub unsafe fn locale_is_al_num(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsAlNum)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_is_alpha(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsAlpha)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_is_cntrl(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsCntrl)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_is_digit(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsDigit)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_is_graph(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsGraph)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_is_lower(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsLower)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_is_print(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsPrint)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_is_punct(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsPunct)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_is_space(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsSpace)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_is_upper(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsUpper)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_is_xdigit(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsXDigit)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_open_catalog_a(locale: *mut Locale, name: CONST_STRPTR, tags: *const TagItem) -> *mut Catalog {
    ((*ILocale).OpenCatalogA)(ILocale, locale, name, tags)
}

#[inline]
pub unsafe fn locale_open_locale(name: CONST_STRPTR) -> *mut Locale {
    ((*ILocale).OpenLocale)(ILocale, name)
}

#[inline]
pub unsafe fn locale_parse_date(locale: *mut Locale, date: *mut DateStamp, fmtTemplate: CONST_STRPTR, getCharFunc: *mut Hook) -> i32 {
    ((*ILocale).ParseDate)(ILocale, locale, date, fmtTemplate, getCharFunc)
}

#[inline]
pub unsafe fn locale_str_convert(locale: *mut Locale, string: CONST_STRPTR, buffer: APTR, bufferSize: u32, r#type: u32) -> u32 {
    ((*ILocale).StrConvert)(ILocale, locale, string, buffer, bufferSize, r#type)
}

#[inline]
pub unsafe fn locale_strn_cmp(locale: *mut Locale, string1: CONST_STRPTR, string2: CONST_STRPTR, length: i32, r#type: u32) -> i32 {
    ((*ILocale).StrnCmp)(ILocale, locale, string1, string2, length, r#type)
}

#[inline]
pub unsafe fn locale_locale_date_to_str(datetime: *mut DateTime) -> i32 {
    ((*ILocale).Locale_DateToStr)(ILocale, datetime)
}

#[inline]
pub unsafe fn locale_locale_str_to_date(datetime: *mut DateTime) -> i32 {
    ((*ILocale).Locale_StrToDate)(ILocale, datetime)
}

#[inline]
pub unsafe fn locale_is_blank(locale: *mut Locale, character: u32) -> i32 {
    ((*ILocale).IsBlank)(ILocale, locale, character)
}

#[inline]
pub unsafe fn locale_format_string32(locale: *mut Locale, fmtTemplate: CONST_STRPTR, dataStream: APTR, putCharFunc: *mut Hook) -> APTR {
    ((*ILocale).FormatString32)(ILocale, locale, fmtTemplate, dataStream, putCharFunc)
}

