//! Convenience wrapper modules.
//!
//! Auto-generated by amigaos4-bindgen.

#[cfg(feature = "application")]
pub mod application;
#[cfg(feature = "asl")]
pub mod asl;
#[cfg(feature = "commodities")]
pub mod commodities;
#[cfg(feature = "datatypes")]
pub mod datatypes;
#[cfg(feature = "diskfont")]
pub mod diskfont;
#[cfg(feature = "dos")]
pub mod dos;
#[cfg(feature = "exec")]
pub mod exec;
#[cfg(feature = "gadtools")]
pub mod gadtools;
#[cfg(feature = "graphics")]
pub mod graphics;
#[cfg(feature = "icon")]
pub mod icon;
#[cfg(feature = "iffparse")]
pub mod iffparse;
#[cfg(feature = "intuition")]
pub mod intuition;
#[cfg(feature = "keymap")]
pub mod keymap;
#[cfg(feature = "layers")]
pub mod layers;
#[cfg(feature = "locale")]
pub mod locale;
#[cfg(feature = "rexxsys")]
pub mod rexxsys;
#[cfg(feature = "timer")]
pub mod timer;
#[cfg(feature = "utility")]
pub mod utility;
#[cfg(feature = "workbench")]
pub mod workbench;
