//! IRexxSys global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::rexxsys::*;

// ---- IRexxSys (RexxSysIFace) ----

extern "C" {
    pub static IRexxSys: *mut RexxSysIFace;
}

#[inline]
pub unsafe fn rexxsys_create_argstring(string: CONST_STRPTR, length: u32) -> STRPTR {
    ((*IRexxSys).CreateArgstring)(IRexxSys, string, length)
}

#[inline]
pub unsafe fn rexxsys_delete_argstring(argstring: STRPTR) {
    ((*IRexxSys).DeleteArgstring)(IRexxSys, argstring)
}

#[inline]
pub unsafe fn rexxsys_length_argstring(argstring: CONST_STRPTR) -> i32 {
    ((*IRexxSys).LengthArgstring)(IRexxSys, argstring)
}

#[inline]
pub unsafe fn rexxsys_create_rexx_msg(port: *mut MsgPort, extension: CONST_STRPTR, host: CONST_STRPTR) -> *mut RexxMsg {
    ((*IRexxSys).CreateRexxMsg)(IRexxSys, port, extension, host)
}

#[inline]
pub unsafe fn rexxsys_delete_rexx_msg(rexxmsg: *mut RexxMsg) {
    ((*IRexxSys).DeleteRexxMsg)(IRexxSys, rexxmsg)
}

#[inline]
pub unsafe fn rexxsys_clear_rexx_msg(msgptr: *mut RexxMsg, count: u32) {
    ((*IRexxSys).ClearRexxMsg)(IRexxSys, msgptr, count)
}

#[inline]
pub unsafe fn rexxsys_fill_rexx_msg(rexxmsg: *mut RexxMsg, count: u32, mask: u32) -> u32 {
    ((*IRexxSys).FillRexxMsg)(IRexxSys, rexxmsg, count, mask)
}

#[inline]
pub unsafe fn rexxsys_is_rexx_msg(rexxmsg: *mut APTR) -> u32 {
    ((*IRexxSys).IsRexxMsg)(IRexxSys, rexxmsg)
}

#[inline]
pub unsafe fn rexxsys_lock_rexx_base(resource: u32) {
    ((*IRexxSys).LockRexxBase)(IRexxSys, resource)
}

#[inline]
pub unsafe fn rexxsys_unlock_rexx_base(resource: u32) {
    ((*IRexxSys).UnlockRexxBase)(IRexxSys, resource)
}

#[inline]
pub unsafe fn rexxsys_create_rexx_host_port(base_name: CONST_STRPTR) -> *mut MsgPort {
    ((*IRexxSys).CreateRexxHostPort)(IRexxSys, base_name)
}

#[inline]
pub unsafe fn rexxsys_delete_rexx_host_port(port: *mut MsgPort) {
    ((*IRexxSys).DeleteRexxHostPort)(IRexxSys, port)
}

#[inline]
pub unsafe fn rexxsys_get_rexx_var_from_msg(name: CONST_STRPTR, buffer: STRPTR, rexxmsg: *mut RexxMsg) -> i32 {
    ((*IRexxSys).GetRexxVarFromMsg)(IRexxSys, name, buffer, rexxmsg)
}

#[inline]
pub unsafe fn rexxsys_set_rexx_var_from_msg(name: CONST_STRPTR, value: CONST_STRPTR, rexxmsg: *mut RexxMsg) -> i32 {
    ((*IRexxSys).SetRexxVarFromMsg)(IRexxSys, name, value, rexxmsg)
}

#[inline]
pub unsafe fn rexxsys_launch_rexx_script(script_name: CONST_STRPTR, host_port: *mut MsgPort, extension: CONST_STRPTR, input_handle: u32, output_handle: u32) -> *mut RexxMsg {
    ((*IRexxSys).LaunchRexxScript)(IRexxSys, script_name, host_port, extension, input_handle, output_handle)
}

#[inline]
pub unsafe fn rexxsys_free_rexx_msg(rexxmsg: *mut RexxMsg) {
    ((*IRexxSys).FreeRexxMsg)(IRexxSys, rexxmsg)
}

