//! ITimer global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::timer::*;

// ---- ITimer (TimerIFace) ----

extern "C" {
    pub static ITimer: *mut TimerIFace;
}

#[inline]
pub unsafe fn timer_add_time(dest: *mut TimeVal, src: *const TimeVal) {
    ((*ITimer).AddTime)(ITimer, dest, src)
}

#[inline]
pub unsafe fn timer_sub_time(dest: *mut TimeVal, src: *const TimeVal) {
    ((*ITimer).SubTime)(ITimer, dest, src)
}

#[inline]
pub unsafe fn timer_cmp_time(dest: *mut TimeVal, src: *const TimeVal) -> i32 {
    ((*ITimer).CmpTime)(ITimer, dest, src)
}

#[inline]
pub unsafe fn timer_read_eclock(dest: *mut EClockVal) -> u32 {
    ((*ITimer).ReadEClock)(ITimer, dest)
}

#[inline]
pub unsafe fn timer_get_sys_time(dest: *mut TimeVal) {
    ((*ITimer).GetSysTime)(ITimer, dest)
}

#[inline]
pub unsafe fn timer_get_up_time(dest: *mut TimeVal) {
    ((*ITimer).GetUpTime)(ITimer, dest)
}

#[inline]
pub unsafe fn timer_micro_delay(microseconds: u32) {
    ((*ITimer).MicroDelay)(ITimer, microseconds)
}

