//! IUtility global(s) and convenience wrappers.
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;
use crate::interfaces::utility::*;

// ---- IUtility (UtilityIFace) ----

extern "C" {
    pub static IUtility: *mut UtilityIFace;
}

#[inline]
pub unsafe fn utility_allocate_tag_items(numTags: u32) -> *mut TagItem {
    ((*IUtility).AllocateTagItems)(IUtility, numTags)
}

#[inline]
pub unsafe fn utility_apply_tag_changes(list: *mut TagItem, changeList: *const TagItem) {
    ((*IUtility).ApplyTagChanges)(IUtility, list, changeList)
}

#[inline]
pub unsafe fn utility_clone_tag_items(original: *const TagItem) -> *mut TagItem {
    ((*IUtility).CloneTagItems)(IUtility, original)
}

#[inline]
pub unsafe fn utility_filter_tag_changes(changeList: *mut TagItem, originalList: *mut TagItem, apply: u32) {
    ((*IUtility).FilterTagChanges)(IUtility, changeList, originalList, apply)
}

#[inline]
pub unsafe fn utility_filter_tag_items(taglist: *mut TagItem, filterArray: *const u32, logic: u32) -> u32 {
    ((*IUtility).FilterTagItems)(IUtility, taglist, filterArray, logic)
}

#[inline]
pub unsafe fn utility_find_tag_item(tagValue: u32, tagList: *const TagItem) -> *mut TagItem {
    ((*IUtility).FindTagItem)(IUtility, tagValue, tagList)
}

#[inline]
pub unsafe fn utility_free_tag_items(tagList: *mut TagItem) {
    ((*IUtility).FreeTagItems)(IUtility, tagList)
}

#[inline]
pub unsafe fn utility_get_tag_data(tagValue: u32, defaultVal: u32, tagList: *const TagItem) -> u32 {
    ((*IUtility).GetTagData)(IUtility, tagValue, defaultVal, tagList)
}

#[inline]
pub unsafe fn utility_map_tags(tagList: *mut TagItem, mapList: *const TagItem, mapType: u32) {
    ((*IUtility).MapTags)(IUtility, tagList, mapList, mapType)
}

#[inline]
pub unsafe fn utility_next_tag_item(tags: *mut *mut TagItem) -> *mut TagItem {
    ((*IUtility).NextTagItem)(IUtility, tags)
}

#[inline]
pub unsafe fn utility_pack_bool_tags(initialFlags: u32, tagList: *const TagItem, boolMap: *const TagItem) -> u32 {
    ((*IUtility).PackBoolTags)(IUtility, initialFlags, tagList, boolMap)
}

#[inline]
pub unsafe fn utility_refresh_tag_item_clones(clone: *mut TagItem, original: *const TagItem) {
    ((*IUtility).RefreshTagItemClones)(IUtility, clone, original)
}

#[inline]
pub unsafe fn utility_tag_in_array(tagValue: u32, tagArray: *const u32) -> u32 {
    ((*IUtility).TagInArray)(IUtility, tagValue, tagArray)
}

#[inline]
pub unsafe fn utility_call_hook_pkt(hook: *mut Hook, object: APTR, message: APTR) -> u32 {
    ((*IUtility).CallHookPkt)(IUtility, hook, object, message)
}

#[inline]
pub unsafe fn utility_add_named_object(nameSpace: *mut NamedObject, object: *mut NamedObject) -> u32 {
    ((*IUtility).AddNamedObject)(IUtility, nameSpace, object)
}

#[inline]
pub unsafe fn utility_alloc_named_object_a(name: CONST_STRPTR, tags: *const TagItem) -> *mut NamedObject {
    ((*IUtility).AllocNamedObjectA)(IUtility, name, tags)
}

#[inline]
pub unsafe fn utility_attempt_rem_named_object(object: *mut NamedObject) -> i32 {
    ((*IUtility).AttemptRemNamedObject)(IUtility, object)
}

#[inline]
pub unsafe fn utility_find_named_object(name_space: *mut NamedObject, name: CONST_STRPTR, previous_object: *mut NamedObject) -> *mut NamedObject {
    ((*IUtility).FindNamedObject)(IUtility, name_space, name, previous_object)
}

#[inline]
pub unsafe fn utility_free_named_object(obj: *mut NamedObject) -> *mut NamedObject {
    ((*IUtility).FreeNamedObject)(IUtility, obj)
}

#[inline]
pub unsafe fn utility_named_object_name(obj: *mut NamedObject) -> STRPTR {
    ((*IUtility).NamedObjectName)(IUtility, obj)
}

#[inline]
pub unsafe fn utility_release_named_object(obj: *mut NamedObject) {
    ((*IUtility).ReleaseNamedObject)(IUtility, obj)
}

#[inline]
pub unsafe fn utility_rem_named_object(obj: *mut NamedObject, message: *mut Message) {
    ((*IUtility).RemNamedObject)(IUtility, obj, message)
}

#[inline]
pub unsafe fn utility_amiga2_date(date_amiga: u32, cd: *mut ClockData) {
    ((*IUtility).Amiga2Date)(IUtility, date_amiga, cd)
}

#[inline]
pub unsafe fn utility_check_date(date: *const ClockData) -> u32 {
    ((*IUtility).CheckDate)(IUtility, date)
}

#[inline]
pub unsafe fn utility_date2_amiga(date: *const ClockData) -> u32 {
    ((*IUtility).Date2Amiga)(IUtility, date)
}

#[inline]
pub unsafe fn utility_create_skip_list(hook: *mut Hook, max_levels: i32) -> *mut SkipList {
    ((*IUtility).CreateSkipList)(IUtility, hook, max_levels)
}

#[inline]
pub unsafe fn utility_delete_skip_list(skipList: *mut SkipList) {
    ((*IUtility).DeleteSkipList)(IUtility, skipList)
}

#[inline]
pub unsafe fn utility_find_skip_node(skipList: *const SkipList, key: APTR) -> *mut SkipNode {
    ((*IUtility).FindSkipNode)(IUtility, skipList, key)
}

#[inline]
pub unsafe fn utility_get_first_skip_node(skipList: *const SkipList) -> *mut SkipNode {
    ((*IUtility).GetFirstSkipNode)(IUtility, skipList)
}

#[inline]
pub unsafe fn utility_get_next_skip_node(skipList: *const SkipList, node: *const SkipNode) -> *mut SkipNode {
    ((*IUtility).GetNextSkipNode)(IUtility, skipList, node)
}

#[inline]
pub unsafe fn utility_insert_skip_node(skipList: *mut SkipList, key: APTR, dataSize: u32) -> *mut SkipNode {
    ((*IUtility).InsertSkipNode)(IUtility, skipList, key, dataSize)
}

#[inline]
pub unsafe fn utility_remove_skip_node(skipList: *mut SkipList, key: APTR) -> u32 {
    ((*IUtility).RemoveSkipNode)(IUtility, skipList, key)
}

#[inline]
pub unsafe fn utility_create_splay_tree(compareHook: *mut Hook) -> *mut SplayTree {
    ((*IUtility).CreateSplayTree)(IUtility, compareHook)
}

#[inline]
pub unsafe fn utility_delete_splay_tree(splayTree: *mut SplayTree) {
    ((*IUtility).DeleteSplayTree)(IUtility, splayTree)
}

#[inline]
pub unsafe fn utility_find_splay_node(splayTree: *const SplayTree, key: APTR) -> *mut SplayNode {
    ((*IUtility).FindSplayNode)(IUtility, splayTree, key)
}

#[inline]
pub unsafe fn utility_insert_splay_node(splayTree: *mut SplayTree, key: APTR, date_size: u32) -> *mut SplayNode {
    ((*IUtility).InsertSplayNode)(IUtility, splayTree, key, date_size)
}

#[inline]
pub unsafe fn utility_remove_splay_node(splayTree: *mut SplayTree, key: APTR) -> *mut SplayNode {
    ((*IUtility).RemoveSplayNode)(IUtility, splayTree, key)
}

#[inline]
pub unsafe fn utility_find_name_nc(list: *mut List, name: CONST_STRPTR) -> *mut Node {
    ((*IUtility).FindNameNC)(IUtility, list, name)
}

#[inline]
pub unsafe fn utility_get_unique_id() -> u32 {
    ((*IUtility).GetUniqueID)(IUtility, )
}

#[inline]
pub unsafe fn utility_message_digest_sha_final(shas: *mut MessageDigest_SHA) {
    ((*IUtility).MessageDigest_SHA_Final)(IUtility, shas)
}

#[inline]
pub unsafe fn utility_message_digest_sha_init(shas: *mut MessageDigest_SHA) {
    ((*IUtility).MessageDigest_SHA_Init)(IUtility, shas)
}

#[inline]
pub unsafe fn utility_message_digest_sha_update(shas: *mut MessageDigest_SHA, data: APTR, num_bytes: i32) {
    ((*IUtility).MessageDigest_SHA_Update)(IUtility, shas, data, num_bytes)
}

#[inline]
pub unsafe fn utility_pack_structure_tags(pack: APTR, pack_table: *const u32, tagList: *const TagItem) -> u32 {
    ((*IUtility).PackStructureTags)(IUtility, pack, pack_table, tagList)
}

#[inline]
pub unsafe fn utility_unpack_structure_tags(pack: CONST_APTR, pack_table: *const u32, tagList: *mut TagItem) -> u32 {
    ((*IUtility).UnpackStructureTags)(IUtility, pack, pack_table, tagList)
}

#[inline]
pub unsafe fn utility_random(state: *mut RandomState) -> u32 {
    ((*IUtility).Random)(IUtility, state)
}

#[inline]
pub unsafe fn utility_set_mem(destination: APTR, fillChar: u8, length: i32) -> APTR {
    ((*IUtility).SetMem)(IUtility, destination, fillChar, length)
}

#[inline]
pub unsafe fn utility_stricmp(s1: CONST_STRPTR, s2: CONST_STRPTR) -> i32 {
    ((*IUtility).Stricmp)(IUtility, s1, s2)
}

#[inline]
pub unsafe fn utility_strlcpy(dst: STRPTR, src: CONST_STRPTR, size: i32) -> i32 {
    ((*IUtility).Strlcpy)(IUtility, dst, src, size)
}

#[inline]
pub unsafe fn utility_strlcat(dst: STRPTR, src: CONST_STRPTR, size: i32) -> i32 {
    ((*IUtility).Strlcat)(IUtility, dst, src, size)
}

#[inline]
pub unsafe fn utility_strnicmp(s1: CONST_STRPTR, s2: CONST_STRPTR, n: i32) -> i32 {
    ((*IUtility).Strnicmp)(IUtility, s1, s2, n)
}

#[inline]
pub unsafe fn utility_to_lower(c: APTR) -> u32 {
    ((*IUtility).ToLower)(IUtility, c)
}

#[inline]
pub unsafe fn utility_to_upper(c: APTR) -> u32 {
    ((*IUtility).ToUpper)(IUtility, c)
}

#[inline]
pub unsafe fn utility_vasprintf(fmt: CONST_STRPTR, args: APTR) -> STRPTR {
    ((*IUtility).VASPrintf)(IUtility, fmt, args)
}

#[inline]
pub unsafe fn utility_vsnprintf(buffer: STRPTR, bufferSize: i32, fmt: CONST_STRPTR, args: APTR) -> i32 {
    ((*IUtility).VSNPrintf)(IUtility, buffer, bufferSize, fmt, args)
}

#[inline]
pub unsafe fn utility_clear_mem(destination: APTR, size: u32) {
    ((*IUtility).ClearMem)(IUtility, destination, size)
}

#[inline]
pub unsafe fn utility_move_mem(source: CONST_APTR, destination: APTR, size: u32) {
    ((*IUtility).MoveMem)(IUtility, source, destination, size)
}

#[inline]
pub unsafe fn utility_strlen(string: CONST_STRPTR) -> u32 {
    ((*IUtility).Strlen)(IUtility, string)
}

#[inline]
pub unsafe fn utility_utf8to_ucs4(utf8_source: CONST_STRPTR, ucs4_destination: *mut i32, ucs4_destination_size: i32, flags: u32) -> i32 {
    ((*IUtility).UTF8toUCS4)(IUtility, utf8_source, ucs4_destination, ucs4_destination_size, flags)
}

#[inline]
pub unsafe fn utility_ucs4to_utf8(ucs4_source: *const i32, utf8_destination: STRPTR, utf8_destination_size: i32, flags: u32) -> i32 {
    ((*IUtility).UCS4toUTF8)(IUtility, ucs4_source, utf8_destination, utf8_destination_size, flags)
}

#[inline]
pub unsafe fn utility_utf8_strnicmp(utf8string1: CONST_STRPTR, utf8string2: CONST_STRPTR, maxUCSchars: i32) -> i32 {
    ((*IUtility).UTF8Strnicmp)(IUtility, utf8string1, utf8string2, maxUCSchars)
}

#[inline]
pub unsafe fn utility_utf8_stricmp(utf8string1: CONST_STRPTR, utf8string2: CONST_STRPTR) -> i32 {
    ((*IUtility).UTF8Stricmp)(IUtility, utf8string1, utf8string2)
}

#[inline]
pub unsafe fn utility_utf8_count(utf8string: CONST_STRPTR, validate: i32) -> i32 {
    ((*IUtility).UTF8Count)(IUtility, utf8string, validate)
}

#[inline]
pub unsafe fn utility_ucs4_count(ucs4string: *const i32, validate: i32) -> i32 {
    ((*IUtility).UCS4Count)(IUtility, ucs4string, validate)
}

#[inline]
pub unsafe fn utility_utf8_encode(ucs4: i32, buffer: STRPTR, bufsize: i32, flags: u32) -> i32 {
    ((*IUtility).UTF8Encode)(IUtility, ucs4, buffer, bufsize, flags)
}

#[inline]
pub unsafe fn utility_utf8_decode(utf8_pptr: *mut CONST_STRPTR, flags: u32) -> i32 {
    ((*IUtility).UTF8Decode)(IUtility, utf8_pptr, flags)
}

#[inline]
pub unsafe fn utility_ucs4_to_lower(ucs4in: i32) -> i32 {
    ((*IUtility).UCS4ToLower)(IUtility, ucs4in)
}

#[inline]
pub unsafe fn utility_ucs4_to_upper(ucs4in: i32) -> i32 {
    ((*IUtility).UCS4ToUpper)(IUtility, ucs4in)
}

#[inline]
pub unsafe fn utility_ucs4_valid(ucs4: i32) -> i32 {
    ((*IUtility).UCS4Valid)(IUtility, ucs4)
}

#[inline]
pub unsafe fn utility_sort_list(list: *mut List, cmpHook: *mut Hook) {
    ((*IUtility).SortList)(IUtility, list, cmpHook)
}

#[inline]
pub unsafe fn utility_sort_min_list(list: *mut MinList, cmpHook: *mut Hook) {
    ((*IUtility).SortMinList)(IUtility, list, cmpHook)
}

