//! ACPIIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ACPIIFace (acpi.h) ----

#[repr(C)]
pub struct ACPIIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ACPIIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ACPIIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub GetAttr: unsafe extern "C" fn(*mut ACPIIFace, u32, APTR), // 4: 76
    pub SetAttr: unsafe extern "C" fn(*mut ACPIIFace, u32, CONST_APTR), // 5: 80
    pub Shutdown: unsafe extern "C" fn(*mut ACPIIFace), // 6: 84
}

