//! AHIIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- AHIIFace (ahi.h) ----

#[repr(C)]
pub struct AHIIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut AHIIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut AHIIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut AHIIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut AHIIFace) -> *mut Interface, // 3: 72
    pub AHI_AllocAudioA: unsafe extern "C" fn(*mut AHIIFace, *mut TagItem) -> *mut AHIAudioCtrl, // 4: 76
    pub AHI_AllocAudio: APTR, // 5: 80 (varargs)
    pub AHI_FreeAudio: unsafe extern "C" fn(*mut AHIIFace, *mut AHIAudioCtrl), // 6: 84
    pub AHI_KillAudio: unsafe extern "C" fn(*mut AHIIFace), // 7: 88
    pub AHI_ControlAudioA: unsafe extern "C" fn(*mut AHIIFace, *mut AHIAudioCtrl, *mut TagItem) -> u32, // 8: 92
    pub AHI_ControlAudio: APTR, // 9: 96 (varargs)
    pub AHI_SetVol: unsafe extern "C" fn(*mut AHIIFace, u16, APTR, APTR, *mut AHIAudioCtrl, u32), // 10: 100
    pub AHI_SetFreq: unsafe extern "C" fn(*mut AHIIFace, u16, u32, *mut AHIAudioCtrl, u32), // 11: 104
    pub AHI_SetSound: unsafe extern "C" fn(*mut AHIIFace, u16, u16, u32, i32, *mut AHIAudioCtrl, u32), // 12: 108
    pub AHI_SetEffect: unsafe extern "C" fn(*mut AHIIFace, APTR, *mut AHIAudioCtrl) -> u32, // 13: 112
    pub AHI_LoadSound: unsafe extern "C" fn(*mut AHIIFace, u16, u32, APTR, *mut AHIAudioCtrl) -> u32, // 14: 116
    pub AHI_UnloadSound: unsafe extern "C" fn(*mut AHIIFace, u16, *mut AHIAudioCtrl), // 15: 120
    pub AHI_NextAudioID: unsafe extern "C" fn(*mut AHIIFace, u32) -> u32, // 16: 124
    pub AHI_GetAudioAttrsA: unsafe extern "C" fn(*mut AHIIFace, u32, *mut AHIAudioCtrl, *mut TagItem) -> u32, // 17: 128
    pub AHI_GetAudioAttrs: APTR, // 18: 132 (varargs)
    pub AHI_BestAudioIDA: unsafe extern "C" fn(*mut AHIIFace, *mut TagItem) -> u32, // 19: 136
    pub AHI_BestAudioID: APTR, // 20: 140 (varargs)
    pub AHI_AllocAudioRequestA: unsafe extern "C" fn(*mut AHIIFace, *mut TagItem) -> *mut AHIAudioModeRequester, // 21: 144
    pub AHI_AllocAudioRequest: APTR, // 22: 148 (varargs)
    pub AHI_AudioRequestA: unsafe extern "C" fn(*mut AHIIFace, *mut AHIAudioModeRequester, *mut TagItem) -> u32, // 23: 152
    pub AHI_AudioRequest: APTR, // 24: 156 (varargs)
    pub AHI_FreeAudioRequest: unsafe extern "C" fn(*mut AHIIFace, *mut AHIAudioModeRequester), // 25: 160
    pub AHI_PlayA: unsafe extern "C" fn(*mut AHIIFace, *mut AHIAudioCtrl, *mut TagItem), // 26: 164
    pub AHI_Play: APTR, // 27: 168 (varargs)
    pub AHI_SampleFrameSize: unsafe extern "C" fn(*mut AHIIFace, u32) -> u32, // 28: 172
    pub AHI_AddAudioMode: unsafe extern "C" fn(*mut AHIIFace, *mut TagItem) -> u32, // 29: 176
    pub AHI_RemoveAudioMode: unsafe extern "C" fn(*mut AHIIFace, u32) -> u32, // 30: 180
    pub AHI_LoadModeFile: unsafe extern "C" fn(*mut AHIIFace, STRPTR) -> u32, // 31: 184
}

