//! AHIsubIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- AHIsubIFace (ahi_sub.h) ----

#[repr(C)]
pub struct AHIsubIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut AHIsubIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut AHIsubIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut AHIsubIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut AHIsubIFace) -> *mut Interface, // 3: 72
    pub AHIsub_AllocAudio: unsafe extern "C" fn(*mut AHIsubIFace, *mut TagItem, *mut AHIAudioCtrlDrv) -> u32, // 4: 76
    pub AHIsub_FreeAudio: unsafe extern "C" fn(*mut AHIsubIFace, *mut AHIAudioCtrlDrv), // 5: 80
    pub AHIsub_Disable: unsafe extern "C" fn(*mut AHIsubIFace, *mut AHIAudioCtrlDrv), // 6: 84
    pub AHIsub_Enable: unsafe extern "C" fn(*mut AHIsubIFace, *mut AHIAudioCtrlDrv), // 7: 88
    pub AHIsub_Start: unsafe extern "C" fn(*mut AHIsubIFace, u32, *mut AHIAudioCtrlDrv) -> u32, // 8: 92
    pub AHIsub_Update: unsafe extern "C" fn(*mut AHIsubIFace, u32, *mut AHIAudioCtrlDrv) -> u32, // 9: 96
    pub AHIsub_Stop: unsafe extern "C" fn(*mut AHIsubIFace, u32, *mut AHIAudioCtrlDrv) -> u32, // 10: 100
    pub AHIsub_SetVol: unsafe extern "C" fn(*mut AHIsubIFace, u16, APTR, APTR, *mut AHIAudioCtrlDrv, u32) -> u32, // 11: 104
    pub AHIsub_SetFreq: unsafe extern "C" fn(*mut AHIsubIFace, u16, u32, *mut AHIAudioCtrlDrv, u32) -> u32, // 12: 108
    pub AHIsub_SetSound: unsafe extern "C" fn(*mut AHIsubIFace, u16, u16, u32, i32, *mut AHIAudioCtrlDrv, u32) -> u32, // 13: 112
    pub AHIsub_SetEffect: unsafe extern "C" fn(*mut AHIsubIFace, APTR, *mut AHIAudioCtrlDrv) -> u32, // 14: 116
    pub AHIsub_LoadSound: unsafe extern "C" fn(*mut AHIsubIFace, u16, u32, APTR, *mut AHIAudioCtrlDrv) -> u32, // 15: 120
    pub AHIsub_UnloadSound: unsafe extern "C" fn(*mut AHIsubIFace, u16, *mut AHIAudioCtrlDrv) -> u32, // 16: 124
    pub AHIsub_GetAttr: unsafe extern "C" fn(*mut AHIsubIFace, u32, i32, i32, *mut TagItem, *mut AHIAudioCtrlDrv) -> i32, // 17: 128
    pub AHIsub_HardwareControl: unsafe extern "C" fn(*mut AHIsubIFace, u32, i32, *mut AHIAudioCtrlDrv) -> i32, // 18: 132
}

