//! AmigaGuideIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- AmigaGuideIFace (amigaguide.h) ----

#[repr(C)]
pub struct AmigaGuideIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut AmigaGuideIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut AmigaGuideIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut AmigaGuideIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut AmigaGuideIFace) -> *mut Interface, // 3: 72
    pub Private1: APTR, // 4: 76
    pub LockAmigaGuideBase: unsafe extern "C" fn(*mut AmigaGuideIFace, APTR) -> i32, // 5: 80
    pub UnlockAmigaGuideBase: unsafe extern "C" fn(*mut AmigaGuideIFace, i32), // 6: 84
    pub Private2: APTR, // 7: 88
    pub OpenAmigaGuideA: unsafe extern "C" fn(*mut AmigaGuideIFace, *mut NewAmigaGuide, *mut TagItem) -> APTR, // 8: 92
    pub OpenAmigaGuide: APTR, // 9: 96 (varargs)
    pub OpenAmigaGuideAsyncA: unsafe extern "C" fn(*mut AmigaGuideIFace, *mut NewAmigaGuide, *mut TagItem) -> APTR, // 10: 100
    pub OpenAmigaGuideAsync: APTR, // 11: 104 (varargs)
    pub CloseAmigaGuide: unsafe extern "C" fn(*mut AmigaGuideIFace, APTR), // 12: 108
    pub AmigaGuideSignal: unsafe extern "C" fn(*mut AmigaGuideIFace, APTR) -> u32, // 13: 112
    pub GetAmigaGuideMsg: unsafe extern "C" fn(*mut AmigaGuideIFace, APTR) -> *mut AmigaGuideMsg, // 14: 116
    pub ReplyAmigaGuideMsg: unsafe extern "C" fn(*mut AmigaGuideIFace, *mut AmigaGuideMsg), // 15: 120
    pub SetAmigaGuideContextA: unsafe extern "C" fn(*mut AmigaGuideIFace, APTR, u32, *mut TagItem) -> i32, // 16: 124
    pub SetAmigaGuideContext: APTR, // 17: 128 (varargs)
    pub SendAmigaGuideContextA: unsafe extern "C" fn(*mut AmigaGuideIFace, APTR, *mut TagItem) -> i32, // 18: 132
    pub SendAmigaGuideContext: APTR, // 19: 136 (varargs)
    pub SendAmigaGuideCmdA: unsafe extern "C" fn(*mut AmigaGuideIFace, APTR, STRPTR, *mut TagItem) -> i32, // 20: 140
    pub SendAmigaGuideCmd: APTR, // 21: 144 (varargs)
    pub SetAmigaGuideAttrsA: unsafe extern "C" fn(*mut AmigaGuideIFace, APTR, *mut TagItem) -> i32, // 22: 148
    pub SetAmigaGuideAttrs: APTR, // 23: 152 (varargs)
    pub GetAmigaGuideAttr: unsafe extern "C" fn(*mut AmigaGuideIFace, u32, APTR, *mut u32) -> i32, // 24: 156
    pub Private3: APTR, // 25: 160
    pub LoadXRef: unsafe extern "C" fn(*mut AmigaGuideIFace, u32, STRPTR) -> i32, // 26: 164
    pub ExpungeXRef: unsafe extern "C" fn(*mut AmigaGuideIFace), // 27: 168
    pub AddAmigaGuideHostA: unsafe extern "C" fn(*mut AmigaGuideIFace, *mut Hook, STRPTR, *mut TagItem) -> APTR, // 28: 172
    pub AddAmigaGuideHost: APTR, // 29: 176 (varargs)
    pub RemoveAmigaGuideHostA: unsafe extern "C" fn(*mut AmigaGuideIFace, APTR, *mut TagItem) -> i32, // 30: 180
    pub RemoveAmigaGuideHost: APTR, // 31: 184 (varargs)
    pub Private4: APTR, // 32: 188
    pub Private5: APTR, // 33: 192
    pub Private6: APTR, // 34: 196
    pub Private7: APTR, // 35: 200
    pub Private8: APTR, // 36: 204
    pub Private9: APTR, // 37: 208
    pub Private10: APTR, // 38: 212
    pub Private11: APTR, // 39: 216
    pub Private12: APTR, // 40: 220
    pub Private13: APTR, // 41: 224
    pub GetAmigaGuideString: unsafe extern "C" fn(*mut AmigaGuideIFace, i32) -> CONST_STRPTR, // 42: 228
}

