//! AIN_IFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- AIN_IFace (amigainput.h) ----

#[repr(C)]
pub struct AIN_IFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut AIN_IFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut AIN_IFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub AIN_GetError: unsafe extern "C" fn(*mut AIN_IFace, APTR) -> u32, // 4: 76
    pub AIN_GetErrorString: unsafe extern "C" fn(*mut AIN_IFace, u32) -> STRPTR, // 5: 80
    pub AIN_CreateContext: unsafe extern "C" fn(*mut AIN_IFace, u32, *mut TagItem) -> APTR, // 6: 84
    pub AIN_DeleteContext: unsafe extern "C" fn(*mut AIN_IFace, APTR), // 7: 88
    pub AIN_EnumDevices: unsafe extern "C" fn(*mut AIN_IFace, APTR, APTR, APTR) -> u32, // 8: 92
    pub AIN_Query: unsafe extern "C" fn(*mut AIN_IFace, APTR, APTR, u32, u32, APTR, u32) -> u32, // 9: 96
    pub AIN_ObtainDevice: unsafe extern "C" fn(*mut AIN_IFace, APTR, APTR) -> *mut APTR, // 10: 100
    pub AIN_ReleaseDevice: unsafe extern "C" fn(*mut AIN_IFace, APTR, *mut APTR), // 11: 104
    pub AIN_SetDeviceParameter: unsafe extern "C" fn(*mut AIN_IFace, APTR, *mut APTR, u32, u32) -> u32, // 12: 108
    pub AIN_GetEvent: unsafe extern "C" fn(*mut AIN_IFace, APTR) -> *mut APTR, // 13: 112
    pub AIN_FreeEvent: unsafe extern "C" fn(*mut AIN_IFace, APTR, *mut APTR), // 14: 116
    pub AIN_ReadDevice: unsafe extern "C" fn(*mut AIN_IFace, APTR, *mut APTR, *mut APTR) -> u32, // 15: 120
    pub AIN_Set: unsafe extern "C" fn(*mut AIN_IFace, APTR, *mut TagItem) -> u32, // 16: 124
    pub AIN_RequestDevice: unsafe extern "C" fn(*mut AIN_IFace, APTR, *mut TagItem) -> *mut _AIN_RequesterResult, // 17: 128
    pub AIN_FreeRequest: unsafe extern "C" fn(*mut AIN_IFace, APTR, *mut _AIN_RequesterResult), // 18: 132
}

