//! ApplicationIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ApplicationIFace (application.h) ----

#[repr(C)]
pub struct ApplicationIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ApplicationIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ApplicationIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut ApplicationIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut ApplicationIFace) -> *mut Interface, // 3: 72
    pub SetAppLibAttrsA: unsafe extern "C" fn(*mut ApplicationIFace, *mut TagItem) -> u32, // 4: 76
    pub SetAppLibAttrs: APTR, // 5: 80 (varargs)
    pub GetAppLibAttrsA: unsafe extern "C" fn(*mut ApplicationIFace, *mut TagItem) -> u32, // 6: 84
    pub GetAppLibAttrs: APTR, // 7: 88 (varargs)
    pub RegisterApplicationA: unsafe extern "C" fn(*mut ApplicationIFace, CONST_STRPTR, *mut TagItem) -> u32, // 8: 92
    pub RegisterApplication: APTR, // 9: 96 (varargs)
    pub UnregisterApplicationA: unsafe extern "C" fn(*mut ApplicationIFace, u32, *mut TagItem) -> u32, // 10: 100
    pub UnregisterApplication: APTR, // 11: 104 (varargs)
    pub SetApplicationAttrsA: unsafe extern "C" fn(*mut ApplicationIFace, u32, *mut TagItem) -> u32, // 12: 108
    pub SetApplicationAttrs: APTR, // 13: 112 (varargs)
    pub GetApplicationAttrsA: unsafe extern "C" fn(*mut ApplicationIFace, u32, *mut TagItem) -> u32, // 14: 116
    pub GetApplicationAttrs: APTR, // 15: 120 (varargs)
    pub FindApplicationA: unsafe extern "C" fn(*mut ApplicationIFace, *mut TagItem) -> u32, // 16: 124
    pub FindApplication: APTR, // 17: 128 (varargs)
    pub LockApplicationIcon: unsafe extern "C" fn(*mut ApplicationIFace, u32) -> u32, // 18: 132
    pub UnlockApplicationIcon: unsafe extern "C" fn(*mut ApplicationIFace, u32), // 19: 136
    pub GetApplicationList: unsafe extern "C" fn(*mut ApplicationIFace) -> *mut MinList, // 20: 140
    pub FreeApplicationList: unsafe extern "C" fn(*mut ApplicationIFace, *mut MinList), // 21: 144
    pub SendApplicationMsg: unsafe extern "C" fn(*mut ApplicationIFace, u32, u32, *mut ApplicationMsg, u32) -> u32, // 22: 148
    pub NotifyA: unsafe extern "C" fn(*mut ApplicationIFace, u32, *mut TagItem) -> u32, // 23: 152
    pub Notify: APTR, // 24: 156 (varargs)
}

