//! ARexxIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ARexxIFace (arexx.h) ----

#[repr(C)]
pub struct ARexxIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ARexxIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ARexxIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut ARexxIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut ARexxIFace) -> *mut Interface, // 3: 72
    pub AREXX_GetClass: unsafe extern "C" fn(*mut ARexxIFace) -> *mut APTR, // 4: 76
}

