//! AslIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- AslIFace (asl.h) ----

#[repr(C)]
pub struct AslIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut AslIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut AslIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut AslIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut AslIFace) -> *mut Interface, // 3: 72
    pub OBSOLETE_AllocFileRequest: unsafe extern "C" fn(*mut AslIFace) -> *mut FileRequester, // 4: 76
    pub OBSOLETE_FreeFileRequest: unsafe extern "C" fn(*mut AslIFace, *mut FileRequester), // 5: 80
    pub OBSOLETE_RequestFile: unsafe extern "C" fn(*mut AslIFace, *mut FileRequester) -> u32, // 6: 84
    pub AllocAslRequest: unsafe extern "C" fn(*mut AslIFace, u32, *const TagItem) -> APTR, // 7: 88
    pub AllocAslRequestTags: APTR, // 8: 92 (varargs)
    pub FreeAslRequest: unsafe extern "C" fn(*mut AslIFace, APTR), // 9: 96
    pub AslRequest: unsafe extern "C" fn(*mut AslIFace, APTR, *const TagItem) -> u32, // 10: 100
    pub AslRequestTags: APTR, // 11: 104 (varargs)
    pub AslFreeVec: unsafe extern "C" fn(*mut AslIFace, APTR), // 12: 108
    pub AslAllocVec: unsafe extern "C" fn(*mut AslIFace, u32, u32) -> APTR, // 13: 112
    pub AbortAslRequest: unsafe extern "C" fn(*mut AslIFace, APTR), // 14: 116
    pub ActivateAslRequest: unsafe extern "C" fn(*mut AslIFace, APTR), // 15: 120
    pub AslControl: unsafe extern "C" fn(*mut AslIFace, *const TagItem) -> u32, // 16: 124
    pub AslControlTags: APTR, // 17: 128 (varargs)
}

