//! BattMemIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- BattMemIFace (battmem.h) ----

#[repr(C)]
pub struct BattMemIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut BattMemIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut BattMemIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut BattMemIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut BattMemIFace) -> *mut Interface, // 3: 72
    pub ObtainBattSemaphore: unsafe extern "C" fn(*mut BattMemIFace), // 4: 76
    pub ReleaseBattSemaphore: unsafe extern "C" fn(*mut BattMemIFace), // 5: 80
    pub ReadBattMem: unsafe extern "C" fn(*mut BattMemIFace, APTR, u32, u32) -> u32, // 6: 84
    pub WriteBattMem: unsafe extern "C" fn(*mut BattMemIFace, CONST_APTR, u32, u32) -> u32, // 7: 88
}

