//! BitMapIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- BitMapIFace (bitmap.h) ----

#[repr(C)]
pub struct BitMapIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut BitMapIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut BitMapIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut BitMapIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut BitMapIFace) -> *mut Interface, // 3: 72
    pub BITMAP_GetClass: unsafe extern "C" fn(*mut BitMapIFace) -> *mut APTR, // 4: 76
}

