//! BlankerModuleIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- BlankerModuleIFace (blankermodule.h) ----

#[repr(C)]
pub struct BlankerModuleIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut BlankerModuleIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut BlankerModuleIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut BlankerModuleIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut BlankerModuleIFace) -> *mut BlankerModuleIFace, // 3: 72
    pub BlankerModuleGet: unsafe extern "C" fn(*mut BlankerModuleIFace, u32, *mut u32) -> u32, // 4: 76
    pub BlankerModuleSet: unsafe extern "C" fn(*mut BlankerModuleIFace, u32, u32) -> u32, // 5: 80
    pub BlankerModuleBlankTask: unsafe extern "C" fn(*mut BlankerModuleIFace), // 6: 84
}

