//! BootSDIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- BootSDIFace (bootsd.h) ----

#[repr(C)]
pub struct BootSDIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut BootSDIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut BootSDIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut BootSDIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut BootSDIFace) -> *mut Interface, // 3: 72
    pub AllocResource: unsafe extern "C" fn(*mut BootSDIFace, *mut i32) -> APTR, // 4: 76
    pub FreeResource: unsafe extern "C" fn(*mut BootSDIFace, APTR) -> u32, // 5: 80
    pub GetGeometry: unsafe extern "C" fn(*mut BootSDIFace, APTR, *mut i32, *mut DosEnvec) -> APTR, // 6: 84
    pub ReadSDCard: unsafe extern "C" fn(*mut BootSDIFace, APTR, *mut i32, APTR, u32, u32) -> u32, // 7: 88
    pub WriteSDCard: unsafe extern "C" fn(*mut BootSDIFace, APTR, *mut i32, APTR, u32, u32) -> u32, // 8: 92
}

