//! BTreeIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- BTreeIFace (btree.h) ----

#[repr(C)]
pub struct BTreeIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut BTreeIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut BTreeIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut BTreeIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut BTreeIFace) -> *mut Interface, // 3: 72
    pub CreateTree: unsafe extern "C" fn(*mut BTreeIFace, u32, *const BTArgArray) -> APTR, // 4: 76
    pub DeleteTree: unsafe extern "C" fn(*mut BTreeIFace, APTR), // 5: 80
    pub InsertTreeNode: unsafe extern "C" fn(*mut BTreeIFace, APTR, CONST_APTR, CONST_APTR) -> APTR, // 6: 84
    pub DeleteTreeNode: unsafe extern "C" fn(*mut BTreeIFace, APTR, APTR), // 7: 88
    pub GetTreeNodeKey: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR, CONST_APTR) -> APTR, // 8: 92
    pub GetTreeNodeData: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR, CONST_APTR) -> APTR, // 9: 96
    pub SuccTreeNode: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR, CONST_APTR) -> APTR, // 10: 100
    pub PredTreeNode: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR, CONST_APTR) -> APTR, // 11: 104
    pub MinTreeNode: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR) -> APTR, // 12: 108
    pub MaxTreeNode: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR) -> APTR, // 13: 112
    pub FindTreeNodeByKey: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR, CONST_APTR) -> APTR, // 14: 116
    pub FindTreeNodeByData: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR, CONST_APTR) -> APTR, // 15: 120
    pub ForTreeNodes: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR, APTR, CONST_APTR) -> u32, // 16: 124
    pub EnumTreeNodes: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR, CONST_APTR, CONST_APTR, APTR, CONST_APTR) -> u32, // 17: 128
    pub GetTreeSize: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR) -> u32, // 18: 132
    pub GetTreeHeight: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR) -> u32, // 19: 136
    pub FlushTree: unsafe extern "C" fn(*mut BTreeIFace, APTR), // 20: 140
    pub SetTreeNodeData: unsafe extern "C" fn(*mut BTreeIFace, CONST_APTR, APTR, CONST_APTR) -> APTR, // 21: 144
}

