//! BulletIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- BulletIFace (bullet.h) ----

#[repr(C)]
pub struct BulletIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut BulletIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut BulletIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut BulletIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut BulletIFace) -> *mut Interface, // 3: 72
    pub OpenEngine: unsafe extern "C" fn(*mut BulletIFace) -> *mut GlyphEngine, // 4: 76
    pub CloseEngine: unsafe extern "C" fn(*mut BulletIFace, *mut GlyphEngine), // 5: 80
    pub SetInfoA: unsafe extern "C" fn(*mut BulletIFace, *mut GlyphEngine, *const TagItem) -> u32, // 6: 84
    pub SetInfo: APTR, // 7: 88 (varargs)
    pub ObtainInfoA: unsafe extern "C" fn(*mut BulletIFace, *mut GlyphEngine, *const TagItem) -> u32, // 8: 92
    pub ObtainInfo: APTR, // 9: 96 (varargs)
    pub ReleaseInfoA: unsafe extern "C" fn(*mut BulletIFace, *mut GlyphEngine, *const TagItem) -> u32, // 10: 100
    pub ReleaseInfo: APTR, // 11: 104 (varargs)
    pub GetGlyphMap: unsafe extern "C" fn(*mut BulletIFace, *mut GlyphEngine, u32, *mut *mut GlyphMap) -> u32, // 12: 108
}

