//! ButtonIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ButtonIFace (button.h) ----

#[repr(C)]
pub struct ButtonIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ButtonIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ButtonIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut ButtonIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut ButtonIFace) -> *mut Interface, // 3: 72
    pub BUTTON_GetClass: unsafe extern "C" fn(*mut ButtonIFace) -> *mut APTR, // 4: 76
}

