//! BZip2IFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- BZip2IFace (bzip2.h) ----

#[repr(C)]
pub struct BZip2IFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut BZip2IFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut BZip2IFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut BZip2IFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut BZip2IFace) -> *mut Interface, // 3: 72
    pub BZ2_bzlibVersion: unsafe extern "C" fn(*mut BZip2IFace) -> *const APTR, // 4: 76
    pub BZ2_bzCompressInit: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR, i32, i32, i32) -> i32, // 5: 80
    pub BZ2_bzCompress: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR, i32) -> i32, // 6: 84
    pub BZ2_bzCompressEnd: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR) -> i32, // 7: 88
    pub BZ2_bzDecompressInit: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR, i32, i32) -> i32, // 8: 92
    pub BZ2_bzDecompress: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR) -> i32, // 9: 96
    pub BZ2_bzDecompressEnd: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR) -> i32, // 10: 100
    pub BZ2_bzBuffToBuffCompress: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR, *mut APTR, *mut APTR, APTR, i32, i32, i32) -> i32, // 11: 104
    pub BZ2_bzBuffToBuffDecompress: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR, *mut APTR, *mut APTR, APTR, i32, i32) -> i32, // 12: 108
    pub BZ2_bzReadOpen: unsafe extern "C" fn(*mut BZip2IFace, *mut i32, *mut APTR, i32, i32, *mut (), i32) -> *mut APTR, // 13: 112
    pub BZ2_bzReadClose: unsafe extern "C" fn(*mut BZip2IFace, *mut i32, *mut APTR), // 14: 116
    pub BZ2_bzReadGetUnused: unsafe extern "C" fn(*mut BZip2IFace, *mut i32, *mut APTR, *mut *mut (), *mut i32), // 15: 120
    pub BZ2_bzRead: unsafe extern "C" fn(*mut BZip2IFace, *mut i32, *mut APTR, *mut (), i32) -> i32, // 16: 124
    pub BZ2_bzWriteOpen: unsafe extern "C" fn(*mut BZip2IFace, *mut i32, *mut APTR, i32, i32, i32) -> *mut APTR, // 17: 128
    pub BZ2_bzWrite: unsafe extern "C" fn(*mut BZip2IFace, *mut i32, *mut APTR, *mut (), i32), // 18: 132
    pub BZ2_bzWriteClose: unsafe extern "C" fn(*mut BZip2IFace, *mut i32, *mut APTR, i32, *mut APTR, *mut APTR), // 19: 136
    pub BZ2_bzWriteClose64: unsafe extern "C" fn(*mut BZip2IFace, *mut i32, *mut APTR, i32, *mut APTR, *mut APTR, *mut APTR, *mut APTR), // 20: 140
    pub BZ2_bzopen: unsafe extern "C" fn(*mut BZip2IFace, *const APTR, *const APTR) -> *mut APTR, // 21: 144
    pub BZ2_bzdopen: unsafe extern "C" fn(*mut BZip2IFace, i32, *const APTR) -> *mut APTR, // 22: 148
    pub BZ2_bzread: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR, *mut (), i32) -> i32, // 23: 152
    pub BZ2_bzwrite: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR, *mut (), i32) -> i32, // 24: 156
    pub BZ2_bzflush: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR) -> i32, // 25: 160
    pub BZ2_bzclose: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR), // 26: 164
    pub BZ2_bzerror: unsafe extern "C" fn(*mut BZip2IFace, *mut APTR, *mut i32) -> *const APTR, // 27: 168
}

