//! CamdDriverIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- CamdDriverIFace (camddriver.h) ----

#[repr(C)]
pub struct CamdDriverIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut CamdDriverIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut CamdDriverIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut CamdDriverIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut CamdDriverIFace), // 3: 72
    pub GetMidiDeviceData: unsafe extern "C" fn(*mut CamdDriverIFace) -> *mut MidiDeviceData, // 4: 76
    pub OpenPort: unsafe extern "C" fn(*mut CamdDriverIFace, *mut MidiDeviceData, i32, APTR, APTR, APTR) -> u32, // 5: 80
    pub ClosePort: unsafe extern "C" fn(*mut CamdDriverIFace, *mut MidiDeviceData, i32), // 6: 84
    pub ActivateXmit: unsafe extern "C" fn(*mut CamdDriverIFace, APTR, i32), // 7: 88
}

