//! CardIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- CardIFace (cardres.h) ----

#[repr(C)]
pub struct CardIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut CardIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut CardIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut CardIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut CardIFace) -> *mut Interface, // 3: 72
    pub OwnCard: unsafe extern "C" fn(*mut CardIFace, *mut CardHandle) -> *mut CardHandle, // 4: 76
    pub ReleaseCard: unsafe extern "C" fn(*mut CardIFace, *mut CardHandle, u32), // 5: 80
    pub GetCardMap: unsafe extern "C" fn(*mut CardIFace) -> *mut CardMemoryMap, // 6: 84
    pub BeginCardAccess: unsafe extern "C" fn(*mut CardIFace, *mut CardHandle) -> u32, // 7: 88
    pub EndCardAccess: unsafe extern "C" fn(*mut CardIFace, *mut CardHandle) -> u32, // 8: 92
    pub ReadCardStatus: unsafe extern "C" fn(*mut CardIFace) -> u8, // 9: 96
    pub CardResetRemove: unsafe extern "C" fn(*mut CardIFace, *mut CardHandle, u32) -> u32, // 10: 100
    pub CardMiscControl: unsafe extern "C" fn(*mut CardIFace, *mut CardHandle, u8) -> u8, // 11: 104
    pub CardAccessSpeed: unsafe extern "C" fn(*mut CardIFace, *mut CardHandle, u32) -> u32, // 12: 108
    pub CardProgramVoltage: unsafe extern "C" fn(*mut CardIFace, *mut CardHandle, u32) -> i32, // 13: 112
    pub CardResetCard: unsafe extern "C" fn(*mut CardIFace, *mut CardHandle) -> u32, // 14: 116
    pub CopyTuple: unsafe extern "C" fn(*mut CardIFace, *const CardHandle, *mut u8, u32, u32) -> u32, // 15: 120
    pub DeviceTuple: unsafe extern "C" fn(*mut CardIFace, *const u8, *mut DeviceTData) -> u32, // 16: 124
    pub IfAmigaXIP: unsafe extern "C" fn(*mut CardIFace, *const CardHandle) -> *mut Resident, // 17: 128
    pub CardForceChange: unsafe extern "C" fn(*mut CardIFace) -> u32, // 18: 132
    pub CardChangeCount: unsafe extern "C" fn(*mut CardIFace) -> u32, // 19: 136
    pub CardInterface: unsafe extern "C" fn(*mut CardIFace) -> u32, // 20: 140
}

