//! CheckBoxIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- CheckBoxIFace (checkbox.h) ----

#[repr(C)]
pub struct CheckBoxIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut CheckBoxIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut CheckBoxIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut CheckBoxIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut CheckBoxIFace) -> *mut Interface, // 3: 72
    pub CHECKBOX_GetClass: unsafe extern "C" fn(*mut CheckBoxIFace) -> *mut APTR, // 4: 76
}

