//! ColorWheelIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ColorWheelIFace (colorwheel.h) ----

#[repr(C)]
pub struct ColorWheelIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ColorWheelIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ColorWheelIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut ColorWheelIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut ColorWheelIFace) -> *mut Interface, // 3: 72
    pub ConvertHSBToRGB: unsafe extern "C" fn(*mut ColorWheelIFace, *mut ColorWheelHSB, *mut ColorWheelRGB), // 4: 76
    pub ConvertRGBToHSB: unsafe extern "C" fn(*mut ColorWheelIFace, *mut ColorWheelRGB, *mut ColorWheelHSB), // 5: 80
}

