//! CommoditiesIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- CommoditiesIFace (commodities.h) ----

#[repr(C)]
pub struct CommoditiesIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut CommoditiesIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut CommoditiesIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut CommoditiesIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut CommoditiesIFace) -> *mut Interface, // 3: 72
    pub CreateCxObj: unsafe extern "C" fn(*mut CommoditiesIFace, u32, i32, i32) -> *mut APTR, // 4: 76
    pub CxBroker: unsafe extern "C" fn(*mut CommoditiesIFace, *const NewBroker, *mut i32) -> *mut APTR, // 5: 80
    pub ActivateCxObj: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR, i32) -> i32, // 6: 84
    pub DeleteCxObj: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR), // 7: 88
    pub DeleteCxObjAll: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR), // 8: 92
    pub CxObjType: unsafe extern "C" fn(*mut CommoditiesIFace, *const APTR) -> u32, // 9: 96
    pub CxObjError: unsafe extern "C" fn(*mut CommoditiesIFace, *const APTR) -> i32, // 10: 100
    pub ClearCxObjError: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR), // 11: 104
    pub SetCxObjPri: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR, i32) -> i32, // 12: 108
    pub AttachCxObj: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR, *mut APTR), // 13: 112
    pub EnqueueCxObj: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR, *mut APTR), // 14: 116
    pub InsertCxObj: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR, *mut APTR, *mut APTR), // 15: 120
    pub RemoveCxObj: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR), // 16: 124
    pub CxReserved0: unsafe extern "C" fn(*mut CommoditiesIFace), // 17: 128
    pub SetTranslate: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR, *mut InputEvent), // 18: 132
    pub SetFilter: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR, CONST_STRPTR), // 19: 136
    pub SetFilterIX: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR, *const APTR), // 20: 140
    pub ParseIX: unsafe extern "C" fn(*mut CommoditiesIFace, CONST_STRPTR, *mut APTR) -> i32, // 21: 144
    pub CxMsgType: unsafe extern "C" fn(*mut CommoditiesIFace, *const APTR) -> u32, // 22: 148
    pub CxMsgData: unsafe extern "C" fn(*mut CommoditiesIFace, *const APTR) -> APTR, // 23: 152
    pub CxMsgID: unsafe extern "C" fn(*mut CommoditiesIFace, *const APTR) -> i32, // 24: 156
    pub DivertCxMsg: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR, *mut APTR, *mut APTR), // 25: 160
    pub RouteCxMsg: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR, *mut APTR), // 26: 164
    pub DisposeCxMsg: unsafe extern "C" fn(*mut CommoditiesIFace, *mut APTR), // 27: 168
    pub InvertKeyMap: unsafe extern "C" fn(*mut CommoditiesIFace, u32, *mut InputEvent, *const KeyMap) -> u32, // 28: 172
    pub AddIEvents: unsafe extern "C" fn(*mut CommoditiesIFace, *mut InputEvent), // 29: 176
    pub CopyBrokerList: unsafe extern "C" fn(*mut CommoditiesIFace, *mut List) -> i32, // 30: 180
    pub FreeBrokerList: unsafe extern "C" fn(*mut CommoditiesIFace, *mut List), // 31: 184
    pub BrokerCommand: unsafe extern "C" fn(*mut CommoditiesIFace, CONST_STRPTR, i32) -> i32, // 32: 188
    pub MatchIX: unsafe extern "C" fn(*mut CommoditiesIFace, *const InputEvent, *const APTR) -> u32, // 33: 192
}

