//! ConsoleIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ConsoleIFace (console.h) ----

#[repr(C)]
pub struct ConsoleIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ConsoleIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ConsoleIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut ConsoleIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut ConsoleIFace) -> *mut Interface, // 3: 72
    pub CDInputHandler: unsafe extern "C" fn(*mut ConsoleIFace, *const InputEvent, *mut Library) -> *mut InputEvent, // 4: 76
    pub RawKeyConvert: unsafe extern "C" fn(*mut ConsoleIFace, *const InputEvent, STRPTR, i32, *const KeyMap) -> i32, // 5: 80
    pub GetConSnip: unsafe extern "C" fn(*mut ConsoleIFace) -> STRPTR, // 6: 84
    pub SetConSnip: unsafe extern "C" fn(*mut ConsoleIFace, STRPTR) -> u32, // 7: 88
    pub AddConSnipHook: unsafe extern "C" fn(*mut ConsoleIFace, *mut Hook), // 8: 92
    pub RemConSnipHook: unsafe extern "C" fn(*mut ConsoleIFace, *mut Hook), // 9: 96
}

