//! CW3GameportIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- CW3GameportIFace (catweasel.h) ----

#[repr(C)]
pub struct CW3GameportIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut CW3GameportIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut CW3GameportIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut CW3GameportIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut CW3GameportIFace) -> *mut Interface, // 3: 72
    pub InByte: unsafe extern "C" fn(*mut CW3GameportIFace, u32) -> u8, // 4: 76
    pub OutByte: unsafe extern "C" fn(*mut CW3GameportIFace, u32, u8), // 5: 80
}

