//! CW3KeyboardIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- CW3KeyboardIFace (catweasel.h) ----

#[repr(C)]
pub struct CW3KeyboardIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut CW3KeyboardIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut CW3KeyboardIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut CW3KeyboardIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut CW3KeyboardIFace) -> *mut Interface, // 3: 72
    pub InByte: unsafe extern "C" fn(*mut CW3KeyboardIFace, u32) -> u8, // 4: 76
    pub OutByte: unsafe extern "C" fn(*mut CW3KeyboardIFace, u32, u8), // 5: 80
}

