//! CyberGfxIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- CyberGfxIFace (cybergraphics.h) ----

#[repr(C)]
pub struct CyberGfxIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut CyberGfxIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut CyberGfxIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut CyberGfxIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut CyberGfxIFace) -> *mut Interface, // 3: 72
    pub Reserved1: unsafe extern "C" fn(*mut CyberGfxIFace), // 4: 76
    pub Reserved2: unsafe extern "C" fn(*mut CyberGfxIFace), // 5: 80
    pub Reserved3: unsafe extern "C" fn(*mut CyberGfxIFace), // 6: 84
    pub Reserved4: unsafe extern "C" fn(*mut CyberGfxIFace), // 7: 88
    pub IsCyberModeID: unsafe extern "C" fn(*mut CyberGfxIFace, u32) -> u32, // 8: 92
    pub BestCModeIDTagList: unsafe extern "C" fn(*mut CyberGfxIFace, *mut TagItem) -> u32, // 9: 96
    pub BestCModeIDTags: APTR, // 10: 100 (varargs)
    pub CModeRequestTagList: unsafe extern "C" fn(*mut CyberGfxIFace, APTR, *mut TagItem) -> u32, // 11: 104
    pub CModeRequestTags: APTR, // 12: 108 (varargs)
    pub AllocCModeListTagList: unsafe extern "C" fn(*mut CyberGfxIFace, *mut TagItem) -> *mut List, // 13: 112
    pub AllocCModeListTags: APTR, // 14: 116 (varargs)
    pub FreeCModeList: unsafe extern "C" fn(*mut CyberGfxIFace, *mut List), // 15: 120
    pub Reserved5: unsafe extern "C" fn(*mut CyberGfxIFace), // 16: 124
    pub ScalePixelArray: unsafe extern "C" fn(*mut CyberGfxIFace, APTR, u16, u16, u16, *mut RastPort, i16, i16, u16, u16, u8) -> i32, // 17: 128
    pub GetCyberMapAttr: unsafe extern "C" fn(*mut CyberGfxIFace, *mut BitMap, u32) -> u32, // 18: 132
    pub GetCyberIDAttr: unsafe extern "C" fn(*mut CyberGfxIFace, u32, u32) -> u32, // 19: 136
    pub ReadRGBPixel: unsafe extern "C" fn(*mut CyberGfxIFace, *mut RastPort, i16, i16) -> u32, // 20: 140
    pub WriteRGBPixel: unsafe extern "C" fn(*mut CyberGfxIFace, *mut RastPort, i16, i16, u32) -> i32, // 21: 144
    pub ReadPixelArray: unsafe extern "C" fn(*mut CyberGfxIFace, APTR, i16, i16, u16, *mut RastPort, i16, i16, u16, u16, u8) -> u32, // 22: 148
    pub WritePixelArray: unsafe extern "C" fn(*mut CyberGfxIFace, APTR, i16, i16, u16, *mut RastPort, i16, i16, u16, u16, u8) -> u32, // 23: 152
    pub MovePixelArray: unsafe extern "C" fn(*mut CyberGfxIFace, i16, i16, *mut RastPort, i16, i16, u16, u16) -> u32, // 24: 156
    pub Reserved6: unsafe extern "C" fn(*mut CyberGfxIFace), // 25: 160
    pub InvertPixelArray: unsafe extern "C" fn(*mut CyberGfxIFace, *mut RastPort, i16, i16, u16, u16) -> u32, // 26: 164
    pub FillPixelArray: unsafe extern "C" fn(*mut CyberGfxIFace, *mut RastPort, i16, i16, u16, u16, u32) -> u32, // 27: 168
    pub DoCDrawMethodTagList: unsafe extern "C" fn(*mut CyberGfxIFace, *mut Hook, *mut RastPort, *mut TagItem), // 28: 172
    pub DoCDrawMethodTags: APTR, // 29: 176 (varargs)
    pub CVideoCtrlTagList: unsafe extern "C" fn(*mut CyberGfxIFace, *mut ViewPort, *mut TagItem), // 30: 180
    pub CVideoCtrlTags: APTR, // 31: 184 (varargs)
    pub LockBitMapTagList: unsafe extern "C" fn(*mut CyberGfxIFace, APTR, *mut TagItem) -> APTR, // 32: 188
    pub LockBitMapTags: APTR, // 33: 192 (varargs)
    pub UnLockBitMap: unsafe extern "C" fn(*mut CyberGfxIFace, APTR), // 34: 196
    pub UnLockBitMapTagList: unsafe extern "C" fn(*mut CyberGfxIFace, APTR, *mut TagItem), // 35: 200
    pub UnLockBitMapTags: APTR, // 36: 204 (varargs)
    pub ExtractColor: unsafe extern "C" fn(*mut CyberGfxIFace, *mut RastPort, *mut BitMap, u32, u32, u32, u32, u32) -> u32, // 37: 208
    pub Reserved7: unsafe extern "C" fn(*mut CyberGfxIFace), // 38: 212
    pub WriteLUTPixelArray: unsafe extern "C" fn(*mut CyberGfxIFace, APTR, i16, i16, u16, *mut RastPort, APTR, i16, i16, u16, u16, u8) -> u32, // 39: 216
    pub Reserved8: unsafe extern "C" fn(*mut CyberGfxIFace), // 40: 220
    pub Reserved9: unsafe extern "C" fn(*mut CyberGfxIFace), // 41: 224
    pub WritePixelArrayAlpha: unsafe extern "C" fn(*mut CyberGfxIFace, APTR, i16, i16, i16, *mut RastPort, i16, i16, u16, u16, u32) -> u32, // 42: 228
    pub BltTemplateAlpha: unsafe extern "C" fn(*mut CyberGfxIFace, APTR, i16, i16, *mut RastPort, i16, i16, u16, u16), // 43: 232
}

