//! DataTypesIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- DataTypesIFace (datatypes.h) ----

#[repr(C)]
pub struct DataTypesIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut DataTypesIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut DataTypesIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut DataTypesIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut DataTypesIFace) -> *mut Interface, // 3: 72
    pub RLDispatch: unsafe extern "C" fn(*mut DataTypesIFace, *mut RexxMsg, *mut STRPTR) -> i32, // 4: 76
    pub ObtainDataTypeA: unsafe extern "C" fn(*mut DataTypesIFace, u32, APTR, *mut APTR) -> *mut DataType, // 5: 80
    pub ObtainDataType: APTR, // 6: 84 (varargs)
    pub ReleaseDataType: unsafe extern "C" fn(*mut DataTypesIFace, *mut DataType), // 7: 88
    pub NewDTObjectA: unsafe extern "C" fn(*mut DataTypesIFace, CONST_STRPTR, *mut APTR) -> *mut APTR, // 8: 92
    pub NewDTObject: APTR, // 9: 96 (varargs)
    pub DisposeDTObject: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR), // 10: 100
    pub SetDTAttrsA: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR, *mut Window, *mut Requester, *mut APTR) -> u32, // 11: 104
    pub SetDTAttrs: APTR, // 12: 108 (varargs)
    pub GetDTAttrsA: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR, *mut APTR) -> u32, // 13: 112
    pub GetDTAttrs: APTR, // 14: 116 (varargs)
    pub AddDTObject: unsafe extern "C" fn(*mut DataTypesIFace, *mut Window, *mut Requester, *mut APTR, i32) -> i32, // 15: 120
    pub RefreshDTObjectA: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR, *mut Window, *mut Requester, *mut APTR), // 16: 124
    pub RefreshDTObjects: APTR, // 17: 128 (varargs)
    pub RefreshDTObject: APTR, // 18: 132 (varargs)
    pub DoAsyncLayout: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR, *mut gpLayout) -> u32, // 19: 136
    pub DoDTMethodA: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR, *mut Window, *mut Requester, APTR) -> u32, // 20: 140
    pub DoDTMethod: APTR, // 21: 144 (varargs)
    pub RemoveDTObject: unsafe extern "C" fn(*mut DataTypesIFace, *mut Window, *mut APTR) -> i32, // 22: 148
    pub GetDTMethods: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR) -> *mut u32, // 23: 152
    pub GetDTTriggerMethods: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR) -> *mut DTMethod, // 24: 156
    pub PrintDTObjectA: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR, *mut Window, *mut Requester, *mut dtPrint) -> u32, // 25: 160
    pub PrintDTObject: APTR, // 26: 164 (varargs)
    pub ObtainDTDrawInfoA: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR, *mut APTR) -> APTR, // 27: 168
    pub ObtainDTDrawInfo: APTR, // 28: 172 (varargs)
    pub DrawDTObjectA: unsafe extern "C" fn(*mut DataTypesIFace, *mut RastPort, *mut APTR, i32, i32, i32, i32, i32, i32, *mut APTR) -> i32, // 29: 176
    pub DrawDTObject: APTR, // 30: 180 (varargs)
    pub ReleaseDTDrawInfo: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR, APTR), // 31: 184
    pub GetDTString: unsafe extern "C" fn(*mut DataTypesIFace, u32) -> CONST_STRPTR, // 32: 188
    pub Reserved1: unsafe extern "C" fn(*mut DataTypesIFace), // 33: 192
    pub Reserved2: unsafe extern "C" fn(*mut DataTypesIFace), // 34: 196
    pub Reserved3: unsafe extern "C" fn(*mut DataTypesIFace), // 35: 200
    pub Reserved4: unsafe extern "C" fn(*mut DataTypesIFace), // 36: 204
    pub Reserved5: unsafe extern "C" fn(*mut DataTypesIFace), // 37: 208
    pub Reserved6: unsafe extern "C" fn(*mut DataTypesIFace), // 38: 212
    pub Reserved7: unsafe extern "C" fn(*mut DataTypesIFace), // 39: 216
    pub Reserved8: unsafe extern "C" fn(*mut DataTypesIFace), // 40: 220
    pub Reserved9: unsafe extern "C" fn(*mut DataTypesIFace), // 41: 224
    pub Reserved10: unsafe extern "C" fn(*mut DataTypesIFace), // 42: 228
    pub Reserved11: unsafe extern "C" fn(*mut DataTypesIFace), // 43: 232
    pub Reserved12: unsafe extern "C" fn(*mut DataTypesIFace), // 44: 236
    pub SaveDTObject: APTR, // 45: 240 (varargs)
    pub DoDTDomain: APTR, // 46: 244 (varargs)
    pub FindToolNode: APTR, // 47: 248 (varargs)
    pub LaunchTool: APTR, // 48: 252 (varargs)
    pub LockDataType: unsafe extern "C" fn(*mut DataTypesIFace, *mut DataType), // 49: 256
    pub FindToolNodeA: unsafe extern "C" fn(*mut DataTypesIFace, *mut List, *mut APTR) -> *mut ToolNode, // 50: 260
    pub LaunchToolA: unsafe extern "C" fn(*mut DataTypesIFace, *mut Tool, CONST_STRPTR, *mut APTR) -> u32, // 51: 264
    pub FindMethod: unsafe extern "C" fn(*mut DataTypesIFace, *mut u32, u32) -> *mut u32, // 52: 268
    pub FindTriggerMethod: unsafe extern "C" fn(*mut DataTypesIFace, *mut DTMethod, CONST_STRPTR, u32) -> *mut DTMethod, // 53: 272
    pub CopyDTMethods: unsafe extern "C" fn(*mut DataTypesIFace, *mut u32, *mut u32, *mut u32) -> *mut u32, // 54: 276
    pub CopyDTTriggerMethods: unsafe extern "C" fn(*mut DataTypesIFace, *mut DTMethod, *mut DTMethod, *mut DTMethod) -> *mut DTMethod, // 55: 280
    pub FreeDTMethods: unsafe extern "C" fn(*mut DataTypesIFace, APTR), // 56: 284
    pub GetDTTriggerMethodDataFlags: unsafe extern "C" fn(*mut DataTypesIFace, u32) -> u32, // 57: 288
    pub SaveDTObjectA: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR, *mut Window, *mut Requester, CONST_STRPTR, u32, u32, *mut APTR) -> u32, // 58: 292
    pub StartDragSelect: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR) -> u32, // 59: 296
    pub DoDTDomainA: unsafe extern "C" fn(*mut DataTypesIFace, *mut APTR, *mut Window, *mut Requester, *mut RastPort, u32, *mut IBox, *mut APTR) -> u32, // 60: 300
    pub datatypesPrivate001: unsafe extern "C" fn(*mut DataTypesIFace) -> u32, // 61: 304
    pub datatypesPrivate002: unsafe extern "C" fn(*mut DataTypesIFace) -> u32, // 62: 308
}

