//! DateBrowserIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- DateBrowserIFace (datebrowser.h) ----

#[repr(C)]
pub struct DateBrowserIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut DateBrowserIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut DateBrowserIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut DateBrowserIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut DateBrowserIFace) -> *mut Interface, // 3: 72
    pub DATEBROWSER_GetClass: unsafe extern "C" fn(*mut DateBrowserIFace) -> *mut APTR, // 4: 76
    pub JulianWeekDay: unsafe extern "C" fn(*mut DateBrowserIFace, u16, u16, i32) -> u16, // 5: 80
    pub JulianMonthDays: unsafe extern "C" fn(*mut DateBrowserIFace, u16, i32) -> u16, // 6: 84
    pub JulianLeapYear: unsafe extern "C" fn(*mut DateBrowserIFace, i32) -> u32, // 7: 88
}

