//! DebugIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- DebugIFace (exec.h) ----

#[repr(C)]
pub struct DebugIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut DebugIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut DebugIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub AddDebugHook: unsafe extern "C" fn(*mut DebugIFace, *mut Task, *mut Hook) -> u32, // 4: 76
    pub DisassembleNative: unsafe extern "C" fn(*mut DebugIFace, APTR, STRPTR, STRPTR) -> APTR, // 5: 80
    pub Disassemble68k: unsafe extern "C" fn(*mut DebugIFace, APTR, STRPTR, STRPTR) -> APTR, // 6: 84
    pub GetDebugLevel: unsafe extern "C" fn(*mut DebugIFace) -> u32, // 7: 88
    pub ReadTaskContext: unsafe extern "C" fn(*mut DebugIFace, *mut Task, *mut ExceptionContext, u32) -> u32, // 8: 92
    pub WriteTaskContext: unsafe extern "C" fn(*mut DebugIFace, *mut Task, *mut ExceptionContext, u32) -> u32, // 9: 96
    pub StackTrace: unsafe extern "C" fn(*mut DebugIFace, *mut Task, *mut Hook) -> i32, // 10: 100
    pub ObtainDebugSymbol: unsafe extern "C" fn(*mut DebugIFace, CONST_APTR, *mut TagItem) -> *mut DebugSymbol, // 11: 104
    pub ObtainDebugSymbolTags: APTR, // 12: 108 (varargs)
    pub ReleaseDebugSymbol: unsafe extern "C" fn(*mut DebugIFace, *mut DebugSymbol), // 13: 112
    pub IsIn68kEmulator: unsafe extern "C" fn(*mut DebugIFace, *const Task) -> u32, // 14: 116
    pub StartDebugOutputNotify: unsafe extern "C" fn(*mut DebugIFace, *mut TagItem) -> *mut DebugOutputNotify, // 15: 120
    pub StartDebugOutputNotifyTags: APTR, // 16: 124 (varargs)
    pub EndDebugOutputNotify: unsafe extern "C" fn(*mut DebugIFace, *mut DebugOutputNotify), // 17: 128
}

