//! DiskIOIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- DiskIOIFace (diskio.h) ----

#[repr(C)]
pub struct DiskIOIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut DiskIOIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut DiskIOIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut DiskIOIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut DiskIOIFace) -> *mut Interface, // 3: 72
    pub Setup: unsafe extern "C" fn(*mut DiskIOIFace, CONST_STRPTR, *const TagItem) -> *mut DiskIO, // 4: 76
    pub SetupTags: APTR, // 5: 80 (varargs)
    pub Cleanup: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskIO), // 6: 84
    pub Update: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskIO), // 7: 88
    pub IsDiskPresent: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskIO) -> u32, // 8: 92
    pub IsWriteProtected: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskIO) -> u32, // 9: 96
    pub Query: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskIO, *const TagItem), // 10: 100
    pub QueryTags: APTR, // 11: 104 (varargs)
    pub FlushIOCache: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskIO) -> i32, // 12: 108
    pub FlushBlocks: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskIO, u64, u32) -> i32, // 13: 112
    pub ReadBlocks: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskIO, u64, APTR, u32) -> i32, // 14: 116
    pub WriteBlocks: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskIO, u64, CONST_APTR, u32) -> i32, // 15: 120
    pub ReadBytes: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskIO, u64, APTR, u32) -> i32, // 16: 124
    pub WriteBytes: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskIO, u64, CONST_APTR, u32) -> i32, // 17: 128
    pub AddDiskChangeHandler: unsafe extern "C" fn(*mut DiskIOIFace, CONST_STRPTR, APTR, APTR, *const TagItem) -> *mut DiskChangeHandler, // 18: 132
    pub AddDiskChangeHandlerTags: APTR, // 19: 136 (varargs)
    pub RemDiskChangeHandler: unsafe extern "C" fn(*mut DiskIOIFace, *mut DiskChangeHandler), // 20: 140
}

