//! DiskfontIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- DiskfontIFace (diskfont.h) ----

#[repr(C)]
pub struct DiskfontIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut DiskfontIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut DiskfontIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut DiskfontIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut DiskfontIFace) -> *mut Interface, // 3: 72
    pub OpenDiskFont: unsafe extern "C" fn(*mut DiskfontIFace, *const TextAttr) -> *mut TextFont, // 4: 76
    pub AvailFonts: unsafe extern "C" fn(*mut DiskfontIFace, STRPTR, i32, u32) -> i32, // 5: 80
    pub NewFontContents: unsafe extern "C" fn(*mut DiskfontIFace, u32, CONST_STRPTR) -> *mut FontContentsHeader, // 6: 84
    pub DisposeFontContents: unsafe extern "C" fn(*mut DiskfontIFace, *mut FontContentsHeader), // 7: 88
    pub NewScaledDiskFont: unsafe extern "C" fn(*mut DiskfontIFace, *mut TextFont, *mut TextAttr) -> *mut DiskFontHeader, // 8: 92
    pub GetDiskFontCtrl: unsafe extern "C" fn(*mut DiskfontIFace, i32) -> i32, // 9: 96
    pub SetDiskFontCtrlA: unsafe extern "C" fn(*mut DiskfontIFace, *const TagItem), // 10: 100
    pub SetDiskFontCtrl: APTR, // 11: 104 (varargs)
    pub EOpenEngine: unsafe extern "C" fn(*mut DiskfontIFace, *mut EGlyphEngine) -> i32, // 12: 108
    pub ECloseEngine: unsafe extern "C" fn(*mut DiskfontIFace, *mut EGlyphEngine), // 13: 112
    pub ESetInfoA: unsafe extern "C" fn(*mut DiskfontIFace, *mut EGlyphEngine, *const TagItem) -> u32, // 14: 116
    pub ESetInfo: APTR, // 15: 120 (varargs)
    pub EObtainInfoA: unsafe extern "C" fn(*mut DiskfontIFace, *mut EGlyphEngine, *const TagItem) -> u32, // 16: 124
    pub EObtainInfo: APTR, // 17: 128 (varargs)
    pub EReleaseInfoA: unsafe extern "C" fn(*mut DiskfontIFace, *mut EGlyphEngine, *const TagItem) -> u32, // 18: 132
    pub EReleaseInfo: APTR, // 19: 136 (varargs)
    pub OpenOutlineFont: unsafe extern "C" fn(*mut DiskfontIFace, CONST_STRPTR, *mut List, u32) -> *mut OutlineFont, // 20: 140
    pub CloseOutlineFont: unsafe extern "C" fn(*mut DiskfontIFace, *mut OutlineFont, *mut List), // 21: 144
    pub WriteFontContents: unsafe extern "C" fn(*mut DiskfontIFace, u32, CONST_STRPTR, *mut FontContentsHeader) -> i32, // 22: 148
    pub WriteDiskFontHeaderA: unsafe extern "C" fn(*mut DiskfontIFace, *mut TextFont, CONST_STRPTR, *const TagItem) -> i32, // 23: 152
    pub WriteDiskFontHeader: APTR, // 24: 156 (varargs)
    pub ObtainCharsetInfo: unsafe extern "C" fn(*mut DiskfontIFace, u32, u32, u32) -> u32, // 25: 160
    pub ObtainTTextAttr: unsafe extern "C" fn(*mut DiskfontIFace, *mut TextFont) -> *mut TTextAttr, // 26: 164
    pub FreeTTextAttr: unsafe extern "C" fn(*mut DiskfontIFace, *mut TTextAttr), // 27: 168
}

