//! DockyIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- DockyIFace (docky.h) ----

#[repr(C)]
pub struct DockyIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut DockyIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut DockyIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut DockyIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut DockyIFace) -> *mut DockyIFace, // 3: 72
    pub DockyGet: unsafe extern "C" fn(*mut DockyIFace, u32, *mut u32) -> u32, // 4: 76
    pub DockySet: unsafe extern "C" fn(*mut DockyIFace, u32, u32) -> u32, // 5: 80
    pub DockyProcess: unsafe extern "C" fn(*mut DockyIFace, u32, *mut u32, *mut u32, *mut u32) -> u32, // 6: 84
}

