//! DrawListIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- DrawListIFace (drawlist.h) ----

#[repr(C)]
pub struct DrawListIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut DrawListIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut DrawListIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut DrawListIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut DrawListIFace) -> *mut Interface, // 3: 72
    pub DRAWLIST_GetClass: unsafe extern "C" fn(*mut DrawListIFace) -> *mut APTR, // 4: 76
}

