//! DTClassIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- DTClassIFace (dtclass.h) ----

#[repr(C)]
pub struct DTClassIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut DTClassIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut DTClassIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut DTClassIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut DTClassIFace) -> *mut Interface, // 3: 72
    pub ObtainEngine: unsafe extern "C" fn(*mut DTClassIFace) -> *mut APTR, // 4: 76
}

