//! ElfIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ElfIFace (elf.h) ----

#[repr(C)]
pub struct ElfIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ElfIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ElfIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut ElfIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut ElfIFace) -> *mut Interface, // 3: 72
    pub OpenElf: unsafe extern "C" fn(*mut ElfIFace, *mut TagItem) -> APTR, // 4: 76
    pub OpenElfTags: APTR, // 5: 80 (varargs)
    pub CloseElf: unsafe extern "C" fn(*mut ElfIFace, APTR, *mut TagItem), // 6: 84
    pub CloseElfTags: APTR, // 7: 88 (varargs)
    pub GetElfAttrs: unsafe extern "C" fn(*mut ElfIFace, APTR, *mut TagItem) -> u32, // 8: 92
    pub GetElfAttrsTags: APTR, // 9: 96 (varargs)
    pub SetElfAttrs: unsafe extern "C" fn(*mut ElfIFace, APTR, *mut TagItem) -> u32, // 10: 100
    pub SetElfAttrsTags: APTR, // 11: 104 (varargs)
    pub GetSectionHeader: unsafe extern "C" fn(*mut ElfIFace, APTR, *mut TagItem) -> *mut APTR, // 12: 108
    pub GetSectionHeaderTags: APTR, // 13: 112 (varargs)
    pub GetSection: unsafe extern "C" fn(*mut ElfIFace, APTR, *mut TagItem) -> APTR, // 14: 116
    pub GetSectionTags: APTR, // 15: 120 (varargs)
    pub ElfLoadSeg: unsafe extern "C" fn(*mut ElfIFace, APTR, *mut TagItem) -> APTR, // 16: 124
    pub ElfLoadSegTags: APTR, // 17: 128 (varargs)
    pub GetElfString: unsafe extern "C" fn(*mut ElfIFace, APTR, u16, u16) -> CONST_STRPTR, // 18: 132
    pub SymbolQuery: unsafe extern "C" fn(*mut ElfIFace, APTR, u32, *mut Elf32_SymbolQuery) -> u32, // 19: 136
    pub UnloadSection: unsafe extern "C" fn(*mut ElfIFace, APTR, *mut TagItem), // 20: 140
    pub UnloadSectionTags: APTR, // 21: 144 (varargs)
    pub AddressToSection: unsafe extern "C" fn(*mut ElfIFace, APTR, APTR) -> u32, // 22: 148
    pub ScanSymbolTable: unsafe extern "C" fn(*mut ElfIFace, APTR, *mut Hook, *mut TagItem), // 23: 152
    pub ScanSymbolTableTags: APTR, // 24: 156 (varargs)
    pub RelocateSection: unsafe extern "C" fn(*mut ElfIFace, APTR, *mut TagItem) -> u32, // 25: 160
    pub RelocateSectionTags: APTR, // 26: 164 (varargs)
    pub CopyDataSegment: unsafe extern "C" fn(*mut ElfIFace, APTR, *mut u32) -> *mut (), // 27: 168
    pub FreeDataSegmentCopy: unsafe extern "C" fn(*mut ElfIFace, APTR, *mut ()), // 28: 172
    pub InitSHLibs: unsafe extern "C" fn(*mut ElfIFace, APTR, u32), // 29: 176
    pub DLOpen: unsafe extern "C" fn(*mut ElfIFace, APTR, CONST_STRPTR, u32) -> APTR, // 30: 180
    pub DLClose: unsafe extern "C" fn(*mut ElfIFace, APTR, APTR) -> APTR, // 31: 184
    pub DLSym: unsafe extern "C" fn(*mut ElfIFace, APTR, APTR, CONST_STRPTR, *mut APTR) -> APTR, // 32: 188
}

