//! ExecIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ExecIFace (exec.h) ----

#[repr(C)]
pub struct ExecIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ExecIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ExecIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub AddHead: unsafe extern "C" fn(*mut ExecIFace, *mut List, *mut Node), // 4: 76
    pub AddMemHandler: unsafe extern "C" fn(*mut ExecIFace, *mut Interrupt), // 5: 80
    pub AddMemList: unsafe extern "C" fn(*mut ExecIFace, u32, u32, i32, APTR, CONST_STRPTR), // 6: 84
    pub AddTail: unsafe extern "C" fn(*mut ExecIFace, *mut List, *mut Node), // 7: 88
    pub AllocAbs: unsafe extern "C" fn(*mut ExecIFace, u32, APTR) -> APTR, // 8: 92
    pub Allocate: unsafe extern "C" fn(*mut ExecIFace, *mut MemHeader, u32) -> APTR, // 9: 96
    pub AllocEntry: unsafe extern "C" fn(*mut ExecIFace, *mut MemList) -> *mut MemList, // 10: 100
    pub AllocMem: unsafe extern "C" fn(*mut ExecIFace, u32, u32) -> APTR, // 11: 104
    pub AllocPooled: unsafe extern "C" fn(*mut ExecIFace, APTR, u32) -> APTR, // 12: 108
    pub AllocVec: unsafe extern "C" fn(*mut ExecIFace, u32, u32) -> APTR, // 13: 112
    pub AllocVecPooled: unsafe extern "C" fn(*mut ExecIFace, APTR, u32) -> APTR, // 14: 116
    pub AvailMem: unsafe extern "C" fn(*mut ExecIFace, u32) -> u32, // 15: 120
    pub CopyMem: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR, APTR, u32), // 16: 124
    pub CopyMemQuick: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR, APTR, u32), // 17: 128
    pub CreatePool: unsafe extern "C" fn(*mut ExecIFace, u32, u32, u32) -> APTR, // 18: 132
    pub Deallocate: unsafe extern "C" fn(*mut ExecIFace, *mut MemHeader, APTR, u32), // 19: 136
    pub DeletePool: unsafe extern "C" fn(*mut ExecIFace, APTR), // 20: 140
    pub Enqueue: unsafe extern "C" fn(*mut ExecIFace, *mut List, *mut Node), // 21: 144
    pub FindName: unsafe extern "C" fn(*mut ExecIFace, *mut List, CONST_STRPTR) -> *mut Node, // 22: 148
    pub FindIName: unsafe extern "C" fn(*mut ExecIFace, *mut List, CONST_STRPTR) -> *mut Node, // 23: 152
    pub Forbid: unsafe extern "C" fn(*mut ExecIFace), // 24: 156
    pub FreeEntry: unsafe extern "C" fn(*mut ExecIFace, *mut MemList), // 25: 160
    pub FreeMem: unsafe extern "C" fn(*mut ExecIFace, APTR, u32), // 26: 164
    pub FreePooled: unsafe extern "C" fn(*mut ExecIFace, APTR, APTR, u32), // 27: 168
    pub FreeVec: unsafe extern "C" fn(*mut ExecIFace, APTR), // 28: 172
    pub FreeVecPooled: unsafe extern "C" fn(*mut ExecIFace, APTR, APTR), // 29: 176
    pub InitData: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR, APTR, u32), // 30: 180
    pub InitStruct: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR, APTR, u32), // 31: 184
    pub Insert: unsafe extern "C" fn(*mut ExecIFace, *mut List, *mut Node, *mut Node), // 32: 188
    pub MakeInterface: unsafe extern "C" fn(*mut ExecIFace, *mut Library, *const TagItem) -> *mut Interface, // 33: 192
    pub MakeInterfaceTags: APTR, // 34: 196 (varargs)
    pub Permit: unsafe extern "C" fn(*mut ExecIFace), // 35: 200
    pub RawDoFmt: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR, CONST_APTR, APTR, APTR) -> APTR, // 36: 204
    pub RemHead: unsafe extern "C" fn(*mut ExecIFace, *mut List) -> *mut Node, // 37: 208
    pub RemMemHandler: unsafe extern "C" fn(*mut ExecIFace, *mut Interrupt), // 38: 212
    pub Remove: unsafe extern "C" fn(*mut ExecIFace, *mut Node), // 39: 216
    pub RemTail: unsafe extern "C" fn(*mut ExecIFace, *mut List) -> *mut Node, // 40: 220
    pub TypeOfMem: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR) -> u32, // 41: 224
    pub InitResident: unsafe extern "C" fn(*mut ExecIFace, *const Resident, u32) -> APTR, // 42: 228
    pub InitCode: unsafe extern "C" fn(*mut ExecIFace, u32, u32), // 43: 232
    pub SumKickData: unsafe extern "C" fn(*mut ExecIFace) -> u32, // 44: 236
    pub AddTask: unsafe extern "C" fn(*mut ExecIFace, *mut Task, CONST_APTR, CONST_APTR, *const TagItem) -> APTR, // 45: 240
    pub AddTaskTags: APTR, // 46: 244 (varargs)
    pub Disable: unsafe extern "C" fn(*mut ExecIFace), // 47: 248
    pub Enable: unsafe extern "C" fn(*mut ExecIFace), // 48: 252
    pub Reschedule: unsafe extern "C" fn(*mut ExecIFace), // 49: 256
    pub FindTask: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR) -> *mut Task, // 50: 260
    pub RemTask: unsafe extern "C" fn(*mut ExecIFace, *mut Task), // 51: 264
    pub SetTaskPri: unsafe extern "C" fn(*mut ExecIFace, *mut Task, i8) -> i8, // 52: 268
    pub StackSwap: unsafe extern "C" fn(*mut ExecIFace, *mut StackSwapStruct), // 53: 272
    pub AllocSignal: unsafe extern "C" fn(*mut ExecIFace, i8) -> i8, // 54: 276
    pub FreeSignal: unsafe extern "C" fn(*mut ExecIFace, i8), // 55: 280
    pub SetExcept: unsafe extern "C" fn(*mut ExecIFace, u32, u32) -> u32, // 56: 284
    pub SetSignal: unsafe extern "C" fn(*mut ExecIFace, u32, u32) -> u32, // 57: 288
    pub Signal: unsafe extern "C" fn(*mut ExecIFace, *mut Task, u32), // 58: 292
    pub Wait: unsafe extern "C" fn(*mut ExecIFace, u32) -> u32, // 59: 296
    pub AddPort: unsafe extern "C" fn(*mut ExecIFace, *mut MsgPort), // 60: 300
    pub CreatePort: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR, i8) -> *mut MsgPort, // 61: 304
    pub CreateMsgPort: unsafe extern "C" fn(*mut ExecIFace) -> *mut MsgPort, // 62: 308
    pub DeletePort: unsafe extern "C" fn(*mut ExecIFace, *mut MsgPort), // 63: 312
    pub DeleteMsgPort: unsafe extern "C" fn(*mut ExecIFace, *mut MsgPort), // 64: 316
    pub FindPort: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR) -> *mut MsgPort, // 65: 320
    pub GetMsg: unsafe extern "C" fn(*mut ExecIFace, *mut MsgPort) -> *mut Message, // 66: 324
    pub PutMsg: unsafe extern "C" fn(*mut ExecIFace, *mut MsgPort, *mut Message), // 67: 328
    pub RemPort: unsafe extern "C" fn(*mut ExecIFace, *mut MsgPort), // 68: 332
    pub ReplyMsg: unsafe extern "C" fn(*mut ExecIFace, *mut Message), // 69: 336
    pub WaitPort: unsafe extern "C" fn(*mut ExecIFace, *mut MsgPort) -> *mut Message, // 70: 340
    pub Cause: unsafe extern "C" fn(*mut ExecIFace, *mut Interrupt), // 71: 344
    pub AddSemaphore: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore), // 72: 348
    pub AttemptSemaphore: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore) -> i32, // 73: 352
    pub AttemptSemaphoreShared: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore) -> i32, // 74: 356
    pub FindSemaphore: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR) -> *mut SignalSemaphore, // 75: 360
    pub InitSemaphore: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore), // 76: 364
    pub ObtainSemaphore: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore), // 77: 368
    pub ObtainSemaphoreList: unsafe extern "C" fn(*mut ExecIFace, *mut List), // 78: 372
    pub ObtainSemaphoreShared: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore), // 79: 376
    pub Procure: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore, *mut SemaphoreMessage), // 80: 380
    pub ReleaseSemaphore: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore), // 81: 384
    pub ReleaseSemaphoreList: unsafe extern "C" fn(*mut ExecIFace, *mut List), // 82: 388
    pub RemSemaphore: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore), // 83: 392
    pub Vacate: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore, *mut SemaphoreMessage), // 84: 396
    pub CreateTask: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR, i32, CONST_APTR, u32, *const TagItem) -> *mut Task, // 85: 400
    pub CreateTaskTags: APTR, // 86: 404 (varargs)
    pub DeleteTask: unsafe extern "C" fn(*mut ExecIFace, *mut Task), // 87: 408
    pub SumLibrary: unsafe extern "C" fn(*mut ExecIFace, *mut Library), // 88: 412
    pub CreateLibrary: unsafe extern "C" fn(*mut ExecIFace, *const TagItem) -> *mut Library, // 89: 416
    pub CreateLibraryTags: APTR, // 90: 420 (varargs)
    pub OpenLibrary: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR, u32) -> *mut Library, // 91: 424
    pub CloseLibrary: unsafe extern "C" fn(*mut ExecIFace, *mut Library) -> APTR, // 92: 428
    pub AddLibrary: unsafe extern "C" fn(*mut ExecIFace, *mut Library), // 93: 432
    pub RemLibrary: unsafe extern "C" fn(*mut ExecIFace, *mut Library) -> u32, // 94: 436
    pub AddDevice: unsafe extern "C" fn(*mut ExecIFace, *mut Device), // 95: 440
    pub RemDevice: unsafe extern "C" fn(*mut ExecIFace, *mut Device) -> u32, // 96: 444
    pub GetInterface: unsafe extern "C" fn(*mut ExecIFace, *mut Library, CONST_STRPTR, u32, *const TagItem) -> *mut Interface, // 97: 448
    pub GetInterfaceTags: APTR, // 98: 452 (varargs)
    pub DropInterface: unsafe extern "C" fn(*mut ExecIFace, *mut Interface), // 99: 456
    pub AddInterface: unsafe extern "C" fn(*mut ExecIFace, *mut Library, *mut Interface), // 100: 460
    pub RemInterface: unsafe extern "C" fn(*mut ExecIFace, *mut Interface), // 101: 464
    pub SumInterface: unsafe extern "C" fn(*mut ExecIFace, *mut Interface), // 102: 468
    pub FindResident: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR) -> *mut Resident, // 103: 472
    pub SetMethod: unsafe extern "C" fn(*mut ExecIFace, *mut Interface, i32, CONST_APTR) -> APTR, // 104: 476
    pub DeleteInterface: unsafe extern "C" fn(*mut ExecIFace, *mut Interface), // 105: 480
    pub DeleteLibrary: unsafe extern "C" fn(*mut ExecIFace, *mut Library), // 106: 484
    pub SetFunction: unsafe extern "C" fn(*mut ExecIFace, *mut Library, i32, CONST_APTR) -> APTR, // 107: 488
    pub CacheClearE: unsafe extern "C" fn(*mut ExecIFace, APTR, u32, u32), // 108: 492
    pub CacheClearU: unsafe extern "C" fn(*mut ExecIFace), // 109: 496
    pub MakeFunctions: unsafe extern "C" fn(*mut ExecIFace, APTR, CONST_APTR, CONST_APTR) -> u32, // 110: 500
    pub OpenDevice: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR, u32, *mut IORequest, u32) -> i32, // 111: 504
    pub CloseDevice: unsafe extern "C" fn(*mut ExecIFace, *mut IORequest) -> APTR, // 112: 508
    pub CreateIORequest: unsafe extern "C" fn(*mut ExecIFace, *const MsgPort, u32) -> *mut IORequest, // 113: 512
    pub DeleteIORequest: unsafe extern "C" fn(*mut ExecIFace, *mut IORequest), // 114: 516
    pub AbortIO: unsafe extern "C" fn(*mut ExecIFace, *mut IORequest), // 115: 520
    pub CheckIO: unsafe extern "C" fn(*mut ExecIFace, *mut IORequest) -> *mut IORequest, // 116: 524
    pub DoIO: unsafe extern "C" fn(*mut ExecIFace, *mut IORequest) -> i8, // 117: 528
    pub SendIO: unsafe extern "C" fn(*mut ExecIFace, *mut IORequest), // 118: 532
    pub BeginIO: unsafe extern "C" fn(*mut ExecIFace, *mut IORequest), // 119: 536
    pub WaitIO: unsafe extern "C" fn(*mut ExecIFace, *mut IORequest) -> i8, // 120: 540
    pub AddResource: unsafe extern "C" fn(*mut ExecIFace, APTR), // 121: 544
    pub RemResource: unsafe extern "C" fn(*mut ExecIFace, APTR), // 122: 548
    pub OpenResource: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR) -> APTR, // 123: 552
    pub AddIntServer: unsafe extern "C" fn(*mut ExecIFace, u32, *mut Interrupt) -> u32, // 124: 556
    pub RemIntServer: unsafe extern "C" fn(*mut ExecIFace, u32, *mut Interrupt), // 125: 560
    pub SetIntVector: unsafe extern "C" fn(*mut ExecIFace, u32, *const Interrupt) -> *mut Interrupt, // 126: 564
    pub ObtainQuickVector: unsafe extern "C" fn(*mut ExecIFace, APTR) -> u32, // 127: 568
    pub Alert: unsafe extern "C" fn(*mut ExecIFace, u32), // 128: 572
    pub SuperState: unsafe extern "C" fn(*mut ExecIFace) -> APTR, // 129: 576
    pub UserState: unsafe extern "C" fn(*mut ExecIFace, APTR), // 130: 580
    pub Supervisor: unsafe extern "C" fn(*mut ExecIFace, APTR) -> u32, // 131: 584
    pub SetTaskTrap: unsafe extern "C" fn(*mut ExecIFace, u32, CONST_APTR, CONST_APTR) -> u32, // 132: 588
    pub AllocTrap: unsafe extern "C" fn(*mut ExecIFace, u32) -> i32, // 133: 592
    pub FreeTrap: unsafe extern "C" fn(*mut ExecIFace, u32), // 134: 596
    pub GetCC: unsafe extern "C" fn(*mut ExecIFace) -> u16, // 135: 600
    pub SetSR: unsafe extern "C" fn(*mut ExecIFace, u32, u32) -> u32, // 136: 604
    pub AVL_AddNode: unsafe extern "C" fn(*mut ExecIFace, *mut *mut AVLNode, *mut AVLNode, APTR) -> *mut AVLNode, // 137: 608
    pub AVL_FindFirstNode: unsafe extern "C" fn(*mut ExecIFace, *const AVLNode) -> *mut AVLNode, // 138: 612
    pub AVL_FindLastNode: unsafe extern "C" fn(*mut ExecIFace, *const AVLNode) -> *mut AVLNode, // 139: 616
    pub AVL_FindNextNodeByAddress: unsafe extern "C" fn(*mut ExecIFace, *const AVLNode) -> *mut AVLNode, // 140: 620
    pub AVL_FindNextNodeByKey: unsafe extern "C" fn(*mut ExecIFace, *const AVLNode, APTR, APTR) -> *mut AVLNode, // 141: 624
    pub AVL_FindNode: unsafe extern "C" fn(*mut ExecIFace, *const AVLNode, APTR, APTR) -> *mut AVLNode, // 142: 628
    pub AVL_FindPrevNodeByAddress: unsafe extern "C" fn(*mut ExecIFace, *const AVLNode) -> *mut AVLNode, // 143: 632
    pub AVL_FindPrevNodeByKey: unsafe extern "C" fn(*mut ExecIFace, *const AVLNode, APTR, APTR) -> *mut AVLNode, // 144: 636
    pub AVL_RemNodeByAddress: unsafe extern "C" fn(*mut ExecIFace, *mut *mut AVLNode, *mut AVLNode) -> *mut AVLNode, // 145: 640
    pub AVL_RemNodeByKey: unsafe extern "C" fn(*mut ExecIFace, *mut *mut AVLNode, APTR, APTR) -> *mut AVLNode, // 146: 644
    pub CacheControl: unsafe extern "C" fn(*mut ExecIFace, u32, u32) -> u32, // 147: 648
    pub LockMem: unsafe extern "C" fn(*mut ExecIFace, APTR, u32) -> u32, // 148: 652
    pub UnlockMem: unsafe extern "C" fn(*mut ExecIFace, APTR, u32), // 149: 656
    pub ReallocVec_UNIMPLEMENTED: APTR, // 150: 660
    pub CachePreDMA: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR, *mut u32, u32) -> APTR, // 151: 664
    pub CachePostDMA: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR, *mut u32, u32), // 152: 668
    pub StartDMA: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR, u32, u32) -> u32, // 153: 672
    pub EndDMA: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR, u32, u32), // 154: 676
    pub GetDMAList: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR, u32, u32, *mut DMAEntry), // 155: 680
    pub AddTrackable: unsafe extern "C" fn(*mut ExecIFace, *mut Task, APTR, *mut Hook) -> *mut Trackable, // 156: 684
    pub FindTrackable: unsafe extern "C" fn(*mut ExecIFace, *mut Task, APTR) -> *mut Trackable, // 157: 688
    pub RemTrackable: unsafe extern "C" fn(*mut ExecIFace, *mut Task, *mut Trackable) -> *mut Trackable, // 158: 692
    pub DeleteTrackable: unsafe extern "C" fn(*mut ExecIFace, *mut Trackable), // 159: 696
    pub AllocSysObject: unsafe extern "C" fn(*mut ExecIFace, u32, *const TagItem) -> APTR, // 160: 700
    pub AllocSysObjectTags: APTR, // 161: 704 (varargs)
    pub FreeSysObject: unsafe extern "C" fn(*mut ExecIFace, u32, APTR), // 162: 708
    pub SuspendTask: unsafe extern "C" fn(*mut ExecIFace, *mut Task, u32), // 163: 712
    pub RestartTask: unsafe extern "C" fn(*mut ExecIFace, *mut Task, u32), // 164: 716
    pub MoveList: unsafe extern "C" fn(*mut ExecIFace, *mut List, *mut List), // 165: 720
    pub NewList: unsafe extern "C" fn(*mut ExecIFace, *mut List), // 166: 724
    pub NewMinList: unsafe extern "C" fn(*mut ExecIFace, *mut MinList), // 167: 728
    pub ColdReboot: unsafe extern "C" fn(*mut ExecIFace), // 168: 732
    pub MakeLibrary: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR, CONST_APTR, CONST_APTR, u32, APTR) -> *mut Library, // 169: 736
    pub Emulate: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR, *const TagItem) -> u32, // 170: 740
    pub EmulateTags: APTR, // 171: 744 (varargs)
    pub DebugPrintF: APTR, // 172: 748 (varargs)
    pub IsNative: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR) -> u32, // 173: 752
    pub Private1: APTR, // 174: 756
    pub Private2: APTR, // 175: 760
    pub GetCPUInfo: unsafe extern "C" fn(*mut ExecIFace, *const TagItem), // 176: 764
    pub GetCPUInfoTags: APTR, // 177: 768 (varargs)
    pub OwnerOfMem: unsafe extern "C" fn(*mut ExecIFace, CONST_APTR) -> *mut Task, // 178: 772
    pub AddResetCallback: unsafe extern "C" fn(*mut ExecIFace, *mut Interrupt) -> u32, // 179: 776
    pub RemResetCallback: unsafe extern "C" fn(*mut ExecIFace, *mut Interrupt), // 180: 780
    pub ItemPoolAlloc: unsafe extern "C" fn(*mut ExecIFace, APTR) -> APTR, // 181: 784
    pub ItemPoolFree: unsafe extern "C" fn(*mut ExecIFace, APTR, APTR), // 182: 788
    pub ItemPoolGC: unsafe extern "C" fn(*mut ExecIFace, APTR), // 183: 792
    pub ItemPoolControl: unsafe extern "C" fn(*mut ExecIFace, APTR, *const TagItem) -> u32, // 184: 796
    pub ItemPoolControlTags: APTR, // 185: 800 (varargs)
    pub ItemPoolFlush: unsafe extern "C" fn(*mut ExecIFace, APTR), // 186: 804
    pub GetHead: unsafe extern "C" fn(*mut ExecIFace, *mut List) -> *mut Node, // 187: 808
    pub GetTail: unsafe extern "C" fn(*mut ExecIFace, *mut List) -> *mut Node, // 188: 812
    pub GetSucc: unsafe extern "C" fn(*mut ExecIFace, *mut Node) -> *mut Node, // 189: 816
    pub GetPred: unsafe extern "C" fn(*mut ExecIFace, *mut Node) -> *mut Node, // 190: 820
    pub IceColdReboot: unsafe extern "C" fn(*mut ExecIFace), // 191: 824
    pub Private3: APTR, // 192: 828
    pub Private4: APTR, // 193: 832
    pub Private5: APTR, // 194: 836
    pub Private6: APTR, // 195: 840
    pub Private7: APTR, // 196: 844
    pub Private8: APTR, // 197: 848
    pub Private9: APTR, // 198: 852
    pub Private10: APTR, // 199: 856
    pub Private11: APTR, // 200: 860
    pub Private12: APTR, // 201: 864
    pub Private13: APTR, // 202: 868
    pub Private14: APTR, // 203: 872
    pub Private15: APTR, // 204: 876
    pub Private16: APTR, // 205: 880
    pub Private17: APTR, // 206: 884
    pub Private18: APTR, // 207: 888
    pub Private19: APTR, // 208: 892
    pub Private20: APTR, // 209: 896
    pub Obsolete1_UNIMPLEMENTED: APTR, // 210: 900
    pub Obsolete2_UNIMPLEMENTED: APTR, // 211: 904
    pub Obsolete3_UNIMPLEMENTED: APTR, // 212: 908
    pub RMapAlloc: unsafe extern "C" fn(*mut ExecIFace, APTR, u32, u32) -> APTR, // 213: 912
    pub RMapFree: unsafe extern "C" fn(*mut ExecIFace, APTR, APTR, u32), // 214: 916
    pub Private21: APTR, // 215: 920
    pub Private22: APTR, // 216: 924
    pub Private23: APTR, // 217: 928
    pub AllocVecTagList: unsafe extern "C" fn(*mut ExecIFace, u32, *const TagItem) -> APTR, // 218: 932
    pub AllocVecTags: APTR, // 219: 936 (varargs)
    pub Private24: APTR, // 220: 940
    pub RMapExtAlloc: unsafe extern "C" fn(*mut ExecIFace, APTR, u32, u32, u32) -> APTR, // 221: 944
    pub RMapExtFree: unsafe extern "C" fn(*mut ExecIFace, APTR, APTR, u32), // 222: 948
    pub Private25: APTR, // 223: 952
    pub AllocNamedMemory: unsafe extern "C" fn(*mut ExecIFace, u32, CONST_STRPTR, CONST_STRPTR, *mut TagItem) -> APTR, // 224: 956
    pub AllocNamedMemoryTags: APTR, // 225: 960 (varargs)
    pub FreeNamedMemory: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR, CONST_STRPTR) -> u32, // 226: 964
    pub FindNamedMemory: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR, CONST_STRPTR) -> *mut (), // 227: 968
    pub UpdateNamedMemory: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR, CONST_STRPTR), // 228: 972
    pub LockNamedMemory: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR, CONST_STRPTR) -> *mut (), // 229: 976
    pub AttemptNamedMemory: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR, CONST_STRPTR) -> *mut (), // 230: 980
    pub UnlockNamedMemory: unsafe extern "C" fn(*mut ExecIFace, CONST_STRPTR, CONST_STRPTR), // 231: 984
    pub ScanNamedMemory: unsafe extern "C" fn(*mut ExecIFace, *mut Hook, u32, APTR) -> u32, // 232: 988
    pub AllocTaskMemEntry: unsafe extern "C" fn(*mut ExecIFace, *mut MemList) -> *mut MemList, // 233: 992
    pub Private26: APTR, // 234: 996
    pub Private27: APTR, // 235: 1000
    pub Private28: APTR, // 236: 1004
    pub Private29: APTR, // 237: 1008
    pub MutexObtain: unsafe extern "C" fn(*mut ExecIFace, APTR), // 238: 1012
    pub MutexAttempt: unsafe extern "C" fn(*mut ExecIFace, APTR) -> u32, // 239: 1016
    pub MutexRelease: unsafe extern "C" fn(*mut ExecIFace, APTR), // 240: 1020
    pub MutexAttemptWithSignal: unsafe extern "C" fn(*mut ExecIFace, APTR, u32) -> u32, // 241: 1024
    pub NewStackRun: unsafe extern "C" fn(*mut ExecIFace, APTR, *const TagItem) -> i32, // 242: 1028
    pub NewStackRunTags: APTR, // 243: 1032 (varargs)
    pub AttemptSemaphoreWithSignal: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore, u32) -> u32, // 244: 1036
    pub AttemptSemaphoreSharedWithSignal: unsafe extern "C" fn(*mut ExecIFace, *mut SignalSemaphore, u32) -> u32, // 245: 1040
    pub GetTaskAttrs: unsafe extern "C" fn(*mut ExecIFace, *mut Task, *const TagItem) -> i32, // 246: 1044
    pub GetTaskAttrsTags: APTR, // 247: 1048 (varargs)
    pub OBSOLETEMutexObtainDisable: unsafe extern "C" fn(*mut ExecIFace, APTR), // 248: 1052
    pub OBSOLETEMutexReleaseEnable: unsafe extern "C" fn(*mut ExecIFace, APTR), // 249: 1056
    pub FindResidentTagList: unsafe extern "C" fn(*mut ExecIFace, *const TagItem) -> *mut Resident, // 250: 1060
    pub FindResidentTags: APTR, // 251: 1064 (varargs)
    pub Private30: APTR, // 252: 1068
    pub Private31: APTR, // 253: 1072
    pub Private32: APTR, // 254: 1076
    pub Private33: APTR, // 255: 1080
    pub Private34: APTR, // 256: 1084
    pub Private35: APTR, // 257: 1088
    pub Private36: APTR, // 258: 1092
    pub Private37: APTR, // 259: 1096
    pub GetSystemInfo: unsafe extern "C" fn(*mut ExecIFace, *const TagItem), // 260: 1100
    pub GetSystemInfoTags: APTR, // 261: 1104 (varargs)
    pub Private38: APTR, // 262: 1108
    pub Private39: APTR, // 263: 1112
    pub Private40: APTR, // 264: 1116
    pub Private41: APTR, // 265: 1120
    pub SetTaskAffinity: unsafe extern "C" fn(*mut ExecIFace, *mut Task, *const TagItem), // 266: 1124
    pub SetTaskAffinityTags: APTR, // 267: 1128 (varargs)
}

