//! ExpansionIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ExpansionIFace (expansion.h) ----

#[repr(C)]
pub struct ExpansionIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ExpansionIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ExpansionIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub AddConfigDev: unsafe extern "C" fn(*mut ExpansionIFace, *mut ConfigDev), // 4: 76
    pub AddBootNode: unsafe extern "C" fn(*mut ExpansionIFace, i32, u32, APTR, *mut ConfigDev) -> u32, // 5: 80
    pub AllocBoardMem: unsafe extern "C" fn(*mut ExpansionIFace, u32) -> u32, // 6: 84
    pub AllocConfigDev: unsafe extern "C" fn(*mut ExpansionIFace) -> *mut ConfigDev, // 7: 88
    pub AllocExpansionMem: unsafe extern "C" fn(*mut ExpansionIFace, u32, u32) -> APTR, // 8: 92
    pub ConfigBoard: unsafe extern "C" fn(*mut ExpansionIFace, APTR, *mut ConfigDev) -> u32, // 9: 96
    pub ConfigChain: unsafe extern "C" fn(*mut ExpansionIFace, APTR) -> u32, // 10: 100
    pub FindConfigDev: unsafe extern "C" fn(*mut ExpansionIFace, *const ConfigDev, i32, i32) -> *mut ConfigDev, // 11: 104
    pub FreeBoardMem: unsafe extern "C" fn(*mut ExpansionIFace, u32, u32), // 12: 108
    pub FreeConfigDev: unsafe extern "C" fn(*mut ExpansionIFace, *mut ConfigDev), // 13: 112
    pub FreeExpansionMem: unsafe extern "C" fn(*mut ExpansionIFace, u32, u32), // 14: 116
    pub ReadExpansionByte: unsafe extern "C" fn(*mut ExpansionIFace, CONST_APTR, u32) -> u8, // 15: 120
    pub ReadExpansionRom: unsafe extern "C" fn(*mut ExpansionIFace, CONST_APTR, *mut ConfigDev) -> u32, // 16: 124
    pub RemConfigDev: unsafe extern "C" fn(*mut ExpansionIFace, *mut ConfigDev), // 17: 128
    pub WriteExpansionByte: unsafe extern "C" fn(*mut ExpansionIFace, APTR, u32, u8), // 18: 132
    pub ObtainConfigBinding: unsafe extern "C" fn(*mut ExpansionIFace), // 19: 136
    pub ReleaseConfigBinding: unsafe extern "C" fn(*mut ExpansionIFace), // 20: 140
    pub SetCurrentBinding: unsafe extern "C" fn(*mut ExpansionIFace, *mut CurrentBinding, u32), // 21: 144
    pub GetCurrentBinding: unsafe extern "C" fn(*mut ExpansionIFace, *const CurrentBinding, u32) -> u32, // 22: 148
    pub MakeDosNode: unsafe extern "C" fn(*mut ExpansionIFace, CONST_APTR) -> *mut DeviceNode, // 23: 152
    pub AddDosNode: unsafe extern "C" fn(*mut ExpansionIFace, i32, u32, *mut DeviceNode) -> u32, // 24: 156
    pub WriteExpansionWord: unsafe extern "C" fn(*mut ExpansionIFace, APTR, u32, u16), // 25: 160
    pub GetMachineInfo: unsafe extern "C" fn(*mut ExpansionIFace, *const TagItem) -> u32, // 26: 164
    pub GetMachineInfoTags: APTR, // 27: 168 (varargs)
}

