//! ExpatIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ExpatIFace (expat.h) ----

#[repr(C)]
pub struct ExpatIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ExpatIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ExpatIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub XML_ParserCreate: unsafe extern "C" fn(*mut ExpatIFace, *const APTR) -> APTR, // 4: 76
    pub XML_ParserCreateNS: unsafe extern "C" fn(*mut ExpatIFace, *const APTR, APTR) -> APTR, // 5: 80
    pub XML_ParserCreate_MM: unsafe extern "C" fn(*mut ExpatIFace, *const APTR, *const APTR, *const APTR) -> APTR, // 6: 84
    pub XML_ExternalEntityParserCreate: unsafe extern "C" fn(*mut ExpatIFace, APTR, *const APTR, *const APTR) -> APTR, // 7: 88
    pub XML_ParserFree: unsafe extern "C" fn(*mut ExpatIFace, APTR), // 8: 92
    pub XML_Parse: unsafe extern "C" fn(*mut ExpatIFace, APTR, *const APTR, i32, i32) -> APTR, // 9: 96
    pub XML_ParseBuffer: unsafe extern "C" fn(*mut ExpatIFace, APTR, i32, i32) -> APTR, // 10: 100
    pub XML_GetBuffer: unsafe extern "C" fn(*mut ExpatIFace, APTR, i32) -> *mut (), // 11: 104
    pub XML_SetStartElementHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 12: 108
    pub XML_SetEndElementHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 13: 112
    pub XML_SetElementHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR, APTR), // 14: 116
    pub XML_SetCharacterDataHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 15: 120
    pub XML_SetProcessingInstructionHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 16: 124
    pub XML_SetCommentHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 17: 128
    pub XML_SetStartCdataSectionHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 18: 132
    pub XML_SetEndCdataSectionHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 19: 136
    pub XML_SetCdataSectionHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR, APTR), // 20: 140
    pub XML_SetDefaultHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 21: 144
    pub XML_SetDefaultHandlerExpand: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 22: 148
    pub XML_SetExternalEntityRefHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 23: 152
    pub XML_SetExternalEntityRefHandlerArg: unsafe extern "C" fn(*mut ExpatIFace, APTR, *mut ()), // 24: 156
    pub XML_SetUnknownEncodingHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR, *mut ()), // 25: 160
    pub XML_SetStartNamespaceDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 26: 164
    pub XML_SetEndNamespaceDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 27: 168
    pub XML_SetNamespaceDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR, APTR), // 28: 172
    pub XML_SetXmlDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 29: 176
    pub XML_SetStartDoctypeDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 30: 180
    pub XML_SetEndDoctypeDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 31: 184
    pub XML_SetDoctypeDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR, APTR), // 32: 188
    pub XML_SetElementDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 33: 192
    pub XML_SetAttlistDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 34: 196
    pub XML_SetEntityDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 35: 200
    pub XML_SetUnparsedEntityDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 36: 204
    pub XML_SetNotationDeclHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 37: 208
    pub XML_SetNotStandaloneHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 38: 212
    pub XML_GetErrorCode: unsafe extern "C" fn(*mut ExpatIFace, APTR) -> APTR, // 39: 216
    pub XML_ErrorString: unsafe extern "C" fn(*mut ExpatIFace, APTR) -> *const APTR, // 40: 220
    pub XML_GetCurrentByteIndex: unsafe extern "C" fn(*mut ExpatIFace, APTR) -> i32, // 41: 224
    pub XML_GetCurrentLineNumber: unsafe extern "C" fn(*mut ExpatIFace, APTR) -> i32, // 42: 228
    pub XML_GetCurrentColumnNumber: unsafe extern "C" fn(*mut ExpatIFace, APTR) -> i32, // 43: 232
    pub XML_GetCurrentByteCount: unsafe extern "C" fn(*mut ExpatIFace, APTR) -> i32, // 44: 236
    pub XML_GetInputContext: unsafe extern "C" fn(*mut ExpatIFace, APTR, *mut i32, *mut i32) -> *const APTR, // 45: 240
    pub XML_SetUserData: unsafe extern "C" fn(*mut ExpatIFace, APTR, *mut ()), // 46: 244
    pub XML_DefaultCurrent: unsafe extern "C" fn(*mut ExpatIFace, APTR), // 47: 248
    pub XML_UseParserAsHandlerArg: unsafe extern "C" fn(*mut ExpatIFace, APTR), // 48: 252
    pub XML_SetBase: unsafe extern "C" fn(*mut ExpatIFace, APTR, *const APTR) -> APTR, // 49: 256
    pub XML_GetBase: unsafe extern "C" fn(*mut ExpatIFace, APTR) -> *const APTR, // 50: 260
    pub XML_GetSpecifiedAttributeCount: unsafe extern "C" fn(*mut ExpatIFace, APTR) -> i32, // 51: 264
    pub XML_GetIdAttributeIndex: unsafe extern "C" fn(*mut ExpatIFace, APTR) -> i32, // 52: 268
    pub XML_SetEncoding: unsafe extern "C" fn(*mut ExpatIFace, APTR, *const APTR) -> APTR, // 53: 272
    pub XML_SetParamEntityParsing: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR) -> i32, // 54: 276
    pub XML_SetReturnNSTriplet: unsafe extern "C" fn(*mut ExpatIFace, APTR, i32), // 55: 280
    pub XML_ExpatVersion: unsafe extern "C" fn(*mut ExpatIFace) -> *const APTR, // 56: 284
    pub XML_ExpatVersionInfo: unsafe extern "C" fn(*mut ExpatIFace) -> APTR, // 57: 288
    pub XML_ParserReset: unsafe extern "C" fn(*mut ExpatIFace, APTR, *const APTR) -> APTR, // 58: 292
    pub XML_SetSkippedEntityHandler: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR), // 59: 296
    pub XML_UseForeignDTD: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR) -> APTR, // 60: 300
    pub XML_GetFeatureList: unsafe extern "C" fn(*mut ExpatIFace) -> *const APTR, // 61: 304
    pub XML_StopParser: unsafe extern "C" fn(*mut ExpatIFace, APTR, APTR) -> APTR, // 62: 308
    pub XML_ResumeParser: unsafe extern "C" fn(*mut ExpatIFace, APTR) -> APTR, // 63: 312
    pub XML_GetParsingStatus: unsafe extern "C" fn(*mut ExpatIFace, APTR, *mut APTR), // 64: 316
    pub XML_FreeContentModel: unsafe extern "C" fn(*mut ExpatIFace, APTR, *mut APTR), // 65: 320
    pub XML_MemMalloc: unsafe extern "C" fn(*mut ExpatIFace, APTR, u32) -> *mut (), // 66: 324
    pub XML_MemRealloc: unsafe extern "C" fn(*mut ExpatIFace, APTR, *mut (), u32) -> *mut (), // 67: 328
    pub XML_MemFree: unsafe extern "C" fn(*mut ExpatIFace, APTR, *mut ()), // 68: 332
    pub XML_SetHashSalt: unsafe extern "C" fn(*mut ExpatIFace, APTR, u32) -> i32, // 69: 336
}

