//! FileSysBoxIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- FileSysBoxIFace (filesysbox.h) ----

#[repr(C)]
pub struct FileSysBoxIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut FileSysBoxIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut FileSysBoxIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub FbxQueryMountMsg: unsafe extern "C" fn(*mut FileSysBoxIFace, *mut Message, i32) -> APTR, // 4: 76
    pub FbxSetupFS: unsafe extern "C" fn(*mut FileSysBoxIFace, *mut Message, *const TagItem, *const fuse_operations, i32, APTR) -> *mut FbxFS, // 5: 80
    pub FbxEventLoop: unsafe extern "C" fn(*mut FileSysBoxIFace, *mut FbxFS) -> i32, // 6: 84
    pub FbxCleanupFS: unsafe extern "C" fn(*mut FileSysBoxIFace, *mut FbxFS), // 7: 88
    pub FbxReturnMountMsg: unsafe extern "C" fn(*mut FileSysBoxIFace, *mut Message, i32, i32), // 8: 92
    pub FbxFuseVersion: unsafe extern "C" fn(*mut FileSysBoxIFace) -> i32, // 9: 96
    pub FbxVersion: unsafe extern "C" fn(*mut FileSysBoxIFace) -> i32, // 10: 100
    pub FbxSetupFSTags: APTR, // 11: 104 (varargs)
    pub FbxSetSignalCallback: unsafe extern "C" fn(*mut FileSysBoxIFace, *mut FbxFS, APTR, u32), // 12: 108
    pub FbxInstallTimerCallback: unsafe extern "C" fn(*mut FileSysBoxIFace, *mut FbxFS, APTR, u32) -> *mut FbxTimerCallbackData, // 13: 112
    pub FbxUninstallTimerCallback: unsafe extern "C" fn(*mut FileSysBoxIFace, *mut FbxFS, *mut FbxTimerCallbackData), // 14: 116
    pub FbxSignalDiskChange: unsafe extern "C" fn(*mut FileSysBoxIFace, *mut FbxFS), // 15: 120
    pub FbxQueryFS: unsafe extern "C" fn(*mut FileSysBoxIFace, *mut FbxFS, *const TagItem), // 16: 124
    pub FbxQueryFSTags: APTR, // 17: 128 (varargs)
    pub FbxGetSysTime: unsafe extern "C" fn(*mut FileSysBoxIFace, *mut FbxFS, *mut TimeVal), // 18: 132
}

