//! FillerIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- FillerIFace (filler.h) ----

#[repr(C)]
pub struct FillerIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut FillerIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut FillerIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut FillerIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut FillerIFace) -> *mut Interface, // 3: 72
    pub FILLER_GetClass: unsafe extern "C" fn(*mut FillerIFace) -> *mut APTR, // 4: 76
}

