//! GadToolsIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- GadToolsIFace (gadtools.h) ----

#[repr(C)]
pub struct GadToolsIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut GadToolsIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut GadToolsIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut GadToolsIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut GadToolsIFace) -> *mut Interface, // 3: 72
    pub CreateGadgetA: unsafe extern "C" fn(*mut GadToolsIFace, u32, *mut Gadget, *const NewGadget, *const TagItem) -> *mut Gadget, // 4: 76
    pub CreateGadget: APTR, // 5: 80 (varargs)
    pub FreeGadgets: unsafe extern "C" fn(*mut GadToolsIFace, *mut Gadget), // 6: 84
    pub GT_SetGadgetAttrsA: unsafe extern "C" fn(*mut GadToolsIFace, *mut Gadget, *mut Window, *mut Requester, *const TagItem), // 7: 88
    pub GT_SetGadgetAttrs: APTR, // 8: 92 (varargs)
    pub CreateMenusA: unsafe extern "C" fn(*mut GadToolsIFace, *const NewMenu, *const TagItem) -> *mut Menu, // 9: 96
    pub CreateMenus: APTR, // 10: 100 (varargs)
    pub FreeMenus: unsafe extern "C" fn(*mut GadToolsIFace, *mut Menu), // 11: 104
    pub LayoutMenuItemsA: unsafe extern "C" fn(*mut GadToolsIFace, *mut MenuItem, APTR, *const TagItem) -> u32, // 12: 108
    pub LayoutMenuItems: APTR, // 13: 112 (varargs)
    pub LayoutMenusA: unsafe extern "C" fn(*mut GadToolsIFace, *mut Menu, APTR, *const TagItem) -> u32, // 14: 116
    pub LayoutMenus: APTR, // 15: 120 (varargs)
    pub GT_GetIMsg: unsafe extern "C" fn(*mut GadToolsIFace, *mut MsgPort) -> *mut IntuiMessage, // 16: 124
    pub GT_ReplyIMsg: unsafe extern "C" fn(*mut GadToolsIFace, *mut IntuiMessage), // 17: 128
    pub GT_RefreshWindow: unsafe extern "C" fn(*mut GadToolsIFace, *mut Window, *mut Requester), // 18: 132
    pub GT_BeginRefresh: unsafe extern "C" fn(*mut GadToolsIFace, *mut Window), // 19: 136
    pub GT_EndRefresh: unsafe extern "C" fn(*mut GadToolsIFace, *mut Window, u32), // 20: 140
    pub GT_FilterIMsg: unsafe extern "C" fn(*mut GadToolsIFace, *const IntuiMessage) -> *mut IntuiMessage, // 21: 144
    pub GT_PostFilterIMsg: unsafe extern "C" fn(*mut GadToolsIFace, *mut IntuiMessage) -> *mut IntuiMessage, // 22: 148
    pub CreateContext: unsafe extern "C" fn(*mut GadToolsIFace, *mut *mut Gadget) -> *mut Gadget, // 23: 152
    pub DrawBevelBoxA: unsafe extern "C" fn(*mut GadToolsIFace, *mut RastPort, i16, i16, i16, i16, *const TagItem), // 24: 156
    pub DrawBevelBox: APTR, // 25: 160 (varargs)
    pub GetVisualInfoA: unsafe extern "C" fn(*mut GadToolsIFace, *mut Screen, *const TagItem) -> APTR, // 26: 164
    pub GetVisualInfo: APTR, // 27: 168 (varargs)
    pub FreeVisualInfo: unsafe extern "C" fn(*mut GadToolsIFace, APTR), // 28: 172
    pub GTReserved0: unsafe extern "C" fn(*mut GadToolsIFace), // 29: 176
    pub GTReserved1: unsafe extern "C" fn(*mut GadToolsIFace), // 30: 180
    pub GTReserved2: unsafe extern "C" fn(*mut GadToolsIFace), // 31: 184
    pub GTReserved3: unsafe extern "C" fn(*mut GadToolsIFace), // 32: 188
    pub GTReserved4: unsafe extern "C" fn(*mut GadToolsIFace), // 33: 192
    pub GTReserved5: unsafe extern "C" fn(*mut GadToolsIFace), // 34: 196
    pub GT_GetGadgetAttrsA: unsafe extern "C" fn(*mut GadToolsIFace, *mut Gadget, *mut Window, *mut Requester, *const TagItem) -> i32, // 35: 200
    pub GT_GetGadgetAttrs: APTR, // 36: 204 (varargs)
}

