//! GetColorIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- GetColorIFace (getcolor.h) ----

#[repr(C)]
pub struct GetColorIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut GetColorIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut GetColorIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut GetColorIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut GetColorIFace) -> *mut Interface, // 3: 72
    pub GETCOLOR_GetClass: unsafe extern "C" fn(*mut GetColorIFace) -> *mut APTR, // 4: 76
}

