//! GetScreenModeIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- GetScreenModeIFace (getscreenmode.h) ----

#[repr(C)]
pub struct GetScreenModeIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut GetScreenModeIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut GetScreenModeIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut GetScreenModeIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut GetScreenModeIFace) -> *mut Interface, // 3: 72
    pub GETSCREENMODE_GetClass: unsafe extern "C" fn(*mut GetScreenModeIFace) -> *mut APTR, // 4: 76
}

