//! HunkIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- HunkIFace (hunk.h) ----

#[repr(C)]
pub struct HunkIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut HunkIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut HunkIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut HunkIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut HunkIFace) -> *mut Interface, // 3: 72
    pub LoadHunk: unsafe extern "C" fn(*mut HunkIFace, *const TagItem) -> u32, // 4: 76
    pub LoadHunkTags: APTR, // 5: 80 (varargs)
    pub UnLoadHunk: unsafe extern "C" fn(*mut HunkIFace, *const TagItem), // 6: 84
    pub UnLoadHunkTags: APTR, // 7: 88 (varargs)
}

