//! I2CIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- I2CIFace (i2c.h) ----

#[repr(C)]
pub struct I2CIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut I2CIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut I2CIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub Probe: unsafe extern "C" fn(*mut I2CIFace, u32) -> u32, // 4: 76
    pub SetSpeed: unsafe extern "C" fn(*mut I2CIFace, u32) -> u32, // 5: 80
    pub Read: unsafe extern "C" fn(*mut I2CIFace, u32, u32, *mut u8, u32) -> i32, // 6: 84
    pub ReadTagList: unsafe extern "C" fn(*mut I2CIFace, u32, u32, *mut u8, u32, *mut TagItem) -> i32, // 7: 88
    pub ReadTags: APTR, // 8: 92 (varargs)
    pub Write: unsafe extern "C" fn(*mut I2CIFace, u32, u32, *mut u8, u32) -> i32, // 9: 96
    pub WriteTagList: unsafe extern "C" fn(*mut I2CIFace, u32, u32, *mut u8, u32, *mut TagItem) -> i32, // 10: 100
    pub WriteTags: APTR, // 11: 104 (varargs)
    pub GetName: unsafe extern "C" fn(*mut I2CIFace) -> STRPTR, // 12: 108
    pub GetDeviceId: unsafe extern "C" fn(*mut I2CIFace, u32) -> u32, // 13: 112
    pub Lock: unsafe extern "C" fn(*mut I2CIFace), // 14: 116
    pub Unlock: unsafe extern "C" fn(*mut I2CIFace), // 15: 120
}

