//! I2CResourceIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// Forward declarations for cross-interface references
#[repr(C)]
pub struct I2CIFace { _opaque: [u8; 0] }

// ---- I2CResourceIFace (i2c.h) ----

#[repr(C)]
pub struct I2CResourceIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut I2CResourceIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut I2CResourceIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub GetBusByNumber: unsafe extern "C" fn(*mut I2CResourceIFace, u32) -> *mut I2CIFace, // 4: 76
    pub GetBusByName: unsafe extern "C" fn(*mut I2CResourceIFace, CONST_STRPTR) -> *mut I2CIFace, // 5: 80
}

