//! IconIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- IconIFace (icon.h) ----

#[repr(C)]
pub struct IconIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut IconIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut IconIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut IconIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut IconIFace) -> *mut Interface, // 3: 72
    pub Private1: APTR, // 4: 76
    pub Private2: APTR, // 5: 80
    pub Private3: APTR, // 6: 84
    pub Private4: APTR, // 7: 88
    pub FreeFreeList: unsafe extern "C" fn(*mut IconIFace, *mut FreeList), // 8: 92
    pub Private5: APTR, // 9: 96
    pub Private6: APTR, // 10: 100
    pub AddFreeList: unsafe extern "C" fn(*mut IconIFace, *mut FreeList, CONST_APTR, u32) -> u32, // 11: 104
    pub GetDiskObject: unsafe extern "C" fn(*mut IconIFace, CONST_STRPTR) -> *mut DiskObject, // 12: 108
    pub PutDiskObject: unsafe extern "C" fn(*mut IconIFace, CONST_STRPTR, *mut APTR) -> u32, // 13: 112
    pub FreeDiskObject: unsafe extern "C" fn(*mut IconIFace, *mut DiskObject), // 14: 116
    pub FindToolType: unsafe extern "C" fn(*mut IconIFace, *mut STRPTR, CONST_STRPTR) -> STRPTR, // 15: 120
    pub MatchToolValue: unsafe extern "C" fn(*mut IconIFace, CONST_STRPTR, CONST_STRPTR) -> u32, // 16: 124
    pub BumpRevision: unsafe extern "C" fn(*mut IconIFace, STRPTR, CONST_STRPTR) -> STRPTR, // 17: 128
    pub FreeAlloc: unsafe extern "C" fn(*mut IconIFace, *mut FreeList, u32, u32) -> APTR, // 18: 132
    pub GetDefDiskObject: unsafe extern "C" fn(*mut IconIFace, i32) -> *mut DiskObject, // 19: 136
    pub PutDefDiskObject: unsafe extern "C" fn(*mut IconIFace, *mut APTR) -> u32, // 20: 140
    pub GetDiskObjectNew: unsafe extern "C" fn(*mut IconIFace, CONST_STRPTR) -> *mut DiskObject, // 21: 144
    pub DeleteDiskObject: unsafe extern "C" fn(*mut IconIFace, CONST_STRPTR) -> u32, // 22: 148
    pub FreeFree: unsafe extern "C" fn(*mut IconIFace, *mut FreeList, APTR) -> u32, // 23: 152
    pub DupDiskObjectA: unsafe extern "C" fn(*mut IconIFace, *mut APTR, *mut APTR) -> *mut DiskObject, // 24: 156
    pub DupDiskObject: APTR, // 25: 160 (varargs)
    pub IconControlA: unsafe extern "C" fn(*mut IconIFace, *mut DiskObject, *mut APTR) -> u32, // 26: 164
    pub IconControl: APTR, // 27: 168 (varargs)
    pub DrawIconStateA: unsafe extern "C" fn(*mut IconIFace, *mut RastPort, *mut APTR, CONST_STRPTR, i32, i32, u32, *mut APTR), // 28: 172
    pub DrawIconState: APTR, // 29: 176 (varargs)
    pub GetIconRectangleA: unsafe extern "C" fn(*mut IconIFace, *mut RastPort, *mut APTR, CONST_STRPTR, *mut Rectangle, *mut APTR) -> u32, // 30: 180
    pub GetIconRectangle: APTR, // 31: 184 (varargs)
    pub NewDiskObject: unsafe extern "C" fn(*mut IconIFace, i32) -> *mut DiskObject, // 32: 188
    pub GetIconTagList: unsafe extern "C" fn(*mut IconIFace, CONST_STRPTR, *mut APTR) -> *mut DiskObject, // 33: 192
    pub GetIconTags: APTR, // 34: 196 (varargs)
    pub PutIconTagList: unsafe extern "C" fn(*mut IconIFace, CONST_STRPTR, *mut APTR, *mut APTR) -> u32, // 35: 200
    pub PutIconTags: APTR, // 36: 204 (varargs)
    pub LayoutIconA: unsafe extern "C" fn(*mut IconIFace, *mut DiskObject, *mut Screen, *mut APTR) -> u32, // 37: 208
    pub LayoutIcon: APTR, // 38: 212 (varargs)
    pub ChangeToSelectedIconColor: unsafe extern "C" fn(*mut IconIFace, *mut ColorRegister), // 39: 216
    pub BumpRevisionLength: unsafe extern "C" fn(*mut IconIFace, STRPTR, CONST_STRPTR, u32) -> STRPTR, // 40: 220
}

