//! IFFParseIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- IFFParseIFace (iffparse.h) ----

#[repr(C)]
pub struct IFFParseIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut IFFParseIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut IFFParseIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut IFFParseIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut IFFParseIFace) -> *mut Interface, // 3: 72
    pub AllocIFF: unsafe extern "C" fn(*mut IFFParseIFace) -> *mut IFFHandle, // 4: 76
    pub OpenIFF: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, i32) -> i32, // 5: 80
    pub ParseIFF: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, i32) -> i32, // 6: 84
    pub CloseIFF: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle), // 7: 88
    pub FreeIFF: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle), // 8: 92
    pub ReadChunkBytes: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, APTR, i32) -> i32, // 9: 96
    pub WriteChunkBytes: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, CONST_APTR, i32) -> i32, // 10: 100
    pub ReadChunkRecords: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, APTR, i32, i32) -> i32, // 11: 104
    pub WriteChunkRecords: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, CONST_APTR, i32, i32) -> i32, // 12: 108
    pub PushChunk: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, i32, i32, i32) -> i32, // 13: 112
    pub PopChunk: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle) -> i32, // 14: 116
    pub EntryHandler: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, i32, i32, i32, *mut Hook, APTR) -> i32, // 15: 120
    pub ExitHandler: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, i32, i32, i32, *mut Hook, APTR) -> i32, // 16: 124
    pub PropChunk: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, i32, i32) -> i32, // 17: 128
    pub PropChunks: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, *const i32, i32) -> i32, // 18: 132
    pub StopChunk: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, i32, i32) -> i32, // 19: 136
    pub StopChunks: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, *const i32, i32) -> i32, // 20: 140
    pub CollectionChunk: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, i32, i32) -> i32, // 21: 144
    pub CollectionChunks: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, *const i32, i32) -> i32, // 22: 148
    pub StopOnExit: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, i32, i32) -> i32, // 23: 152
    pub FindProp: unsafe extern "C" fn(*mut IFFParseIFace, *const IFFHandle, i32, i32) -> *mut StoredProperty, // 24: 156
    pub FindCollection: unsafe extern "C" fn(*mut IFFParseIFace, *const IFFHandle, i32, i32) -> *mut CollectionItem, // 25: 160
    pub FindPropContext: unsafe extern "C" fn(*mut IFFParseIFace, *const IFFHandle) -> *mut ContextNode, // 26: 164
    pub CurrentChunk: unsafe extern "C" fn(*mut IFFParseIFace, *const IFFHandle) -> *mut ContextNode, // 27: 168
    pub ParentChunk: unsafe extern "C" fn(*mut IFFParseIFace, *const ContextNode) -> *mut ContextNode, // 28: 172
    pub AllocLocalItem: unsafe extern "C" fn(*mut IFFParseIFace, i32, i32, i32, i32) -> *mut LocalContextItem, // 29: 176
    pub LocalItemData: unsafe extern "C" fn(*mut IFFParseIFace, *const LocalContextItem) -> APTR, // 30: 180
    pub SetLocalItemPurge: unsafe extern "C" fn(*mut IFFParseIFace, *mut LocalContextItem, *const Hook), // 31: 184
    pub FreeLocalItem: unsafe extern "C" fn(*mut IFFParseIFace, *mut LocalContextItem), // 32: 188
    pub FindLocalItem: unsafe extern "C" fn(*mut IFFParseIFace, *const IFFHandle, i32, i32, i32) -> *mut LocalContextItem, // 33: 192
    pub StoreLocalItem: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, *mut LocalContextItem, i32) -> i32, // 34: 196
    pub StoreItemInContext: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, *mut LocalContextItem, *mut ContextNode), // 35: 200
    pub InitIFF: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle, i32, *const Hook), // 36: 204
    pub InitIFFasDOS: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle), // 37: 208
    pub InitIFFasClip: unsafe extern "C" fn(*mut IFFParseIFace, *mut IFFHandle), // 38: 212
    pub OpenClipboard: unsafe extern "C" fn(*mut IFFParseIFace, i32) -> *mut ClipboardHandle, // 39: 216
    pub CloseClipboard: unsafe extern "C" fn(*mut IFFParseIFace, *mut ClipboardHandle), // 40: 220
    pub GoodID: unsafe extern "C" fn(*mut IFFParseIFace, i32) -> i32, // 41: 224
    pub GoodType: unsafe extern "C" fn(*mut IFFParseIFace, i32) -> i32, // 42: 228
    pub IDtoStr: unsafe extern "C" fn(*mut IFFParseIFace, i32, STRPTR) -> STRPTR, // 43: 232
}

