//! IntegerIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- IntegerIFace (integer.h) ----

#[repr(C)]
pub struct IntegerIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut IntegerIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut IntegerIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut IntegerIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut IntegerIFace) -> *mut Interface, // 3: 72
    pub INTEGER_GetClass: unsafe extern "C" fn(*mut IntegerIFace) -> *mut APTR, // 4: 76
}

