//! IntuitionIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- IntuitionIFace (intuition.h) ----

#[repr(C)]
pub struct IntuitionIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut IntuitionIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut IntuitionIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut IntuitionIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut IntuitionIFace) -> *mut Interface, // 3: 72
    pub OpenIntuition: unsafe extern "C" fn(*mut IntuitionIFace), // 4: 76
    pub Intuition: unsafe extern "C" fn(*mut IntuitionIFace, *mut InputEvent), // 5: 80
    pub AddGadget: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut Gadget, u16) -> u16, // 6: 84
    pub ClearDMRequest: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window) -> u32, // 7: 88
    pub ClearMenuStrip: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window), // 8: 92
    pub ClearPointer: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window), // 9: 96
    pub CloseScreen: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen) -> u32, // 10: 100
    pub CloseWindow: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window), // 11: 104
    pub CloseWorkBench: unsafe extern "C" fn(*mut IntuitionIFace) -> i32, // 12: 108
    pub CurrentTime: unsafe extern "C" fn(*mut IntuitionIFace, *mut u32, *mut u32), // 13: 112
    pub DisplayAlert: unsafe extern "C" fn(*mut IntuitionIFace, u32, CONST_STRPTR, u16) -> u32, // 14: 116
    pub DisplayBeep: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen), // 15: 120
    pub DoubleClick: unsafe extern "C" fn(*mut IntuitionIFace, u32, u32, u32, u32) -> u32, // 16: 124
    pub DrawBorder: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, *const Border, i16, i16), // 17: 128
    pub DrawImage: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, *mut Image, i16, i16), // 18: 132
    pub EndRequest: unsafe extern "C" fn(*mut IntuitionIFace, *mut Requester, *mut Window), // 19: 136
    pub GetDefPrefs: unsafe extern "C" fn(*mut IntuitionIFace, *mut Preferences, i16) -> *mut Preferences, // 20: 140
    pub GetPrefs: unsafe extern "C" fn(*mut IntuitionIFace, *mut Preferences, i16) -> *mut Preferences, // 21: 144
    pub InitRequester: unsafe extern "C" fn(*mut IntuitionIFace, *mut Requester), // 22: 148
    pub ItemAddress: unsafe extern "C" fn(*mut IntuitionIFace, *const Menu, u16) -> *mut MenuItem, // 23: 152
    pub ModifyIDCMP: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, u32) -> u32, // 24: 156
    pub ModifyProp: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, *mut Window, *mut Requester, u16, u16, u16, u16, u16), // 25: 160
    pub MoveScreen: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, i16, i16), // 26: 164
    pub MoveWindow: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, i16, i16), // 27: 168
    pub OffGadget: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, *mut Window, *mut Requester), // 28: 172
    pub OffMenu: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, u16), // 29: 176
    pub OnGadget: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, *mut Window, *mut Requester), // 30: 180
    pub OnMenu: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, u16), // 31: 184
    pub OpenScreen: unsafe extern "C" fn(*mut IntuitionIFace, *const NewScreen) -> *mut Screen, // 32: 188
    pub OpenWindow: unsafe extern "C" fn(*mut IntuitionIFace, *const NewWindow) -> *mut Window, // 33: 192
    pub OpenWorkBench: unsafe extern "C" fn(*mut IntuitionIFace) -> u32, // 34: 196
    pub PrintIText: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, *const IntuiText, i16, i16), // 35: 200
    pub RefreshGadgets: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, *mut Window, *mut Requester), // 36: 204
    pub RemoveGadget: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut Gadget) -> u16, // 37: 208
    pub ReportMouse: unsafe extern "C" fn(*mut IntuitionIFace, u32, *mut Window), // 38: 212
    pub ReportMouse1: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, u32), // 39: 216
    pub Request: unsafe extern "C" fn(*mut IntuitionIFace, *mut Requester, *mut Window) -> u32, // 40: 220
    pub ScreenToBack: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen), // 41: 224
    pub ScreenToFront: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen), // 42: 228
    pub SetDMRequest: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut Requester) -> u32, // 43: 232
    pub SetMenuStrip: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut Menu) -> u32, // 44: 236
    pub SetPointer: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut u16, i16, i16, i16, i16), // 45: 240
    pub SetWindowTitles: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, CONST_STRPTR, CONST_STRPTR), // 46: 244
    pub ShowTitle: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, u32), // 47: 248
    pub SizeWindow: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, i16, i16), // 48: 252
    pub ViewAddress: unsafe extern "C" fn(*mut IntuitionIFace) -> *mut View, // 49: 256
    pub ViewPortAddress: unsafe extern "C" fn(*mut IntuitionIFace, *const Window) -> *mut ViewPort, // 50: 260
    pub WindowToBack: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window), // 51: 264
    pub WindowToFront: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window), // 52: 268
    pub WindowLimits: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, i32, i32, u32, u32) -> u32, // 53: 272
    pub SetPrefs: unsafe extern "C" fn(*mut IntuitionIFace, *const Preferences, i32, u32) -> *mut Preferences, // 54: 276
    pub IntuiTextLength: unsafe extern "C" fn(*mut IntuitionIFace, *const IntuiText) -> i32, // 55: 280
    pub WBenchToBack: unsafe extern "C" fn(*mut IntuitionIFace) -> u32, // 56: 284
    pub WBenchToFront: unsafe extern "C" fn(*mut IntuitionIFace) -> u32, // 57: 288
    pub AutoRequest: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *const IntuiText, *const IntuiText, *const IntuiText, u32, u32, u16, u16) -> u32, // 58: 292
    pub BeginRefresh: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window), // 59: 296
    pub BuildSysRequest: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *const IntuiText, *const IntuiText, *const IntuiText, u32, u16, u16) -> *mut Window, // 60: 300
    pub EndRefresh: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, i32), // 61: 304
    pub FreeSysRequest: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window), // 62: 308
    pub MakeScreen: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen) -> i32, // 63: 312
    pub RemakeDisplay: unsafe extern "C" fn(*mut IntuitionIFace) -> i32, // 64: 316
    pub RethinkDisplay: unsafe extern "C" fn(*mut IntuitionIFace) -> i32, // 65: 320
    pub AllocRemember: unsafe extern "C" fn(*mut IntuitionIFace, *mut *mut Remember, u32, u32) -> APTR, // 66: 324
    pub AlohaWorkbench: unsafe extern "C" fn(*mut IntuitionIFace, i32), // 67: 328
    pub FreeRemember: unsafe extern "C" fn(*mut IntuitionIFace, *mut *mut Remember, u32), // 68: 332
    pub LockIBase: unsafe extern "C" fn(*mut IntuitionIFace, u32) -> u32, // 69: 336
    pub UnlockIBase: unsafe extern "C" fn(*mut IntuitionIFace, u32), // 70: 340
    pub GetScreenData: unsafe extern "C" fn(*mut IntuitionIFace, APTR, u16, u16, *const Screen) -> i32, // 71: 344
    pub RefreshGList: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, *mut Window, *mut Requester, i16), // 72: 348
    pub AddGList: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut Gadget, u16, i16, *mut Requester) -> u16, // 73: 352
    pub RemoveGList: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut Gadget, i16) -> u16, // 74: 356
    pub ActivateWindow: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window), // 75: 360
    pub RefreshWindowFrame: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window), // 76: 364
    pub ActivateGadget: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, *mut Window, *mut Requester) -> u32, // 77: 368
    pub NewModifyProp: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, *mut Window, *mut Requester, u16, u16, u16, u16, u16, i16), // 78: 372
    pub QueryOverscan: unsafe extern "C" fn(*mut IntuitionIFace, u32, *mut Rectangle, i16) -> i32, // 79: 376
    pub MoveWindowInFrontOf: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut Window), // 80: 380
    pub ChangeWindowBox: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, i16, i16, i16, i16), // 81: 384
    pub SetEditHook: unsafe extern "C" fn(*mut IntuitionIFace, *mut Hook) -> *mut Hook, // 82: 388
    pub SetMouseQueue: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, u16) -> i32, // 83: 392
    pub ZipWindow: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window), // 84: 396
    pub LockPubScreen: unsafe extern "C" fn(*mut IntuitionIFace, CONST_STRPTR) -> *mut Screen, // 85: 400
    pub UnlockPubScreen: unsafe extern "C" fn(*mut IntuitionIFace, CONST_STRPTR, *mut Screen), // 86: 404
    pub LockPubScreenList: unsafe extern "C" fn(*mut IntuitionIFace) -> *mut List, // 87: 408
    pub UnlockPubScreenList: unsafe extern "C" fn(*mut IntuitionIFace), // 88: 412
    pub NextPubScreen: unsafe extern "C" fn(*mut IntuitionIFace, *const Screen, STRPTR) -> STRPTR, // 89: 416
    pub SetDefaultPubScreen: unsafe extern "C" fn(*mut IntuitionIFace, CONST_STRPTR), // 90: 420
    pub SetPubScreenModes: unsafe extern "C" fn(*mut IntuitionIFace, u16) -> u16, // 91: 424
    pub PubScreenStatus: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, u16) -> u16, // 92: 428
    pub ObtainGIRPort: unsafe extern "C" fn(*mut IntuitionIFace, *mut GadgetInfo) -> *mut RastPort, // 93: 432
    pub ReleaseGIRPort: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort), // 94: 436
    pub GadgetMouse: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, *mut GadgetInfo, *mut i16), // 95: 440
    pub SetIPrefs: unsafe extern "C" fn(*mut IntuitionIFace, APTR, i32, i32) -> APTR, // 96: 444
    pub GetDefaultPubScreen: unsafe extern "C" fn(*mut IntuitionIFace, STRPTR), // 97: 448
    pub EasyRequestArgs: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *const EasyStruct, *mut u32, APTR) -> i32, // 98: 452
    pub EasyRequest: APTR, // 99: 456 (varargs)
    pub BuildEasyRequestArgs: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *const EasyStruct, u32, APTR) -> *mut Window, // 100: 460
    pub BuildEasyRequest: APTR, // 101: 464 (varargs)
    pub SysReqHandler: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut u32, u32) -> i32, // 102: 468
    pub OpenWindowTagList: unsafe extern "C" fn(*mut IntuitionIFace, *const NewWindow, *const TagItem) -> *mut Window, // 103: 472
    pub OpenWindowTags: APTR, // 104: 476 (varargs)
    pub OpenScreenTagList: unsafe extern "C" fn(*mut IntuitionIFace, *const NewScreen, *const TagItem) -> *mut Screen, // 105: 480
    pub OpenScreenTags: APTR, // 106: 484 (varargs)
    pub DrawImageState: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, *mut Image, i16, i16, u32, *const DrawInfo), // 107: 488
    pub PointInImage: unsafe extern "C" fn(*mut IntuitionIFace, u32, *mut Image) -> u32, // 108: 492
    pub EraseImage: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, *mut Image, i16, i16), // 109: 496
    pub NewObjectA: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR, APTR, *const TagItem) -> *mut APTR, // 110: 500
    pub NewObject: APTR, // 111: 504 (varargs)
    pub DisposeObject: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR), // 112: 508
    pub SetAttrsA: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR, *const TagItem) -> u32, // 113: 512
    pub SetAttrs: APTR, // 114: 516 (varargs)
    pub GetAttr: unsafe extern "C" fn(*mut IntuitionIFace, u32, *mut APTR, *mut u32) -> u32, // 115: 520
    pub SetGadgetAttrsA: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, *mut Window, *mut Requester, *const TagItem) -> u32, // 116: 524
    pub SetGadgetAttrs: APTR, // 117: 528 (varargs)
    pub NextObject: unsafe extern "C" fn(*mut IntuitionIFace, *mut *mut APTR) -> *mut APTR, // 118: 532
    pub FindClass: unsafe extern "C" fn(*mut IntuitionIFace, APTR) -> *mut APTR, // 119: 536
    pub MakeClass: unsafe extern "C" fn(*mut IntuitionIFace, APTR, APTR, *const APTR, u16, u32) -> *mut APTR, // 120: 540
    pub AddClass: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR), // 121: 544
    pub GetScreenDrawInfo: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen) -> *mut DrawInfo, // 122: 548
    pub FreeScreenDrawInfo: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, *mut DrawInfo), // 123: 552
    pub ResetMenuStrip: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut Menu) -> u32, // 124: 556
    pub RemoveClass: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR), // 125: 560
    pub FreeClass: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR) -> u32, // 126: 564
    pub LockClassList: unsafe extern "C" fn(*mut IntuitionIFace) -> *mut List, // 127: 568
    pub UnlockClassList: unsafe extern "C" fn(*mut IntuitionIFace), // 128: 572
    pub Reserved1: unsafe extern "C" fn(*mut IntuitionIFace), // 129: 576
    pub Reserved2: unsafe extern "C" fn(*mut IntuitionIFace), // 130: 580
    pub Reserved3: unsafe extern "C" fn(*mut IntuitionIFace), // 131: 584
    pub Reserved4: unsafe extern "C" fn(*mut IntuitionIFace), // 132: 588
    pub Reserved5: unsafe extern "C" fn(*mut IntuitionIFace), // 133: 592
    pub Reserved6: unsafe extern "C" fn(*mut IntuitionIFace), // 134: 596
    pub AllocScreenBuffer: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, *mut BitMap, u32) -> *mut ScreenBuffer, // 135: 600
    pub FreeScreenBuffer: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, *mut ScreenBuffer), // 136: 604
    pub ChangeScreenBuffer: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, *mut ScreenBuffer) -> u32, // 137: 608
    pub ScreenDepth: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, u32, APTR), // 138: 612
    pub ScreenPosition: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, u32, i32, i32, i32, i32), // 139: 616
    pub ScrollWindowRaster: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, i16, i16, i16, i16, i16, i16), // 140: 620
    pub LendMenus: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut Window), // 141: 624
    pub DoGadgetMethodA: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, *mut Window, *mut Requester, APTR) -> u32, // 142: 628
    pub DoGadgetMethod: APTR, // 143: 632 (varargs)
    pub SetWindowPointerA: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *const TagItem), // 144: 636
    pub SetWindowPointer: APTR, // 145: 640 (varargs)
    pub TimedDisplayAlert: unsafe extern "C" fn(*mut IntuitionIFace, u32, CONST_STRPTR, u16, u32) -> u32, // 146: 644
    pub HelpControl: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, u32), // 147: 648
    pub ShowWindow: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut Window) -> u32, // 148: 652
    pub HideWindow: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window) -> u32, // 149: 656
    pub GetAttrsA: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR, *mut TagItem) -> u32, // 150: 660
    pub GetAttrs: APTR, // 151: 664 (varargs)
    pub LockGUIPrefs: unsafe extern "C" fn(*mut IntuitionIFace, u32) -> APTR, // 152: 668
    pub UnlockGUIPrefs: unsafe extern "C" fn(*mut IntuitionIFace, APTR), // 153: 672
    pub SetGUIAttrsA: unsafe extern "C" fn(*mut IntuitionIFace, APTR, *mut DrawInfo, *mut TagItem) -> u32, // 154: 676
    pub SetGUIAttrs: APTR, // 155: 680 (varargs)
    pub GetGUIAttrsA: unsafe extern "C" fn(*mut IntuitionIFace, APTR, *mut DrawInfo, *mut TagItem) -> u32, // 156: 684
    pub GetGUIAttrs: APTR, // 157: 688 (varargs)
    pub GetHalfPens: unsafe extern "C" fn(*mut IntuitionIFace, *mut DrawInfo, u32, *mut u16, *mut u16) -> u32, // 158: 692
    pub GadgetBox: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, APTR, u32, u32, APTR) -> u32, // 159: 696
    pub RefreshSetGadgetAttrsA: unsafe extern "C" fn(*mut IntuitionIFace, *mut Gadget, *mut Window, *mut Requester, *mut TagItem), // 160: 700
    pub RefreshSetGadgetAttrs: APTR, // 161: 704 (varargs)
    pub IDoSuperMethodA: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR, *mut APTR, APTR) -> u32, // 162: 708
    pub IDoSuperMethod: APTR, // 163: 712 (varargs)
    pub ISetSuperAttrsA: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR, *mut APTR, *mut TagItem) -> u32, // 164: 716
    pub ISetSuperAttrs: APTR, // 165: 720 (varargs)
    pub ICoerceMethodA: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR, *mut APTR, APTR) -> u32, // 166: 724
    pub ICoerceMethod: APTR, // 167: 728 (varargs)
    pub IDoMethodA: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR, APTR) -> u32, // 168: 732
    pub IDoMethod: APTR, // 169: 736 (varargs)
    pub OpenClass: unsafe extern "C" fn(*mut IntuitionIFace, CONST_STRPTR, u32, *mut *mut APTR) -> *mut ClassLibrary, // 170: 740
    pub CloseClass: unsafe extern "C" fn(*mut IntuitionIFace, *mut ClassLibrary), // 171: 744
    pub SetDisplayBeepHook: unsafe extern "C" fn(*mut IntuitionIFace, *mut Hook) -> *mut Hook, // 172: 748
    pub LockScreen: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, u32) -> u32, // 173: 752
    pub UnlockScreen: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen), // 174: 756
    pub GetWindowAttrsA: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut TagItem) -> i32, // 175: 760
    pub GetWindowAttrs: APTR, // 176: 764 (varargs)
    pub SetWindowAttrsA: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, *mut TagItem) -> i32, // 177: 768
    pub SetWindowAttrs: APTR, // 178: 772 (varargs)
    pub GetWindowAttr: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, u32, APTR, u32) -> i32, // 179: 776
    pub SetWindowAttr: unsafe extern "C" fn(*mut IntuitionIFace, *mut Window, u32, APTR, u32) -> i32, // 180: 780
    pub StripIntuiMessages: unsafe extern "C" fn(*mut IntuitionIFace, *mut MsgPort, *mut Window), // 181: 784
    pub Reserved7: unsafe extern "C" fn(*mut IntuitionIFace), // 182: 788
    pub Reserved8: unsafe extern "C" fn(*mut IntuitionIFace), // 183: 792
    pub GetScreenAttrsA: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, *mut TagItem) -> i32, // 184: 796
    pub GetScreenAttrs: APTR, // 185: 800 (varargs)
    pub SetScreenAttrsA: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, *mut TagItem) -> i32, // 186: 804
    pub SetScreenAttrs: APTR, // 187: 808 (varargs)
    pub GetScreenAttr: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, u32, APTR, u32) -> i32, // 188: 812
    pub SetScreenAttr: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, u32, APTR, u32) -> i32, // 189: 816
    pub LockScreenList: unsafe extern "C" fn(*mut IntuitionIFace) -> *mut Screen, // 190: 820
    pub UnlockScreenList: unsafe extern "C" fn(*mut IntuitionIFace), // 191: 824
    pub LockScreenGI: unsafe extern "C" fn(*mut IntuitionIFace, *mut GadgetInfo, u32) -> *mut RastPort, // 192: 828
    pub UnlockScreenGI: unsafe extern "C" fn(*mut IntuitionIFace, *mut GadgetInfo, *mut RastPort), // 193: 832
    pub GetMarkedBlock: unsafe extern "C" fn(*mut IntuitionIFace, *mut SGWork) -> u32, // 194: 836
    pub SetMarkedBlock: unsafe extern "C" fn(*mut IntuitionIFace, *mut SGWork, u32), // 195: 840
    pub ObtainBitMapSourceA: unsafe extern "C" fn(*mut IntuitionIFace, CONST_STRPTR, *mut TagItem) -> APTR, // 196: 844
    pub ObtainBitMapSource: APTR, // 197: 848 (varargs)
    pub ReleaseBitMapSource: unsafe extern "C" fn(*mut IntuitionIFace, APTR), // 198: 852
    pub ObtainBitMapInstanceA: unsafe extern "C" fn(*mut IntuitionIFace, APTR, *mut Screen, *mut TagItem) -> APTR, // 199: 856
    pub ObtainBitMapInstance: APTR, // 200: 860 (varargs)
    pub ReleaseBitMapInstance: unsafe extern "C" fn(*mut IntuitionIFace, APTR), // 201: 864
    pub EmbossDisableRect: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, i32, i32, i32, i32, u32, u32, *mut DrawInfo), // 202: 868
    pub EmbossDisableText: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, CONST_STRPTR, u32, u32, u32, *mut DrawInfo), // 203: 872
    pub PrintEmbossedDisabledIText: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, *mut IntuiText, i32, i32, u32, u32, *mut DrawInfo), // 204: 876
    pub IntuiTextExtent: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, *mut IntuiText, *mut TextExtent) -> u32, // 205: 880
    pub ShadeRectOld: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, i32, i32, i32, i32, u32, u32, u32, *mut DrawInfo) -> u32, // 206: 884
    pub DisableTemplateRGB: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, i32, i32, i32, i32, APTR, u32, u32), // 207: 888
    pub SetScreenBitMapInstance: unsafe extern "C" fn(*mut IntuitionIFace, *mut Screen, u32, APTR) -> u32, // 208: 892
    pub FindMenuKey: unsafe extern "C" fn(*mut IntuitionIFace, *mut Menu, i32) -> u16, // 209: 896
    pub BitMapInstanceControlA: unsafe extern "C" fn(*mut IntuitionIFace, APTR, *mut TagItem) -> u32, // 210: 900
    pub BitMapInstanceControl: APTR, // 211: 904 (varargs)
    pub ObtainIPluginList: unsafe extern "C" fn(*mut IntuitionIFace, u32, u32, u32) -> *mut List, // 212: 908
    pub ReleaseIPluginList: unsafe extern "C" fn(*mut IntuitionIFace, *mut List), // 213: 912
    pub OpenGUIPlugin: unsafe extern "C" fn(*mut IntuitionIFace, STRPTR, u32, u32, u32, u32) -> *mut GUIPlugin, // 214: 916
    pub CloseGUIPlugin: unsafe extern "C" fn(*mut IntuitionIFace, *mut GUIPlugin), // 215: 920
    pub DrawSysImageA: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, i32, i32, i32, i32, u32, u32, u32, *mut DrawInfo, *mut TagItem) -> u32, // 216: 924
    pub DrawSysImage: APTR, // 217: 928 (varargs)
    pub DoRender: unsafe extern "C" fn(*mut IntuitionIFace, *mut APTR, *mut GadgetInfo, u32) -> u32, // 218: 932
    pub SetRenderDomain: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, *mut Rectangle) -> u32, // 219: 936
    pub GetRenderDomain: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, *mut Rectangle) -> u32, // 220: 940
    pub DrawGradient: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, i32, i32, i32, i32, *mut IBox, u32, *mut GradientSpec, *mut DrawInfo) -> u32, // 221: 944
    pub DirectionVector: unsafe extern "C" fn(*mut IntuitionIFace, u32) -> u32, // 222: 948
    pub ShadeRectA: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, i32, i32, i32, i32, u32, u32, u32, *mut DrawInfo, *mut TagItem) -> u32, // 223: 952
    pub ShadeRect: APTR, // 224: 956 (varargs)
    pub DoScrollHook: unsafe extern "C" fn(*mut IntuitionIFace, *mut ScrollHook, i32), // 225: 960
    pub ObtainIBackFill: unsafe extern "C" fn(*mut IntuitionIFace, *mut DrawInfo, u32, u32, u32) -> *mut Hook, // 226: 964
    pub ReleaseIBackFill: unsafe extern "C" fn(*mut IntuitionIFace, *mut Hook), // 227: 968
    pub IntuitionControlA: unsafe extern "C" fn(*mut IntuitionIFace, APTR, *mut TagItem) -> u32, // 228: 972
    pub IntuitionControl: APTR, // 229: 976 (varargs)
    pub StartScreenNotifyTagList: unsafe extern "C" fn(*mut IntuitionIFace, *mut TagItem) -> APTR, // 230: 980
    pub StartScreenNotifyTags: APTR, // 231: 984 (varargs)
    pub EndScreenNotify: unsafe extern "C" fn(*mut IntuitionIFace, APTR) -> u32, // 232: 988
    pub DisableTemplate: unsafe extern "C" fn(*mut IntuitionIFace, *mut RastPort, i32, i32, i32, i32, APTR, i32, u32, u32, u32, *mut DrawInfo), // 233: 992
}

