//! KeymapIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- KeymapIFace (keymap.h) ----

#[repr(C)]
pub struct KeymapIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut KeymapIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut KeymapIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut KeymapIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut KeymapIFace) -> *mut Interface, // 3: 72
    pub SetKeyMapDefault: unsafe extern "C" fn(*mut KeymapIFace, *const KeyMap), // 4: 76
    pub AskKeyMapDefault: unsafe extern "C" fn(*mut KeymapIFace) -> *mut KeyMap, // 5: 80
    pub MapRawKey: unsafe extern "C" fn(*mut KeymapIFace, *const InputEvent, STRPTR, i16, *const KeyMap) -> i16, // 6: 84
    pub MapANSI: unsafe extern "C" fn(*mut KeymapIFace, CONST_STRPTR, i32, STRPTR, i32, *const KeyMap) -> i32, // 7: 88
    pub OpenKeyMapHandleA: unsafe extern "C" fn(*mut KeymapIFace, CONST_STRPTR, *const TagItem) -> APTR, // 8: 92
    pub OpenKeyMapHandle: APTR, // 9: 96 (varargs)
    pub CloseKeyMapHandle: unsafe extern "C" fn(*mut KeymapIFace, APTR), // 10: 100
    pub ObtainKeyMapInfoA: unsafe extern "C" fn(*mut KeymapIFace, APTR, *const TagItem) -> u32, // 11: 104
    pub ObtainKeyMapInfo: APTR, // 12: 108 (varargs)
    pub ReleaseKeyMapInfoA: unsafe extern "C" fn(*mut KeymapIFace, APTR, *const TagItem), // 13: 112
    pub ReleaseKeyMapInfo: APTR, // 14: 116 (varargs)
    pub ObtainRawKeyInfoA: unsafe extern "C" fn(*mut KeymapIFace, *const TagItem), // 15: 120
    pub ObtainRawKeyInfo: APTR, // 16: 124 (varargs)
    pub KeyMapControlTagList: unsafe extern "C" fn(*mut KeymapIFace, *const TagItem) -> u32, // 17: 128
    pub KeyMapControlTags: APTR, // 18: 132 (varargs)
}

