//! LabelIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- LabelIFace (label.h) ----

#[repr(C)]
pub struct LabelIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut LabelIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut LabelIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut LabelIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut LabelIFace) -> *mut Interface, // 3: 72
    pub LABEL_GetClass: unsafe extern "C" fn(*mut LabelIFace) -> *mut APTR, // 4: 76
}

