//! LanguageIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- LanguageIFace (language.h) ----

#[repr(C)]
pub struct LanguageIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut LanguageIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut LanguageIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut LanguageIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut LanguageIFace) -> *mut Interface, // 3: 72
    pub LG_GetDriverInfo: unsafe extern "C" fn(*mut LanguageIFace) -> u32, // 4: 76
    pub LG_ConvToLower: unsafe extern "C" fn(*mut LanguageIFace, u32) -> u32, // 5: 80
    pub LG_ConvToUpper: unsafe extern "C" fn(*mut LanguageIFace, u32) -> u32, // 6: 84
    pub LG_GetCodeSet: unsafe extern "C" fn(*mut LanguageIFace) -> u32, // 7: 88
    pub LG_GetLocaleStr: unsafe extern "C" fn(*mut LanguageIFace, u32) -> CONST_STRPTR, // 8: 92
    pub LG_IsAlNum: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 9: 96
    pub LG_IsAlpha: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 10: 100
    pub LG_IsCntrl: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 11: 104
    pub LG_IsDigit: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 12: 108
    pub LG_IsGraph: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 13: 112
    pub LG_IsLower: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 14: 116
    pub LG_IsPrint: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 15: 120
    pub LG_IsPunct: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 16: 124
    pub LG_IsSpace: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 17: 128
    pub LG_IsUpper: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 18: 132
    pub LG_IsXDigit: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 19: 136
    pub LG_StrConvert: unsafe extern "C" fn(*mut LanguageIFace, CONST_STRPTR, APTR, u32, u32) -> u32, // 20: 140
    pub LG_StrnCmp: unsafe extern "C" fn(*mut LanguageIFace, CONST_STRPTR, CONST_STRPTR, i32, u32) -> i32, // 21: 144
    pub LG_IsBlank: unsafe extern "C" fn(*mut LanguageIFace, u32) -> i32, // 22: 148
}

