//! LayersIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- LayersIFace (layers.h) ----

#[repr(C)]
pub struct LayersIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut LayersIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut LayersIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut LayersIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut LayersIFace) -> *mut Interface, // 3: 72
    pub InitLayers: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info), // 4: 76
    pub CreateUpfrontLayer: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info, *mut BitMap, i32, i32, i32, i32, i32, *mut BitMap) -> *mut Layer, // 5: 80
    pub CreateBehindLayer: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info, *mut BitMap, i32, i32, i32, i32, i32, *mut BitMap) -> *mut Layer, // 6: 84
    pub UpfrontLayer: unsafe extern "C" fn(*mut LayersIFace, i32, *mut Layer) -> i32, // 7: 88
    pub BehindLayer: unsafe extern "C" fn(*mut LayersIFace, i32, *mut Layer) -> i32, // 8: 92
    pub MoveLayer: unsafe extern "C" fn(*mut LayersIFace, i32, *mut Layer, i32, i32) -> i32, // 9: 96
    pub SizeLayer: unsafe extern "C" fn(*mut LayersIFace, i32, *mut Layer, i32, i32) -> i32, // 10: 100
    pub ScrollLayer: unsafe extern "C" fn(*mut LayersIFace, i32, *mut Layer, i32, i32), // 11: 104
    pub BeginUpdate: unsafe extern "C" fn(*mut LayersIFace, *mut Layer) -> i32, // 12: 108
    pub EndUpdate: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, u16), // 13: 112
    pub DeleteLayer: unsafe extern "C" fn(*mut LayersIFace, i32, *mut Layer) -> i32, // 14: 116
    pub LockLayer: unsafe extern "C" fn(*mut LayersIFace, i32, *mut Layer), // 15: 120
    pub UnlockLayer: unsafe extern "C" fn(*mut LayersIFace, *mut Layer), // 16: 124
    pub LockLayers: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info), // 17: 128
    pub UnlockLayers: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info) -> u32, // 18: 132
    pub LockLayerInfo: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info), // 19: 136
    pub SwapBitsRastPortClipRect: unsafe extern "C" fn(*mut LayersIFace, *mut RastPort, *mut ClipRect), // 20: 140
    pub WhichLayer: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info, i16, i16) -> *mut Layer, // 21: 144
    pub UnlockLayerInfo: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info), // 22: 148
    pub NewLayerInfo: unsafe extern "C" fn(*mut LayersIFace) -> *mut Layer_Info, // 23: 152
    pub DisposeLayerInfo: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info), // 24: 156
    pub FattenLayerInfo: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info) -> i32, // 25: 160
    pub ThinLayerInfo: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info), // 26: 164
    pub MoveLayerInFrontOf: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, *mut Layer) -> i32, // 27: 168
    pub InstallClipRegion: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, *mut APTR) -> *mut Region, // 28: 172
    pub MoveSizeLayer: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, i32, i32, i32, i32) -> i32, // 29: 176
    pub CreateUpfrontHookLayer: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info, *mut BitMap, i32, i32, i32, i32, i32, *mut Hook, *mut BitMap) -> *mut Layer, // 30: 180
    pub CreateBehindHookLayer: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info, *mut BitMap, i32, i32, i32, i32, i32, *mut Hook, *mut BitMap) -> *mut Layer, // 31: 184
    pub InstallLayerHook: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, *mut Hook) -> *mut Hook, // 32: 188
    pub InstallLayerInfoHook: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info, *mut APTR) -> *mut Hook, // 33: 192
    pub SortLayerCR: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, i16, i16), // 34: 196
    pub DoHookClipRects: unsafe extern "C" fn(*mut LayersIFace, *mut APTR, *mut RastPort, *mut APTR), // 35: 200
    pub LayerOccluded: unsafe extern "C" fn(*mut LayersIFace, *mut Layer) -> i32, // 36: 204
    pub HideLayer: unsafe extern "C" fn(*mut LayersIFace, *mut Layer) -> i32, // 37: 208
    pub ShowLayer: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, *mut Layer) -> i32, // 38: 212
    pub SetLayerInfoBounds: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info, *mut Rectangle) -> i32, // 39: 216
    pub AllocClipRect: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info) -> *mut ClipRect, // 40: 220
    pub FreeClipRect: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info, *mut ClipRect), // 41: 224
    pub CreateLayerA: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info, *mut TagItem) -> *mut Layer, // 42: 228
    pub CreateLayer: APTR, // 43: 232 (varargs)
    pub ChangeLayerShape: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, *mut Region, *mut Hook) -> *mut Region, // 44: 236
    pub CreateBackFillHookA: unsafe extern "C" fn(*mut LayersIFace, *mut TagItem) -> *mut Hook, // 45: 240
    pub CreateBackFillHook: APTR, // 46: 244 (varargs)
    pub DeleteBackFillHook: unsafe extern "C" fn(*mut LayersIFace, *mut Hook), // 47: 248
    pub SetBackFillHookAttrsA: unsafe extern "C" fn(*mut LayersIFace, *mut Hook, *mut TagItem) -> u32, // 48: 252
    pub SetBackFillHookAttrs: APTR, // 49: 256 (varargs)
    pub GetBackFillHookAttrsA: unsafe extern "C" fn(*mut LayersIFace, *mut Hook, *mut TagItem) -> u32, // 50: 260
    pub GetBackFillHookAttrs: APTR, // 51: 264 (varargs)
    pub ComposeLayersA: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, *mut Rectangle, *mut TagItem) -> u32, // 52: 268
    pub ComposeLayers: APTR, // 53: 272 (varargs)
    pub GetOffScreenLayerBitMap: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, *mut BitMap, *mut Rectangle) -> *mut BitMap, // 54: 276
    pub SetLayerInfoAttrsA: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info, *mut TagItem) -> u32, // 55: 280
    pub SetLayerInfoAttrs: APTR, // 56: 284 (varargs)
    pub GetLayerInfoAttrsA: unsafe extern "C" fn(*mut LayersIFace, *mut Layer_Info, *mut TagItem) -> u32, // 57: 288
    pub GetLayerInfoAttrs: APTR, // 58: 292 (varargs)
    pub ChangeLayerAlpha: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, *mut ClipRect, *mut Hook) -> *mut ClipRect, // 59: 296
    pub SetForegroundAlpha: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, APTR, u32, u32, i32, i32, u32, u32, u32) -> u32, // 60: 300
    pub SetLayerOpaqueness: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, u32) -> u32, // 61: 304
    pub SetLayerOverlayRect: unsafe extern "C" fn(*mut LayersIFace, *mut Layer, i32, i32, i32, i32, u32) -> u32, // 62: 308
}

