//! LayoutIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- LayoutIFace (layout.h) ----

#[repr(C)]
pub struct LayoutIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut LayoutIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut LayoutIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut LayoutIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut LayoutIFace) -> *mut Interface, // 3: 72
    pub LAYOUT_GetClass: unsafe extern "C" fn(*mut LayoutIFace) -> *mut APTR, // 4: 76
    pub ActivateLayoutGadget: unsafe extern "C" fn(*mut LayoutIFace, *mut Gadget, *mut Window, *mut Requester, u32) -> u32, // 5: 80
    pub FlushLayoutDomainCache: unsafe extern "C" fn(*mut LayoutIFace, *mut Gadget), // 6: 84
    pub RethinkLayout: unsafe extern "C" fn(*mut LayoutIFace, *mut Gadget, *mut Window, *mut Requester, u32) -> u32, // 7: 88
    pub LayoutLimits: unsafe extern "C" fn(*mut LayoutIFace, *mut Gadget, *mut LayoutLimits, *mut TextFont, *mut Screen), // 8: 92
    pub PAGE_GetClass: unsafe extern "C" fn(*mut LayoutIFace) -> *mut APTR, // 9: 96
    pub SetPageGadgetAttrsA: unsafe extern "C" fn(*mut LayoutIFace, *mut Gadget, *mut APTR, *mut Window, *mut Requester, *mut TagItem) -> u32, // 10: 100
    pub SetPageGadgetAttrs: APTR, // 11: 104 (varargs)
    pub RefreshPageGadget: unsafe extern "C" fn(*mut LayoutIFace, *mut Gadget, *mut APTR, *mut Window, *mut Requester), // 12: 108
}

