//! ListBrowserIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ListBrowserIFace (listbrowser.h) ----

#[repr(C)]
pub struct ListBrowserIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ListBrowserIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ListBrowserIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut ListBrowserIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut ListBrowserIFace) -> *mut Interface, // 3: 72
    pub LISTBROWSER_GetClass: unsafe extern "C" fn(*mut ListBrowserIFace) -> *mut IClass, // 4: 76
    pub AllocListBrowserNodeA: unsafe extern "C" fn(*mut ListBrowserIFace, u16, *mut TagItem) -> *mut Node, // 5: 80
    pub AllocListBrowserNode: APTR, // 6: 84 (varargs)
    pub FreeListBrowserNode: unsafe extern "C" fn(*mut ListBrowserIFace, *mut Node), // 7: 88
    pub SetListBrowserNodeAttrsA: unsafe extern "C" fn(*mut ListBrowserIFace, *mut Node, *mut TagItem), // 8: 92
    pub SetListBrowserNodeAttrs: APTR, // 9: 96 (varargs)
    pub GetListBrowserNodeAttrsA: unsafe extern "C" fn(*mut ListBrowserIFace, *mut Node, *mut TagItem), // 10: 100
    pub GetListBrowserNodeAttrs: APTR, // 11: 104 (varargs)
    pub ListBrowserSelectAll: unsafe extern "C" fn(*mut ListBrowserIFace, *mut List), // 12: 108
    pub ShowListBrowserNodeChildren: unsafe extern "C" fn(*mut ListBrowserIFace, *mut Node, i16), // 13: 112
    pub HideListBrowserNodeChildren: unsafe extern "C" fn(*mut ListBrowserIFace, *mut Node), // 14: 116
    pub ShowAllListBrowserChildren: unsafe extern "C" fn(*mut ListBrowserIFace, *mut List), // 15: 120
    pub HideAllListBrowserChildren: unsafe extern "C" fn(*mut ListBrowserIFace, *mut List), // 16: 124
    pub FreeListBrowserList: unsafe extern "C" fn(*mut ListBrowserIFace, *mut List), // 17: 128
    pub AllocLBColumnInfoA: unsafe extern "C" fn(*mut ListBrowserIFace, u16, *mut TagItem) -> *mut ColumnInfo, // 18: 132
    pub AllocLBColumnInfo: APTR, // 19: 136 (varargs)
    pub SetLBColumnInfoAttrsA: unsafe extern "C" fn(*mut ListBrowserIFace, *mut ColumnInfo, *mut TagItem) -> i32, // 20: 140
    pub SetLBColumnInfoAttrs: APTR, // 21: 144 (varargs)
    pub GetLBColumnInfoAttrsA: unsafe extern "C" fn(*mut ListBrowserIFace, *mut ColumnInfo, *mut TagItem) -> i32, // 22: 148
    pub GetLBColumnInfoAttrs: APTR, // 23: 152 (varargs)
    pub FreeLBColumnInfo: unsafe extern "C" fn(*mut ListBrowserIFace, *mut ColumnInfo), // 24: 156
    pub ListBrowserClearAll: unsafe extern "C" fn(*mut ListBrowserIFace, *mut List), // 25: 160
}

