//! LocaleIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- LocaleIFace (locale.h) ----

#[repr(C)]
pub struct LocaleIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut LocaleIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut LocaleIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut LocaleIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut LocaleIFace) -> *mut Interface, // 3: 72
    pub Private1: APTR, // 4: 76
    pub CloseCatalog: unsafe extern "C" fn(*mut LocaleIFace, *mut Catalog), // 5: 80
    pub CloseLocale: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale), // 6: 84
    pub ConvToLower: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> u32, // 7: 88
    pub ConvToUpper: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> u32, // 8: 92
    pub FormatDate: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, CONST_STRPTR, *mut DateStamp, *mut Hook), // 9: 96
    pub FormatString: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, CONST_STRPTR, APTR, *mut Hook) -> APTR, // 10: 100
    pub GetCatalogStr: unsafe extern "C" fn(*mut LocaleIFace, *mut Catalog, i32, CONST_STRPTR) -> CONST_STRPTR, // 11: 104
    pub GetLocaleStr: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> CONST_STRPTR, // 12: 108
    pub IsAlNum: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 13: 112
    pub IsAlpha: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 14: 116
    pub IsCntrl: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 15: 120
    pub IsDigit: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 16: 124
    pub IsGraph: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 17: 128
    pub IsLower: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 18: 132
    pub IsPrint: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 19: 136
    pub IsPunct: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 20: 140
    pub IsSpace: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 21: 144
    pub IsUpper: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 22: 148
    pub IsXDigit: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 23: 152
    pub OpenCatalogA: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, CONST_STRPTR, *const TagItem) -> *mut Catalog, // 24: 156
    pub OpenCatalog: APTR, // 25: 160 (varargs)
    pub OpenLocale: unsafe extern "C" fn(*mut LocaleIFace, CONST_STRPTR) -> *mut Locale, // 26: 164
    pub ParseDate: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, *mut DateStamp, CONST_STRPTR, *mut Hook) -> i32, // 27: 168
    pub Private2: APTR, // 28: 172
    pub StrConvert: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, CONST_STRPTR, APTR, u32, u32) -> u32, // 29: 176
    pub StrnCmp: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, CONST_STRPTR, CONST_STRPTR, i32, u32) -> i32, // 30: 180
    pub Locale_DateToStr: unsafe extern "C" fn(*mut LocaleIFace, *mut DateTime) -> i32, // 31: 184
    pub Locale_StrToDate: unsafe extern "C" fn(*mut LocaleIFace, *mut DateTime) -> i32, // 32: 188
    pub IsBlank: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, u32) -> i32, // 33: 192
    pub FormatString32: unsafe extern "C" fn(*mut LocaleIFace, *mut Locale, CONST_STRPTR, APTR, *mut Hook) -> APTR, // 34: 196
}

