//! LowLevelIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- LowLevelIFace (lowlevel.h) ----

#[repr(C)]
pub struct LowLevelIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut LowLevelIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut LowLevelIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut LowLevelIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut LowLevelIFace) -> *mut Interface, // 3: 72
    pub ReadJoyPort: unsafe extern "C" fn(*mut LowLevelIFace, u32) -> u32, // 4: 76
    pub GetLanguageSelection: unsafe extern "C" fn(*mut LowLevelIFace) -> u8, // 5: 80
    pub Private1: APTR, // 6: 84
    pub GetKey: unsafe extern "C" fn(*mut LowLevelIFace) -> u32, // 7: 88
    pub QueryKeys: unsafe extern "C" fn(*mut LowLevelIFace, *mut KeyQuery, u8), // 8: 92
    pub AddKBInt: unsafe extern "C" fn(*mut LowLevelIFace, APTR, APTR) -> APTR, // 9: 96
    pub RemKBInt: unsafe extern "C" fn(*mut LowLevelIFace, APTR), // 10: 100
    pub SystemControlA: unsafe extern "C" fn(*mut LowLevelIFace, *const TagItem) -> u32, // 11: 104
    pub SystemControl: APTR, // 12: 108 (varargs)
    pub AddTimerInt: unsafe extern "C" fn(*mut LowLevelIFace, APTR, APTR) -> APTR, // 13: 112
    pub RemTimerInt: unsafe extern "C" fn(*mut LowLevelIFace, APTR), // 14: 116
    pub StopTimerInt: unsafe extern "C" fn(*mut LowLevelIFace, APTR), // 15: 120
    pub StartTimerInt: unsafe extern "C" fn(*mut LowLevelIFace, APTR, u32, u32), // 16: 124
    pub ElapsedTime: unsafe extern "C" fn(*mut LowLevelIFace, *mut EClockVal) -> u32, // 17: 128
    pub AddVBlankInt: unsafe extern "C" fn(*mut LowLevelIFace, APTR, APTR) -> APTR, // 18: 132
    pub RemVBlankInt: unsafe extern "C" fn(*mut LowLevelIFace, APTR), // 19: 136
    pub Private2: APTR, // 20: 140
    pub Private3: APTR, // 21: 144
    pub SetJoyPortAttrsA: unsafe extern "C" fn(*mut LowLevelIFace, u32, *const TagItem) -> u32, // 22: 148
    pub SetJoyPortAttrs: APTR, // 23: 152 (varargs)
}

