//! LZMAIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- LZMAIFace (lzma.h) ----

#[repr(C)]
pub struct LZMAIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut LZMAIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut LZMAIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut LZMAIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut LZMAIFace) -> *mut Interface, // 3: 72
    pub lzma_code: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR) -> APTR, // 4: 76
    pub lzma_end: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR), // 5: 80
    pub lzma_memusage: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 6: 84
    pub lzma_memlimit_get: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 7: 88
    pub lzma_memlimit_set: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR) -> APTR, // 8: 92
    pub lzma_block_header_size: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR) -> APTR, // 9: 96
    pub lzma_block_header_encode: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, *mut APTR) -> APTR, // 10: 100
    pub lzma_block_header_decode: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR, *const APTR) -> APTR, // 11: 104
    pub lzma_block_compressed_size: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR) -> APTR, // 12: 108
    pub lzma_block_unpadded_size: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 13: 112
    pub lzma_block_total_size: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 14: 116
    pub lzma_block_encoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR) -> APTR, // 15: 120
    pub lzma_block_decoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR) -> APTR, // 16: 124
    pub lzma_block_buffer_bound: unsafe extern "C" fn(*mut LZMAIFace, u32) -> u32, // 17: 128
    pub lzma_block_buffer_encode: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR, *const APTR, u32, *mut APTR, *mut u32, u32) -> APTR, // 18: 132
    pub lzma_block_buffer_decode: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR, *const APTR, *mut u32, u32, *mut APTR, *mut u32, u32) -> APTR, // 19: 136
    pub lzma_check_is_supported: unsafe extern "C" fn(*mut LZMAIFace, APTR) -> APTR, // 20: 140
    pub lzma_check_size: unsafe extern "C" fn(*mut LZMAIFace, APTR) -> APTR, // 21: 144
    pub lzma_crc32: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, u32, APTR) -> APTR, // 22: 148
    pub lzma_crc64: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, u32, APTR) -> APTR, // 23: 152
    pub lzma_get_check: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 24: 156
    pub lzma_easy_encoder_memusage: unsafe extern "C" fn(*mut LZMAIFace, APTR) -> APTR, // 25: 160
    pub lzma_easy_decoder_memusage: unsafe extern "C" fn(*mut LZMAIFace, APTR) -> APTR, // 26: 164
    pub lzma_easy_encoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR, APTR) -> APTR, // 27: 168
    pub lzma_easy_buffer_encode: unsafe extern "C" fn(*mut LZMAIFace, APTR, APTR, *mut APTR, *const APTR, u32, *mut APTR, *mut u32, u32) -> APTR, // 28: 172
    pub lzma_stream_encoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR, APTR) -> APTR, // 29: 176
    pub lzma_alone_encoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR) -> APTR, // 30: 180
    pub lzma_stream_buffer_bound: unsafe extern "C" fn(*mut LZMAIFace, u32) -> u32, // 31: 184
    pub lzma_stream_buffer_encode: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR, *mut APTR, *const APTR, u32, *mut APTR, *mut u32, u32) -> APTR, // 32: 188
    pub lzma_stream_decoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR, APTR) -> APTR, // 33: 192
    pub lzma_auto_decoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR, APTR) -> APTR, // 34: 196
    pub lzma_alone_decoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR) -> APTR, // 35: 200
    pub lzma_stream_buffer_decode: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR, *mut APTR, *const APTR, *mut u32, u32, *mut APTR, *mut u32, u32) -> APTR, // 36: 204
    pub lzma_filter_encoder_is_supported: unsafe extern "C" fn(*mut LZMAIFace, APTR) -> APTR, // 37: 208
    pub lzma_filter_decoder_is_supported: unsafe extern "C" fn(*mut LZMAIFace, APTR) -> APTR, // 38: 212
    pub lzma_filters_copy: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, *mut APTR, *mut APTR) -> APTR, // 39: 216
    pub lzma_raw_encoder_memusage: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 40: 220
    pub lzma_raw_decoder_memusage: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 41: 224
    pub lzma_raw_encoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR) -> APTR, // 42: 228
    pub lzma_raw_decoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR) -> APTR, // 43: 232
    pub lzma_filters_update: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR) -> APTR, // 44: 236
    pub lzma_raw_buffer_encode: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, *mut APTR, *const APTR, u32, *mut APTR, *mut u32, u32) -> APTR, // 45: 240
    pub lzma_raw_buffer_decode: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, *mut APTR, *const APTR, *mut u32, u32, *mut APTR, *mut u32, u32) -> APTR, // 46: 244
    pub lzma_properties_size: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR) -> APTR, // 47: 248
    pub lzma_properties_encode: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, *mut APTR) -> APTR, // 48: 252
    pub lzma_properties_decode: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR, *const APTR, u32) -> APTR, // 49: 256
    pub lzma_filter_flags_size: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR) -> APTR, // 50: 260
    pub lzma_filter_flags_encode: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, *mut APTR, *mut u32, u32) -> APTR, // 51: 264
    pub lzma_filter_flags_decode: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR, *const APTR, *mut u32, u32) -> APTR, // 52: 268
    pub lzma_physmem: unsafe extern "C" fn(*mut LZMAIFace) -> APTR, // 53: 272
    pub lzma_index_memusage: unsafe extern "C" fn(*mut LZMAIFace, APTR, APTR) -> APTR, // 54: 276
    pub lzma_index_memused: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 55: 280
    pub lzma_index_init: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR) -> *mut APTR, // 56: 284
    pub lzma_index_end: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR), // 57: 288
    pub lzma_index_append: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR, APTR, APTR) -> APTR, // 58: 292
    pub lzma_index_stream_flags: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR) -> APTR, // 59: 296
    pub lzma_index_checks: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 60: 300
    pub lzma_index_stream_padding: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR) -> APTR, // 61: 304
    pub lzma_index_stream_count: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 62: 308
    pub lzma_index_block_count: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 63: 312
    pub lzma_index_size: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 64: 316
    pub lzma_index_stream_size: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 65: 320
    pub lzma_index_total_size: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 66: 324
    pub lzma_index_file_size: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 67: 328
    pub lzma_index_uncompressed_size: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 68: 332
    pub lzma_index_iter_init: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR), // 69: 336
    pub lzma_index_iter_rewind: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR), // 70: 340
    pub lzma_index_iter_next: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR) -> APTR, // 71: 344
    pub lzma_index_iter_locate: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR) -> APTR, // 72: 348
    pub lzma_index_cat: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR, *mut APTR) -> APTR, // 73: 352
    pub lzma_index_dup: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, *mut APTR) -> *mut APTR, // 74: 356
    pub lzma_index_encoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR) -> APTR, // 75: 360
    pub lzma_index_decoder: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut *mut APTR, APTR) -> APTR, // 76: 364
    pub lzma_index_buffer_encode: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, *mut APTR, *mut u32, u32) -> APTR, // 77: 368
    pub lzma_index_buffer_decode: unsafe extern "C" fn(*mut LZMAIFace, *mut *mut APTR, *mut APTR, *mut APTR, *const APTR, *mut u32, u32) -> APTR, // 78: 372
    pub lzma_index_hash_init: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR) -> *mut APTR, // 79: 376
    pub lzma_index_hash_end: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR), // 80: 380
    pub lzma_index_hash_append: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR, APTR) -> APTR, // 81: 384
    pub lzma_index_hash_decode: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR, *mut u32, u32) -> APTR, // 82: 388
    pub lzma_index_hash_size: unsafe extern "C" fn(*mut LZMAIFace, *const APTR) -> APTR, // 83: 392
    pub lzma_mf_is_supported: unsafe extern "C" fn(*mut LZMAIFace, APTR) -> APTR, // 84: 396
    pub lzma_mode_is_supported: unsafe extern "C" fn(*mut LZMAIFace, APTR) -> APTR, // 85: 400
    pub lzma_lzma_preset: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, APTR) -> APTR, // 86: 404
    pub lzma_stream_header_encode: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, *mut APTR) -> APTR, // 87: 408
    pub lzma_stream_footer_encode: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, *mut APTR) -> APTR, // 88: 412
    pub lzma_stream_header_decode: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR) -> APTR, // 89: 416
    pub lzma_stream_footer_decode: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *const APTR) -> APTR, // 90: 420
    pub lzma_stream_flags_compare: unsafe extern "C" fn(*mut LZMAIFace, *const APTR, *const APTR) -> APTR, // 91: 424
    pub lzma_version_number: unsafe extern "C" fn(*mut LZMAIFace) -> APTR, // 92: 428
    pub lzma_version_string: unsafe extern "C" fn(*mut LZMAIFace) -> *const APTR, // 93: 432
    pub lzma_vli_encode: unsafe extern "C" fn(*mut LZMAIFace, APTR, *mut u32, *mut APTR, *mut u32, u32) -> APTR, // 94: 436
    pub lzma_vli_decode: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut u32, *const APTR, *mut u32, u32) -> APTR, // 95: 440
    pub lzma_vli_size: unsafe extern "C" fn(*mut LZMAIFace, APTR) -> APTR, // 96: 444
    pub lzma_get_progress: unsafe extern "C" fn(*mut LZMAIFace, *mut APTR, *mut APTR, *mut APTR), // 97: 448
}

