//! MiscIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- MiscIFace (misc.h) ----

#[repr(C)]
pub struct MiscIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut MiscIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut MiscIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut MiscIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut MiscIFace) -> *mut Interface, // 3: 72
    pub AllocMiscResource: unsafe extern "C" fn(*mut MiscIFace, u32, CONST_STRPTR) -> CONST_STRPTR, // 4: 76
    pub FreeMiscResource: unsafe extern "C" fn(*mut MiscIFace, u32), // 5: 80
}

