//! MMUIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- MMUIFace (exec.h) ----

#[repr(C)]
pub struct MMUIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut MMUIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut MMUIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub MapMemory: unsafe extern "C" fn(*mut MMUIFace, APTR, APTR, u32, u32) -> u32, // 4: 76
    pub UnmapMemory: unsafe extern "C" fn(*mut MMUIFace, APTR, u32), // 5: 80
    pub RemapMemory: unsafe extern "C" fn(*mut MMUIFace, APTR, APTR, u32, u32), // 6: 84
    pub SetMemoryAttrs: unsafe extern "C" fn(*mut MMUIFace, APTR, u32, u32), // 7: 88
    pub GetMemoryAttrs: unsafe extern "C" fn(*mut MMUIFace, APTR, u32) -> u32, // 8: 92
    pub GetPhysicalAddress: unsafe extern "C" fn(*mut MMUIFace, APTR) -> APTR, // 9: 96
}

