//! MounterIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- MounterIFace (mounter.h) ----

#[repr(C)]
pub struct MounterIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut MounterIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut MounterIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut MounterIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut MounterIFace) -> *mut Interface, // 3: 72
    pub AnnounceDevice: unsafe extern "C" fn(*mut MounterIFace, CONST_STRPTR, u32, *mut TagItem) -> u32, // 4: 76
    pub AnnounceDeviceTags: APTR, // 5: 80 (varargs)
    pub DenounceDevice: unsafe extern "C" fn(*mut MounterIFace, CONST_STRPTR, u32), // 6: 84
}

