//! NVIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- NVIFace (nonvolatile.h) ----

#[repr(C)]
pub struct NVIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut NVIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut NVIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut NVIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut NVIFace) -> *mut Interface, // 3: 72
    pub GetCopyNV: unsafe extern "C" fn(*mut NVIFace, CONST_STRPTR, CONST_STRPTR, u32) -> APTR, // 4: 76
    pub FreeNVData: unsafe extern "C" fn(*mut NVIFace, APTR), // 5: 80
    pub StoreNV: unsafe extern "C" fn(*mut NVIFace, CONST_STRPTR, CONST_STRPTR, APTR, u32, u32) -> u16, // 6: 84
    pub DeleteNV: unsafe extern "C" fn(*mut NVIFace, CONST_STRPTR, CONST_STRPTR, u32) -> u32, // 7: 88
    pub GetNVInfo: unsafe extern "C" fn(*mut NVIFace, u32) -> *mut NVInfo, // 8: 92
    pub GetNVList: unsafe extern "C" fn(*mut NVIFace, CONST_STRPTR, u32) -> *mut MinList, // 9: 96
    pub SetNVProtection: unsafe extern "C" fn(*mut NVIFace, CONST_STRPTR, CONST_STRPTR, i32, u32) -> u32, // 10: 100
    pub SetUBootVar: unsafe extern "C" fn(*mut NVIFace, CONST_STRPTR, CONST_STRPTR) -> u32, // 11: 104
    pub GetUBootVar: unsafe extern "C" fn(*mut NVIFace, CONST_STRPTR) -> CONST_STRPTR, // 12: 108
    pub FreeUBootVar: unsafe extern "C" fn(*mut NVIFace, CONST_STRPTR), // 13: 112
}

