//! OpenFirmwareIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- OpenFirmwareIFace (openfirmware.h) ----

#[repr(C)]
pub struct OpenFirmwareIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut OpenFirmwareIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut OpenFirmwareIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut OpenFirmwareIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut OpenFirmwareIFace) -> *mut Interface, // 3: 72
    pub CallRTAS: unsafe extern "C" fn(*mut OpenFirmwareIFace, *mut u32) -> u32, // 4: 76
    pub GetRTASService: unsafe extern "C" fn(*mut OpenFirmwareIFace, CONST_STRPTR) -> u32, // 5: 80
    pub Root: unsafe extern "C" fn(*mut OpenFirmwareIFace) -> APTR, // 6: 84
    pub Peer: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR) -> APTR, // 7: 88
    pub Child: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR) -> APTR, // 8: 92
    pub Parent: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR) -> APTR, // 9: 96
    pub FindProp: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR, CONST_STRPTR) -> APTR, // 10: 100
    pub FirstProp: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR) -> APTR, // 11: 104
    pub NextProp: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR, APTR) -> APTR, // 12: 108
    pub GetPropName: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR, STRPTR, u32) -> u32, // 13: 112
    pub PropDataSize: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR) -> u32, // 14: 116
    pub GetPropData: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR, APTR, u32) -> u32, // 15: 120
    pub GetNumAddressCells: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR) -> u32, // 16: 124
    pub GetNumSizeCells: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR) -> u32, // 17: 128
    pub FindNodeByStrProp: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR, CONST_STRPTR, CONST_STRPTR, u32) -> APTR, // 18: 132
    pub FindNodeByName: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR, CONST_STRPTR) -> APTR, // 19: 136
    pub FindNodeByDeviceType: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR, CONST_STRPTR) -> APTR, // 20: 140
    pub FindCompatibleNode: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR, CONST_STRPTR) -> APTR, // 21: 144
    pub FindNodeByPath: unsafe extern "C" fn(*mut OpenFirmwareIFace, CONST_STRPTR) -> APTR, // 22: 148
    pub GetPropDataLong: unsafe extern "C" fn(*mut OpenFirmwareIFace, APTR, CONST_STRPTR, u32, u32) -> u32, // 23: 152
}

