//! PaletteIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- PaletteIFace (palette.h) ----

#[repr(C)]
pub struct PaletteIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut PaletteIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut PaletteIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut PaletteIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut PaletteIFace) -> *mut Interface, // 3: 72
    pub PALETTE_GetClass: unsafe extern "C" fn(*mut PaletteIFace) -> *mut APTR, // 4: 76
}

