//! PartitionIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- PartitionIFace (partition.h) ----

#[repr(C)]
pub struct PartitionIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut PartitionIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut PartitionIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut PartitionIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut PartitionIFace) -> *mut Interface, // 3: 72
    pub PARTITION_GetClass: unsafe extern "C" fn(*mut PartitionIFace) -> *mut APTR, // 4: 76
    pub AllocPartitionNodeA: unsafe extern "C" fn(*mut PartitionIFace, *mut TagItem) -> *mut Node, // 5: 80
    pub AllocPartitionNode: APTR, // 6: 84 (varargs)
    pub FreePartitionNode: unsafe extern "C" fn(*mut PartitionIFace, *mut Node), // 7: 88
    pub SetPartitionNodeAttrsA: unsafe extern "C" fn(*mut PartitionIFace, *mut Node, *mut TagItem), // 8: 92
    pub SetPartitionNodeAttrs: APTR, // 9: 96 (varargs)
    pub GetPartitionNodeAttrsA: unsafe extern "C" fn(*mut PartitionIFace, *mut Node, *mut TagItem), // 10: 100
    pub GetPartitionNodeAttrs: APTR, // 11: 104 (varargs)
}

