//! PASDMAIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- PASDMAIFace (pasemi_dma.h) ----

#[repr(C)]
pub struct PASDMAIFace {
    pub data: InterfaceData,

    pub ReadDMARegByte: unsafe extern "C" fn(*mut PASDMAIFace, u32) -> u8, // 0: 60
    pub ReadDMARegWord: unsafe extern "C" fn(*mut PASDMAIFace, u32) -> u16, // 1: 64
    pub ReadDMARegLong: unsafe extern "C" fn(*mut PASDMAIFace, u32) -> u32, // 2: 68
    pub WriteDMARegLong: unsafe extern "C" fn(*mut PASDMAIFace, u32, u32), // 3: 72
    pub WriteIOBRegLong: unsafe extern "C" fn(*mut PASDMAIFace, u32, u32), // 4: 76
    pub AllocChannel: unsafe extern "C" fn(*mut PASDMAIFace, APTR, u32) -> *mut PASDMAChannel, // 5: 80
    pub FreeChannel: unsafe extern "C" fn(*mut PASDMAIFace, *mut PASDMAChannel), // 6: 84
    pub StartChannel: unsafe extern "C" fn(*mut PASDMAIFace, *mut PASDMAChannel, u32), // 7: 88
    pub StopChannel: unsafe extern "C" fn(*mut PASDMAIFace, *mut PASDMAChannel) -> u32, // 8: 92
    pub AllocRing: unsafe extern "C" fn(*mut PASDMAIFace, *mut PASDMAChannel, u32) -> u32, // 9: 96
    pub FreeRing: unsafe extern "C" fn(*mut PASDMAIFace, *mut PASDMAChannel), // 10: 100
    pub AllocBuffer: unsafe extern "C" fn(*mut PASDMAIFace, u32) -> APTR, // 11: 104
    pub FreeBuffer: unsafe extern "C" fn(*mut PASDMAIFace, APTR), // 12: 108
    pub AllocEvent: unsafe extern "C" fn(*mut PASDMAIFace) -> i8, // 13: 112
    pub FreeEvent: unsafe extern "C" fn(*mut PASDMAIFace, u8), // 14: 116
    pub SetEvent: unsafe extern "C" fn(*mut PASDMAIFace, u8), // 15: 120
    pub ClearEvent: unsafe extern "C" fn(*mut PASDMAIFace, u8), // 16: 124
    pub AllocFunction: unsafe extern "C" fn(*mut PASDMAIFace) -> i8, // 17: 128
    pub FreeFunction: unsafe extern "C" fn(*mut PASDMAIFace, u8), // 18: 132
}

