//! PenMapIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- PenMapIFace (penmap.h) ----

#[repr(C)]
pub struct PenMapIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut PenMapIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut PenMapIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut PenMapIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut PenMapIFace) -> *mut Interface, // 3: 72
    pub PENMAP_GetClass: unsafe extern "C" fn(*mut PenMapIFace) -> *mut APTR, // 4: 76
}

