//! PerformanceMonitorIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- PerformanceMonitorIFace (performancemonitor.h) ----

#[repr(C)]
pub struct PerformanceMonitorIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut PerformanceMonitorIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut PerformanceMonitorIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub CounterGet: unsafe extern "C" fn(*mut PerformanceMonitorIFace, u32) -> u32, // 4: 76
    pub CounterMatch: unsafe extern "C" fn(*mut PerformanceMonitorIFace, u32) -> u32, // 5: 80
    pub CounterControl: unsafe extern "C" fn(*mut PerformanceMonitorIFace, u32, i32, u32) -> u32, // 6: 84
    pub EventControl: unsafe extern "C" fn(*mut PerformanceMonitorIFace, *mut TagItem) -> u32, // 7: 88
    pub EventControlTags: APTR, // 8: 92 (varargs)
    pub SetInterruptVector: unsafe extern "C" fn(*mut PerformanceMonitorIFace, u32, *mut Interrupt) -> *mut Interrupt, // 9: 96
    pub Mark: unsafe extern "C" fn(*mut PerformanceMonitorIFace, *mut Task), // 10: 100
    pub Unmark: unsafe extern "C" fn(*mut PerformanceMonitorIFace, *mut Task), // 11: 104
    pub MonitorControl: unsafe extern "C" fn(*mut PerformanceMonitorIFace, *mut TagItem) -> u32, // 12: 108
    pub MonitorControlTags: APTR, // 13: 112 (varargs)
    pub Query: unsafe extern "C" fn(*mut PerformanceMonitorIFace, u32) -> u32, // 14: 116
    pub SetSampledAddress: unsafe extern "C" fn(*mut PerformanceMonitorIFace, APTR), // 15: 120
    pub GetSampledAddress: unsafe extern "C" fn(*mut PerformanceMonitorIFace) -> APTR, // 16: 124
    pub SetBreakpoint: unsafe extern "C" fn(*mut PerformanceMonitorIFace, u32, APTR, u32, u32), // 17: 128
}

