//! PictureIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- PictureIFace (picture.h) ----

#[repr(C)]
pub struct PictureIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut PictureIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut PictureIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut PictureIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut PictureIFace) -> *mut Interface, // 3: 72
    pub PICTURE_GetClass: unsafe extern "C" fn(*mut PictureIFace) -> *mut APTR, // 4: 76
    pub PICTURE_Private: unsafe extern "C" fn(*mut PictureIFace), // 5: 80
}

