//! PopupMenuIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- PopupMenuIFace (popupmenu.h) ----

#[repr(C)]
pub struct PopupMenuIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut PopupMenuIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut PopupMenuIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut PopupMenuIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut PopupMenuIFace) -> *mut Interface, // 3: 72
    pub POPUPMENU_GetClass: unsafe extern "C" fn(*mut PopupMenuIFace) -> *mut APTR, // 4: 76
    pub POPUPMENU_GetItemClass: unsafe extern "C" fn(*mut PopupMenuIFace) -> *mut APTR, // 5: 80
    pub POPUPMENU_MakeMXListA: unsafe extern "C" fn(*mut PopupMenuIFace, *mut u32) -> APTR, // 6: 84
    pub POPUPMENU_MakeMXList: APTR, // 7: 88 (varargs)
    pub POPUPMENU_FreeIDList: unsafe extern "C" fn(*mut PopupMenuIFace, APTR), // 8: 92
    pub POPUPMENU_MakeIDListA: unsafe extern "C" fn(*mut PopupMenuIFace, *mut TagItem) -> APTR, // 9: 96
    pub POPUPMENU_MakeIDList: APTR, // 10: 100 (varargs)
}

