//! PrefsObjectsIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- PrefsObjectsIFace (application.h) ----

#[repr(C)]
pub struct PrefsObjectsIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut PrefsObjectsIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut PrefsObjectsIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut PrefsObjectsIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut PrefsObjectsIFace) -> *mut Interface, // 3: 72
    pub BeginDeserialization: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut ALPOGetProcInfo) -> u32, // 4: 76
    pub PrefsBaseObjectA: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, *mut u32, *mut TagItem) -> *mut APTR, // 5: 80
    pub PrefsBaseObject: APTR, // 6: 84 (varargs)
    pub PrefsStringA: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, *mut u32, *mut TagItem) -> *mut APTR, // 7: 88
    pub PrefsString: APTR, // 8: 92 (varargs)
    pub PrefsNumberA: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, *mut u32, *mut TagItem) -> *mut APTR, // 9: 96
    pub PrefsNumber: APTR, // 10: 100 (varargs)
    pub PrefsDateA: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, *mut u32, *mut TagItem) -> *mut APTR, // 11: 104
    pub PrefsDate: APTR, // 12: 108 (varargs)
    pub PrefsBinaryA: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, *mut u32, *mut TagItem) -> *mut APTR, // 13: 112
    pub PrefsBinary: APTR, // 14: 116 (varargs)
    pub PrefsDictionaryA: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, *mut u32, *mut TagItem) -> *mut APTR, // 15: 120
    pub PrefsDictionary: APTR, // 16: 124 (varargs)
    pub PrefsArrayA: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, *mut u32, *mut TagItem) -> *mut APTR, // 17: 128
    pub PrefsArray: APTR, // 18: 132 (varargs)
    pub DictSetObjectForKey: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, *mut APTR, CONST_STRPTR) -> u32, // 19: 136
    pub DictGetObjectForKey: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, CONST_STRPTR) -> *mut APTR, // 20: 140
    pub DictGetStringForKey: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, CONST_STRPTR, CONST_STRPTR) -> CONST_STRPTR, // 21: 144
    pub DictGetIntegerForKey: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, CONST_STRPTR, i32) -> i32, // 22: 148
    pub DictGetBoolForKey: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, CONST_STRPTR, u32) -> u32, // 23: 152
    pub DictGetOptionForKey: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, CONST_STRPTR, *mut CONST_STRPTR, i32) -> i32, // 24: 156
    pub ReadPrefsA: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, *mut TagItem) -> u32, // 25: 160
    pub ReadPrefs: APTR, // 26: 164 (varargs)
    pub WritePrefsA: unsafe extern "C" fn(*mut PrefsObjectsIFace, *mut APTR, *mut TagItem) -> u32, // 27: 168
    pub WritePrefs: APTR, // 28: 172 (varargs)
}

