//! RadioButtonIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- RadioButtonIFace (radiobutton.h) ----

#[repr(C)]
pub struct RadioButtonIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut RadioButtonIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut RadioButtonIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut RadioButtonIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut RadioButtonIFace) -> *mut Interface, // 3: 72
    pub RADIOBUTTON_GetClass: unsafe extern "C" fn(*mut RadioButtonIFace) -> *mut APTR, // 4: 76
    pub AllocRadioButtonNodeA: unsafe extern "C" fn(*mut RadioButtonIFace, u16, *mut TagItem) -> *mut Node, // 5: 80
    pub AllocRadioButtonNode: APTR, // 6: 84 (varargs)
    pub FreeRadioButtonNode: unsafe extern "C" fn(*mut RadioButtonIFace, *mut Node), // 7: 88
    pub SetRadioButtonNodeAttrsA: unsafe extern "C" fn(*mut RadioButtonIFace, *mut Node, *mut TagItem), // 8: 92
    pub SetRadioButtonNodeAttrs: APTR, // 9: 96 (varargs)
    pub GetRadioButtonNodeAttrsA: unsafe extern "C" fn(*mut RadioButtonIFace, *mut Node, *mut TagItem), // 10: 100
    pub GetRadioButtonNodeAttrs: APTR, // 11: 104 (varargs)
}

