//! RamdriveIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- RamdriveIFace (ramdrive.h) ----

#[repr(C)]
pub struct RamdriveIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut RamdriveIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut RamdriveIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut RamdriveIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut RamdriveIFace) -> *mut Interface, // 3: 72
    pub KillRAD0: unsafe extern "C" fn(*mut RamdriveIFace) -> STRPTR, // 4: 76
    pub KillRAD: unsafe extern "C" fn(*mut RamdriveIFace, u32) -> STRPTR, // 5: 80
}

