//! RealTimeIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- RealTimeIFace (realtime.h) ----

#[repr(C)]
pub struct RealTimeIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut RealTimeIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut RealTimeIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut RealTimeIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut RealTimeIFace) -> *mut Interface, // 3: 72
    pub LockRealTime: unsafe extern "C" fn(*mut RealTimeIFace, u32) -> APTR, // 4: 76
    pub UnlockRealTime: unsafe extern "C" fn(*mut RealTimeIFace, APTR), // 5: 80
    pub CreatePlayerA: unsafe extern "C" fn(*mut RealTimeIFace, *const TagItem) -> *mut Player, // 6: 84
    pub CreatePlayer: APTR, // 7: 88 (varargs)
    pub DeletePlayer: unsafe extern "C" fn(*mut RealTimeIFace, *mut Player), // 8: 92
    pub SetPlayerAttrsA: unsafe extern "C" fn(*mut RealTimeIFace, *mut Player, *const TagItem) -> u32, // 9: 96
    pub SetPlayerAttrs: APTR, // 10: 100 (varargs)
    pub SetConductorState: unsafe extern "C" fn(*mut RealTimeIFace, *mut Player, u32, i32) -> i32, // 11: 104
    pub ExternalSync: unsafe extern "C" fn(*mut RealTimeIFace, *mut Player, i32, i32) -> u32, // 12: 108
    pub NextConductor: unsafe extern "C" fn(*mut RealTimeIFace, *const Conductor) -> *mut Conductor, // 13: 112
    pub FindConductor: unsafe extern "C" fn(*mut RealTimeIFace, CONST_STRPTR) -> *mut Conductor, // 14: 116
    pub GetPlayerAttrsA: unsafe extern "C" fn(*mut RealTimeIFace, *const Player, *const TagItem) -> u32, // 15: 120
    pub GetPlayerAttrs: APTR, // 16: 124 (varargs)
}

