//! ResourceIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ResourceIFace (resource.h) ----

#[repr(C)]
pub struct ResourceIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ResourceIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ResourceIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut ResourceIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut ResourceIFace) -> *mut Interface, // 3: 72
    pub RL_OpenResource: unsafe extern "C" fn(*mut ResourceIFace, APTR, *mut Screen, *mut Catalog) -> APTR, // 4: 76
    pub RL_CloseResource: unsafe extern "C" fn(*mut ResourceIFace, APTR), // 5: 80
    pub RL_NewObjectA: unsafe extern "C" fn(*mut ResourceIFace, APTR, APTR, *mut TagItem) -> *mut APTR, // 6: 84
    pub RL_NewObject: APTR, // 7: 88 (varargs)
    pub RL_DisposeObject: unsafe extern "C" fn(*mut ResourceIFace, APTR, *mut APTR), // 8: 92
    pub RL_NewGroupA: unsafe extern "C" fn(*mut ResourceIFace, APTR, APTR, *mut TagItem) -> *mut *mut APTR, // 9: 96
    pub RL_NewGroup: APTR, // 10: 100 (varargs)
    pub RL_DisposeGroup: unsafe extern "C" fn(*mut ResourceIFace, APTR, *mut *mut APTR), // 11: 104
    pub RL_GetObjectArray: unsafe extern "C" fn(*mut ResourceIFace, APTR, *mut APTR, APTR) -> *mut *mut APTR, // 12: 108
    pub RL_SetResourceScreen: unsafe extern "C" fn(*mut ResourceIFace, APTR, *mut Screen) -> u32, // 13: 112
}

