//! RexxSysIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- RexxSysIFace (rexxsyslib.h) ----

#[repr(C)]
pub struct RexxSysIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut RexxSysIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut RexxSysIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub Private1: APTR, // 4: 76
    pub Private2: APTR, // 5: 80
    pub Private3: APTR, // 6: 84
    pub Private4: APTR, // 7: 88
    pub Private5: APTR, // 8: 92
    pub Private6: APTR, // 9: 96
    pub Private7: APTR, // 10: 100
    pub Private8: APTR, // 11: 104
    pub Private9: APTR, // 12: 108
    pub Private10: APTR, // 13: 112
    pub Private11: APTR, // 14: 116
    pub Private12: APTR, // 15: 120
    pub Private13: APTR, // 16: 124
    pub Private14: APTR, // 17: 128
    pub Private15: APTR, // 18: 132
    pub Private16: APTR, // 19: 136
    pub CreateArgstring: unsafe extern "C" fn(*mut RexxSysIFace, CONST_STRPTR, u32) -> STRPTR, // 20: 140
    pub DeleteArgstring: unsafe extern "C" fn(*mut RexxSysIFace, STRPTR), // 21: 144
    pub LengthArgstring: unsafe extern "C" fn(*mut RexxSysIFace, CONST_STRPTR) -> i32, // 22: 148
    pub CreateRexxMsg: unsafe extern "C" fn(*mut RexxSysIFace, *mut MsgPort, CONST_STRPTR, CONST_STRPTR) -> *mut RexxMsg, // 23: 152
    pub DeleteRexxMsg: unsafe extern "C" fn(*mut RexxSysIFace, *mut RexxMsg), // 24: 156
    pub ClearRexxMsg: unsafe extern "C" fn(*mut RexxSysIFace, *mut RexxMsg, u32), // 25: 160
    pub FillRexxMsg: unsafe extern "C" fn(*mut RexxSysIFace, *mut RexxMsg, u32, u32) -> u32, // 26: 164
    pub IsRexxMsg: unsafe extern "C" fn(*mut RexxSysIFace, *mut APTR) -> u32, // 27: 168
    pub Private17: APTR, // 28: 172
    pub Private18: APTR, // 29: 176
    pub Private19: APTR, // 30: 180
    pub Private20: APTR, // 31: 184
    pub Private21: APTR, // 32: 188
    pub Private22: APTR, // 33: 192
    pub Private23: APTR, // 34: 196
    pub Private24: APTR, // 35: 200
    pub Private25: APTR, // 36: 204
    pub Private26: APTR, // 37: 208
    pub Private27: APTR, // 38: 212
    pub Private28: APTR, // 39: 216
    pub Private29: APTR, // 40: 220
    pub Private30: APTR, // 41: 224
    pub Private31: APTR, // 42: 228
    pub Private32: APTR, // 43: 232
    pub Private33: APTR, // 44: 236
    pub Private34: APTR, // 45: 240
    pub Private35: APTR, // 46: 244
    pub Private36: APTR, // 47: 248
    pub Private37: APTR, // 48: 252
    pub Private38: APTR, // 49: 256
    pub Private39: APTR, // 50: 260
    pub Private40: APTR, // 51: 264
    pub Private41: APTR, // 52: 268
    pub Private42: APTR, // 53: 272
    pub Private43: APTR, // 54: 276
    pub Private44: APTR, // 55: 280
    pub Private45: APTR, // 56: 284
    pub Private46: APTR, // 57: 288
    pub Private47: APTR, // 58: 292
    pub Private48: APTR, // 59: 296
    pub Private49: APTR, // 60: 300
    pub Private50: APTR, // 61: 304
    pub Private51: APTR, // 62: 308
    pub Private52: APTR, // 63: 312
    pub Private53: APTR, // 64: 316
    pub Private54: APTR, // 65: 320
    pub Private55: APTR, // 66: 324
    pub Private56: APTR, // 67: 328
    pub Private57: APTR, // 68: 332
    pub Private58: APTR, // 69: 336
    pub Private59: APTR, // 70: 340
    pub Private60: APTR, // 71: 344
    pub Private61: APTR, // 72: 348
    pub Private62: APTR, // 73: 352
    pub LockRexxBase: unsafe extern "C" fn(*mut RexxSysIFace, u32), // 74: 356
    pub UnlockRexxBase: unsafe extern "C" fn(*mut RexxSysIFace, u32), // 75: 360
    pub Private63: APTR, // 76: 364
    pub Private64: APTR, // 77: 368
    pub Private65: APTR, // 78: 372
    pub CreateRexxHostPort: unsafe extern "C" fn(*mut RexxSysIFace, CONST_STRPTR) -> *mut MsgPort, // 79: 376
    pub DeleteRexxHostPort: unsafe extern "C" fn(*mut RexxSysIFace, *mut MsgPort), // 80: 380
    pub GetRexxVarFromMsg: unsafe extern "C" fn(*mut RexxSysIFace, CONST_STRPTR, STRPTR, *mut RexxMsg) -> i32, // 81: 384
    pub SetRexxVarFromMsg: unsafe extern "C" fn(*mut RexxSysIFace, CONST_STRPTR, CONST_STRPTR, *mut RexxMsg) -> i32, // 82: 388
    pub LaunchRexxScript: unsafe extern "C" fn(*mut RexxSysIFace, CONST_STRPTR, *mut MsgPort, CONST_STRPTR, u32, u32) -> *mut RexxMsg, // 83: 392
    pub FreeRexxMsg: unsafe extern "C" fn(*mut RexxSysIFace, *mut RexxMsg), // 84: 396
}

