//! ScreenBlankerIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ScreenBlankerIFace (screenblanker.h) ----

#[repr(C)]
pub struct ScreenBlankerIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ScreenBlankerIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ScreenBlankerIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut ScreenBlankerIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut ScreenBlankerIFace) -> *mut IScreenBlanker, // 3: 72
    pub OpenBlankerModuleA: unsafe extern "C" fn(*mut ScreenBlankerIFace, CONST_STRPTR, *mut TagItem) -> u32, // 4: 76
    pub OpenBlankerModule: APTR, // 5: 80 (varargs)
    pub CloseBlankerModule: unsafe extern "C" fn(*mut ScreenBlankerIFace), // 6: 84
    pub SetBlankingMode: unsafe extern "C" fn(*mut ScreenBlankerIFace, u32) -> u32, // 7: 88
    pub SetScreenBlankerAttrsA: unsafe extern "C" fn(*mut ScreenBlankerIFace, *mut TagItem) -> u32, // 8: 92
    pub SetScreenBlankerAttrs: APTR, // 9: 96 (varargs)
    pub GetScreenBlankerAttrsA: unsafe extern "C" fn(*mut ScreenBlankerIFace, *mut TagItem) -> u32, // 10: 100
    pub GetScreenBlankerAttrs: APTR, // 11: 104 (varargs)
}

