//! ScrollerIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ScrollerIFace (scroller.h) ----

#[repr(C)]
pub struct ScrollerIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ScrollerIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ScrollerIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut ScrollerIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut ScrollerIFace) -> *mut Interface, // 3: 72
    pub SCROLLER_GetClass: unsafe extern "C" fn(*mut ScrollerIFace) -> *mut APTR, // 4: 76
}

