//! SketchBoardIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- SketchBoardIFace (sketchboard.h) ----

#[repr(C)]
pub struct SketchBoardIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut SketchBoardIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut SketchBoardIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut SketchBoardIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut SketchBoardIFace) -> *mut Interface, // 3: 72
    pub SKETCHBOARD_GetClass: unsafe extern "C" fn(*mut SketchBoardIFace) -> *mut APTR, // 4: 76
}

