//! SliderIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- SliderIFace (slider.h) ----

#[repr(C)]
pub struct SliderIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut SliderIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut SliderIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut SliderIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut SliderIFace) -> *mut Interface, // 3: 72
    pub SLIDER_GetClass: unsafe extern "C" fn(*mut SliderIFace) -> *mut APTR, // 4: 76
}

