//! SpaceIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- SpaceIFace (space.h) ----

#[repr(C)]
pub struct SpaceIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut SpaceIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut SpaceIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut SpaceIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut SpaceIFace) -> *mut Interface, // 3: 72
    pub SPACE_GetClass: unsafe extern "C" fn(*mut SpaceIFace) -> *mut APTR, // 4: 76
}

