//! SpeedBarIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- SpeedBarIFace (speedbar.h) ----

#[repr(C)]
pub struct SpeedBarIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut SpeedBarIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut SpeedBarIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut SpeedBarIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut SpeedBarIFace) -> *mut Interface, // 3: 72
    pub SPEEDBAR_GetClass: unsafe extern "C" fn(*mut SpeedBarIFace) -> *mut APTR, // 4: 76
    pub AllocSpeedButtonNodeA: unsafe extern "C" fn(*mut SpeedBarIFace, u16, *mut TagItem) -> *mut Node, // 5: 80
    pub AllocSpeedButtonNode: APTR, // 6: 84 (varargs)
    pub FreeSpeedButtonNode: unsafe extern "C" fn(*mut SpeedBarIFace, *mut Node), // 7: 88
    pub SetSpeedButtonNodeAttrsA: unsafe extern "C" fn(*mut SpeedBarIFace, *mut Node, *mut TagItem), // 8: 92
    pub SetSpeedButtonNodeAttrs: APTR, // 9: 96 (varargs)
    pub GetSpeedButtonNodeAttrsA: unsafe extern "C" fn(*mut SpeedBarIFace, *mut Node, *mut TagItem), // 10: 100
    pub GetSpeedButtonNodeAttrs: APTR, // 11: 104 (varargs)
}

