//! StringIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- StringIFace (string.h) ----

#[repr(C)]
pub struct StringIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut StringIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut StringIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut StringIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut StringIFace) -> *mut Interface, // 3: 72
    pub STRING_GetClass: unsafe extern "C" fn(*mut StringIFace) -> *mut APTR, // 4: 76
}

