//! TextClipIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- TextClipIFace (textclip.h) ----

#[repr(C)]
pub struct TextClipIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut TextClipIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut TextClipIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut TextClipIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut TextClipIFace) -> *mut Interface, // 3: 72
    pub WriteClipVector: unsafe extern "C" fn(*mut TextClipIFace, CONST_STRPTR, u32) -> i32, // 4: 76
    pub ReadClipVector: unsafe extern "C" fn(*mut TextClipIFace, *mut STRPTR, *mut u32) -> i32, // 5: 80
    pub DisposeClipVector: unsafe extern "C" fn(*mut TextClipIFace, STRPTR), // 6: 84
}

