//! TextEditorIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- TextEditorIFace (texteditor.h) ----

#[repr(C)]
pub struct TextEditorIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut TextEditorIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut TextEditorIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut TextEditorIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut TextEditorIFace) -> *mut Interface, // 3: 72
    pub TEXTEDITOR_GetClass: unsafe extern "C" fn(*mut TextEditorIFace) -> *mut APTR, // 4: 76
}

