//! TimerIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- TimerIFace (timer.h) ----

#[repr(C)]
pub struct TimerIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut TimerIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut TimerIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut TimerIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut TimerIFace) -> *mut Interface, // 3: 72
    pub AddTime: unsafe extern "C" fn(*mut TimerIFace, *mut TimeVal, *const TimeVal), // 4: 76
    pub SubTime: unsafe extern "C" fn(*mut TimerIFace, *mut TimeVal, *const TimeVal), // 5: 80
    pub CmpTime: unsafe extern "C" fn(*mut TimerIFace, *mut TimeVal, *const TimeVal) -> i32, // 6: 84
    pub ReadEClock: unsafe extern "C" fn(*mut TimerIFace, *mut EClockVal) -> u32, // 7: 88
    pub GetSysTime: unsafe extern "C" fn(*mut TimerIFace, *mut TimeVal), // 8: 92
    pub GetUpTime: unsafe extern "C" fn(*mut TimerIFace, *mut TimeVal), // 9: 96
    pub MicroDelay: unsafe extern "C" fn(*mut TimerIFace, u32), // 10: 100
}

