//! TimesyncIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- TimesyncIFace (timesync.h) ----

#[repr(C)]
pub struct TimesyncIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut TimesyncIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut TimesyncIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut TimesyncIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut TimesyncIFace) -> *mut Interface, // 3: 72
    pub RemoteSyncA: unsafe extern "C" fn(*mut TimesyncIFace, *const TagItem) -> u32, // 4: 76
    pub RemoteSync: APTR, // 5: 80 (varargs)
}

