//! TimezoneIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- TimezoneIFace (timezone.h) ----

#[repr(C)]
pub struct TimezoneIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut TimezoneIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut TimezoneIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut TimezoneIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut TimezoneIFace) -> *mut Interface, // 3: 72
    pub GetTimezoneAttrsA: unsafe extern "C" fn(*mut TimezoneIFace, APTR, *const TagItem) -> u32, // 4: 76
    pub GetTimezoneAttrs: APTR, // 5: 80 (varargs)
    pub ParseZone: unsafe extern "C" fn(*mut TimezoneIFace, CONST_STRPTR) -> u32, // 6: 84
    pub GetUTCTime: unsafe extern "C" fn(*mut TimezoneIFace, *mut TimeVal) -> u32, // 7: 88
    pub SetTimezoneAttrsA: unsafe extern "C" fn(*mut TimezoneIFace, APTR, *const TagItem) -> u32, // 8: 92
    pub SetTimezoneAttrs: APTR, // 9: 96 (varargs)
}

