//! USBFDIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- USBFDIFace (usbfd.h) ----

#[repr(C)]
pub struct USBFDIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut USBFDIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut USBFDIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut USBFDIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut USBFDIFace) -> *mut Interface, // 3: 72
    pub USBFDGetAttrsA: unsafe extern "C" fn(*mut USBFDIFace, *mut TagItem), // 4: 76
    pub USBFDGetAttrs: APTR, // 5: 80 (varargs)
    pub USBFDRunFunction: unsafe extern "C" fn(*mut USBFDIFace, *mut USBFDStartupMsg) -> i32, // 6: 84
    pub USBFDRunInterface: unsafe extern "C" fn(*mut USBFDIFace, *mut USBFDStartupMsg) -> i32, // 7: 88
}

