//! USBHCDIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- USBHCDIFace (usbhcd.h) ----

#[repr(C)]
pub struct USBHCDIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut USBHCDIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut USBHCDIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut USBHCDIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut USBHCDIFace) -> *mut Interface, // 3: 72
    pub USBHCAddFunctionA: unsafe extern "C" fn(*mut USBHCDIFace, APTR, APTR, APTR, *mut TagItem) -> APTR, // 4: 76
    pub USBHCAddFunction: APTR, // 5: 80 (varargs)
    pub USBHCRemFunction: unsafe extern "C" fn(*mut USBHCDIFace, APTR, APTR), // 6: 84
    pub USBHCAddEndPointA: unsafe extern "C" fn(*mut USBHCDIFace, APTR, APTR, APTR, i32, *mut TagItem) -> APTR, // 7: 88
    pub USBHCAddEndPoint: APTR, // 8: 92 (varargs)
    pub USBHCRemEndPoint: unsafe extern "C" fn(*mut USBHCDIFace, APTR, APTR), // 9: 96
    pub USBHCGetAttrsA: unsafe extern "C" fn(*mut USBHCDIFace, *mut TagItem), // 10: 100
    pub USBHCGetAttrs: APTR, // 11: 104 (varargs)
    pub USBHCInitRootHubA: unsafe extern "C" fn(*mut USBHCDIFace, APTR, *mut UsbRawInterface, *mut APTR, *mut TagItem) -> i32, // 12: 108
    pub USBHCInitRootHub: APTR, // 13: 112 (varargs)
    pub USBHCUninitRootHub: unsafe extern "C" fn(*mut USBHCDIFace, APTR, APTR), // 14: 116
    pub USBHCGetFrameNumber: unsafe extern "C" fn(*mut USBHCDIFace, APTR, *mut TimeVal) -> u32, // 15: 120
    pub USBHCGetUnitAttrsA: unsafe extern "C" fn(*mut USBHCDIFace, APTR, *mut TagItem), // 16: 124
    pub USBHCGetUnitAttrs: APTR, // 17: 128 (varargs)
}

