//! USBResourceIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- USBResourceIFace (usbresource.h) ----

#[repr(C)]
pub struct USBResourceIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut USBResourceIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut USBResourceIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut USBResourceIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut USBResourceIFace) -> *mut Interface, // 3: 72
    pub USBResRegisterFDA: unsafe extern "C" fn(*mut USBResourceIFace, *mut TagItem) -> APTR, // 4: 76
    pub USBResRegisterFD: APTR, // 5: 80 (varargs)
    pub USBResUnregisterFD: unsafe extern "C" fn(*mut USBResourceIFace, APTR), // 6: 84
    pub USBResRegisterHCDA: unsafe extern "C" fn(*mut USBResourceIFace, *mut TagItem) -> APTR, // 7: 88
    pub USBResRegisterHCD: APTR, // 8: 92 (varargs)
    pub USBResUnregisterHCD: unsafe extern "C" fn(*mut USBResourceIFace, APTR), // 9: 96
    pub Reserved1: unsafe extern "C" fn(*mut USBResourceIFace), // 10: 100
    pub Reserved2: unsafe extern "C" fn(*mut USBResourceIFace), // 11: 104
    pub Reserved3: unsafe extern "C" fn(*mut USBResourceIFace), // 12: 108
    pub Reserved4: unsafe extern "C" fn(*mut USBResourceIFace), // 13: 112
    pub Reserved5: unsafe extern "C" fn(*mut USBResourceIFace), // 14: 116
    pub Reserved6: unsafe extern "C" fn(*mut USBResourceIFace), // 15: 120
    pub USBResAddNotify: unsafe extern "C" fn(*mut USBResourceIFace, u32, *mut MsgPort) -> APTR, // 16: 124
    pub USBResRemNotify: unsafe extern "C" fn(*mut USBResourceIFace, APTR), // 17: 128
    pub Reserved7: unsafe extern "C" fn(*mut USBResourceIFace), // 18: 132
    pub Reserved8: unsafe extern "C" fn(*mut USBResourceIFace), // 19: 136
    pub Reserved9: unsafe extern "C" fn(*mut USBResourceIFace), // 20: 140
    pub Reserved10: unsafe extern "C" fn(*mut USBResourceIFace), // 21: 144
}

