//! USBSysIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- USBSysIFace (usbsys.h) ----

#[repr(C)]
pub struct USBSysIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut USBSysIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut USBSysIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut USBSysIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut USBSysIFace) -> *mut Interface, // 3: 72
    pub USBAllocRequestA: unsafe extern "C" fn(*mut USBSysIFace, *mut IORequest, *mut TagItem) -> *mut USBIOReq, // 4: 76
    pub USBAllocRequest: APTR, // 5: 80 (varargs)
    pub USBFreeRequest: unsafe extern "C" fn(*mut USBSysIFace, *mut USBIOReq), // 6: 84
    pub USBFindFunctionA: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbRawFunction, *mut TagItem) -> *mut UsbRawFunction, // 7: 88
    pub USBFindFunction: APTR, // 8: 92 (varargs)
    pub USBLockFunction: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbRawFunction), // 9: 96
    pub USBUnlockFunction: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbRawFunction), // 10: 100
    pub USBClaimFunction: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbRawFunction, APTR, *mut MsgPort) -> *mut UsbFunction, // 11: 104
    pub USBDeclaimFunction: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbFunction), // 12: 108
    pub USBAddFunctionA: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbInterface, *mut TagItem) -> *mut UsbRawFunction, // 13: 112
    pub USBAddFunction: APTR, // 14: 116 (varargs)
    pub USBRemFunction: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbRawFunction, *mut UsbInterface), // 15: 120
    pub USBGetEndPoint: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbFunction, *mut UsbInterface, i32) -> *mut UsbEndPoint, // 16: 124
    pub USBEPControlXferA: unsafe extern "C" fn(*mut USBSysIFace, *mut IORequest, *mut UsbEndPoint, u32, u32, u32, u32, APTR, u32, *mut TagItem) -> i32, // 17: 128
    pub USBEPControlXfer: APTR, // 18: 132 (varargs)
    pub USBEPGetDescriptorA: unsafe extern "C" fn(*mut USBSysIFace, *mut IORequest, *mut UsbEndPoint, u32, i32, i32, *mut TagItem) -> *mut USBBusDscHead, // 19: 136
    pub USBEPGetDescriptor: APTR, // 20: 140 (varargs)
    pub USBFktGetCfgDescriptorsA: unsafe extern "C" fn(*mut USBSysIFace, *mut IORequest, *mut UsbFunction, u32, *mut TagItem) -> *mut USBBusCfgDsc, // 21: 144
    pub USBFktGetCfgDescriptors: APTR, // 22: 148 (varargs)
    pub USBFktSetConfigurationA: unsafe extern "C" fn(*mut USBSysIFace, *mut IORequest, *mut UsbFunction, *mut USBBusCfgDsc, *mut TagItem) -> i32, // 23: 152
    pub USBFktSetConfiguration: APTR, // 24: 156 (varargs)
    pub USBParseDescriptors: unsafe extern "C" fn(*mut USBSysIFace, *mut USBBusDscHead, u32) -> *mut USBBusDscHead, // 25: 160
    pub USBFreeDescriptors: unsafe extern "C" fn(*mut USBSysIFace, *mut USBBusDscHead), // 26: 164
    pub USBNextDescriptor: unsafe extern "C" fn(*mut USBSysIFace, *mut USBBusDscHead) -> *mut USBBusDscHead, // 27: 168
    pub USBPrevDescriptor: unsafe extern "C" fn(*mut USBSysIFace, *mut USBBusDscHead) -> *mut USBBusDscHead, // 28: 172
    pub USBObtainResourceA: unsafe extern "C" fn(*mut USBSysIFace, u32, APTR, *mut TagItem) -> i32, // 29: 176
    pub USBObtainResource: APTR, // 30: 180 (varargs)
    pub USBReleaseResource: unsafe extern "C" fn(*mut USBSysIFace, u32, APTR), // 31: 184
    pub USBFindInterfaceA: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbRawInterface, *mut TagItem) -> *mut UsbRawInterface, // 32: 188
    pub USBFindInterface: APTR, // 33: 192 (varargs)
    pub USBLockInterface: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbRawInterface), // 34: 196
    pub USBUnlockInterface: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbRawInterface), // 35: 200
    pub USBClaimInterface: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbRawInterface, APTR, *mut MsgPort) -> *mut UsbInterface, // 36: 204
    pub USBDeclaimInterface: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbInterface), // 37: 208
    pub USBGetInterface: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbFunction, i32) -> *mut UsbInterface, // 38: 212
    pub USBIntGetConfigurationA: unsafe extern "C" fn(*mut USBSysIFace, *mut IORequest, *mut UsbInterface, *mut TagItem) -> *mut USBBusDscHead, // 39: 216
    pub USBIntGetConfiguration: APTR, // 40: 220 (varargs)
    pub USBIntGetAltSettingA: unsafe extern "C" fn(*mut USBSysIFace, *mut IORequest, *mut UsbInterface, *mut TagItem) -> *mut USBBusDscHead, // 41: 224
    pub USBIntGetAltSetting: APTR, // 42: 228 (varargs)
    pub USBIntSetAltSettingA: unsafe extern "C" fn(*mut USBSysIFace, *mut IORequest, *mut UsbInterface, u32, *mut TagItem) -> i32, // 43: 232
    pub USBIntSetAltSetting: APTR, // 44: 236 (varargs)
    pub USBLogPuts: unsafe extern "C" fn(*mut USBSysIFace, i32, CONST_STRPTR, CONST_STRPTR), // 45: 240
    pub USBLogVPrintf: unsafe extern "C" fn(*mut USBSysIFace, i32, CONST_STRPTR, CONST_STRPTR, *mut u32), // 46: 244
    pub USBSetFunctionAttrsA: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbFunction, *mut TagItem) -> i32, // 47: 248
    pub USBSetFunctionAttrs: APTR, // 48: 252 (varargs)
    pub USBSetInterfaceAttrsA: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbInterface, *mut TagItem) -> i32, // 49: 256
    pub USBSetInterfaceAttrs: APTR, // 50: 260 (varargs)
    pub USBGetStackAttrsA: unsafe extern "C" fn(*mut USBSysIFace, *mut TagItem), // 51: 264
    pub USBGetStackAttrs: APTR, // 52: 268 (varargs)
    pub USBGetRawFunctionAttrsA: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbRawFunction, *mut TagItem), // 53: 272
    pub USBGetRawFunctionAttrs: APTR, // 54: 276 (varargs)
    pub USBGetRawInterfaceAttrsA: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbRawInterface, *mut TagItem), // 55: 280
    pub USBGetRawInterfaceAttrs: APTR, // 56: 284 (varargs)
    pub USBFktDriverRunning: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbFunction), // 57: 288
    pub USBIfcDriverRunning: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbInterface), // 58: 292
    pub USBEPDestall: unsafe extern "C" fn(*mut USBSysIFace, *mut IORequest, *mut UsbEndPoint) -> i32, // 59: 296
    pub USBAllocObjectTags: APTR, // 60: 300 (varargs)
    pub USBAllocObject: unsafe extern "C" fn(*mut USBSysIFace, u32, *mut TagItem) -> APTR, // 61: 304
    pub USBFreeObject: unsafe extern "C" fn(*mut USBSysIFace, u32, APTR), // 62: 308
    pub USBLogPrintf: APTR, // 63: 312 (varargs)
    pub USBScanA: unsafe extern "C" fn(*mut USBSysIFace, u32, *mut Hook, *mut TagItem) -> i32, // 64: 316
    pub USBScan: APTR, // 65: 320 (varargs)
    pub USBGetEndPointAttrsA: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbEndPoint, *mut TagItem), // 66: 324
    pub USBGetEndPointAttrs: APTR, // 67: 328 (varargs)
    pub USBGetFrameNumber: unsafe extern "C" fn(*mut USBSysIFace, *mut UsbEndPoint, *mut TimeVal) -> u32, // 68: 332
    pub USBSetIsoTransferCount: unsafe extern "C" fn(*mut USBSysIFace, *mut USBIOReq, u32) -> u32, // 69: 336
    pub USBSetIsoTransferSetup: unsafe extern "C" fn(*mut USBSysIFace, *mut USBIOReq, u32, u32, u32) -> u32, // 70: 340
    pub USBGetIsoTransferResult: unsafe extern "C" fn(*mut USBSysIFace, *mut USBIOReq, u32, *mut *mut USBTransferSetup) -> *mut USBTransferResult, // 71: 344
    pub USBGetIsoTransferSetupHcd: unsafe extern "C" fn(*mut USBSysIFace, *mut USBIOReqHCD, u32) -> *mut USBTransferSetup, // 72: 348
    pub USBSetIsoTransferResultHcd: unsafe extern "C" fn(*mut USBSysIFace, *mut USBIOReqHCD, u32, u32, i32) -> u32, // 73: 352
}

