//! UtilityIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- UtilityIFace (utility.h) ----

#[repr(C)]
pub struct UtilityIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut UtilityIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut UtilityIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub AllocateTagItems: unsafe extern "C" fn(*mut UtilityIFace, u32) -> *mut TagItem, // 4: 76
    pub ApplyTagChanges: unsafe extern "C" fn(*mut UtilityIFace, *mut TagItem, *const TagItem), // 5: 80
    pub CloneTagItems: unsafe extern "C" fn(*mut UtilityIFace, *const TagItem) -> *mut TagItem, // 6: 84
    pub FilterTagChanges: unsafe extern "C" fn(*mut UtilityIFace, *mut TagItem, *mut TagItem, u32), // 7: 88
    pub FilterTagItems: unsafe extern "C" fn(*mut UtilityIFace, *mut TagItem, *const u32, u32) -> u32, // 8: 92
    pub FindTagItem: unsafe extern "C" fn(*mut UtilityIFace, u32, *const TagItem) -> *mut TagItem, // 9: 96
    pub FreeTagItems: unsafe extern "C" fn(*mut UtilityIFace, *mut TagItem), // 10: 100
    pub GetTagData: unsafe extern "C" fn(*mut UtilityIFace, u32, u32, *const TagItem) -> u32, // 11: 104
    pub MapTags: unsafe extern "C" fn(*mut UtilityIFace, *mut TagItem, *const TagItem, u32), // 12: 108
    pub NextTagItem: unsafe extern "C" fn(*mut UtilityIFace, *mut *mut TagItem) -> *mut TagItem, // 13: 112
    pub PackBoolTags: unsafe extern "C" fn(*mut UtilityIFace, u32, *const TagItem, *const TagItem) -> u32, // 14: 116
    pub RefreshTagItemClones: unsafe extern "C" fn(*mut UtilityIFace, *mut TagItem, *const TagItem), // 15: 120
    pub TagInArray: unsafe extern "C" fn(*mut UtilityIFace, u32, *const u32) -> u32, // 16: 124
    pub CallHookPkt: unsafe extern "C" fn(*mut UtilityIFace, *mut Hook, APTR, APTR) -> u32, // 17: 128
    pub CallHook: APTR, // 18: 132 (varargs)
    pub AddNamedObject: unsafe extern "C" fn(*mut UtilityIFace, *mut NamedObject, *mut NamedObject) -> u32, // 19: 136
    pub AllocNamedObjectA: unsafe extern "C" fn(*mut UtilityIFace, CONST_STRPTR, *const TagItem) -> *mut NamedObject, // 20: 140
    pub AllocNamedObject: APTR, // 21: 144 (varargs)
    pub AttemptRemNamedObject: unsafe extern "C" fn(*mut UtilityIFace, *mut NamedObject) -> i32, // 22: 148
    pub FindNamedObject: unsafe extern "C" fn(*mut UtilityIFace, *mut NamedObject, CONST_STRPTR, *mut NamedObject) -> *mut NamedObject, // 23: 152
    pub FreeNamedObject: unsafe extern "C" fn(*mut UtilityIFace, *mut NamedObject) -> *mut NamedObject, // 24: 156
    pub NamedObjectName: unsafe extern "C" fn(*mut UtilityIFace, *mut NamedObject) -> STRPTR, // 25: 160
    pub ReleaseNamedObject: unsafe extern "C" fn(*mut UtilityIFace, *mut NamedObject), // 26: 164
    pub RemNamedObject: unsafe extern "C" fn(*mut UtilityIFace, *mut NamedObject, *mut Message), // 27: 168
    pub Amiga2Date: unsafe extern "C" fn(*mut UtilityIFace, u32, *mut ClockData), // 28: 172
    pub CheckDate: unsafe extern "C" fn(*mut UtilityIFace, *const ClockData) -> u32, // 29: 176
    pub Date2Amiga: unsafe extern "C" fn(*mut UtilityIFace, *const ClockData) -> u32, // 30: 180
    pub CreateSkipList: unsafe extern "C" fn(*mut UtilityIFace, *mut Hook, i32) -> *mut SkipList, // 31: 184
    pub DeleteSkipList: unsafe extern "C" fn(*mut UtilityIFace, *mut SkipList), // 32: 188
    pub FindSkipNode: unsafe extern "C" fn(*mut UtilityIFace, *const SkipList, APTR) -> *mut SkipNode, // 33: 192
    pub GetFirstSkipNode: unsafe extern "C" fn(*mut UtilityIFace, *const SkipList) -> *mut SkipNode, // 34: 196
    pub GetNextSkipNode: unsafe extern "C" fn(*mut UtilityIFace, *const SkipList, *const SkipNode) -> *mut SkipNode, // 35: 200
    pub InsertSkipNode: unsafe extern "C" fn(*mut UtilityIFace, *mut SkipList, APTR, u32) -> *mut SkipNode, // 36: 204
    pub RemoveSkipNode: unsafe extern "C" fn(*mut UtilityIFace, *mut SkipList, APTR) -> u32, // 37: 208
    pub CreateSplayTree: unsafe extern "C" fn(*mut UtilityIFace, *mut Hook) -> *mut SplayTree, // 38: 212
    pub DeleteSplayTree: unsafe extern "C" fn(*mut UtilityIFace, *mut SplayTree), // 39: 216
    pub FindSplayNode: unsafe extern "C" fn(*mut UtilityIFace, *const SplayTree, APTR) -> *mut SplayNode, // 40: 220
    pub InsertSplayNode: unsafe extern "C" fn(*mut UtilityIFace, *mut SplayTree, APTR, u32) -> *mut SplayNode, // 41: 224
    pub RemoveSplayNode: unsafe extern "C" fn(*mut UtilityIFace, *mut SplayTree, APTR) -> *mut SplayNode, // 42: 228
    pub FindNameNC: unsafe extern "C" fn(*mut UtilityIFace, *mut List, CONST_STRPTR) -> *mut Node, // 43: 232
    pub GetUniqueID: unsafe extern "C" fn(*mut UtilityIFace) -> u32, // 44: 236
    pub MessageDigest_SHA_Final: unsafe extern "C" fn(*mut UtilityIFace, *mut MessageDigest_SHA), // 45: 240
    pub MessageDigest_SHA_Init: unsafe extern "C" fn(*mut UtilityIFace, *mut MessageDigest_SHA), // 46: 244
    pub MessageDigest_SHA_Update: unsafe extern "C" fn(*mut UtilityIFace, *mut MessageDigest_SHA, APTR, i32), // 47: 248
    pub PackStructureTags: unsafe extern "C" fn(*mut UtilityIFace, APTR, *const u32, *const TagItem) -> u32, // 48: 252
    pub UnpackStructureTags: unsafe extern "C" fn(*mut UtilityIFace, CONST_APTR, *const u32, *mut TagItem) -> u32, // 49: 256
    pub Random: unsafe extern "C" fn(*mut UtilityIFace, *mut RandomState) -> u32, // 50: 260
    pub SetMem: unsafe extern "C" fn(*mut UtilityIFace, APTR, u8, i32) -> APTR, // 51: 264
    pub Stricmp: unsafe extern "C" fn(*mut UtilityIFace, CONST_STRPTR, CONST_STRPTR) -> i32, // 52: 268
    pub Strlcpy: unsafe extern "C" fn(*mut UtilityIFace, STRPTR, CONST_STRPTR, i32) -> i32, // 53: 272
    pub Strlcat: unsafe extern "C" fn(*mut UtilityIFace, STRPTR, CONST_STRPTR, i32) -> i32, // 54: 276
    pub Strnicmp: unsafe extern "C" fn(*mut UtilityIFace, CONST_STRPTR, CONST_STRPTR, i32) -> i32, // 55: 280
    pub ToLower: unsafe extern "C" fn(*mut UtilityIFace, APTR) -> u32, // 56: 284
    pub ToUpper: unsafe extern "C" fn(*mut UtilityIFace, APTR) -> u32, // 57: 288
    pub VASPrintf: unsafe extern "C" fn(*mut UtilityIFace, CONST_STRPTR, APTR) -> STRPTR, // 58: 292
    pub ASPrintf: APTR, // 59: 296 (varargs)
    pub VSNPrintf: unsafe extern "C" fn(*mut UtilityIFace, STRPTR, i32, CONST_STRPTR, APTR) -> i32, // 60: 300
    pub SNPrintf: APTR, // 61: 304 (varargs)
    pub ClearMem: unsafe extern "C" fn(*mut UtilityIFace, APTR, u32), // 62: 308
    pub MoveMem: unsafe extern "C" fn(*mut UtilityIFace, CONST_APTR, APTR, u32), // 63: 312
    pub Strlen: unsafe extern "C" fn(*mut UtilityIFace, CONST_STRPTR) -> u32, // 64: 316
    pub UTF8toUCS4: unsafe extern "C" fn(*mut UtilityIFace, CONST_STRPTR, *mut i32, i32, u32) -> i32, // 65: 320
    pub UCS4toUTF8: unsafe extern "C" fn(*mut UtilityIFace, *const i32, STRPTR, i32, u32) -> i32, // 66: 324
    pub UTF8Strnicmp: unsafe extern "C" fn(*mut UtilityIFace, CONST_STRPTR, CONST_STRPTR, i32) -> i32, // 67: 328
    pub UTF8Stricmp: unsafe extern "C" fn(*mut UtilityIFace, CONST_STRPTR, CONST_STRPTR) -> i32, // 68: 332
    pub UTF8Count: unsafe extern "C" fn(*mut UtilityIFace, CONST_STRPTR, i32) -> i32, // 69: 336
    pub UCS4Count: unsafe extern "C" fn(*mut UtilityIFace, *const i32, i32) -> i32, // 70: 340
    pub UTF8Encode: unsafe extern "C" fn(*mut UtilityIFace, i32, STRPTR, i32, u32) -> i32, // 71: 344
    pub UTF8Decode: unsafe extern "C" fn(*mut UtilityIFace, *mut CONST_STRPTR, u32) -> i32, // 72: 348
    pub UCS4ToLower: unsafe extern "C" fn(*mut UtilityIFace, i32) -> i32, // 73: 352
    pub UCS4ToUpper: unsafe extern "C" fn(*mut UtilityIFace, i32) -> i32, // 74: 356
    pub UCS4Valid: unsafe extern "C" fn(*mut UtilityIFace, i32) -> i32, // 75: 360
    pub SortList: unsafe extern "C" fn(*mut UtilityIFace, *mut List, *mut Hook), // 76: 364
    pub SortMinList: unsafe extern "C" fn(*mut UtilityIFace, *mut MinList, *mut Hook), // 77: 368
}

