//! VersionIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- VersionIFace (version.h) ----

#[repr(C)]
pub struct VersionIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut VersionIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut VersionIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut VersionIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut VersionIFace) -> *mut Interface, // 3: 72
    pub GetReleaseString: unsafe extern "C" fn(*mut VersionIFace) -> CONST_STRPTR, // 4: 76
    pub GetOSString: unsafe extern "C" fn(*mut VersionIFace) -> CONST_STRPTR, // 5: 80
    pub GetCopyrightString: unsafe extern "C" fn(*mut VersionIFace) -> CONST_STRPTR, // 6: 84
    pub GetCompanyString: unsafe extern "C" fn(*mut VersionIFace) -> CONST_STRPTR, // 7: 88
    pub GetLocalizedReleaseString: unsafe extern "C" fn(*mut VersionIFace) -> CONST_STRPTR, // 8: 92
    pub GetLocalizedOSString: unsafe extern "C" fn(*mut VersionIFace) -> CONST_STRPTR, // 9: 96
    pub GetLocalizedCopyrightString: unsafe extern "C" fn(*mut VersionIFace) -> CONST_STRPTR, // 10: 100
    pub GetLocalizedCompanyString: unsafe extern "C" fn(*mut VersionIFace) -> CONST_STRPTR, // 11: 104
}

