//! VirtualIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- VirtualIFace (virtual.h) ----

#[repr(C)]
pub struct VirtualIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut VirtualIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut VirtualIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut VirtualIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut VirtualIFace) -> *mut Interface, // 3: 72
    pub VIRTUAL_GetClass: unsafe extern "C" fn(*mut VirtualIFace) -> *mut APTR, // 4: 76
    pub RefreshVirtualGadget: unsafe extern "C" fn(*mut VirtualIFace, *mut Gadget, *mut APTR, *mut Window, *mut Requester), // 5: 80
    pub RethinkVirtualSize: unsafe extern "C" fn(*mut VirtualIFace, *mut APTR, *mut APTR, *mut TextFont, *mut Screen, *mut LayoutLimits) -> u32, // 6: 84
}

