//! XadMasterIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- XadMasterIFace (xadmaster.h) ----

#[repr(C)]
pub struct XadMasterIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut XadMasterIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut XadMasterIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut XadMasterIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut XadMasterIFace) -> *mut Interface, // 3: 72
    pub xadAllocObjectA: unsafe extern "C" fn(*mut XadMasterIFace, APTR, *const TagItem) -> APTR, // 4: 76
    pub xadAllocObject: APTR, // 5: 80 (varargs)
    pub xadFreeObjectA: unsafe extern "C" fn(*mut XadMasterIFace, APTR, *const TagItem), // 6: 84
    pub xadFreeObject: APTR, // 7: 88 (varargs)
    pub xadRecogFileA: unsafe extern "C" fn(*mut XadMasterIFace, APTR, *const (), *const TagItem) -> *mut xadClient, // 8: 92
    pub xadRecogFile: APTR, // 9: 96 (varargs)
    pub xadGetInfoA: unsafe extern "C" fn(*mut XadMasterIFace, *mut xadArchiveInfo, *const TagItem) -> APTR, // 10: 100
    pub xadGetInfo: APTR, // 11: 104 (varargs)
    pub xadFreeInfo: unsafe extern "C" fn(*mut XadMasterIFace, *mut xadArchiveInfo), // 12: 108
    pub xadFileUnArcA: unsafe extern "C" fn(*mut XadMasterIFace, *mut xadArchiveInfo, *const TagItem) -> APTR, // 13: 112
    pub xadFileUnArc: APTR, // 14: 116 (varargs)
    pub xadDiskUnArcA: unsafe extern "C" fn(*mut XadMasterIFace, *mut xadArchiveInfo, *const TagItem) -> APTR, // 15: 120
    pub xadDiskUnArc: APTR, // 16: 124 (varargs)
    pub xadGetErrorText: unsafe extern "C" fn(*mut XadMasterIFace, APTR) -> APTR, // 17: 128
    pub xadGetClientInfo: unsafe extern "C" fn(*mut XadMasterIFace) -> *mut xadClient, // 18: 132
    pub xadHookAccess: unsafe extern "C" fn(*mut XadMasterIFace, APTR, APTR, APTR, *mut xadArchiveInfo) -> APTR, // 19: 136
    pub xadConvertDatesA: unsafe extern "C" fn(*mut XadMasterIFace, *const TagItem) -> APTR, // 20: 140
    pub xadConvertDates: APTR, // 21: 144 (varargs)
    pub xadCalcCRC16: unsafe extern "C" fn(*mut XadMasterIFace, APTR, APTR, APTR, *const APTR) -> APTR, // 22: 148
    pub xadCalcCRC32: unsafe extern "C" fn(*mut XadMasterIFace, APTR, APTR, APTR, *const APTR) -> APTR, // 23: 152
    pub xadAllocVec: unsafe extern "C" fn(*mut XadMasterIFace, APTR, APTR) -> APTR, // 24: 156
    pub xadCopyMem: unsafe extern "C" fn(*mut XadMasterIFace, *const (), APTR, APTR), // 25: 160
    pub xadHookTagAccessA: unsafe extern "C" fn(*mut XadMasterIFace, APTR, APTR, APTR, *mut xadArchiveInfo, *const TagItem) -> APTR, // 26: 164
    pub xadHookTagAccess: APTR, // 27: 168 (varargs)
    pub xadConvertProtectionA: unsafe extern "C" fn(*mut XadMasterIFace, *const TagItem) -> APTR, // 28: 172
    pub xadConvertProtection: APTR, // 29: 176 (varargs)
    pub xadGetDiskInfoA: unsafe extern "C" fn(*mut XadMasterIFace, *mut xadArchiveInfo, *const TagItem) -> APTR, // 30: 180
    pub xadGetDiskInfo: APTR, // 31: 184 (varargs)
    pub xadDiskFileUnArcA: unsafe extern "C" fn(*mut XadMasterIFace, *mut xadArchiveInfo, *const TagItem) -> APTR, // 32: 188
    pub xadDiskFileUnArc: APTR, // 33: 192 (varargs)
    pub xadGetHookAccessA: unsafe extern "C" fn(*mut XadMasterIFace, *mut xadArchiveInfo, *const TagItem) -> APTR, // 34: 196
    pub xadGetHookAccess: APTR, // 35: 200 (varargs)
    pub xadFreeHookAccessA: unsafe extern "C" fn(*mut XadMasterIFace, *mut xadArchiveInfo, *const TagItem), // 36: 204
    pub xadFreeHookAccess: APTR, // 37: 208 (varargs)
    pub xadAddFileEntryA: unsafe extern "C" fn(*mut XadMasterIFace, *mut xadFileInfo, *mut xadArchiveInfo, *const TagItem) -> APTR, // 38: 212
    pub xadAddFileEntry: APTR, // 39: 216 (varargs)
    pub xadAddDiskEntryA: unsafe extern "C" fn(*mut XadMasterIFace, *mut xadDiskInfo, *mut xadArchiveInfo, *const TagItem) -> APTR, // 40: 220
    pub xadAddDiskEntry: APTR, // 41: 224 (varargs)
    pub xadGetFilenameA: unsafe extern "C" fn(*mut XadMasterIFace, APTR, APTR, *const APTR, *const APTR, *const TagItem) -> APTR, // 42: 228
    pub xadGetFilename: APTR, // 43: 232 (varargs)
    pub xadConvertNameA: unsafe extern "C" fn(*mut XadMasterIFace, APTR, *const TagItem) -> APTR, // 44: 236
    pub xadConvertName: APTR, // 45: 240 (varargs)
    pub xadGetDefaultNameA: unsafe extern "C" fn(*mut XadMasterIFace, *const TagItem) -> APTR, // 46: 244
    pub xadGetDefaultName: APTR, // 47: 248 (varargs)
    pub xadGetSystemInfo: unsafe extern "C" fn(*mut XadMasterIFace) -> *const xadSystemInfo, // 48: 252
}

