//! XenaIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- XenaIFace (xena.h) ----

#[repr(C)]
pub struct XenaIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut XenaIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut XenaIFace) -> u32, // 1: 64
    pub Expunge: unsafe extern "C" fn(*mut XenaIFace), // 2: 68
    pub Clone: unsafe extern "C" fn(*mut XenaIFace) -> *mut Interface, // 3: 72
    pub AllocResource: unsafe extern "C" fn(*mut XenaIFace, u32, CONST_STRPTR) -> CONST_STRPTR, // 4: 76
    pub FreeResource: unsafe extern "C" fn(*mut XenaIFace, u32), // 5: 80
}

