//! ZIFace interface vtable struct(s).
//!
//! Auto-generated by amigaos4-bindgen.

use crate::types::*;

// ---- ZIFace (z.h) ----

#[repr(C)]
pub struct ZIFace {
    pub data: InterfaceData,

    pub Obtain: unsafe extern "C" fn(*mut ZIFace) -> u32, // 0: 60
    pub Release: unsafe extern "C" fn(*mut ZIFace) -> u32, // 1: 64
    pub Expunge_UNIMPLEMENTED: APTR, // 2: 68
    pub Clone_UNIMPLEMENTED: APTR, // 3: 72
    pub DeflateInit: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32) -> i32, // 4: 76
    pub Deflate: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32) -> i32, // 5: 80
    pub DeflateEnd: unsafe extern "C" fn(*mut ZIFace, *mut APTR) -> i32, // 6: 84
    pub InflateInit: unsafe extern "C" fn(*mut ZIFace, *mut APTR) -> i32, // 7: 88
    pub Inflate: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32) -> i32, // 8: 92
    pub InflateEnd: unsafe extern "C" fn(*mut ZIFace, *mut APTR) -> i32, // 9: 96
    pub DeflateInit2: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32, i32, i32, i32, i32) -> i32, // 10: 100
    pub DeflateSetDictionary: unsafe extern "C" fn(*mut ZIFace, *mut APTR, *const u8, u32) -> i32, // 11: 104
    pub DeflateCopy: unsafe extern "C" fn(*mut ZIFace, *mut APTR, *mut APTR) -> i32, // 12: 108
    pub DeflateReset: unsafe extern "C" fn(*mut ZIFace, *mut APTR) -> i32, // 13: 112
    pub DeflateParams: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32, i32) -> i32, // 14: 116
    pub DeflateTune: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32, i32, i32, i32) -> i32, // 15: 120
    pub DeflateBound: unsafe extern "C" fn(*mut ZIFace, *mut APTR, u32) -> u32, // 16: 124
    pub DeflatePrime: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32, i32) -> i32, // 17: 128
    pub DeflateSetHeader: unsafe extern "C" fn(*mut ZIFace, *mut APTR, *mut APTR) -> i32, // 18: 132
    pub InflateInit2: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32) -> i32, // 19: 136
    pub InflateSetDictionary: unsafe extern "C" fn(*mut ZIFace, *mut APTR, *const u8, u32) -> i32, // 20: 140
    pub InflateSync: unsafe extern "C" fn(*mut ZIFace, *mut APTR) -> i32, // 21: 144
    pub InflateCopy: unsafe extern "C" fn(*mut ZIFace, *mut APTR, *mut APTR) -> i32, // 22: 148
    pub InflateReset: unsafe extern "C" fn(*mut ZIFace, *mut APTR) -> i32, // 23: 152
    pub InflatePrime: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32, i32) -> i32, // 24: 156
    pub InflateGetHeader: unsafe extern "C" fn(*mut ZIFace, *mut APTR, *mut APTR) -> i32, // 25: 160
    pub InflateBackInit: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32, *mut u8) -> i32, // 26: 164
    pub InflateBack: unsafe extern "C" fn(*mut ZIFace, *mut APTR, APTR, *mut (), APTR, *mut ()) -> i32, // 27: 168
    pub InflateBackEnd: unsafe extern "C" fn(*mut ZIFace, *mut APTR) -> i32, // 28: 172
    pub Adler32: unsafe extern "C" fn(*mut ZIFace, u32, *const u8, u32) -> u32, // 29: 176
    pub Adler32Combine: unsafe extern "C" fn(*mut ZIFace, u32, u32, i32) -> u32, // 30: 180
    pub CRC32: unsafe extern "C" fn(*mut ZIFace, u32, *const u8, u32) -> u32, // 31: 184
    pub CRC32Combine: unsafe extern "C" fn(*mut ZIFace, u32, u32, i32) -> u32, // 32: 188
    pub ZlibVersion: unsafe extern "C" fn(*mut ZIFace) -> CONST_STRPTR, // 33: 192
    pub Compress: unsafe extern "C" fn(*mut ZIFace, APTR, *mut u32, CONST_APTR, u32) -> i32, // 34: 196
    pub Uncompress: unsafe extern "C" fn(*mut ZIFace, APTR, *mut u32, CONST_APTR, u32) -> i32, // 35: 200
    pub Compress2: unsafe extern "C" fn(*mut ZIFace, APTR, *mut u32, CONST_APTR, u32, i32) -> i32, // 36: 204
    pub CompressBound: unsafe extern "C" fn(*mut ZIFace, u32) -> u32, // 37: 208
    pub InflateGetDictionary: unsafe extern "C" fn(*mut ZIFace, *mut APTR, *mut u8, *mut u32) -> i32, // 38: 212
    pub ZError: unsafe extern "C" fn(*mut ZIFace, i32) -> CONST_STRPTR, // 39: 216
    pub Uncompress2: unsafe extern "C" fn(*mut ZIFace, APTR, *mut u32, CONST_APTR, *mut u32) -> i32, // 40: 220
    pub InflateReset2: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32) -> i32, // 41: 224
    pub InflateValidate: unsafe extern "C" fn(*mut ZIFace, *mut APTR, i32) -> i32, // 42: 228
}

